name = "araharu"
compatibility_date = "2025-10-01"
pages_build_output_dir = "out"

[vars]
APP_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "araharu-db"
database_id = "acca6d0c-c6d6-4762-ab7d-2777f2fd3783"

[env.production]
name = "araharu"

[env.production.vars]
APP_ENV = "production"

[[env.production.d1_databases]]
binding = "DB"
database_name = "araharu-db"
database_id = "acca6d0c-c6d6-4762-ab7d-2777f2fd3783"

# Secrets are set via `wrangler secret put`:
# wrangler secret put ANTHROPIC_API_KEY
# wrangler secret put CRON_SECRET
# wrangler secret put AUTH_SECRET
