/**
 * 형용사 관형사형 글로스 → 해요체 서술형 맵.
 * english-generator 의 품사 라우터가 이 맵을 형용사 화이트리스트로도 사용한다.
 * (k가 '다'로 끝나면 동사, 이 맵에 있으면 형용사, 아니면 명사.)
 * cat: 'thing'=사물 서술 / 'person'=감정·성격·신체상태(사람 주어) / 'weather'=날씨(오늘은 프레임).
 */
export type AdjCat = "thing" | "person" | "weather";
export interface AdjPred {
  p: string;
  cat: AdjCat;
}

export const ADJ_PRED: Record<string, AdjPred> = {
  "큰": { p: "커요", cat: "thing" },
  "작은": { p: "작아요", cat: "thing" },
  "뜨거운": { p: "뜨거워요", cat: "thing" },
  "차가운": { p: "차가워요", cat: "thing" },
  "빠른": { p: "빨라요", cat: "thing" },
  "느린": { p: "느려요", cat: "thing" },
  "좋은": { p: "좋아요", cat: "thing" },
  "나쁜": { p: "나빠요", cat: "thing" },
  "긴": { p: "길어요", cat: "thing" },
  "짧은": { p: "짧아요", cat: "thing" },
  "새로운": { p: "새로워요", cat: "thing" },
  "오래된": { p: "오래됐어요", cat: "thing" },
  "예쁜": { p: "예뻐요", cat: "thing" },
  "키가 큰": { p: "키가 커요", cat: "person" },
  "깨끗한": { p: "깨끗해요", cat: "thing" },
  "더러운": { p: "더러워요", cat: "thing" },
  "강한": { p: "강해요", cat: "thing" },
  "약한": { p: "약해요", cat: "thing" },
  "재미있는": { p: "재미있어요", cat: "thing" },
  "조용한": { p: "조용해요", cat: "thing" },
  "시끄러운": { p: "시끄러워요", cat: "thing" },
  "부드러운": { p: "부드러워요", cat: "thing" },
  "딱딱한": { p: "딱딱해요", cat: "thing" },
  "둥근": { p: "둥글어요", cat: "thing" },
  "어린": { p: "어려요", cat: "person" },
  "밝은": { p: "밝아요", cat: "thing" },
  "어두운": { p: "어두워요", cat: "thing" },
  "무거운": { p: "무거워요", cat: "thing" },
  "가벼운": { p: "가벼워요", cat: "thing" },
  "두꺼운": { p: "두꺼워요", cat: "thing" },
  "얇은": { p: "얇아요", cat: "thing" },
  "깊은": { p: "깊어요", cat: "thing" },
  "넓은": { p: "넓어요", cat: "thing" },
  "날카로운": { p: "날카로워요", cat: "thing" },
  "키 큰": { p: "키가 커요", cat: "person" },
  "키 작은": { p: "키가 작아요", cat: "person" },
  "열린": { p: "열려 있어요", cat: "thing" },
  "닫힌": { p: "닫혀 있어요", cat: "thing" },
  "위로": { p: "위에 있어요", cat: "thing" },
  "아래로": { p: "아래에 있어요", cat: "thing" },
  "젖은": { p: "젖었어요", cat: "thing" },
  "마른": { p: "말랐어요", cat: "thing" },
  "친절한": { p: "친절해요", cat: "person" },
  "용감한": { p: "용감해요", cat: "person" },
  "똑똑한": { p: "똑똑해요", cat: "person" },
  "더 큰": { p: "더 커요", cat: "thing" },
  "더 작은": { p: "더 작아요", cat: "thing" },
  "더 빠른": { p: "더 빨라요", cat: "thing" },
  "더 느린": { p: "더 느려요", cat: "thing" },
  "더 강한": { p: "더 강해요", cat: "thing" },
  "더 똑똑한": { p: "더 똑똑해요", cat: "person" },
  "아름다운": { p: "아름다워요", cat: "thing" },
  "중요한": { p: "중요해요", cat: "thing" },
  "다른": { p: "달라요", cat: "thing" },
  "인기 있는": { p: "인기 있어요", cat: "thing" },
  "어려운": { p: "어려워요", cat: "thing" },
  "맛있는": { p: "맛있어요", cat: "thing" },
  "위험한": { p: "위험해요", cat: "thing" },
  "멋진": { p: "멋져요", cat: "thing" },
  "끔찍한": { p: "끔찍해요", cat: "thing" },
  "비싼": { p: "비싸요", cat: "thing" },
  "싼": { p: "싸요", cat: "thing" },
  "유명한": { p: "유명해요", cat: "thing" },
  "필요한": { p: "필요해요", cat: "thing" },
  "가능한": { p: "가능해요", cat: "thing" },
  "더 무거운": { p: "더 무거워요", cat: "thing" },
  "더 가벼운": { p: "더 가벼워요", cat: "thing" },
  "더 깊은": { p: "더 깊어요", cat: "thing" },
  "더 넓은": { p: "더 넓어요", cat: "thing" },
  "훌륭한": { p: "훌륭해요", cat: "thing" },
  "거대한": { p: "거대해요", cat: "thing" },
  "아주 작은": { p: "아주 작아요", cat: "thing" },
  "고대의": { p: "아주 오래됐어요", cat: "thing" },
  "현대의": { p: "현대적이에요", cat: "thing" },
  "다채로운": { p: "다채로워요", cat: "thing" },
  "정직한": { p: "정직해요", cat: "person" },
  "너그러운": { p: "너그러워요", cat: "person" },
  "고집 센": { p: "고집이 세요", cat: "person" },
  "창의적인": { p: "창의적이에요", cat: "person" },
  "책임감 있는": { p: "책임감이 있어요", cat: "person" },
  "예의 바른": { p: "예의가 발라요", cat: "person" },
  "호기심 많은": { p: "호기심이 많아요", cat: "person" },
  "야망 있는": { p: "야망이 있어요", cat: "person" },
  "겸손한": { p: "겸손해요", cat: "person" },
  "충성스러운": { p: "충성스러워요", cat: "person" },
  "독립적인": { p: "독립적이에요", cat: "person" },
  "부지런한": { p: "부지런해요", cat: "person" },
  "협력적인": { p: "협력적이에요", cat: "person" },
  "공손한": { p: "공손해요", cat: "person" },
  "사려깊은": { p: "사려 깊어요", cat: "person" },
  "모험적인": { p: "모험적이에요", cat: "person" },
  "활발한": { p: "활발해요", cat: "person" },
  "믿을 수 있는": { p: "믿을 수 있어요", cat: "person" },
  "유연한": { p: "유연해요", cat: "person" },
  "행복한": { p: "행복해요", cat: "person" },
  "슬픈": { p: "슬퍼요", cat: "person" },
  "배고픈": { p: "배고파요", cat: "person" },
  "화난": { p: "화났어요", cat: "person" },
  "무서운": { p: "무서워요", cat: "person" },
  "놀란": { p: "놀랐어요", cat: "person" },
  "피곤한": { p: "피곤해요", cat: "person" },
  "신나는": { p: "신나요", cat: "person" },
  "지루한": { p: "지루해요", cat: "person" },
  "외로운": { p: "외로워요", cat: "person" },
  "자랑스러운": { p: "자랑스러워요", cat: "person" },
  "수줍은": { p: "수줍어요", cat: "person" },
  "긴장한": { p: "긴장돼요", cat: "person" },
  "궁금한": { p: "궁금해요", cat: "person" },
  "감사한": { p: "감사해요", cat: "person" },
  "걱정되는": { p: "걱정돼요", cat: "person" },
  "차분한": { p: "차분해요", cat: "person" },
  "쾌활한": { p: "쾌활해요", cat: "person" },
  "웃긴": { p: "웃겨요", cat: "person" },
  "심술궂은": { p: "심술궂어요", cat: "person" },
  "졸린": { p: "졸려요", cat: "person" },
  "목마른": { p: "목말라요", cat: "person" },
  "배부른": { p: "배불러요", cat: "person" },
  "아픈": { p: "아파요", cat: "person" },
  "건강한": { p: "건강해요", cat: "person" },
  "들뜬": { p: "들떴어요", cat: "person" },
  "운이 좋은": { p: "운이 좋아요", cat: "person" },
  "두려운": { p: "두려워요", cat: "person" },
  "미안한": { p: "미안해요", cat: "person" },
  "편안한": { p: "편안해요", cat: "person" },
  "혼란스러운": { p: "혼란스러워요", cat: "person" },
  "기쁜": { p: "기뻐요", cat: "person" },
  "속상한": { p: "속상해요", cat: "person" },
  "활기찬": { p: "활기차요", cat: "person" },
  "다정한": { p: "다정해요", cat: "person" },
  "게으른": { p: "게을러요", cat: "person" },
  "참을성 있는": { p: "참을성이 있어요", cat: "person" },
  "질투하는": { p: "질투해요", cat: "person" },
  "실망한": { p: "실망했어요", cat: "person" },
  "부끄러운": { p: "부끄러워요", cat: "person" },
  "희망찬": { p: "희망차요", cat: "person" },
  "깜짝 놀란": { p: "깜짝 놀랐어요", cat: "person" },
  "안도한": { p: "안심했어요", cat: "person" },
  "좌절한": { p: "좌절했어요", cat: "person" },
  "평화로운": { p: "평화로워요", cat: "person" },
  "짜증난": { p: "짜증나요", cat: "person" },
  "결심한": { p: "결심했어요", cat: "person" },
  "화창한": { p: "화창해요", cat: "weather" },
  "비 오는": { p: "비가 와요", cat: "weather" },
  "흐린": { p: "흐려요", cat: "weather" },
  "눈 오는": { p: "눈이 와요", cat: "weather" },
  "바람 부는": { p: "바람이 불어요", cat: "weather" },
  "따뜻한": { p: "따뜻해요", cat: "weather" },
  "시원한": { p: "시원해요", cat: "weather" },
  "폭풍인": { p: "폭풍이 쳐요", cat: "weather" },
  "안개 낀": { p: "안개가 꼈어요", cat: "weather" },
  "습한": { p: "습해요", cat: "weather" },
  "건조한": { p: "건조해요", cat: "weather" },
  "얼어붙는": { p: "얼어붙을 듯 추워요", cat: "weather" },
  "쌀쌀한": { p: "쌀쌀해요", cat: "weather" },
  "끓는 듯 더운": { p: "너무 더워요", cat: "weather" },
  "산들바람 부는": { p: "산들바람이 불어요", cat: "weather" },
  "구름 낀": { p: "구름이 꼈어요", cat: "weather" },
  "얼음처럼 찬": { p: "얼음처럼 차가워요", cat: "weather" },
  "맑은": { p: "맑아요", cat: "weather" },
  "추운": { p: "추워요", cat: "weather" },
  "폭풍우의": { p: "폭풍우가 쳐요", cat: "weather" },
  "달콤한": { p: "달콤해요", cat: "thing" },
  "신": { p: "시어요", cat: "thing" },
  "짠": { p: "짜요", cat: "thing" },
};
