/**
 * Procedural Korean General Knowledge Generator
 * Generates grade-appropriate knowledge entries for Korean elementary education.
 * 500+ unique entries per call using seeded PRNG.
 *
 * Categories: 과학, 지리, 역사, 자연, 인체, 동물, 식물, 우주, 날씨, 문화,
 *             수학상식, 지구과학, 생활상식, 물리, 화학, 생물, 환경
 */
import type { KnowledgeEntry } from '@/types/curriculum';

// Seeded PRNG for reproducible generation
function seededRandom(seed: number) {
  let s = seed;
  return () => { s = (s * 9301 + 49297) % 233280; return s / 233280; };
}

function shuffle<T>(arr: T[], random: () => number): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

// ============================================================
// Grade 1-2: Very simple facts (animals, seasons, body parts, basic nature)
// 240+ entries
// ============================================================
const GRADE_1_2: KnowledgeEntry[] = [
  // === 동물 (35) ===
  { text: '강아지의 새끼를 ___라고 부른다.', answer: '강아지', category: '동물' },
  { text: '고양이는 ___을 좋아하는 동물이다.', answer: '생선', category: '동물' },
  { text: '닭이 낳는 것은 ___이다.', answer: '달걀', category: '동물' },
  { text: '소는 ___를 먹는 초식동물이다.', answer: '풀', category: '동물' },
  { text: '개구리는 어릴 때 ___라고 불린다.', answer: '올챙이', category: '동물' },
  { text: '나비는 원래 ___였다가 변한다.', answer: '애벌레', category: '동물' },
  { text: '토끼의 귀는 매우 ___다.', answer: '길', category: '동물' },
  { text: '거북이는 등에 딱딱한 ___이 있다.', answer: '껍데기', category: '동물' },
  { text: '벌은 꽃에서 ___을 모은다.', answer: '꿀', category: '동물' },
  { text: '새는 ___로 하늘을 난다.', answer: '날개', category: '동물' },
  { text: '물고기는 ___로 숨을 쉰다.', answer: '아가미', category: '동물' },
  { text: '오리는 발에 ___이 있어서 헤엄을 잘 친다.', answer: '물갈퀴', category: '동물' },
  { text: '사자는 동물의 ___이라고 불린다.', answer: '왕', category: '동물' },
  { text: '기린의 ___은 매우 길다.', answer: '목', category: '동물' },
  { text: '코끼리는 긴 ___로 물을 마신다.', answer: '코', category: '동물' },
  { text: '펭귄은 날지 못하는 ___이다.', answer: '새', category: '동물' },
  { text: '다람쥐는 겨울을 대비해 ___을 모은다.', answer: '도토리', category: '동물' },
  { text: '젖소에게서 ___을 얻는다.', answer: '우유', category: '동물' },
  { text: '양에게서 ___을 깎아 옷을 만든다.', answer: '털', category: '동물' },
  { text: '고슴도치는 몸에 뾰족한 ___이 있다.', answer: '가시', category: '동물' },
  { text: '무당벌레는 몸에 ___이 있다.', answer: '점', category: '동물' },
  { text: '부엉이는 주로 ___에 활동한다.', answer: '밤', category: '동물' },
  { text: '낙타의 등에는 ___이 있다.', answer: '혹', category: '동물' },
  { text: '잠자리는 ___이 네 개이다.', answer: '날개', category: '동물' },
  { text: '독수리는 하늘 높이 ___수 있다.', answer: '날', category: '동물' },
  { text: '거미는 ___을 쳐서 먹이를 잡는다.', answer: '거미줄', category: '동물' },
  { text: '앵무새는 사람의 ___을 따라 할 수 있다.', answer: '말', category: '동물' },
  { text: '북극곰의 털은 ___ 색이다.', answer: '흰', category: '동물' },
  { text: '반딧불이는 밤에 ___을 낸다.', answer: '빛', category: '동물' },
  { text: '꿀을 만드는 곤충은 ___이다.', answer: '벌', category: '동물' },
  { text: '하마는 주로 ___속에서 생활한다.', answer: '물', category: '동물' },
  { text: '두더지는 ___속에서 산다.', answer: '땅', category: '동물' },
  { text: '돌고래는 바다에 사는 ___류이다.', answer: '포유', category: '동물' },
  { text: '개미는 자기 몸보다 ___것을 들 수 있다.', answer: '무거운', category: '동물' },
  { text: '말은 사람이 ___을 탈 수 있는 동물이다.', answer: '등', category: '동물' },

  // === 자연 (35) ===
  { text: '비가 온 뒤 하늘에 뜨는 일곱 색깔 띠를 ___라고 한다.', answer: '무지개', category: '자연' },
  { text: '하늘에서 내리는 하얀 결정을 ___이라고 한다.', answer: '눈', category: '자연' },
  { text: '식물이 자라려면 ___과 물이 필요하다.', answer: '햇빛', category: '자연' },
  { text: '나무에서 떨어지는 것을 ___이라고 한다.', answer: '낙엽', category: '자연' },
  { text: '봄에 꽃이 ___다.', answer: '핀', category: '자연' },
  { text: '강물은 높은 곳에서 ___곳으로 흐른다.', answer: '낮은', category: '자연' },
  { text: '바다의 물은 ___맛이 난다.', answer: '짠', category: '자연' },
  { text: '하루 중 해가 뜨는 때를 ___이라 한다.', answer: '아침', category: '자연' },
  { text: '달은 밤에 하늘에서 ___을 낸다.', answer: '빛', category: '자연' },
  { text: '여름에는 날씨가 매우 ___다.', answer: '덥', category: '자연' },
  { text: '겨울에는 날씨가 매우 ___다.', answer: '춥', category: '자연' },
  { text: '나무의 뿌리는 ___속에 있다.', answer: '땅', category: '자연' },
  { text: '씨앗을 심으면 ___이 자란다.', answer: '싹', category: '자연' },
  { text: '구름에서 물방울이 떨어지는 것을 ___라고 한다.', answer: '비', category: '자연' },
  { text: '일 년은 ___달이다.', answer: '열두', category: '자연' },
  { text: '일주일은 ___일이다.', answer: '칠', category: '자연' },
  { text: '하루는 ___시간이다.', answer: '스물네', category: '자연' },
  { text: '봄 다음에 오는 계절은 ___이다.', answer: '여름', category: '자연' },
  { text: '가을 다음에 오는 계절은 ___이다.', answer: '겨울', category: '자연' },
  { text: '물을 얼리면 ___이 된다.', answer: '얼음', category: '자연' },
  { text: '얼음을 가열하면 ___이 된다.', answer: '물', category: '자연' },
  { text: '태양은 ___쪽에서 뜬다.', answer: '동', category: '자연' },
  { text: '태양은 ___쪽으로 진다.', answer: '서', category: '자연' },
  { text: '무지개는 ___가지 색으로 이루어져 있다.', answer: '일곱', category: '자연' },
  { text: '꽃에서 좋은 ___이 난다.', answer: '향기', category: '자연' },
  { text: '연못에는 ___가 살고 있다.', answer: '물고기', category: '자연' },
  { text: '흙 위에 자라는 초록색 식물을 ___이라 한다.', answer: '풀', category: '자연' },
  { text: '가을에 논에서 거두는 곡식은 ___이다.', answer: '벼', category: '자연' },
  { text: '해가 지면 하늘이 ___색으로 변한다.', answer: '주황', category: '자연' },
  { text: '돌멩이를 물에 던지면 ___으로 가라앉는다.', answer: '아래', category: '자연' },
  { text: '밤에 하늘에서 빛나는 것은 ___이다.', answer: '별', category: '자연' },
  { text: '산꼭대기에서 흘러내리는 물줄기를 ___이라 한다.', answer: '계곡', category: '자연' },
  { text: '바람이 세게 부는 날을 ___이 센 날이라 한다.', answer: '바람', category: '자연' },
  { text: '나뭇잎이 초록색인 이유는 ___소 때문이다.', answer: '엽록', category: '자연' },
  { text: '비가 온 뒤 하늘에 뜨는 것은 ___이다.', answer: '무지개', category: '자연' },

  // === 인체 (30) ===
  { text: '사람의 심장은 가슴 ___쪽에 있다.', answer: '왼', category: '인체' },
  { text: '음식을 씹는 것은 ___이다.', answer: '이빨', category: '인체' },
  { text: '눈으로 사물을 ___수 있다.', answer: '볼', category: '인체' },
  { text: '코로 냄새를 ___수 있다.', answer: '맡을', category: '인체' },
  { text: '귀로 소리를 ___수 있다.', answer: '들을', category: '인체' },
  { text: '손가락은 한 손에 ___개이다.', answer: '다섯', category: '인체' },
  { text: '사람의 몸속에는 빨간 ___가 흐른다.', answer: '피', category: '인체' },
  { text: '허파는 ___을 쉬는 데 사용한다.', answer: '숨', category: '인체' },
  { text: '위장은 음식을 ___하는 역할을 한다.', answer: '소화', category: '인체' },
  { text: '뇌는 ___속에 있다.', answer: '머리', category: '인체' },
  { text: '혀로 음식의 ___을 느낀다.', answer: '맛', category: '인체' },
  { text: '사람은 두 ___로 걷는다.', answer: '다리', category: '인체' },
  { text: '사람의 체온은 약 ___도이다.', answer: '36.5', category: '인체' },
  { text: '심장은 ___을 온몸으로 보내준다.', answer: '피', category: '인체' },
  { text: '머리카락은 ___에서 자란다.', answer: '머리', category: '인체' },
  { text: '사람의 눈은 ___개이다.', answer: '두', category: '인체' },
  { text: '콧구멍은 ___개이다.', answer: '두', category: '인체' },
  { text: '발가락은 한 발에 ___개이다.', answer: '다섯', category: '인체' },
  { text: '눈물은 ___에서 나온다.', answer: '눈', category: '인체' },
  { text: '땀은 ___을 통해 나온다.', answer: '피부', category: '인체' },
  { text: '뼈는 몸을 ___해 준다.', answer: '지탱', category: '인체' },
  { text: '피부로 뜨겁고 차가운 것을 ___할 수 있다.', answer: '느낄', category: '인체' },
  { text: '젖니가 빠지면 ___가 난다.', answer: '영구치', category: '인체' },
  { text: '사람은 하루에 약 8시간 ___을 자야 건강하다.', answer: '잠', category: '인체' },
  { text: '목은 머리와 ___을 이어준다.', answer: '몸통', category: '인체' },
  { text: '배꼽은 ___에 있다.', answer: '배', category: '인체' },
  { text: '혀로 느끼는 맛은 단맛, 짠맛, 신맛, ___이다.', answer: '쓴맛', category: '인체' },
  { text: '우리 몸에서 피를 온몸으로 보내는 기관은 ___이다.', answer: '심장', category: '인체' },
  { text: '귀로 하는 것은 ___이다.', answer: '듣기', category: '인체' },
  { text: '근육이 있어서 몸을 ___일 수 있다.', answer: '움직', category: '인체' },

  // === 식물 (30) ===
  { text: '꽃이 지고 나면 ___이 열린다.', answer: '열매', category: '식물' },
  { text: '장미에는 ___이 있어 찔릴 수 있다.', answer: '가시', category: '식물' },
  { text: '해바라기는 ___을 따라 고개를 돌린다.', answer: '해', category: '식물' },
  { text: '벼에서 ___을 얻는다.', answer: '쌀', category: '식물' },
  { text: '감자는 ___속에서 자란다.', answer: '땅', category: '식물' },
  { text: '봄에 피는 대표적인 꽃은 ___이다.', answer: '벚꽃', category: '식물' },
  { text: '소나무는 겨울에도 잎이 ___다.', answer: '푸르', category: '식물' },
  { text: '단풍나무의 잎은 가을에 ___색으로 변한다.', answer: '빨간', category: '식물' },
  { text: '은행나무의 잎은 가을에 ___색으로 변한다.', answer: '노란', category: '식물' },
  { text: '식물의 뿌리는 ___에서 물을 흡수한다.', answer: '땅', category: '식물' },
  { text: '선인장은 물이 적은 ___에서 잘 자란다.', answer: '사막', category: '식물' },
  { text: '연꽃은 ___위에 핀다.', answer: '물', category: '식물' },
  { text: '무궁화는 ___의 나라꽃이다.', answer: '대한민국', category: '식물' },
  { text: '나팔꽃은 ___에 핀다.', answer: '아침', category: '식물' },
  { text: '밤나무에서 ___을 수확할 수 있다.', answer: '밤', category: '식물' },
  { text: '잔디는 ___색이다.', answer: '초록', category: '식물' },
  { text: '고추는 익으면 ___색이 된다.', answer: '빨간', category: '식물' },
  { text: '수박은 ___에 맛있게 먹는 과일이다.', answer: '여름', category: '식물' },
  { text: '귤은 ___에서 주로 재배한다.', answer: '제주도', category: '식물' },
  { text: '배추는 ___을 담그는 데 쓴다.', answer: '김치', category: '식물' },
  { text: '민들레 씨앗은 ___을 타고 날아간다.', answer: '바람', category: '식물' },
  { text: '도토리는 ___나무의 열매이다.', answer: '참나무', category: '식물' },
  { text: '나무의 나이는 ___을 세면 알 수 있다.', answer: '나이테', category: '식물' },
  { text: '강낭콩을 심으면 먼저 ___가 나온다.', answer: '뿌리', category: '식물' },
  { text: '사과나무는 ___에 열매가 열린다.', answer: '가을', category: '식물' },
  { text: '사과는 ___색이다.', answer: '빨간', category: '식물' },
  { text: '여름에 즐기는 과일로 초록색 껍질의 ___이 있다.', answer: '수박', category: '식물' },
  { text: '식물이 자라려면 물, 햇빛, ___이 필요하다.', answer: '공기', category: '식물' },
  { text: '콩나물은 ___에서 싹이 튼 것이다.', answer: '콩', category: '식물' },
  { text: '버섯은 ___이 없어도 자란다.', answer: '햇빛', category: '식물' },

  // === 날씨 (30) ===
  { text: '하늘에 떠있는 흰 것을 ___이라 한다.', answer: '구름', category: '날씨' },
  { text: '천둥과 함께 치는 빛을 ___라 한다.', answer: '번개', category: '날씨' },
  { text: '눈이 많이 내리면 ___을 만들 수 있다.', answer: '눈사람', category: '날씨' },
  { text: '비가 오기 전에 하늘이 ___해진다.', answer: '흐려', category: '날씨' },
  { text: '안개가 끼면 앞이 잘 ___지 않는다.', answer: '보이', category: '날씨' },
  { text: '태풍이 오면 ___이 매우 세게 분다.', answer: '바람', category: '날씨' },
  { text: '이슬은 ___에 풀잎 위에 맺힌다.', answer: '아침', category: '날씨' },
  { text: '장마는 ___에 비가 오래 내리는 것이다.', answer: '여름', category: '날씨' },
  { text: '우산은 ___가 올 때 쓴다.', answer: '비', category: '날씨' },
  { text: '여름에 갑자기 세게 내리는 비를 ___라 한다.', answer: '소나기', category: '날씨' },
  { text: '가을 하늘은 매우 ___고 높다.', answer: '맑', category: '날씨' },
  { text: '봄에 중국에서 날아오는 먼지를 ___이라 한다.', answer: '황사', category: '날씨' },
  { text: '온도를 재는 도구를 ___라 한다.', answer: '온도계', category: '날씨' },
  { text: '맑은 날 하늘은 ___색이다.', answer: '파란', category: '날씨' },
  { text: '빗방울이 얼어서 떨어지는 것을 ___라 한다.', answer: '우박', category: '날씨' },
  { text: '기온이 0도 이하로 내려가면 물이 ___다.', answer: '언', category: '날씨' },
  { text: '겨울에 입김이 나오는 이유는 공기가 ___기 때문이다.', answer: '차갑', category: '날씨' },
  { text: '여름에는 낮이 ___고 겨울에는 낮이 짧다.', answer: '길', category: '날씨' },
  { text: '눈이 녹으면 ___이 된다.', answer: '물', category: '날씨' },
  { text: '추운 날 창문에 ___이 맺힌다.', answer: '김', category: '날씨' },
  { text: '비가 많이 오면 ___이 날 수 있어 조심해야 한다.', answer: '홍수', category: '날씨' },
  { text: '겨울에 눈이 많이 내리면 ___이라 부른다.', answer: '폭설', category: '날씨' },
  { text: '날씨를 미리 알려주는 것을 일기___라 한다.', answer: '예보', category: '날씨' },
  { text: '겨울에 내리는 하얀 것은 ___이다.', answer: '눈', category: '날씨' },
  { text: '날씨가 추우면 물이 얼어 ___이 된다.', answer: '얼음', category: '날씨' },
  { text: '비가 되기 전 하늘에 모인 것은 ___이다.', answer: '구름', category: '날씨' },
  { text: '서리는 가을 ___에 내린다.', answer: '새벽', category: '날씨' },
  { text: '바람의 방향을 알려주는 도구를 ___라 한다.', answer: '풍향계', category: '날씨' },
  { text: '햇빛이 강한 날에는 ___을 발라야 한다.', answer: '선크림', category: '날씨' },
  { text: '봄에는 새싹이 ___다.', answer: '돋는', category: '날씨' },

  // === 생활상식 (30) ===
  { text: '횡단보도를 건널 때는 ___을 보고 건넌다.', answer: '신호등', category: '생활상식' },
  { text: '불이 나면 전화번호 ___에 전화한다.', answer: '119', category: '생활상식' },
  { text: '도둑이 들면 전화번호 ___에 전화한다.', answer: '112', category: '생활상식' },
  { text: '밥을 먹기 전에 ___을 씻어야 한다.', answer: '손', category: '생활상식' },
  { text: '이를 닦지 않으면 ___가 생길 수 있다.', answer: '충치', category: '생활상식' },
  { text: '쓰레기는 ___에 버려야 한다.', answer: '쓰레기통', category: '생활상식' },
  { text: '교통 신호등의 빨간불은 ___이라는 뜻이다.', answer: '멈춤', category: '생활상식' },
  { text: '교통 신호등의 초록불은 ___이라는 뜻이다.', answer: '건너감', category: '생활상식' },
  { text: '운동을 하면 몸이 ___해진다.', answer: '건강', category: '생활상식' },
  { text: '잠을 충분히 자야 ___가 잘 자란다.', answer: '키', category: '생활상식' },
  { text: '자전거를 탈 때는 ___을 써야 안전하다.', answer: '헬멧', category: '생활상식' },
  { text: '도서관에서는 ___히 해야 한다.', answer: '조용', category: '생활상식' },
  { text: '어른에게 물건을 드릴 때는 두 ___으로 드린다.', answer: '손', category: '생활상식' },
  { text: '재활용품은 ___하여 버려야 한다.', answer: '분리수거', category: '생활상식' },
  { text: '식사 후에는 ___을 닦아야 한다.', answer: '이', category: '생활상식' },
  { text: '비 오는 날에는 ___을 가져간다.', answer: '우산', category: '생활상식' },
  { text: '약은 반드시 ___의 지시에 따라 먹어야 한다.', answer: '의사', category: '생활상식' },
  { text: '모르는 사람을 따라가면 ___하다.', answer: '위험', category: '생활상식' },
  { text: '에스컬레이터에서는 ___을 잡아야 한다.', answer: '손잡이', category: '생활상식' },
  { text: '감기에 걸리면 ___을 많이 마셔야 한다.', answer: '물', category: '생활상식' },
  { text: '태극기는 우리나라의 ___이다.', answer: '국기', category: '생활상식' },
  { text: '우리나라의 국가는 ___이다.', answer: '애국가', category: '생활상식' },
  { text: '추울 때는 옷을 ___게 입어야 한다.', answer: '따뜻하', category: '생활상식' },
  { text: '놀이터에서는 ___을 지켜야 한다.', answer: '규칙', category: '생활상식' },
  { text: '아침에 일어나면 ___을 해야 상쾌하다.', answer: '세수', category: '생활상식' },
  { text: '물에 빠진 사람을 보면 ___에 신고해야 한다.', answer: '119', category: '생활상식' },
  { text: '우유를 오래 두면 ___해진다.', answer: '상', category: '생활상식' },
  { text: '물은 하루에 ___컵 이상 마시는 것이 좋다.', answer: '여섯', category: '생활상식' },
  { text: '선생님께 인사할 때는 ___을 해야 한다.', answer: '인사', category: '생활상식' },
  { text: '차가 오는 방향을 살피며 ___를 건너야 한다.', answer: '길', category: '생활상식' },

  // === 문화 (30) ===
  { text: '설날에 어른에게 하는 인사를 ___라 한다.', answer: '세배', category: '문화' },
  { text: '추석에 먹는 대표 음식은 ___이다.', answer: '송편', category: '문화' },
  { text: '한글을 만든 왕은 ___이다.', answer: '세종대왕', category: '문화' },
  { text: '한글날은 ___월 9일이다.', answer: '10', category: '문화' },
  { text: '어린이날은 ___월 5일이다.', answer: '5', category: '문화' },
  { text: '크리스마스는 ___월 25일이다.', answer: '12', category: '문화' },
  { text: '우리나라 전통 옷을 ___이라 한다.', answer: '한복', category: '문화' },
  { text: '우리나라 전통 집을 ___이라 한다.', answer: '한옥', category: '문화' },
  { text: '우리나라 전통 음식을 ___이라 한다.', answer: '한식', category: '문화' },
  { text: '떡국은 ___에 먹는 음식이다.', answer: '설날', category: '문화' },
  { text: '김치는 ___를 발효시켜 만든다.', answer: '배추', category: '문화' },
  { text: '된장은 ___으로 만든다.', answer: '콩', category: '문화' },
  { text: '탈춤은 ___을 쓰고 추는 춤이다.', answer: '탈', category: '문화' },
  { text: '사물놀이에서 쓰는 악기는 꽹과리, 징, 장구, ___이다.', answer: '북', category: '문화' },
  { text: '태권도는 우리나라의 전통 ___이다.', answer: '무술', category: '문화' },
  { text: '윷놀이는 ___날에 하는 전통 놀이이다.', answer: '설', category: '문화' },
  { text: '제기차기는 ___로 제기를 차는 놀이이다.', answer: '발', category: '문화' },
  { text: '팥죽은 ___에 먹는 전통 음식이다.', answer: '동지', category: '문화' },
  { text: '삼계탕은 ___에 먹는 보양식이다.', answer: '여름', category: '문화' },
  { text: '부채는 더울 때 ___을 일으키는 도구이다.', answer: '바람', category: '문화' },
  { text: '한지는 우리나라 전통 ___이다.', answer: '종이', category: '문화' },
  { text: '광복절은 ___월 15일이다.', answer: '8', category: '문화' },
  { text: '단오에는 ___를 뛰는 풍습이 있다.', answer: '그네', category: '문화' },
  { text: '정월 대보름에 먹는 것은 ___이다.', answer: '오곡밥', category: '문화' },
  { text: '비빔밥은 밥에 여러 ___를 넣어 비벼 먹는다.', answer: '나물', category: '문화' },
  { text: '가야금은 ___을 뜯어 소리를 내는 악기이다.', answer: '줄', category: '문화' },
  { text: '연날리기는 ___에 하는 전통 놀이이다.', answer: '정월', category: '문화' },
  { text: '한국의 전통 차는 ___차가 유명하다.', answer: '녹', category: '문화' },
  { text: '보자기는 물건을 ___때 사용한다.', answer: '쌀', category: '문화' },
  { text: '개천절은 ___월 3일이다.', answer: '10', category: '문화' },

  // === 우주 (기초, 15) ===
  { text: '지구는 ___양 주위를 돈다.', answer: '태', category: '우주' },
  { text: '밤하늘에 빛나는 것을 ___이라 한다.', answer: '별', category: '우주' },
  { text: '달은 지구 주위를 ___다.', answer: '돈', category: '우주' },
  { text: '해는 ___쪽에서 뜬다.', answer: '동', category: '우주' },
  { text: '해는 ___쪽으로 진다.', answer: '서', category: '우주' },
  { text: '지구에서 가장 가까운 별은 ___이다.', answer: '태양', category: '우주' },
  { text: '달의 모양은 매일 ___한다.', answer: '변', category: '우주' },
  { text: '보름달은 ___고 둥글다.', answer: '크', category: '우주' },
  { text: '낮에 하늘이 밝은 것은 ___때문이다.', answer: '태양', category: '우주' },
  { text: '하늘에서 별이 떨어지는 것처럼 보이는 것을 ___이라 한다.', answer: '별똥별', category: '우주' },
  { text: '지구는 둥근 ___모양이다.', answer: '공', category: '우주' },
  { text: '낮과 밤이 바뀌는 것은 지구가 ___하기 때문이다.', answer: '자전', category: '우주' },
  { text: '계절이 바뀌는 것은 지구가 ___하기 때문이다.', answer: '공전', category: '우주' },
  { text: '달은 약 ___일마다 모양이 바뀐다.', answer: '30', category: '우주' },
  { text: '태양계에서 지구는 ___번째 행성이다.', answer: '세', category: '우주' },

  // === 과학 (기초, 10) ===
  { text: '물이 얼면 ___가 된다.', answer: '얼음', category: '과학' },
  { text: '소리가 벽에 부딪혀 되돌아오는 것을 ___라고 한다.', answer: '메아리', category: '과학' },
  { text: '식물이 햇빛을 받아 양분을 만드는 것을 ___이라 한다.', answer: '광합성', category: '과학' },
  { text: '화산에서 나오는 뜨거운 액체를 ___라고 한다.', answer: '용암', category: '과학' },
  { text: '자석은 ___을 끌어당긴다.', answer: '철', category: '과학' },
  { text: '무거운 물건은 물에 ___는다.', answer: '가라앉', category: '과학' },
  { text: '나무토막은 물에 ___다.', answer: '뜬', category: '과학' },
  { text: '물에 소금을 녹이면 ___이 된다.', answer: '소금물', category: '과학' },
  { text: '빛이 물체에 가로막혀 생기는 것은 ___이다.', answer: '그림자', category: '과학' },
  { text: '공룡은 약 ___년 전에 살았다.', answer: '6500만', category: '과학' },
];

// ============================================================
// Grade 3-4: Intermediate facts (Korean geography, basic history, science concepts)
// 220+ entries
// ============================================================
const GRADE_3_4: KnowledgeEntry[] = [
  // === 지리 (35) ===
  { text: '대한민국의 수도는 ___이다.', answer: '서울', category: '지리' },
  { text: '우리나라에서 가장 큰 섬은 ___이다.', answer: '제주도', category: '지리' },
  { text: '우리나라에서 가장 높은 산은 ___이다.', answer: '한라산', category: '지리' },
  { text: '우리나라에서 가장 긴 강은 ___이다.', answer: '낙동강', category: '지리' },
  { text: '서울을 관통하는 강은 ___이다.', answer: '한강', category: '지리' },
  { text: '우리나라의 동쪽 바다를 ___이라 한다.', answer: '동해', category: '지리' },
  { text: '우리나라의 서쪽 바다를 ___이라 한다.', answer: '서해', category: '지리' },
  { text: '우리나라의 남쪽 바다를 ___이라 한다.', answer: '남해', category: '지리' },
  { text: '독도는 ___에 있는 우리나라 영토이다.', answer: '동해', category: '지리' },
  { text: '한반도의 가장 높은 산은 ___이다.', answer: '백두산', category: '지리' },
  { text: '부산은 우리나라에서 두 번째로 ___도시이다.', answer: '큰', category: '지리' },
  { text: '경주는 ___왕조의 수도였다.', answer: '신라', category: '지리' },
  { text: '인천에는 국제___이 있다.', answer: '공항', category: '지리' },
  { text: '강원도는 ___과 바다가 모두 있는 지역이다.', answer: '산', category: '지리' },
  { text: '전라도는 ___이 넓어 곡식이 많이 자란다.', answer: '평야', category: '지리' },
  { text: '지도에서 위쪽은 ___을 가리킨다.', answer: '북쪽', category: '지리' },
  { text: '지도에서 아래쪽은 ___을 가리킨다.', answer: '남쪽', category: '지리' },
  { text: '우리나라는 아시아 대륙의 ___에 있다.', answer: '동쪽', category: '지리' },
  { text: '휴전선은 남한과 ___을 나누는 선이다.', answer: '북한', category: '지리' },
  { text: '우리나라의 영토는 한___이다.', answer: '반도', category: '지리' },
  { text: '태백산맥은 한반도의 ___쪽을 따라 이어진다.', answer: '동', category: '지리' },
  { text: '울릉도는 ___에 있는 섬이다.', answer: '동해', category: '지리' },
  { text: '대전은 우리나라의 ___에 있다.', answer: '중앙', category: '지리' },
  { text: '광주는 ___도의 대표 도시이다.', answer: '전라남', category: '지리' },
  { text: '대구는 ___도의 대표 도시이다.', answer: '경상북', category: '지리' },
  { text: '세종시는 우리나라의 ___수도이다.', answer: '행정', category: '지리' },
  { text: '설악산은 ___도에 있다.', answer: '강원', category: '지리' },
  { text: '남한강과 북한강이 합쳐져 ___이 된다.', answer: '한강', category: '지리' },
  { text: '금강은 ___도를 흐르는 강이다.', answer: '충청', category: '지리' },
  { text: '영산강은 ___도를 흐르는 강이다.', answer: '전라', category: '지리' },
  { text: '한반도를 가로지르는 큰 강은 한강과 ___이다.', answer: '낙동강', category: '지리' },
  { text: '지리산은 ___개의 도에 걸쳐 있다.', answer: '세', category: '지리' },
  { text: '제주도에는 ___이라는 높은 산이 있다.', answer: '한라산', category: '지리' },
  { text: '여수는 ___도에 있는 도시이다.', answer: '전라남', category: '지리' },
  { text: '충청도의 대표 도시는 ___이다.', answer: '대전', category: '지리' },

  // === 역사 (35) ===
  { text: '우리나라 최초의 나라는 ___이다.', answer: '고조선', category: '역사' },
  { text: '고조선을 세운 사람은 ___이다.', answer: '단군왕검', category: '역사' },
  { text: '삼국시대의 세 나라는 고구려, 백제, ___이다.', answer: '신라', category: '역사' },
  { text: '신라의 수도는 ___이었다.', answer: '경주', category: '역사' },
  { text: '백제의 마지막 수도는 ___이었다.', answer: '부여', category: '역사' },
  { text: '고구려의 수도는 ___이었다.', answer: '평양', category: '역사' },
  { text: '삼국을 통일한 나라는 ___이다.', answer: '신라', category: '역사' },
  { text: '한글을 만든 왕은 ___이다.', answer: '세종대왕', category: '역사' },
  { text: '한글이 만들어진 이름은 ___이다.', answer: '훈민정음', category: '역사' },
  { text: '이순신 장군은 ___를 만들어 왜적을 물리쳤다.', answer: '거북선', category: '역사' },
  { text: '임진왜란은 ___나라가 침략한 전쟁이다.', answer: '일본', category: '역사' },
  { text: '고려를 세운 왕은 ___이다.', answer: '왕건', category: '역사' },
  { text: '조선을 세운 왕은 ___이다.', answer: '이성계', category: '역사' },
  { text: '조선의 수도는 ___이었다.', answer: '한양', category: '역사' },
  { text: '경복궁은 ___시대의 궁궐이다.', answer: '조선', category: '역사' },
  { text: '첨성대는 ___를 관측하던 건물이다.', answer: '별', category: '역사' },
  { text: '석굴암은 ___에 있는 문화재이다.', answer: '경주', category: '역사' },
  { text: '불국사는 ___시대에 만들어진 절이다.', answer: '신라', category: '역사' },
  { text: '광개토대왕은 ___의 왕이다.', answer: '고구려', category: '역사' },
  { text: '을지문덕 장군은 ___전투에서 승리했다.', answer: '살수', category: '역사' },
  { text: '강감찬 장군은 ___전투에서 거란군을 물리쳤다.', answer: '귀주', category: '역사' },
  { text: '고려시대에 만든 금속 활자는 세계 ___의 금속 활자이다.', answer: '최초', category: '역사' },
  { text: '팔만대장경은 ___에 보관되어 있다.', answer: '해인사', category: '역사' },
  { text: '3·1 운동은 ___년에 일어났다.', answer: '1919', category: '역사' },
  { text: '대한민국은 ___년에 정부가 수립되었다.', answer: '1948', category: '역사' },
  { text: '6·25 전쟁은 ___년에 일어났다.', answer: '1950', category: '역사' },
  { text: '유관순은 3·1 운동 때 만세를 부른 ___이다.', answer: '열사', category: '역사' },
  { text: '세종대왕은 조선 제___대 왕이다.', answer: '4', category: '역사' },
  { text: '측우기는 ___을 재는 도구이다.', answer: '강수량', category: '역사' },
  { text: '해시계는 해의 ___으로 시간을 알려주는 도구이다.', answer: '그림자', category: '역사' },
  { text: '고인돌은 ___시대의 무덤이다.', answer: '청동기', category: '역사' },
  { text: '거북선을 만든 사람은 ___이다.', answer: '이순신', category: '역사' },
  { text: '임진왜란 때 바다에서 싸운 장군은 ___이다.', answer: '이순신', category: '역사' },
  { text: '우리나라 최초의 금속활자 인쇄물은 ___이다.', answer: '직지심체요절', category: '역사' },
  { text: '고구려, 백제, 신라를 합쳐 ___라고 부른다.', answer: '삼국', category: '역사' },

  // === 과학 (35) ===
  { text: '물이 끓는 온도는 섭씨 ___도이다.', answer: '100', category: '과학' },
  { text: '물이 어는 온도는 섭씨 ___도이다.', answer: '0', category: '과학' },
  { text: '자석에는 N극과 ___극이 있다.', answer: 'S', category: '과학' },
  { text: '같은 극의 자석은 서로 ___한다.', answer: '밀어냄', category: '과학' },
  { text: '다른 극의 자석은 서로 ___한다.', answer: '끌어당김', category: '과학' },
  { text: '소리는 물체가 ___할 때 만들어진다.', answer: '진동', category: '과학' },
  { text: '빛은 직진하지만 거울에 닿으면 ___한다.', answer: '반사', category: '과학' },
  { text: '전기가 흐르는 길을 ___라 한다.', answer: '회로', category: '과학' },
  { text: '전구에 불이 켜지려면 ___가 흘러야 한다.', answer: '전기', category: '과학' },
  { text: '건전지에는 +극과 ___극이 있다.', answer: '-', category: '과학' },
  { text: '공기 중에 가장 많은 기체는 ___이다.', answer: '질소', category: '과학' },
  { text: '사람이 숨을 쉬는 데 필요한 기체는 ___이다.', answer: '산소', category: '과학' },
  { text: '사람이 내뿜는 기체는 ___이다.', answer: '이산화탄소', category: '과학' },
  { text: '물질의 세 가지 상태는 고체, 액체, ___이다.', answer: '기체', category: '과학' },
  { text: '얼음은 물의 ___상태이다.', answer: '고체', category: '과학' },
  { text: '수증기는 물의 ___상태이다.', answer: '기체', category: '과학' },
  { text: '무게를 재는 도구를 ___라 한다.', answer: '저울', category: '과학' },
  { text: '길이를 재는 도구를 ___라 한다.', answer: '자', category: '과학' },
  { text: '온도를 재는 도구를 ___라 한다.', answer: '온도계', category: '과학' },
  { text: '물에 소금을 녹이면 ___이 된다.', answer: '소금물', category: '과학' },
  { text: '기름은 물에 ___지 않는다.', answer: '섞이', category: '과학' },
  { text: '돋보기로 빛을 모으면 ___가 높아진다.', answer: '온도', category: '과학' },
  { text: '그림자는 빛의 ___편에 생긴다.', answer: '반대', category: '과학' },
  { text: '소리가 벽에 부딪혀 되돌아오는 것을 ___라 한다.', answer: '메아리', category: '과학' },
  { text: '나침반의 바늘은 항상 ___쪽을 가리킨다.', answer: '북', category: '과학' },
  { text: '빛의 삼원색은 빨강, 초록, ___이다.', answer: '파랑', category: '과학' },
  { text: '물이 수증기로 변하는 것을 ___이라 한다.', answer: '증발', category: '과학' },
  { text: '수증기가 물방울로 변하는 것을 ___이라 한다.', answer: '응결', category: '과학' },
  { text: '식물이 물을 흡수하는 부분은 ___이다.', answer: '뿌리', category: '과학' },
  { text: '철은 ___에 붙는 성질이 있다.', answer: '자석', category: '과학' },
  { text: '렌즈는 빛을 ___시키는 도구이다.', answer: '굴절', category: '과학' },
  { text: '화산이 폭발하면 ___가 흘러나온다.', answer: '용암', category: '과학' },
  { text: '지층은 ___이 쌓여 만들어진 것이다.', answer: '흙', category: '과학' },
  { text: '태양에서 지구까지 빛이 도달하는 데 약 ___분 걸린다.', answer: '8', category: '과학' },
  { text: '무지개는 빛이 ___되어 생기는 것이다.', answer: '분산', category: '과학' },

  // === 지구과학 (30) ===
  { text: '지구의 표면은 대부분 ___으로 덮여 있다.', answer: '물', category: '지구과학' },
  { text: '화석은 옛날 ___의 흔적이다.', answer: '생물', category: '지구과학' },
  { text: '공룡은 지금은 ___한 동물이다.', answer: '멸종', category: '지구과학' },
  { text: '지진은 ___이 흔들리는 현상이다.', answer: '땅', category: '지구과학' },
  { text: '바위가 부서져서 작아진 것을 ___이라 한다.', answer: '모래', category: '지구과학' },
  { text: '흙은 바위가 ___되어 만들어진다.', answer: '풍화', category: '지구과학' },
  { text: '강의 하류에 흙이 쌓이는 것을 ___이라 한다.', answer: '퇴적', category: '지구과학' },
  { text: '지구의 내부는 매우 ___다.', answer: '뜨겁', category: '지구과학' },
  { text: '지구의 겉면을 ___라 한다.', answer: '지각', category: '지구과학' },
  { text: '바다의 밀물과 썰물은 ___의 인력 때문이다.', answer: '달', category: '지구과학' },
  { text: '암석의 종류는 화성암, 퇴적암, ___이다.', answer: '변성암', category: '지구과학' },
  { text: '석탄은 옛날 ___이 변한 것이다.', answer: '식물', category: '지구과학' },
  { text: '대기권은 지구를 둘러싼 ___층이다.', answer: '공기', category: '지구과학' },
  { text: '지구 표면의 약 70%는 ___이다.', answer: '바다', category: '지구과학' },
  { text: '대륙은 지구에 ___개가 있다.', answer: '여섯', category: '지구과학' },
  { text: '가장 큰 대륙은 ___대륙이다.', answer: '아시아', category: '지구과학' },
  { text: '바닷물이 짠 이유는 ___이 녹아 있기 때문이다.', answer: '소금', category: '지구과학' },
  { text: '빙하는 오래된 ___이 굳어진 것이다.', answer: '눈', category: '지구과학' },
  { text: '사막은 비가 매우 ___오는 지역이다.', answer: '적게', category: '지구과학' },
  { text: '지구가 태양을 한 바퀴 도는 데 ___이 걸린다.', answer: '1년', category: '지구과학' },
  { text: '지구가 한 바퀴 자전하는 데 ___시간이 걸린다.', answer: '24', category: '지구과학' },
  { text: '태풍은 따뜻한 ___위에서 만들어진다.', answer: '바다', category: '지구과학' },
  { text: '지진이 바다에서 일어나면 ___가 발생할 수 있다.', answer: '해일', category: '지구과학' },
  { text: '오존층은 자외선을 ___해 준다.', answer: '차단', category: '지구과학' },
  { text: '석유는 옛날 ___이 변한 것이다.', answer: '생물', category: '지구과학' },
  { text: '열대우림은 비가 ___오는 더운 지역이다.', answer: '많이', category: '지구과학' },
  { text: '달이 지구를 한 바퀴 도는 데 약 ___일이 걸린다.', answer: '27', category: '지구과학' },
  { text: '해수면이 올라가는 원인은 지구 ___때문이다.', answer: '온난화', category: '지구과학' },
  { text: '가장 작은 대륙은 ___대륙이다.', answer: '오세아니아', category: '지구과학' },
  { text: '화산에서 나오는 뜨거운 돌을 ___이라 한다.', answer: '용암', category: '지구과학' },

  // === 수학상식 (30) ===
  { text: '삼각형의 각의 합은 ___도이다.', answer: '180', category: '수학상식' },
  { text: '사각형의 각의 합은 ___도이다.', answer: '360', category: '수학상식' },
  { text: '원에는 꼭짓점이 ___개이다.', answer: '0', category: '수학상식' },
  { text: '삼각형에는 꼭짓점이 ___개이다.', answer: '3', category: '수학상식' },
  { text: '정사각형의 네 변의 길이는 모두 ___다.', answer: '같', category: '수학상식' },
  { text: '직각은 ___도이다.', answer: '90', category: '수학상식' },
  { text: '1km는 ___m이다.', answer: '1000', category: '수학상식' },
  { text: '1m는 ___cm이다.', answer: '100', category: '수학상식' },
  { text: '1kg은 ___g이다.', answer: '1000', category: '수학상식' },
  { text: '1시간은 ___분이다.', answer: '60', category: '수학상식' },
  { text: '1분은 ___초이다.', answer: '60', category: '수학상식' },
  { text: '1L는 ___mL이다.', answer: '1000', category: '수학상식' },
  { text: '원주율은 약 ___이다.', answer: '3.14', category: '수학상식' },
  { text: '1다스는 ___개이다.', answer: '12', category: '수학상식' },
  { text: '정육면체의 면은 ___개이다.', answer: '6', category: '수학상식' },
  { text: '정육면체의 꼭짓점은 ___개이다.', answer: '8', category: '수학상식' },
  { text: '정육면체의 모서리는 ___개이다.', answer: '12', category: '수학상식' },
  { text: '직사각형의 넓이는 가로 곱하기 ___이다.', answer: '세로', category: '수학상식' },
  { text: '삼각형의 넓이는 밑변 곱하기 높이 나누기 ___이다.', answer: '2', category: '수학상식' },
  { text: '수직인 두 직선이 만나는 각도는 ___도이다.', answer: '90', category: '수학상식' },
  { text: '가장 작은 소수는 ___이다.', answer: '2', category: '수학상식' },
  { text: '분수에서 위의 수를 ___라 한다.', answer: '분자', category: '수학상식' },
  { text: '분수에서 아래의 수를 ___라 한다.', answer: '분모', category: '수학상식' },
  { text: '1년은 ___개월이다.', answer: '12', category: '수학상식' },
  { text: '1주일은 ___일이다.', answer: '7', category: '수학상식' },
  { text: '한 해의 마지막 달은 ___월이다.', answer: '12', category: '수학상식' },
  { text: '반지름이 같은 원은 크기가 ___다.', answer: '같', category: '수학상식' },
  { text: '평행한 두 직선은 아무리 가도 만나지 ___는다.', answer: '않', category: '수학상식' },
  { text: '대칭인 도형은 반으로 접으면 ___맞는다.', answer: '겹쳐', category: '수학상식' },
  { text: '원의 둘레를 지름으로 나누면 ___가 된다.', answer: '원주율', category: '수학상식' },

  // === 우주 (중급, 20) ===
  { text: '태양계에는 ___개의 행성이 있다.', answer: '8', category: '우주' },
  { text: '태양에서 가장 가까운 행성은 ___이다.', answer: '수성', category: '우주' },
  { text: '태양에서 세 번째 행성은 ___이다.', answer: '지구', category: '우주' },
  { text: '태양계에서 가장 큰 행성은 ___이다.', answer: '목성', category: '우주' },
  { text: '고리가 아름다운 행성은 ___이다.', answer: '토성', category: '우주' },
  { text: '붉은 행성이라 불리는 것은 ___이다.', answer: '화성', category: '우주' },
  { text: '태양은 뜨거운 ___로 이루어져 있다.', answer: '가스', category: '우주' },
  { text: '달에는 ___가 없어서 소리가 전달되지 않는다.', answer: '공기', category: '우주' },
  { text: '별자리 중 국자 모양의 별자리는 ___이다.', answer: '북두칠성', category: '우주' },
  { text: '은하수는 수많은 ___이 모여 있는 것이다.', answer: '별', category: '우주' },
  { text: '우주에서 지구를 보면 ___색으로 보인다.', answer: '파란', category: '우주' },
  { text: '인공___는 지구 주위를 도는 기계이다.', answer: '위성', category: '우주' },
  { text: '우주비행사는 우주에서 ___가 없어 둥둥 뜬다.', answer: '중력', category: '우주' },
  { text: '달 표면에는 ___가 많다.', answer: '분화구', category: '우주' },
  { text: '태양계에서 가장 작은 행성은 ___이다.', answer: '수성', category: '우주' },
  { text: '화성은 ___색으로 보여서 붉은 행성이라 불린다.', answer: '붉은', category: '우주' },
  { text: '지구는 태양 주위를 도는데 이것을 ___이라 한다.', answer: '공전', category: '우주' },
  { text: '지구가 스스로 도는 것을 ___이라 한다.', answer: '자전', category: '우주' },
  { text: '지구의 자연위성은 ___이다.', answer: '달', category: '우주' },
  { text: '태양에서 지구까지 빛이 도달하는 데 약 ___분 걸린다.', answer: '8', category: '우주' },

  // === 동물 (중급, 15) ===
  { text: '곤충의 몸은 머리, 가슴, ___으로 나뉜다.', answer: '배', category: '동물' },
  { text: '양서류는 물과 ___에서 모두 살 수 있다.', answer: '육지', category: '동물' },
  { text: '곤충의 다리는 ___개이다.', answer: '6', category: '동물' },
  { text: '거미의 다리는 ___개이다.', answer: '8', category: '동물' },
  { text: '포유류는 새끼에게 ___을 먹인다.', answer: '젖', category: '동물' },
  { text: '파충류의 몸은 ___으로 덮여 있다.', answer: '비늘', category: '동물' },
  { text: '박쥐는 ___를 사용해 어둠 속에서 날아다닌다.', answer: '초음파', category: '동물' },
  { text: '연어는 알을 낳기 위해 강의 ___로 거슬러 올라간다.', answer: '상류', category: '동물' },
  { text: '문어의 다리는 ___개이다.', answer: '8', category: '동물' },
  { text: '카멜레온은 주변 환경에 맞게 ___을 바꾼다.', answer: '색깔', category: '동물' },
  { text: '고래는 물속에서 살지만 ___로 숨을 쉰다.', answer: '폐', category: '동물' },
  { text: '변온동물은 체온이 주변 환경에 따라 ___한다.', answer: '변', category: '동물' },
  { text: '양서류는 어릴 때 ___에서 살다가 육지로 올라온다.', answer: '물', category: '동물' },
  { text: '오징어의 다리는 ___개이다.', answer: '10', category: '동물' },
  { text: '세계에서 가장 큰 동물은 ___이다.', answer: '대왕고래', category: '동물' },

  // === 나라 (5) ===
  { text: '우리나라의 국기는 ___이다.', answer: '태극기', category: '문화' },
  { text: '우리나라의 국화는 ___이다.', answer: '무궁화', category: '문화' },
  { text: '대한민국의 대통령이 사는 곳은 ___이다.', answer: '용산', category: '문화' },
  { text: '우리 몸에서 음식을 소화하는 기관은 ___이다.', answer: '위', category: '인체' },
  { text: '식물의 잎이 하는 가장 중요한 일은 ___이다.', answer: '광합성', category: '과학' },
];

// ============================================================
// Grade 5-6: Advanced facts (world geography, detailed history, physics/chemistry basics)
// 250+ entries
// ============================================================
const GRADE_5_6: KnowledgeEntry[] = [
  // === 지리 (세계, 35) ===
  { text: '지구에서 가장 큰 바다는 ___이다.', answer: '태평양', category: '지리' },
  { text: '지구에서 가장 큰 대륙은 ___이다.', answer: '아시아', category: '지리' },
  { text: '세계에서 가장 높은 산은 ___이다.', answer: '에베레스트', category: '지리' },
  { text: '세계에서 가장 긴 강은 ___이다.', answer: '나일강', category: '지리' },
  { text: '세계에서 가장 큰 사막은 ___이다.', answer: '사하라', category: '지리' },
  { text: '세계에서 가장 큰 나라는 ___이다.', answer: '러시아', category: '지리' },
  { text: '세계에서 인구가 가장 많은 나라는 ___이다.', answer: '중국', category: '지리' },
  { text: '일본의 수도는 ___이다.', answer: '도쿄', category: '지리' },
  { text: '중국의 수도는 ___이다.', answer: '베이징', category: '지리' },
  { text: '미국의 수도는 ___이다.', answer: '워싱턴 D.C.', category: '지리' },
  { text: '영국의 수도는 ___이다.', answer: '런던', category: '지리' },
  { text: '프랑스의 수도는 ___이다.', answer: '파리', category: '지리' },
  { text: '이탈리아의 수도는 ___이다.', answer: '로마', category: '지리' },
  { text: '독일의 수도는 ___이다.', answer: '베를린', category: '지리' },
  { text: '호주의 수도는 ___이다.', answer: '캔버라', category: '지리' },
  { text: '브라질의 수도는 ___이다.', answer: '브라질리아', category: '지리' },
  { text: '이집트에는 유명한 ___가 있다.', answer: '피라미드', category: '지리' },
  { text: '적도는 지구의 ___을 가로지르는 선이다.', answer: '가운데', category: '지리' },
  { text: '남극과 북극은 지구에서 가장 ___곳이다.', answer: '추운', category: '지리' },
  { text: '아마존 열대우림은 ___대륙에 있다.', answer: '남아메리카', category: '지리' },
  { text: '히말라야 산맥은 ___대륙에 있다.', answer: '아시아', category: '지리' },
  { text: '나이아가라 폭포는 ___와 캐나다 사이에 있다.', answer: '미국', category: '지리' },
  { text: '그린란드는 세계에서 가장 큰 ___이다.', answer: '섬', category: '지리' },
  { text: '태평양과 대서양을 잇는 운하는 ___운하이다.', answer: '파나마', category: '지리' },
  { text: '세계에서 가장 깊은 호수는 ___호이다.', answer: '바이칼', category: '지리' },
  { text: '한국, 중국, 일본은 ___아시아에 속한다.', answer: '동', category: '지리' },
  { text: '인도는 ___아시아에 속한다.', answer: '남', category: '지리' },
  { text: '위도 0도 선을 ___라 한다.', answer: '적도', category: '지리' },
  { text: '경도 0도 선을 ___자오선이라 한다.', answer: '본초', category: '지리' },
  { text: '만리장성은 ___에 있는 건축물이다.', answer: '중국', category: '지리' },
  { text: '자유의 여신상은 ___에 있다.', answer: '미국', category: '지리' },
  { text: '에펠탑은 ___에 있다.', answer: '파리', category: '지리' },
  { text: '콜로세움은 ___에 있는 고대 경기장이다.', answer: '로마', category: '지리' },
  { text: '지중해는 유럽과 ___사이에 있는 바다이다.', answer: '아프리카', category: '지리' },
  { text: '유럽에서 가장 긴 강은 ___강이다.', answer: '볼가', category: '지리' },

  // === 역사 (심화, 35) ===
  { text: '고구려를 세운 왕은 ___이다.', answer: '주몽', category: '역사' },
  { text: '백제를 세운 왕은 ___이다.', answer: '온조', category: '역사' },
  { text: '신라를 세운 왕은 ___이다.', answer: '박혁거세', category: '역사' },
  { text: '발해를 세운 사람은 ___이다.', answer: '대조영', category: '역사' },
  { text: '고려의 수도는 ___이었다.', answer: '개경', category: '역사' },
  { text: '조선시대 과학자 ___은 물시계를 만들었다.', answer: '장영실', category: '역사' },
  { text: '임진왜란이 일어난 해는 ___년이다.', answer: '1592', category: '역사' },
  { text: '병자호란은 ___나라의 침입으로 일어났다.', answer: '청', category: '역사' },
  { text: '실학자 ___은 목민심서를 썼다.', answer: '정약용', category: '역사' },
  { text: '동학 농민 운동의 지도자는 ___이다.', answer: '전봉준', category: '역사' },
  { text: '일제 강점기는 ___년부터 시작되었다.', answer: '1910', category: '역사' },
  { text: '대한민국 임시정부는 중국 ___에 세워졌다.', answer: '상하이', category: '역사' },
  { text: '한국전쟁의 휴전 협정은 ___년에 맺어졌다.', answer: '1953', category: '역사' },
  { text: '88 올림픽은 ___에서 열렸다.', answer: '서울', category: '역사' },
  { text: '2002년 월드컵은 한국과 ___이 공동 개최했다.', answer: '일본', category: '역사' },
  { text: '이집트 문명은 ___강 유역에서 발전했다.', answer: '나일', category: '역사' },
  { text: '민주주의가 처음 시작된 나라는 ___이다.', answer: '그리스', category: '역사' },
  { text: '콜럼버스는 ___년에 아메리카 대륙을 발견했다.', answer: '1492', category: '역사' },
  { text: '프랑스 혁명은 ___년에 일어났다.', answer: '1789', category: '역사' },
  { text: '제2차 세계대전은 ___년에 끝났다.', answer: '1945', category: '역사' },
  { text: '국제연합(UN)은 ___년에 설립되었다.', answer: '1945', category: '역사' },
  { text: '광복절은 일본으로부터 ___한 날이다.', answer: '독립', category: '역사' },
  { text: '5·18 민주화 운동은 ___에서 일어났다.', answer: '광주', category: '역사' },
  { text: '훈민정음이 반포된 해는 ___년이다.', answer: '1446', category: '역사' },
  { text: '직지심체요절은 세계에서 가장 오래된 ___인쇄물이다.', answer: '금속활자', category: '역사' },
  { text: '갑오개혁은 ___년에 일어났다.', answer: '1894', category: '역사' },
  { text: '한일병합조약은 ___년에 체결되었다.', answer: '1910', category: '역사' },
  { text: '간디는 ___의 독립 운동 지도자이다.', answer: '인도', category: '역사' },
  { text: '이순신 장군의 대표적 해전은 ___해전이다.', answer: '한산도', category: '역사' },
  { text: '조선시대 왕의 일기를 ___이라 한다.', answer: '조선왕조실록', category: '역사' },
  { text: '수원 화성을 지은 왕은 ___이다.', answer: '정조', category: '역사' },
  { text: '안중근 의사는 이토 히로부미를 ___에서 저격했다.', answer: '하얼빈', category: '역사' },
  { text: '김구 선생은 대한민국 ___정부의 주석이었다.', answer: '임시', category: '역사' },
  { text: '제1차 세계대전은 ___년에 시작되었다.', answer: '1914', category: '역사' },
  { text: '마틴 루터 킹은 ___운동의 지도자이다.', answer: '인권', category: '역사' },

  // === 과학/물리/화학 (35) ===
  { text: '빛의 속도는 초속 약 ___만 km이다.', answer: '30', category: '과학' },
  { text: '소리의 속도는 초속 약 ___m이다.', answer: '340', category: '과학' },
  { text: '원소 기호 O는 ___를 나타낸다.', answer: '산소', category: '과학' },
  { text: '원소 기호 H는 ___를 나타낸다.', answer: '수소', category: '과학' },
  { text: '원소 기호 C는 ___를 나타낸다.', answer: '탄소', category: '과학' },
  { text: '원소 기호 N는 ___를 나타낸다.', answer: '질소', category: '과학' },
  { text: '원소 기호 Fe는 ___를 나타낸다.', answer: '철', category: '과학' },
  { text: '물의 화학식은 ___이다.', answer: 'H₂O', category: '과학' },
  { text: '이산화탄소의 화학식은 ___이다.', answer: 'CO₂', category: '과학' },
  { text: '전류의 단위는 ___이다.', answer: '암페어', category: '물리' },
  { text: '전압의 단위는 ___이다.', answer: '볼트', category: '물리' },
  { text: '저항의 단위는 ___이다.', answer: '옴', category: '물리' },
  { text: '힘의 단위는 ___이다.', answer: '뉴턴', category: '물리' },
  { text: '에너지의 단위는 ___이다.', answer: '줄', category: '물리' },
  { text: '원자의 중심에는 ___이 있다.', answer: '원자핵', category: '과학' },
  { text: '원자핵 주위를 도는 것은 ___이다.', answer: '전자', category: '과학' },
  { text: '산성 용액은 리트머스 종이를 ___색으로 변하게 한다.', answer: '빨간', category: '화학' },
  { text: '염기성 용액은 리트머스 종이를 ___색으로 변하게 한다.', answer: '파란', category: '화학' },
  { text: 'pH 7은 ___성이다.', answer: '중', category: '화학' },
  { text: '뉴턴이 발견한 법칙은 만유___의 법칙이다.', answer: '인력', category: '물리' },
  { text: '지레의 원리를 발견한 과학자는 ___이다.', answer: '아르키메데스', category: '과학' },
  { text: '진화론을 주장한 과학자는 ___이다.', answer: '다윈', category: '과학' },
  { text: '상대성 이론을 발표한 과학자는 ___이다.', answer: '아인슈타인', category: '과학' },
  { text: '백열전구를 발명한 사람은 ___이다.', answer: '에디슨', category: '과학' },
  { text: '전화기를 발명한 사람은 ___이다.', answer: '벨', category: '과학' },
  { text: '증기기관을 개량한 사람은 ___이다.', answer: '와트', category: '과학' },
  { text: '페니실린을 발견한 과학자는 ___이다.', answer: '플레밍', category: '과학' },
  { text: '전기가 잘 통하는 물질을 ___라 한다.', answer: '도체', category: '물리' },
  { text: '전기가 통하지 않는 물질을 ___라 한다.', answer: '부도체', category: '물리' },
  { text: '빛이 렌즈를 지날 때 꺾이는 현상을 ___이라 한다.', answer: '굴절', category: '물리' },
  { text: '온도가 높아지면 물질의 부피가 ___한다.', answer: '팽창', category: '물리' },
  { text: '전자석은 ___가 흐를 때만 자석이 된다.', answer: '전기', category: '물리' },
  { text: '소리는 ___을 통해 전달된다.', answer: '매질', category: '물리' },
  { text: '진공에서는 소리가 전달되지 ___는다.', answer: '않', category: '물리' },
  { text: '물체의 빠르기를 나타내는 것을 ___라 한다.', answer: '속력', category: '물리' },

  // === 생물/환경 (20) ===
  { text: 'DNA는 생물의 ___정보를 담고 있다.', answer: '유전', category: '생물' },
  { text: '세포의 에너지 공장이라 불리는 것은 ___이다.', answer: '미토콘드리아', category: '생물' },
  { text: '광합성은 ___체에서 일어난다.', answer: '엽록', category: '생물' },
  { text: '먹이사슬의 가장 아래에는 ___이 있다.', answer: '식물', category: '생물' },
  { text: '식물 세포에만 있는 것으로 ___이 있다.', answer: '세포벽', category: '생물' },
  { text: '광합성에서 식물이 내보내는 기체는 ___이다.', answer: '산소', category: '생물' },
  { text: '산소와 수소가 결합하면 ___이 된다.', answer: '물', category: '화학' },
  { text: '리트머스 종이가 파란색에서 빨간색으로 변하면 ___이다.', answer: '산성', category: '화학' },
  { text: '산성과 염기성의 중간을 ___이라 한다.', answer: '중성', category: '화학' },
  { text: '화석연료를 태우면 ___가 배출된다.', answer: '이산화탄소', category: '환경' },
  { text: '오존층은 태양의 ___를 차단한다.', answer: '자외선', category: '환경' },
  { text: '재생 에너지에는 태양열, 풍력, ___등이 있다.', answer: '수력', category: '환경' },
  { text: '식물이 꽃가루를 옮기는 것을 ___이라 한다.', answer: '수분', category: '식물' },
  { text: '꽃의 암술과 ___이 만나야 열매가 생긴다.', answer: '수술', category: '식물' },
  { text: '광합성에 필요한 세 가지는 빛, 물, ___이다.', answer: '이산화탄소', category: '식물' },
  { text: '식물의 잎에서 수분이 증발하는 것을 ___이라 한다.', answer: '증산작용', category: '식물' },
  { text: '씨앗이 싹트는 것을 ___이라 한다.', answer: '발아', category: '식물' },
  { text: '식충식물은 ___를 잡아 양분을 얻는다.', answer: '곤충', category: '식물' },
  { text: '겉씨식물의 대표는 ___이다.', answer: '소나무', category: '식물' },
  { text: '속씨식물은 씨가 ___안에 들어 있다.', answer: '열매', category: '식물' },

  // === 인체 (심화, 20) ===
  { text: '사람의 뼈는 약 ___개이다.', answer: '206', category: '인체' },
  { text: '사람의 근육은 약 ___개이다.', answer: '600', category: '인체' },
  { text: '적혈구는 ___를 운반한다.', answer: '산소', category: '인체' },
  { text: '백혈구는 ___을 물리친다.', answer: '세균', category: '인체' },
  { text: '소장에서 영양분을 ___한다.', answer: '흡수', category: '인체' },
  { text: '대장에서 ___을 흡수한다.', answer: '수분', category: '인체' },
  { text: '간은 ___을 해독하는 역할을 한다.', answer: '독소', category: '인체' },
  { text: '신장(콩팥)은 ___을 걸러내는 역할을 한다.', answer: '노폐물', category: '인체' },
  { text: '심장은 하루에 약 ___만 번 뛴다.', answer: '10', category: '인체' },
  { text: '뇌는 전체 산소의 약 ___%를 사용한다.', answer: '20', category: '인체' },
  { text: '인체에서 가장 큰 장기는 ___이다.', answer: '피부', category: '인체' },
  { text: '인체에서 가장 작은 뼈는 귀 속의 ___이다.', answer: '등골뼈', category: '인체' },
  { text: '혈액형은 크게 A, B, AB, ___형으로 나뉜다.', answer: 'O', category: '인체' },
  { text: '호흡에서 사람이 내보내는 기체는 ___이다.', answer: '이산화탄소', category: '인체' },
  { text: '사람의 폐는 ___개이다.', answer: '두', category: '인체' },
  { text: '원자를 이루는 양성자, 중성자, ___이 있다.', answer: '전자', category: '과학' },
  { text: '지구의 중력 가속도는 약 ___m/s²이다.', answer: '9.8', category: '과학' },
  { text: '열이 전달되는 세 가지 방법은 전도, 대류, ___이다.', answer: '복사', category: '과학' },
  { text: '공기 중 산소의 비율은 약 ___퍼센트이다.', answer: '21', category: '과학' },
  { text: '지구 대기의 약 78%를 차지하는 기체는 ___이다.', answer: '질소', category: '과학' },

  // === 우주 (심화, 20) ===
  { text: '태양계의 행성 순서는 수금지화목토___해이다.', answer: '천', category: '우주' },
  { text: '명왕성은 현재 ___으로 분류된다.', answer: '왜소행성', category: '우주' },
  { text: '빛이 1년 동안 가는 거리를 ___이라 한다.', answer: '광년', category: '우주' },
  { text: '태양은 약 ___억 년 전에 만들어졌다.', answer: '46', category: '우주' },
  { text: '우리 은하의 이름은 ___이다.', answer: '은하수', category: '우주' },
  { text: '블랙홀은 빛도 빠져나올 수 없을 만큼 ___이 강하다.', answer: '중력', category: '우주' },
  { text: '달에 처음 착륙한 우주비행사는 ___이다.', answer: '닐 암스트롱', category: '우주' },
  { text: '국제 우주 정거장의 약자는 ___이다.', answer: 'ISS', category: '우주' },
  { text: '태양의 표면 온도는 약 ___도이다.', answer: '6000', category: '우주' },
  { text: '화성에는 태양계 최대의 화산인 ___이 있다.', answer: '올림푸스산', category: '우주' },
  { text: '목성의 대적점은 거대한 ___이다.', answer: '폭풍', category: '우주' },
  { text: '혜성의 꼬리는 ___에 가까워질 때 생긴다.', answer: '태양', category: '우주' },
  { text: '소행성이 가장 많은 곳은 화성과 ___사이이다.', answer: '목성', category: '우주' },
  { text: '우주의 나이는 약 ___억 년이다.', answer: '138', category: '우주' },
  { text: '우주가 시작된 사건을 ___이라 한다.', answer: '빅뱅', category: '우주' },
  { text: '달이 지구 그림자에 가려지는 것을 ___이라 한다.', answer: '월식', category: '우주' },
  { text: '해가 달에 가려지는 현상을 ___이라 한다.', answer: '일식', category: '우주' },
  { text: '지구의 자전축은 약 ___도 기울어져 있다.', answer: '23.5', category: '우주' },
  { text: '지구의 내부 구조는 지각, 맨틀, ___으로 나뉜다.', answer: '핵', category: '지구과학' },
  { text: '암석이 풍화되어 만들어지는 것은 ___이다.', answer: '흙', category: '지구과학' },

  // === 수학상식 (심화, 20) ===
  { text: '피타고라스의 정리에서 빗변의 제곱은 나머지 두 변의 제곱의 ___이다.', answer: '합', category: '수학상식' },
  { text: '원의 넓이를 구하는 공식은 πr___이다.', answer: '²', category: '수학상식' },
  { text: '원의 둘레를 구하는 공식은 2π___이다.', answer: 'r', category: '수학상식' },
  { text: '비율을 백분율로 나타내면 ___로 표시한다.', answer: '%', category: '수학상식' },
  { text: '속력의 공식은 거리 나누기 ___이다.', answer: '시간', category: '수학상식' },
  { text: '평균을 구하려면 합을 ___로 나눈다.', answer: '개수', category: '수학상식' },
  { text: '최대공약수의 영어 약자는 ___이다.', answer: 'GCD', category: '수학상식' },
  { text: '최소공배수의 영어 약자는 ___이다.', answer: 'LCM', category: '수학상식' },
  { text: '1, 1, 2, 3, 5, 8, 13은 ___수열이다.', answer: '피보나치', category: '수학상식' },
  { text: '확률에서 반드시 일어나는 사건의 확률은 ___이다.', answer: '1', category: '수학상식' },
  { text: '확률에서 절대 일어나지 않는 사건의 확률은 ___이다.', answer: '0', category: '수학상식' },
  { text: '정다면체는 모두 ___가지이다.', answer: '5', category: '수학상식' },
  { text: '대칭축이 무한히 많은 도형은 ___이다.', answer: '원', category: '수학상식' },
  { text: '약수와 ___는 수의 성질을 나타낸다.', answer: '배수', category: '수학상식' },
  { text: '소수점 아래 첫째 자리는 ___의 자리이다.', answer: '십분', category: '수학상식' },

  // === 생활상식 (심화, 20) ===
  { text: '우리나라의 화폐 단위는 ___이다.', answer: '원', category: '생활상식' },
  { text: '일본의 화폐 단위는 ___이다.', answer: '엔', category: '생활상식' },
  { text: '미국의 화폐 단위는 ___이다.', answer: '달러', category: '생활상식' },
  { text: '유럽의 공통 화폐는 ___이다.', answer: '유로', category: '생활상식' },
  { text: '올림픽은 ___년마다 열린다.', answer: '4', category: '생활상식' },
  { text: 'FIFA 월드컵은 ___년마다 열린다.', answer: '4', category: '생활상식' },
  { text: '국제연합(UN)의 본부는 ___에 있다.', answer: '뉴욕', category: '생활상식' },
  { text: '노벨상은 ___에서 시상한다.', answer: '스웨덴', category: '생활상식' },
  { text: '인터넷의 www는 ___의 약자이다.', answer: 'World Wide Web', category: '생활상식' },
  { text: '비타민 C가 많은 과일은 ___이다.', answer: '레몬', category: '생활상식' },
  { text: '칼슘이 많은 음식은 ___이다.', answer: '우유', category: '생활상식' },
  { text: '탄수화물은 우리 몸에 ___를 공급한다.', answer: '에너지', category: '생활상식' },
  { text: '단백질은 ___을 만드는 데 필요하다.', answer: '근육', category: '생활상식' },
  { text: '지방은 체온을 ___하는 역할을 한다.', answer: '유지', category: '생활상식' },
  { text: '소리의 빠르기를 ___라고 한다.', answer: '음속', category: '생활상식' },

  // === 문화 (심화, 15) ===
  { text: '유네스코 세계문화유산에 등록된 한국의 궁궐은 ___이다.', answer: '창덕궁', category: '문화' },
  { text: '판소리에서 가장 유명한 작품은 ___이다.', answer: '춘향전', category: '문화' },
  { text: '한국의 전통 공연 예술인 판소리는 유네스코 ___유산이다.', answer: '무형문화', category: '문화' },
  { text: '비빔밥으로 유명한 한국의 도시는 ___이다.', answer: '전주', category: '문화' },
  { text: '고려청자는 ___색을 띤다.', answer: '비취', category: '문화' },
  { text: '조선시대 그림 중 풍속화로 유명한 화가는 ___이다.', answer: '김홍도', category: '문화' },
  { text: '훈민정음은 ___개의 자음과 모음으로 이루어져 있다.', answer: '28', category: '문화' },
  { text: '현재 한글의 자모 수는 ___개이다.', answer: '24', category: '문화' },
  { text: '한글의 자음은 ___개이다.', answer: '14', category: '문화' },
  { text: '화산 활동으로 생긴 바위를 ___암이라 한다.', answer: '화성', category: '지구과학' },
];

// ============================================================
// Main export function
// ============================================================
export function generateKnowledgePool(grade: number, seed: number): KnowledgeEntry[] {
  const random = seededRandom(seed * 13 + grade * 47);

  // Select grade-appropriate templates
  let basePool: KnowledgeEntry[];
  if (grade <= 2) {
    basePool = [...GRADE_1_2];
  } else if (grade <= 4) {
    // Grade 3-4 includes some grade 1-2 entries for reinforcement
    basePool = [...GRADE_3_4, ...GRADE_1_2.filter((_, i) => i % 3 === 0)];
  } else {
    // Grade 5-6 includes some grade 3-4 entries for reinforcement
    basePool = [...GRADE_5_6, ...GRADE_3_4.filter((_, i) => i % 3 === 0)];
  }

  // Shuffle the base pool
  const shuffled = shuffle(basePool, random);

  // Fill to reach 500 entries
  const target = 500;
  const result: KnowledgeEntry[] = [];

  while (result.length < target) {
    const remaining = target - result.length;
    if (remaining >= shuffled.length) {
      result.push(...shuffled);
    } else {
      result.push(...shuffled.slice(0, remaining));
    }
  }

  // Final shuffle of the complete result
  return shuffle(result, random);
}
