/**
 * Procedural Safety Education Generator
 * Generates grade-appropriate Korean safety education fill-in-the-blank problems.
 * 15 categories, 500+ unique entries per call using seeded PRNG.
 */
import type { SafetyEntry } from "@/types/curriculum";

function seededRandom(seed: number) {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

function shuffle<T>(rng: () => number, arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

type GradeGroup = "1-2" | "3-4" | "5-6";

interface SafetyTemplate {
  text: string;
  answer: string;
  category: string;
  gradeGroup: GradeGroup;
}

// ─────────────────────────────────────────────
// 1. 교통안전
// ─────────────────────────────────────────────
const TRAFFIC_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "횡단보도를 건널 때는 ___을 확인해야 한다.", answer: "신호등", category: "교통안전", gradeGroup: "1-2" },
  { text: "횡단보도에서는 초록불이 켜졌을 때 ___를 확인하고 건넌다.", answer: "좌우", category: "교통안전", gradeGroup: "1-2" },
  { text: "길을 건널 때는 ___을 들어 운전자에게 보여 준다.", answer: "손", category: "교통안전", gradeGroup: "1-2" },
  { text: "차도가 아닌 ___로 걸어야 안전하다.", answer: "인도", category: "교통안전", gradeGroup: "1-2" },
  { text: "빨간 신호등이 켜지면 ___해야 한다.", answer: "멈춤", category: "교통안전", gradeGroup: "1-2" },
  { text: "차에서 내릴 때는 ___이 오는지 확인해야 한다.", answer: "차", category: "교통안전", gradeGroup: "1-2" },
  { text: "버스를 탈 때는 ___에 줄을 서서 기다린다.", answer: "정류장", category: "교통안전", gradeGroup: "1-2" },
  { text: "자동차에 탈 때는 반드시 ___를 매야 한다.", answer: "안전벨트", category: "교통안전", gradeGroup: "1-2" },
  { text: "비 오는 날에는 밝은 색 ___을 입어 운전자가 잘 볼 수 있게 한다.", answer: "옷", category: "교통안전", gradeGroup: "1-2" },
  { text: "도로에서 ___를 하면 위험하다.", answer: "놀이", category: "교통안전", gradeGroup: "1-2" },
  { text: "보호자 없이 큰 ___를 혼자 건너면 안 된다.", answer: "도로", category: "교통안전", gradeGroup: "1-2" },
  { text: "어린이 통학버스에서 내릴 때는 버스가 완전히 ___한 후 내린다.", answer: "정차", category: "교통안전", gradeGroup: "1-2" },
  { text: "골목길에서 나올 때는 ___을 먼저 멈추고 살핀다.", answer: "발걸음", category: "교통안전", gradeGroup: "1-2" },
  { text: "횡단보도에서는 ___으로 빠르게 건너야 한다.", answer: "뛰지 않고 걸어서", category: "교통안전", gradeGroup: "1-2" },
  { text: "차가 다니는 곳에서는 ___을 쓰면 위험하다.", answer: "이어폰", category: "교통안전", gradeGroup: "1-2" },
  { text: "신호등이 없는 횡단보도에서는 차가 완전히 ___한 후 건넌다.", answer: "멈춤", category: "교통안전", gradeGroup: "1-2" },
  { text: "횡단보도에서는 ___쪽을 먼저 보고 건넌다.", answer: "왼", category: "교통안전", gradeGroup: "1-2" },
  { text: "학교 앞 ___구역에서는 차가 천천히 다녀야 한다.", answer: "어린이 보호", category: "교통안전", gradeGroup: "1-2" },
  { text: "차 뒤에서 ___를 하면 운전자가 볼 수 없어 위험하다.", answer: "숨바꼭질", category: "교통안전", gradeGroup: "1-2" },
  { text: "밤에 길을 걸을 때는 ___이 있는 옷을 입으면 안전하다.", answer: "반사", category: "교통안전", gradeGroup: "1-2" },
  { text: "어린이 보호구역의 제한 속도는 시속 ___km이다.", answer: "30", category: "교통안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "자전거를 탈 때는 반드시 ___를 착용해야 한다.", answer: "헬멧", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거는 도로의 ___쪽으로 통행해야 한다.", answer: "오른", category: "교통안전", gradeGroup: "3-4" },
  { text: "교통사고가 발생하면 ___번으로 신고해야 한다.", answer: "112", category: "교통안전", gradeGroup: "3-4" },
  { text: "야간에 자전거를 탈 때는 ___등을 켜야 한다.", answer: "전조", category: "교통안전", gradeGroup: "3-4" },
  { text: "킥보드를 탈 때도 ___을 착용해야 한다.", answer: "보호장구", category: "교통안전", gradeGroup: "3-4" },
  { text: "교차로에서는 ___을 준수해야 한다.", answer: "교통신호", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거 타기 전에 ___와 체인을 점검해야 한다.", answer: "브레이크", category: "교통안전", gradeGroup: "3-4" },
  { text: "도로에서 인라인스케이트를 타면 ___하다.", answer: "위험", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거를 탈 때 ___을 사용하면 안 된다.", answer: "휴대전화", category: "교통안전", gradeGroup: "3-4" },
  { text: "교통표지판 중 ___표지판은 빨간색 원 안에 표시된다.", answer: "금지", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거 전용도로는 ___색으로 표시되어 있다.", answer: "파란", category: "교통안전", gradeGroup: "3-4" },
  { text: "비 오는 날 자전거를 탈 때 ___거리가 길어지므로 주의한다.", answer: "제동", category: "교통안전", gradeGroup: "3-4" },
  { text: "횡단보도가 없는 곳에서는 ___를 이용해 길을 건넌다.", answer: "육교", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거를 탈 때 ___명이 함께 타면 안 된다.", answer: "두", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거 탈 때 야간에는 ___색 옷을 입으면 안전하다.", answer: "밝은", category: "교통안전", gradeGroup: "3-4" },
  { text: "통학로에서는 지정된 ___원의 안내를 따른다.", answer: "교통안전지도", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거를 탄 후에는 안전한 곳에 ___을 채워 보관한다.", answer: "잠금장치", category: "교통안전", gradeGroup: "3-4" },
  { text: "보행 중 ___을 보면서 걸으면 사고 위험이 높다.", answer: "스마트폰", category: "교통안전", gradeGroup: "3-4" },
  { text: "교통사고 목격 시 ___을 기억하고 신고한다.", answer: "차량 번호", category: "교통안전", gradeGroup: "3-4" },
  { text: "자전거 헬멧은 머리 ___에 맞게 조절해서 쓴다.", answer: "크기", category: "교통안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "도로교통법에 따르면 만 ___세 미만은 보호자 동반 없이 도로에서 자전거를 탈 수 없다.", answer: "13", category: "교통안전", gradeGroup: "5-6" },
  { text: "전동킥보드는 만 ___세 이상부터 이용할 수 있다.", answer: "16", category: "교통안전", gradeGroup: "5-6" },
  { text: "음주운전은 ___에 의해 처벌받는 범죄 행위이다.", answer: "법률", category: "교통안전", gradeGroup: "5-6" },
  { text: "보행자 사고 시 가해 차량의 ___번호를 기억해야 한다.", answer: "번호판", category: "교통안전", gradeGroup: "5-6" },
  { text: "교통사고 현장에서는 2차 사고를 방지하기 위해 ___를 설치한다.", answer: "삼각대", category: "교통안전", gradeGroup: "5-6" },
  { text: "자전거 이용 시 ___로 방향 전환 신호를 보내야 한다.", answer: "수신호", category: "교통안전", gradeGroup: "5-6" },
  { text: "교통안전 표지 중 노란색 다이아몬드는 ___표지이다.", answer: "주의", category: "교통안전", gradeGroup: "5-6" },
  { text: "교통사고 발생 시 부상자를 함부로 ___이면 2차 부상 위험이 있다.", answer: "움직", category: "교통안전", gradeGroup: "5-6" },
  { text: "횡단보도 사고 시 운전자는 ___의무를 진다.", answer: "구호", category: "교통안전", gradeGroup: "5-6" },
  { text: "어린이 통학버스 옆을 지날 때 다른 차는 일시 ___해야 한다.", answer: "정지", category: "교통안전", gradeGroup: "5-6" },
  { text: "보행자 전용도로에서는 ___이 통행할 수 없다.", answer: "자동차", category: "교통안전", gradeGroup: "5-6" },
  { text: "교통사고 시 보험사에 ___를 신고해야 한다.", answer: "사고 접수", category: "교통안전", gradeGroup: "5-6" },
  { text: "야간 보행 시 ___를 사용하면 운전자가 보행자를 잘 볼 수 있다.", answer: "반사 팔찌", category: "교통안전", gradeGroup: "5-6" },
  { text: "무단횡단은 ___법 위반으로 과태료가 부과될 수 있다.", answer: "도로교통", category: "교통안전", gradeGroup: "5-6" },
  { text: "자전거도 도로교통법상 ___에 해당한다.", answer: "차", category: "교통안전", gradeGroup: "5-6" },
  { text: "교통사고 목격자는 ___진술을 통해 사고 해결에 도움을 줄 수 있다.", answer: "증인", category: "교통안전", gradeGroup: "5-6" },
  { text: "스쿨존에서 사고를 내면 일반 도로보다 ___이 가중된다.", answer: "처벌", category: "교통안전", gradeGroup: "5-6" },
  { text: "대중교통을 이용하면 교통사고 위험과 ___오염을 줄일 수 있다.", answer: "환경", category: "교통안전", gradeGroup: "5-6" },
  { text: "고속도로에서 고장 시 갓길에 정차하고 ___m 뒤에 삼각대를 놓는다.", answer: "100", category: "교통안전", gradeGroup: "5-6" },
  { text: "보행자는 도로의 ___쪽으로 통행하는 것이 원칙이다.", answer: "왼", category: "교통안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 2. 화재안전
// ─────────────────────────────────────────────
const FIRE_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "불이 났을 때는 ___번에 신고해야 한다.", answer: "119", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 시 엘리베이터 대신 ___를 이용해야 한다.", answer: "계단", category: "화재안전", gradeGroup: "1-2" },
  { text: "불이 나면 젖은 ___으로 코와 입을 막는다.", answer: "수건", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 시에는 ___을 낮추고 대피한다.", answer: "자세", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 경보가 울리면 즉시 밖으로 ___해야 한다.", answer: "대피", category: "화재안전", gradeGroup: "1-2" },
  { text: "성냥이나 ___는 어린이가 만지면 안 된다.", answer: "라이터", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 대피 훈련은 ___적으로 해야 한다.", answer: "정기", category: "화재안전", gradeGroup: "1-2" },
  { text: "집에서 불이 나면 ___부터 나가야 한다.", answer: "먼저 대피", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 시 연기가 많으면 ___로 기어서 이동한다.", answer: "바닥", category: "화재안전", gradeGroup: "1-2" },
  { text: "불이 난 곳에서 나오면 절대 다시 ___하면 안 된다.", answer: "들어가", category: "화재안전", gradeGroup: "1-2" },
  { text: "옷에 불이 붙으면 멈추고 ___서 불을 끈다.", answer: "굴러", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재가 발생하면 큰 소리로 '___야!'라고 외친다.", answer: "불이", category: "화재안전", gradeGroup: "1-2" },
  { text: "가스레인지 근처에서 ___를 하면 안 된다.", answer: "장난", category: "화재안전", gradeGroup: "1-2" },
  { text: "콘센트에 ___를 너무 많이 꽂으면 화재가 날 수 있다.", answer: "플러그", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 대피 시 문을 열기 전에 문의 ___를 확인한다.", answer: "온도", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 시 대피할 수 없으면 ___에서 구조를 기다린다.", answer: "베란다", category: "화재안전", gradeGroup: "1-2" },
  { text: "촛불은 잠자기 전에 반드시 ___야 한다.", answer: "꺼", category: "화재안전", gradeGroup: "1-2" },
  { text: "난로나 히터 가까이에 ___을 놓으면 화재 위험이 있다.", answer: "빨래", category: "화재안전", gradeGroup: "1-2" },
  { text: "화재 시 ___으로 코와 입을 막으면 연기를 덜 마실 수 있다.", answer: "옷소매", category: "화재안전", gradeGroup: "1-2" },
  { text: "대피 경로에는 ___을 두지 않아야 한다.", answer: "물건", category: "화재안전", gradeGroup: "1-2" },
  { text: "집에서 화재 발생 시 가족과 만날 ___을 미리 정해 둔다.", answer: "장소", category: "화재안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "소화기를 사용할 때 먼저 ___을 뽑아야 한다.", answer: "안전핀", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화기 사용 시 바람을 ___에 두고 분사한다.", answer: "등", category: "화재안전", gradeGroup: "3-4" },
  { text: "화재 시 방문을 닫으면 불과 ___의 확산을 막을 수 있다.", answer: "연기", category: "화재안전", gradeGroup: "3-4" },
  { text: "가정에서 화재감지기인 ___를 설치하면 안전하다.", answer: "화재경보기", category: "화재안전", gradeGroup: "3-4" },
  { text: "전기 화재 시에는 ___로 끄면 안 된다.", answer: "물", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화기의 사용 순서는 안전핀 뽑기, 호스 잡기, ___을 누르기이다.", answer: "손잡이", category: "화재안전", gradeGroup: "3-4" },
  { text: "기름에 불이 붙으면 ___으로 덮어 산소를 차단한다.", answer: "뚜껑", category: "화재안전", gradeGroup: "3-4" },
  { text: "아파트 화재 시 ___칸 완강기를 이용할 수 있다.", answer: "피난", category: "화재안전", gradeGroup: "3-4" },
  { text: "건물마다 비치된 ___도를 미리 확인해 두어야 한다.", answer: "대피경로", category: "화재안전", gradeGroup: "3-4" },
  { text: "화재의 3요소는 열, 산소, ___이다.", answer: "연료", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화기는 불의 ___부분을 향해 분사한다.", answer: "아래", category: "화재안전", gradeGroup: "3-4" },
  { text: "가스 냄새가 나면 ___을 열어 환기시킨다.", answer: "창문", category: "화재안전", gradeGroup: "3-4" },
  { text: "가스 누출 시 ___스위치를 만지면 안 된다.", answer: "전기", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화기의 유효기간은 보통 ___년이다.", answer: "10", category: "화재안전", gradeGroup: "3-4" },
  { text: "산불을 발견하면 ___에 신고한다.", answer: "산림청", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화전은 건물 벽에 설치된 ___소화 장비이다.", answer: "옥내", category: "화재안전", gradeGroup: "3-4" },
  { text: "화재 시 비상구 위치를 알려 주는 ___등은 초록색이다.", answer: "유도", category: "화재안전", gradeGroup: "3-4" },
  { text: "캠핑장에서 화기 사용 후 ___을 완전히 끄고 자리를 뜬다.", answer: "불씨", category: "화재안전", gradeGroup: "3-4" },
  { text: "담뱃불이 완전히 꺼지지 않으면 ___가 날 수 있다.", answer: "화재", category: "화재안전", gradeGroup: "3-4" },
  { text: "소화기의 압력 게이지가 ___색이면 정상이다.", answer: "초록", category: "화재안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "화재 발생 시 신고할 때 ___와 상황을 정확히 알려야 한다.", answer: "주소", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재의 종류 중 A급 화재는 ___화재이다.", answer: "일반", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재의 종류 중 B급 화재는 ___화재이다.", answer: "유류", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재의 종류 중 C급 화재는 ___화재이다.", answer: "전기", category: "화재안전", gradeGroup: "5-6" },
  { text: "고층 건물 화재 시 옥상으로 대피할 때 ___의 도움을 받는다.", answer: "헬기", category: "화재안전", gradeGroup: "5-6" },
  { text: "화상을 입으면 즉시 ___로 15분 이상 식힌다.", answer: "흐르는 찬물", category: "화재안전", gradeGroup: "5-6" },
  { text: "스프링클러는 일정 온도에 도달하면 자동으로 ___를 뿌린다.", answer: "물", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재 진압 후에도 ___이 남아 재발화할 수 있다.", answer: "잔불", category: "화재안전", gradeGroup: "5-6" },
  { text: "연기 흡입은 화재 사망의 주요 원인이므로 ___확보가 중요하다.", answer: "호흡", category: "화재안전", gradeGroup: "5-6" },
  { text: "소방차 진입로를 막는 불법 ___는 화재 진압을 방해한다.", answer: "주차", category: "화재안전", gradeGroup: "5-6" },
  { text: "D급 화재는 ___화재로 특수 소화약제가 필요하다.", answer: "금속", category: "화재안전", gradeGroup: "5-6" },
  { text: "방화는 고의로 불을 지르는 ___행위이다.", answer: "범죄", category: "화재안전", gradeGroup: "5-6" },
  { text: "공동주택에서는 소방 ___훈련에 반드시 참여해야 한다.", answer: "대피", category: "화재안전", gradeGroup: "5-6" },
  { text: "완강기는 고층에서 ___를 타고 내려오는 피난 기구이다.", answer: "줄", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재 현장에서 소방관의 ___에 따라야 한다.", answer: "지시", category: "화재안전", gradeGroup: "5-6" },
  { text: "소방시설법에 따라 다중이용시설에는 ___를 반드시 비치해야 한다.", answer: "소화기", category: "화재안전", gradeGroup: "5-6" },
  { text: "밀폐 공간에서 화재 시 ___가 빠르게 소진된다.", answer: "산소", category: "화재안전", gradeGroup: "5-6" },
  { text: "화재 보험에 가입하면 화재 ___를 보상받을 수 있다.", answer: "피해", category: "화재안전", gradeGroup: "5-6" },
  { text: "자동화재탐지설비는 ___를 감지하여 경보를 울린다.", answer: "열과 연기", category: "화재안전", gradeGroup: "5-6" },
  { text: "피난 사다리는 아파트 ___에 설치되어 있다.", answer: "베란다", category: "화재안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 3. 인터넷안전
// ─────────────────────────────────────────────
const INTERNET_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "인터넷을 할 때는 부모님의 ___을 받아야 한다.", answer: "허락", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "모르는 사람의 ___를 클릭하면 안 된다.", answer: "링크", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷에서 나의 ___과 주소를 알려 주면 안 된다.", answer: "이름", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "컴퓨터를 너무 오래 하면 ___이 나빠진다.", answer: "눈", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷에서 무서운 내용을 보면 ___에게 알려야 한다.", answer: "부모님", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷으로 ___를 하면 건강에 좋지 않다.", answer: "밤샘", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "스마트폰 사용 시간은 하루 ___시간 이내가 좋다.", answer: "1", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "게임을 할 때는 정해진 ___을 지켜야 한다.", answer: "시간", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷에서 친구에게 ___을 하면 안 된다.", answer: "욕", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "모르는 사람이 보낸 ___을 열어 보면 안 된다.", answer: "메시지", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "유튜브를 볼 때는 어린이용 ___를 사용한다.", answer: "모드", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "온라인에서 다른 사람의 ___을 함부로 퍼뜨리면 안 된다.", answer: "사진", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "태블릿을 사용할 때는 ___를 바르게 하고 사용한다.", answer: "자세", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷에서 본 내용이 모두 ___인 것은 아니다.", answer: "사실", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "온라인에서 나쁜 말을 들으면 ___을 끄고 어른에게 말한다.", answer: "화면", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "게임에서 이기지 못해도 ___를 부리면 안 된다.", answer: "화", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "인터넷 사용 후에는 ___을 하며 몸을 움직인다.", answer: "스트레칭", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "부모님이 설정한 인터넷 사용 ___을 지켜야 한다.", answer: "규칙", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "스마트폰을 가까이서 보면 ___이 나빠질 수 있다.", answer: "시력", category: "인터넷안전", gradeGroup: "1-2" },
  { text: "온라인에서 선물을 준다는 말에 ___하면 안 된다.", answer: "속", category: "인터넷안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "비밀번호는 다른 사람에게 ___하면 안 된다.", answer: "공유", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "인터넷 게시물에 ___을 쓰는 것은 사이버 폭력이다.", answer: "악플", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "비밀번호는 영문, 숫자, ___를 섞어 만든다.", answer: "특수문자", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "인터넷에서 만난 사람을 실제로 ___하면 위험하다.", answer: "만나", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "다른 사람의 ___을 함부로 복사하면 저작권 침해이다.", answer: "글", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "게임에서 ___결제를 함부로 하면 안 된다.", answer: "유료", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "불법 ___을 다운받으면 법에 위반된다.", answer: "파일", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "인터넷에서 모르는 프로그램을 ___하면 바이러스에 감염될 수 있다.", answer: "설치", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "SNS에 자신의 위치를 실시간으로 ___하면 위험하다.", answer: "공개", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "스마트폰 사용 후에는 ___를 쉬어야 한다.", answer: "눈", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "사이버 폭력을 당하면 ___을 캡처해서 증거를 남긴다.", answer: "화면", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "와이파이 비밀번호 없는 공개 ___은 해킹 위험이 있다.", answer: "네트워크", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "온라인 대화에서 상대방의 ___을 존중해야 한다.", answer: "감정", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "인터넷 게시글을 쓸 때는 ___을 사용해야 한다.", answer: "바른 말", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "컴퓨터 바이러스를 예방하려면 ___프로그램을 설치한다.", answer: "백신", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "허위 정보를 퍼뜨리는 것을 ___뉴스라고 한다.", answer: "가짜", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "온라인 쇼핑 시 ___사이트인지 확인해야 한다.", answer: "안전한", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "게임 이용 등급을 확인하고 자기 ___에 맞는 게임을 한다.", answer: "나이", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "인터넷에서 받은 파일은 ___검사를 한 후 연다.", answer: "바이러스", category: "인터넷안전", gradeGroup: "3-4" },
  { text: "온라인에서 거짓 ___을 만들어 활동하면 안 된다.", answer: "신분", category: "인터넷안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "온라인에서 타인을 지속적으로 괴롭히는 것을 ___라고 한다.", answer: "사이버 불링", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "피싱 메일은 개인정보를 ___하기 위한 사기이다.", answer: "탈취", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "SNS에 올린 정보는 완전히 ___할 수 없으므로 신중해야 한다.", answer: "삭제", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "온라인 게임에서 현금 ___는 사기 피해를 당할 수 있다.", answer: "거래", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "2단계 ___을 설정하면 계정 보안이 강화된다.", answer: "인증", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "저작권이 있는 콘텐츠를 무단으로 사용하면 ___적 책임을 질 수 있다.", answer: "법", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "디지털 ___은 한번 남으면 지우기 어려우므로 신중하게 행동한다.", answer: "발자국", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "딥페이크는 ___를 조작하여 만든 가짜 영상이다.", answer: "얼굴", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "랜섬웨어는 컴퓨터 파일을 ___하고 돈을 요구하는 악성 프로그램이다.", answer: "암호화", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "VPN은 인터넷 ___를 암호화하여 보안을 강화한다.", answer: "통신", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "개인정보를 수집하는 앱의 ___방침을 읽어 봐야 한다.", answer: "개인정보처리", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "소셜 미디어의 과도한 사용은 ___건강에 해로울 수 있다.", answer: "정신", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "인터넷 중독 자가 진단은 한국정보화진흥원 ___에서 할 수 있다.", answer: "홈페이지", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "인터넷 사기 피해를 당하면 ___에 신고한다.", answer: "경찰", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "불법 도박 사이트에 접속하면 ___처벌을 받을 수 있다.", answer: "법적", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "타인의 계정을 무단으로 사용하는 것은 ___에 해당한다.", answer: "해킹", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "사이버 명예훼손은 ___상에서도 처벌받는 범죄이다.", answer: "온라인", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "인터넷 윤리를 지키는 것을 ___이라고 한다.", answer: "네티켓", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "온라인 결제 시 ___인증서를 통해 본인 확인을 한다.", answer: "공인", category: "인터넷안전", gradeGroup: "5-6" },
  { text: "스팸 메일을 열면 악성 ___에 감염될 수 있다.", answer: "코드", category: "인터넷안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 4. 학교안전
// ─────────────────────────────────────────────
const SCHOOL_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "복도에서는 ___지 않고 걸어야 한다.", answer: "뛰", category: "학교안전", gradeGroup: "1-2" },
  { text: "계단에서는 ___을 잡고 올라간다.", answer: "난간", category: "학교안전", gradeGroup: "1-2" },
  { text: "교실에서 가위를 전달할 때는 ___부분을 잡고 건넨다.", answer: "날", category: "학교안전", gradeGroup: "1-2" },
  { text: "학교에서 다치면 ___실로 간다.", answer: "보건", category: "학교안전", gradeGroup: "1-2" },
  { text: "창문에 ___을 걸터앉으면 위험하다.", answer: "몸", category: "학교안전", gradeGroup: "1-2" },
  { text: "쉬는 시간에 교실에서 ___를 던지면 안 된다.", answer: "물건", category: "학교안전", gradeGroup: "1-2" },
  { text: "빗자루로 친구를 ___면 안 된다.", answer: "때리", category: "학교안전", gradeGroup: "1-2" },
  { text: "급식실에서는 ___면서 먹으면 안 된다.", answer: "뛰", category: "학교안전", gradeGroup: "1-2" },
  { text: "학교에서 모르는 사람이 부르면 따라가지 말고 ___에게 알린다.", answer: "선생님", category: "학교안전", gradeGroup: "1-2" },
  { text: "복도에서는 ___쪽으로 걸어야 한다.", answer: "오른", category: "학교안전", gradeGroup: "1-2" },
  { text: "교실 문을 세게 ___으면 손이 끼일 수 있다.", answer: "닫", category: "학교안전", gradeGroup: "1-2" },
  { text: "학용품인 ___로 장난치면 다칠 수 있다.", answer: "칼", category: "학교안전", gradeGroup: "1-2" },
  { text: "계단에서 친구를 ___면 큰 사고가 날 수 있다.", answer: "밀", category: "학교안전", gradeGroup: "1-2" },
  { text: "학교 놀이터 기구를 사용할 때는 ___를 지켜야 한다.", answer: "차례", category: "학교안전", gradeGroup: "1-2" },
  { text: "바닥이 젖어 있으면 ___질 수 있으므로 조심한다.", answer: "미끄러", category: "학교안전", gradeGroup: "1-2" },
  { text: "화장실 바닥이 젖어 있으면 ___이 있다.", answer: "위험", category: "학교안전", gradeGroup: "1-2" },
  { text: "급식 때 뜨거운 국을 받을 때는 ___히 걸어야 한다.", answer: "천천", category: "학교안전", gradeGroup: "1-2" },
  { text: "책상 모서리에 ___를 부딪히지 않도록 조심한다.", answer: "머리", category: "학교안전", gradeGroup: "1-2" },
  { text: "실험 도구는 선생님의 ___에 따라 사용한다.", answer: "지시", category: "학교안전", gradeGroup: "1-2" },
  { text: "체육 시간에는 운동에 적합한 ___를 신어야 한다.", answer: "운동화", category: "학교안전", gradeGroup: "1-2" },
  { text: "화재 대피 시 교실에서 ___에 줄을 서서 이동한다.", answer: "질서 있게", category: "학교안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "과학 실험 시 ___를 착용하여 눈을 보호한다.", answer: "보안경", category: "학교안전", gradeGroup: "3-4" },
  { text: "실험실에서 화학 약품을 만질 때는 ___를 끼어야 한다.", answer: "장갑", category: "학교안전", gradeGroup: "3-4" },
  { text: "실습 중 사고가 발생하면 즉시 ___에게 보고한다.", answer: "선생님", category: "학교안전", gradeGroup: "3-4" },
  { text: "체육 시간에 준비 ___을 충분히 해야 부상을 예방할 수 있다.", answer: "운동", category: "학교안전", gradeGroup: "3-4" },
  { text: "미술 시간에 날카로운 도구를 사용할 때는 ___에 주의한다.", answer: "안전", category: "학교안전", gradeGroup: "3-4" },
  { text: "무거운 물건을 들 때는 ___를 굽혀서 든다.", answer: "무릎", category: "학교안전", gradeGroup: "3-4" },
  { text: "학교 운동장에서 야구를 할 때는 ___를 쓰고 한다.", answer: "헬멧", category: "학교안전", gradeGroup: "3-4" },
  { text: "과학 실험 시 화학 약품의 ___를 직접 맡으면 안 된다.", answer: "냄새", category: "학교안전", gradeGroup: "3-4" },
  { text: "음악실에서 악기를 함부로 ___면 안 된다.", answer: "던지", category: "학교안전", gradeGroup: "3-4" },
  { text: "학교 수영장에서는 ___의 지도 아래 입수한다.", answer: "선생님", category: "학교안전", gradeGroup: "3-4" },
  { text: "조리 실습 시 뜨거운 기름이 ___수 있으므로 주의한다.", answer: "튈", category: "학교안전", gradeGroup: "3-4" },
  { text: "현장 학습 시 ___을 이탈하면 안 된다.", answer: "대열", category: "학교안전", gradeGroup: "3-4" },
  { text: "학교 안전 점검은 매 ___기 초에 실시한다.", answer: "학", category: "학교안전", gradeGroup: "3-4" },
  { text: "목공 실습 시 ___을 착용하여 눈을 보호한다.", answer: "보안경", category: "학교안전", gradeGroup: "3-4" },
  { text: "체육 시간에 ___을 빼고 운동해야 부상을 예방한다.", answer: "장신구", category: "학교안전", gradeGroup: "3-4" },
  { text: "과학실에서 실험 후 ___을 깨끗이 씻어야 한다.", answer: "손", category: "학교안전", gradeGroup: "3-4" },
  { text: "학교 식당에서 칼을 사용할 때는 ___을 향해 자른다.", answer: "바깥쪽", category: "학교안전", gradeGroup: "3-4" },
  { text: "교실 콘센트에 ___을 넣으면 감전 위험이 있다.", answer: "쇠붙이", category: "학교안전", gradeGroup: "3-4" },
  { text: "비상 대피로는 항상 ___게 유지해야 한다.", answer: "열려 있", category: "학교안전", gradeGroup: "3-4" },
  { text: "학교 내 소화전 위치를 미리 ___두어야 한다.", answer: "알아", category: "학교안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "학교 안전사고 발생 시 ___조치를 먼저 취한다.", answer: "응급", category: "학교안전", gradeGroup: "5-6" },
  { text: "체육 시간에 과격한 운동 중 ___가 나면 즉시 중단한다.", answer: "통증", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교에서 지진 대피 훈련 시 책상 아래로 들어가 ___를 보호한다.", answer: "머리", category: "학교안전", gradeGroup: "5-6" },
  { text: "과학실에서 알코올램프 사용 후 ___으로 덮어 끈다.", answer: "뚜껑", category: "학교안전", gradeGroup: "5-6" },
  { text: "실험 중 유리가 깨지면 맨손이 아닌 ___를 사용해 정리한다.", answer: "빗자루", category: "학교안전", gradeGroup: "5-6" },
  { text: "체육관에서 운동 시 ___을 충분히 갖추어야 한다.", answer: "보호장비", category: "학교안전", gradeGroup: "5-6" },
  { text: "실험실에서는 반드시 ___를 확인 후 약품을 사용한다.", answer: "라벨", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 안전교육은 연간 ___시간 이상 실시해야 한다.", answer: "51", category: "학교안전", gradeGroup: "5-6" },
  { text: "화학 실험 시 환기를 위해 ___장치를 사용한다.", answer: "흄후드", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 내 CCTV는 학생 ___을 위해 설치되어 있다.", answer: "안전", category: "학교안전", gradeGroup: "5-6" },
  { text: "체육 시간에 탈수 증상이 나타나면 ___를 충분히 마신다.", answer: "물", category: "학교안전", gradeGroup: "5-6" },
  { text: "과학 실험 보고서에 ___사항을 기록해 두면 안전에 도움이 된다.", answer: "주의", category: "학교안전", gradeGroup: "5-6" },
  { text: "야외 체험학습 시 ___에 맞는 복장을 준비한다.", answer: "날씨", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 실험실에서 산과 알칼리를 혼합하면 ___반응이 일어난다.", answer: "발열", category: "학교안전", gradeGroup: "5-6" },
  { text: "방과 후 활동 시에도 안전 ___을 준수해야 한다.", answer: "수칙", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 안전사고 발생 시 학교안전공제회에 ___를 청구할 수 있다.", answer: "보상", category: "학교안전", gradeGroup: "5-6" },
  { text: "운동 전 ___운동, 운동 후 정리운동을 해야 부상을 예방한다.", answer: "준비", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 시설물이 파손되면 즉시 ___에게 신고한다.", answer: "관리자", category: "학교안전", gradeGroup: "5-6" },
  { text: "학교 안전사고 시 목격자의 ___이 중요한 증거가 된다.", answer: "진술", category: "학교안전", gradeGroup: "5-6" },
  { text: "교내에서 위험물질을 발견하면 만지지 말고 ___에게 알린다.", answer: "선생님", category: "학교안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 5. 놀이안전
// ─────────────────────────────────────────────
const PLAY_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "그네를 탈 때는 ___을 꼭 잡아야 한다.", answer: "줄", category: "놀이안전", gradeGroup: "1-2" },
  { text: "미끄럼틀을 거꾸로 ___면 위험하다.", answer: "올라가", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이터에서 ___를 밀면 안 된다.", answer: "친구", category: "놀이안전", gradeGroup: "1-2" },
  { text: "시소를 탈 때 갑자기 ___면 상대방이 다칠 수 있다.", answer: "내리", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이터 바닥이 젖었을 때는 ___질 수 있으므로 조심한다.", answer: "미끄러", category: "놀이안전", gradeGroup: "1-2" },
  { text: "철봉에서 놀 때는 ___이 미끄러지지 않도록 한다.", answer: "손", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이기구가 ___져 있으면 사용하지 않는다.", answer: "고장나", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이기구 위에서 ___를 던지면 안 된다.", answer: "물건", category: "놀이안전", gradeGroup: "1-2" },
  { text: "그네가 움직일 때 앞으로 ___가면 위험하다.", answer: "다가", category: "놀이안전", gradeGroup: "1-2" },
  { text: "높은 곳에서 ___면 크게 다칠 수 있다.", answer: "뛰어내리", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이터에서 놀 때 ___끈이 달린 옷은 놀이기구에 걸릴 수 있다.", answer: "목", category: "놀이안전", gradeGroup: "1-2" },
  { text: "장난감 총의 ___을 사람에게 겨누면 안 된다.", answer: "총구", category: "놀이안전", gradeGroup: "1-2" },
  { text: "볼풀장에서 다른 친구의 ___를 밟지 않도록 주의한다.", answer: "몸", category: "놀이안전", gradeGroup: "1-2" },
  { text: "인라인스케이트를 탈 때는 ___와 무릎보호대를 착용한다.", answer: "헬멧", category: "놀이안전", gradeGroup: "1-2" },
  { text: "공놀이는 ___가 없는 넓은 곳에서 한다.", answer: "차", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이터 모래를 ___에 넣으면 안 된다.", answer: "입", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이기구를 탈 때는 ___를 기다려야 한다.", answer: "차례", category: "놀이안전", gradeGroup: "1-2" },
  { text: "밖에서 놀다 다치면 바로 ___에게 알려야 한다.", answer: "어른", category: "놀이안전", gradeGroup: "1-2" },
  { text: "비 온 뒤 놀이기구는 ___워서 미끄러울 수 있다.", answer: "젖", category: "놀이안전", gradeGroup: "1-2" },
  { text: "날카로운 ___을 가지고 놀면 다칠 수 있다.", answer: "물건", category: "놀이안전", gradeGroup: "1-2" },
  { text: "놀이터에서 놀고 난 후에는 반드시 ___을 씻어야 한다.", answer: "손", category: "놀이안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "자전거를 탈 때는 ___와 팔꿈치 보호대를 착용한다.", answer: "무릎", category: "놀이안전", gradeGroup: "3-4" },
  { text: "트램펄린을 탈 때는 한 번에 ___명만 사용해야 한다.", answer: "한", category: "놀이안전", gradeGroup: "3-4" },
  { text: "야외 활동 시 ___에 쏘이지 않도록 주의한다.", answer: "벌", category: "놀이안전", gradeGroup: "3-4" },
  { text: "연을 날릴 때 ___선 근처에서 하면 안 된다.", answer: "전", category: "놀이안전", gradeGroup: "3-4" },
  { text: "산에서 놀 때는 ___길을 벗어나지 않는다.", answer: "등산", category: "놀이안전", gradeGroup: "3-4" },
  { text: "캠핑 시 ___에 가까이 가지 않는다.", answer: "불", category: "놀이안전", gradeGroup: "3-4" },
  { text: "야외 놀이 후에는 ___에 물려 있는지 확인한다.", answer: "진드기", category: "놀이안전", gradeGroup: "3-4" },
  { text: "놀이공원에서 놀이기구를 탈 때 ___을 매야 한다.", answer: "안전바", category: "놀이안전", gradeGroup: "3-4" },
  { text: "축구를 할 때는 ___를 착용하여 정강이를 보호한다.", answer: "신가드", category: "놀이안전", gradeGroup: "3-4" },
  { text: "배드민턴을 할 때 라켓을 ___면 다른 사람이 다칠 수 있다.", answer: "던지", category: "놀이안전", gradeGroup: "3-4" },
  { text: "야외에서 놀 때 ___이 심하면 실내로 들어간다.", answer: "더위", category: "놀이안전", gradeGroup: "3-4" },
  { text: "공원에서 반려동물에게 함부로 ___을 가까이하면 물릴 수 있다.", answer: "손", category: "놀이안전", gradeGroup: "3-4" },
  { text: "보드게임 조각 같은 작은 ___은 동생이 삼킬 수 있어 주의한다.", answer: "부품", category: "놀이안전", gradeGroup: "3-4" },
  { text: "줄넘기를 할 때는 주변에 충분한 ___을 확보한다.", answer: "공간", category: "놀이안전", gradeGroup: "3-4" },
  { text: "등산할 때는 ___이 편한 등산화를 신는다.", answer: "발", category: "놀이안전", gradeGroup: "3-4" },
  { text: "야구공을 받을 때는 ___를 착용한다.", answer: "글러브", category: "놀이안전", gradeGroup: "3-4" },
  { text: "킥보드를 탈 때는 내리막길에서 ___를 줄여야 한다.", answer: "속도", category: "놀이안전", gradeGroup: "3-4" },
  { text: "놀이터 기구의 ___부분에 손이 끼지 않도록 주의한다.", answer: "틈", category: "놀이안전", gradeGroup: "3-4" },
  { text: "롤러코스터는 키 ___cm 이상인 사람만 탈 수 있다.", answer: "제한", category: "놀이안전", gradeGroup: "3-4" },
  { text: "폭죽이나 불꽃놀이 제품은 어린이가 ___면 안 된다.", answer: "사용하", category: "놀이안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "익스트림 스포츠를 할 때는 전문 ___의 지도 아래 해야 한다.", answer: "강사", category: "놀이안전", gradeGroup: "5-6" },
  { text: "야외 활동 시 ___예보를 미리 확인한다.", answer: "날씨", category: "놀이안전", gradeGroup: "5-6" },
  { text: "겨울에 ___판 위에서 놀 때 두께를 확인해야 한다.", answer: "얼음", category: "놀이안전", gradeGroup: "5-6" },
  { text: "승마 체험 시 반드시 ___을 착용한다.", answer: "안전모", category: "놀이안전", gradeGroup: "5-6" },
  { text: "레프팅을 할 때는 ___를 반드시 입어야 한다.", answer: "구명조끼", category: "놀이안전", gradeGroup: "5-6" },
  { text: "스키를 탈 때는 자기 ___에 맞는 코스를 선택한다.", answer: "수준", category: "놀이안전", gradeGroup: "5-6" },
  { text: "암벽 등반 시 ___장비를 반드시 점검한다.", answer: "안전", category: "놀이안전", gradeGroup: "5-6" },
  { text: "번지점프는 ___검사를 통과한 시설에서만 해야 한다.", answer: "안전", category: "놀이안전", gradeGroup: "5-6" },
  { text: "스노보드를 탈 때 ___보호대를 착용하면 손목 부상을 예방한다.", answer: "손목", category: "놀이안전", gradeGroup: "5-6" },
  { text: "패러글라이딩은 기상 ___에 따라 비행 가능 여부가 결정된다.", answer: "조건", category: "놀이안전", gradeGroup: "5-6" },
  { text: "서핑을 할 때 다른 서퍼와 충분한 ___를 유지한다.", answer: "거리", category: "놀이안전", gradeGroup: "5-6" },
  { text: "야영지에서는 야생 ___에 주의해야 한다.", answer: "동물", category: "놀이안전", gradeGroup: "5-6" },
  { text: "산악자전거를 탈 때는 전신 ___를 착용한다.", answer: "보호장구", category: "놀이안전", gradeGroup: "5-6" },
  { text: "스쿠버다이빙은 반드시 ___와 함께 해야 한다.", answer: "버디", category: "놀이안전", gradeGroup: "5-6" },
  { text: "놀이기구 안전사고 시 ___에 신고하여 조사를 요청할 수 있다.", answer: "소비자원", category: "놀이안전", gradeGroup: "5-6" },
  { text: "야외 체험 시 ___를 챙겨 탈수를 예방한다.", answer: "식수", category: "놀이안전", gradeGroup: "5-6" },
  { text: "짚라인 체험 시 ___에 이상이 없는지 직원에게 확인한다.", answer: "장비", category: "놀이안전", gradeGroup: "5-6" },
  { text: "카누를 탈 때는 반드시 ___를 착용한다.", answer: "구명조끼", category: "놀이안전", gradeGroup: "5-6" },
  { text: "야외 캠프에서 ___에 의한 식중독에 주의한다.", answer: "음식", category: "놀이안전", gradeGroup: "5-6" },
  { text: "놀이공원에서는 안전 ___의 지시에 따라야 한다.", answer: "요원", category: "놀이안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 6. 식품안전
// ─────────────────────────────────────────────
const FOOD_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "음식을 먹기 전에는 반드시 ___을 씻어야 한다.", answer: "손", category: "식품안전", gradeGroup: "1-2" },
  { text: "유통기한이 ___난 음식은 먹으면 안 된다.", answer: "지", category: "식품안전", gradeGroup: "1-2" },
  { text: "길에서 파는 음식은 ___하지 않을 수 있다.", answer: "위생적", category: "식품안전", gradeGroup: "1-2" },
  { text: "음식을 먹다 배가 아프면 ___에게 말해야 한다.", answer: "어른", category: "식품안전", gradeGroup: "1-2" },
  { text: "날것의 고기나 ___는 익혀서 먹어야 한다.", answer: "생선", category: "식품안전", gradeGroup: "1-2" },
  { text: "냉장고에서 꺼낸 음식은 ___를 확인한다.", answer: "냄새", category: "식품안전", gradeGroup: "1-2" },
  { text: "과일을 먹기 전에 깨끗이 ___야 한다.", answer: "씻어", category: "식품안전", gradeGroup: "1-2" },
  { text: "밥을 먹을 때 ___으면서 먹으면 체할 수 있다.", answer: "급하게 뛰", category: "식품안전", gradeGroup: "1-2" },
  { text: "뜨거운 음식을 먹을 때는 ___서 먹는다.", answer: "식혀", category: "식품안전", gradeGroup: "1-2" },
  { text: "떨어진 음식은 ___에 넣으면 안 된다.", answer: "입", category: "식품안전", gradeGroup: "1-2" },
  { text: "물은 끓인 물이나 정수된 ___을 마셔야 한다.", answer: "물", category: "식품안전", gradeGroup: "1-2" },
  { text: "급식을 받을 때 ___을 하고 먹는다.", answer: "손 씻기", category: "식품안전", gradeGroup: "1-2" },
  { text: "음식을 씹을 때 ___면서 먹으면 목에 걸릴 수 있다.", answer: "떠들", category: "식품안전", gradeGroup: "1-2" },
  { text: "간식은 ___을 확인하고 먹어야 한다.", answer: "유통기한", category: "식품안전", gradeGroup: "1-2" },
  { text: "우유는 ___에 보관하지 않으면 상할 수 있다.", answer: "냉장고", category: "식품안전", gradeGroup: "1-2" },
  { text: "길에 떨어진 열매를 ___면 안 된다.", answer: "먹", category: "식품안전", gradeGroup: "1-2" },
  { text: "음식을 만들기 전에 ___를 깨끗이 닦아야 한다.", answer: "조리대", category: "식품안전", gradeGroup: "1-2" },
  { text: "모르는 버섯을 ___면 중독될 수 있다.", answer: "먹", category: "식품안전", gradeGroup: "1-2" },
  { text: "음식에서 이상한 ___가 나면 먹지 않는다.", answer: "맛", category: "식품안전", gradeGroup: "1-2" },
  { text: "포장이 부풀어 오른 음식은 ___이 번식했을 수 있다.", answer: "세균", category: "식품안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "식중독을 예방하려면 음식을 ___도 이상에서 충분히 익혀야 한다.", answer: "75", category: "식품안전", gradeGroup: "3-4" },
  { text: "여름철에는 음식이 쉽게 ___하므로 주의해야 한다.", answer: "상", category: "식품안전", gradeGroup: "3-4" },
  { text: "알레르기가 있는 음식의 ___를 미리 확인해야 한다.", answer: "성분", category: "식품안전", gradeGroup: "3-4" },
  { text: "도마와 칼은 육류용과 ___용을 구분해서 사용한다.", answer: "채소", category: "식품안전", gradeGroup: "3-4" },
  { text: "손에 ___가 있을 때 음식을 만지면 세균이 옮겨질 수 있다.", answer: "상처", category: "식품안전", gradeGroup: "3-4" },
  { text: "식품 포장에 있는 ___표시를 확인하고 구매한다.", answer: "인증", category: "식품안전", gradeGroup: "3-4" },
  { text: "냉동 식품을 해동할 때는 ___에서 천천히 녹인다.", answer: "냉장고", category: "식품안전", gradeGroup: "3-4" },
  { text: "음식을 조리한 후 ___시간 이내에 먹는 것이 안전하다.", answer: "2", category: "식품안전", gradeGroup: "3-4" },
  { text: "계란을 만진 후에는 반드시 손을 ___야 한다.", answer: "씻어", category: "식품안전", gradeGroup: "3-4" },
  { text: "식중독의 3대 예방 원칙은 손 씻기, 익혀 먹기, ___보관하기이다.", answer: "냉장", category: "식품안전", gradeGroup: "3-4" },
  { text: "조리 후 남은 음식은 ___에 밀봉하여 보관한다.", answer: "용기", category: "식품안전", gradeGroup: "3-4" },
  { text: "급식에서 알레르기 유발 식품은 ___에 표시되어 있다.", answer: "식단표", category: "식품안전", gradeGroup: "3-4" },
  { text: "채소는 ___로 흐르는 물에 3번 이상 씻는다.", answer: "깨끗이", category: "식품안전", gradeGroup: "3-4" },
  { text: "음식물 쓰레기는 ___하여 위생적으로 처리한다.", answer: "분리배출", category: "식품안전", gradeGroup: "3-4" },
  { text: "한여름에 도시락을 가져갈 때 ___팩을 넣으면 좋다.", answer: "아이스", category: "식품안전", gradeGroup: "3-4" },
  { text: "손을 씻을 때는 ___초 이상 비누로 문질러야 한다.", answer: "30", category: "식품안전", gradeGroup: "3-4" },
  { text: "식기를 ___로 소독하면 세균을 제거할 수 있다.", answer: "열탕", category: "식품안전", gradeGroup: "3-4" },
  { text: "김밥은 만든 후 ___시간 이내에 먹는 것이 안전하다.", answer: "2", category: "식품안전", gradeGroup: "3-4" },
  { text: "방부제는 식품의 ___을 방지하기 위해 사용된다.", answer: "부패", category: "식품안전", gradeGroup: "3-4" },
  { text: "조리 기구는 사용 후 반드시 ___해야 한다.", answer: "세척", category: "식품안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "식중독을 일으키는 대표적 세균으로 ___균이 있다.", answer: "살모넬라", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 첨가물 중 ___제는 식품의 색을 내기 위해 사용된다.", answer: "착색", category: "식품안전", gradeGroup: "5-6" },
  { text: "HACCP 마크는 식품의 ___관리가 인증된 표시이다.", answer: "위생", category: "식품안전", gradeGroup: "5-6" },
  { text: "교차 오염을 방지하려면 조리 기구를 ___별로 구분 사용한다.", answer: "식재료", category: "식품안전", gradeGroup: "5-6" },
  { text: "구토와 설사 증상이 나타나면 ___을 의심해 볼 수 있다.", answer: "식중독", category: "식품안전", gradeGroup: "5-6" },
  { text: "가공식품의 ___표를 확인하면 영양소 정보를 알 수 있다.", answer: "영양성분", category: "식품안전", gradeGroup: "5-6" },
  { text: "식중독 예방을 위해 조리 시 ___을 착용한다.", answer: "위생장갑", category: "식품안전", gradeGroup: "5-6" },
  { text: "노로바이러스는 겨울철에 주로 발생하는 ___바이러스이다.", answer: "식중독", category: "식품안전", gradeGroup: "5-6" },
  { text: "유전자 변형 식품을 ___라고 표기한다.", answer: "GMO", category: "식품안전", gradeGroup: "5-6" },
  { text: "식중독 발생 시 의료기관에서 ___검사를 받아야 한다.", answer: "대변", category: "식품안전", gradeGroup: "5-6" },
  { text: "캄필로박터균은 주로 덜 익힌 ___에서 발견된다.", answer: "닭고기", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 이력 추적 제도를 통해 식품의 ___경로를 확인할 수 있다.", answer: "유통", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 위해 신고는 ___번으로 할 수 있다.", answer: "1399", category: "식품안전", gradeGroup: "5-6" },
  { text: "보툴리누스균은 ___식품에서 주로 발생한다.", answer: "통조림", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 알레르기의 대표적 원인 식품으로 우유, 계란, ___이 있다.", answer: "땅콩", category: "식품안전", gradeGroup: "5-6" },
  { text: "아나필락시스는 심각한 ___반응으로 응급 처치가 필요하다.", answer: "알레르기", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 안전을 관리하는 정부 기관은 ___처이다.", answer: "식품의약품안전", category: "식품안전", gradeGroup: "5-6" },
  { text: "생수의 수질 기준은 먹는 물 ___법에 의해 관리된다.", answer: "관리", category: "식품안전", gradeGroup: "5-6" },
  { text: "식품 표시에서 '소비기한'은 먹어도 ___한 마지막 날짜이다.", answer: "안전", category: "식품안전", gradeGroup: "5-6" },
  { text: "집단 식중독 발생 시 ___에 신고해야 한다.", answer: "보건소", category: "식품안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 7. 자연재해
// ─────────────────────────────────────────────
const NATURAL_DISASTER: SafetyTemplate[] = [
  // Grade 1-2
  { text: "지진이 나면 ___아래로 들어가 몸을 보호한다.", answer: "책상", category: "자연재해", gradeGroup: "1-2" },
  { text: "천둥 번개가 칠 때는 ___아래로 피하지 않는다.", answer: "나무", category: "자연재해", gradeGroup: "1-2" },
  { text: "태풍이 오면 ___을 닫고 집 안에 있어야 한다.", answer: "창문", category: "자연재해", gradeGroup: "1-2" },
  { text: "홍수가 나면 높은 ___으로 대피해야 한다.", answer: "곳", category: "자연재해", gradeGroup: "1-2" },
  { text: "비가 많이 올 때 ___에 가까이 가면 위험하다.", answer: "하천", category: "자연재해", gradeGroup: "1-2" },
  { text: "지진이 나면 ___로 머리를 보호한다.", answer: "방석", category: "자연재해", gradeGroup: "1-2" },
  { text: "태풍이 오면 밖에 있는 ___을 안으로 들여놓는다.", answer: "물건", category: "자연재해", gradeGroup: "1-2" },
  { text: "폭설이 내리면 미끄러지지 않도록 ___을 조심해서 걷는다.", answer: "길", category: "자연재해", gradeGroup: "1-2" },
  { text: "황사가 심한 날에는 ___을 쓰고 외출한다.", answer: "마스크", category: "자연재해", gradeGroup: "1-2" },
  { text: "지진이 멈추면 ___를 이용해 밖으로 나간다.", answer: "계단", category: "자연재해", gradeGroup: "1-2" },
  { text: "번개가 칠 때 물에 들어가면 ___을 당할 수 있다.", answer: "감전", category: "자연재해", gradeGroup: "1-2" },
  { text: "비가 많이 오는 날 ___이 있는 곳은 위험하다.", answer: "웅덩이", category: "자연재해", gradeGroup: "1-2" },
  { text: "큰 비가 올 때 ___도로를 걸으면 맨홀에 빠질 수 있다.", answer: "침수된", category: "자연재해", gradeGroup: "1-2" },
  { text: "지진 시 가스레인지의 ___을 잠가야 한다.", answer: "밸브", category: "자연재해", gradeGroup: "1-2" },
  { text: "폭풍이 올 때 큰 ___에서 떨어지는 가지를 조심한다.", answer: "나무", category: "자연재해", gradeGroup: "1-2" },
  { text: "갑자기 바닷물이 빠지면 ___가 올 수 있으므로 대피한다.", answer: "해일", category: "자연재해", gradeGroup: "1-2" },
  { text: "폭설로 길이 미끄러우면 ___보폭으로 걷는다.", answer: "작은", category: "자연재해", gradeGroup: "1-2" },
  { text: "우박이 내리면 ___안으로 대피한다.", answer: "건물", category: "자연재해", gradeGroup: "1-2" },
  { text: "황사가 심한 날 집에 들어오면 ___을 갈아입는다.", answer: "옷", category: "자연재해", gradeGroup: "1-2" },
  { text: "지진이 나면 유리창 근처에서 ___져야 한다.", answer: "떨어", category: "자연재해", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "지진 발생 시 흔들림이 멈추면 ___로 대피한다.", answer: "운동장", category: "자연재해", gradeGroup: "3-4" },
  { text: "태풍 시 강풍으로 날아오는 ___에 주의해야 한다.", answer: "간판", category: "자연재해", gradeGroup: "3-4" },
  { text: "지진의 세기를 나타내는 단위는 ___이다.", answer: "규모", category: "자연재해", gradeGroup: "3-4" },
  { text: "쓰나미가 발생하면 해안에서 ___로 빠르게 대피한다.", answer: "고지대", category: "자연재해", gradeGroup: "3-4" },
  { text: "폭염 시 외출을 자제하고 충분한 ___을 섭취해야 한다.", answer: "수분", category: "자연재해", gradeGroup: "3-4" },
  { text: "미세먼지가 심한 날에는 외출 후 반드시 ___을 씻는다.", answer: "손", category: "자연재해", gradeGroup: "3-4" },
  { text: "재난 발생 시 ___방송을 통해 정보를 얻는다.", answer: "재난", category: "자연재해", gradeGroup: "3-4" },
  { text: "호우 경보가 발령되면 지하 ___는 침수될 수 있으므로 대피한다.", answer: "주차장", category: "자연재해", gradeGroup: "3-4" },
  { text: "산사태 위험 지역에서는 큰 비가 올 때 ___해야 한다.", answer: "대피", category: "자연재해", gradeGroup: "3-4" },
  { text: "가뭄이 심할 때는 ___을 아껴 써야 한다.", answer: "물", category: "자연재해", gradeGroup: "3-4" },
  { text: "자연재해를 대비하여 ___가방을 미리 준비해 둔다.", answer: "비상", category: "자연재해", gradeGroup: "3-4" },
  { text: "비상 가방에는 물, 손전등, ___을 넣어 둔다.", answer: "비상식량", category: "자연재해", gradeGroup: "3-4" },
  { text: "폭염 주의보가 발령되면 오후 2시경 ___활동을 자제한다.", answer: "야외", category: "자연재해", gradeGroup: "3-4" },
  { text: "눈사태 위험 지역에서는 큰 ___를 내면 안 된다.", answer: "소리", category: "자연재해", gradeGroup: "3-4" },
  { text: "황사 발생 시 창문을 닫고 ___기를 가동한다.", answer: "공기청정", category: "자연재해", gradeGroup: "3-4" },
  { text: "태풍의 강도는 중심 부근 최대 ___으로 분류한다.", answer: "풍속", category: "자연재해", gradeGroup: "3-4" },
  { text: "집중호우 시 ___에 있으면 빠르게 높은 곳으로 이동한다.", answer: "저지대", category: "자연재해", gradeGroup: "3-4" },
  { text: "지진 시 건물 밖에 있으면 넓은 ___로 이동한다.", answer: "공터", category: "자연재해", gradeGroup: "3-4" },
  { text: "재난 시 ___전화를 이용하여 안부를 확인한다.", answer: "재난안전", category: "자연재해", gradeGroup: "3-4" },
  { text: "미세먼지 예보 등급 중 '___'이면 외출을 삼간다.", answer: "매우 나쁨", category: "자연재해", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "한국의 지진 관측은 ___청에서 담당한다.", answer: "기상", category: "자연재해", gradeGroup: "5-6" },
  { text: "긴급 재난 문자는 ___를 통해 전송된다.", answer: "휴대전화", category: "자연재해", gradeGroup: "5-6" },
  { text: "지진 대피 시 3가지 행동 수칙은 엎드려, 잡아, ___이다.", answer: "기다려", category: "자연재해", gradeGroup: "5-6" },
  { text: "태풍의 눈에서는 일시적으로 바람이 ___지만 곧 다시 강해진다.", answer: "약해", category: "자연재해", gradeGroup: "5-6" },
  { text: "폭염 시 열사병 환자가 발생하면 ___한 곳으로 옮기고 체온을 낮춘다.", answer: "시원", category: "자연재해", gradeGroup: "5-6" },
  { text: "재난 시 가족과 만날 ___을 미리 정해 둔다.", answer: "장소", category: "자연재해", gradeGroup: "5-6" },
  { text: "지진 시 ___가 차단될 수 있으므로 손전등을 준비한다.", answer: "전기", category: "자연재해", gradeGroup: "5-6" },
  { text: "화산 폭발 시 ___재가 내리면 마스크와 고글을 착용한다.", answer: "화산", category: "자연재해", gradeGroup: "5-6" },
  { text: "리히터 규모 ___이상의 지진은 건물 붕괴를 일으킬 수 있다.", answer: "6", category: "자연재해", gradeGroup: "5-6" },
  { text: "기상청의 지진 ___시스템은 국민에게 빠르게 정보를 전달한다.", answer: "조기경보", category: "자연재해", gradeGroup: "5-6" },
  { text: "재난안전 관리를 총괄하는 정부 기관은 ___부이다.", answer: "행정안전", category: "자연재해", gradeGroup: "5-6" },
  { text: "지진해일 경보 시 해안가에서 최소 ___m 이상 높은 곳으로 대피한다.", answer: "10", category: "자연재해", gradeGroup: "5-6" },
  { text: "폭염으로 인한 온열 질환 중 가장 위험한 것은 ___병이다.", answer: "열사", category: "자연재해", gradeGroup: "5-6" },
  { text: "황사의 주된 발원지는 중국의 ___사막이다.", answer: "고비", category: "자연재해", gradeGroup: "5-6" },
  { text: "기후변화로 자연재해의 ___와 강도가 증가하고 있다.", answer: "빈도", category: "자연재해", gradeGroup: "5-6" },
  { text: "홍수 피해 후 오염된 물로 인해 ___병이 발생할 수 있다.", answer: "수인성 전염", category: "자연재해", gradeGroup: "5-6" },
  { text: "산사태는 비가 많이 온 후 ___이 무너지면서 발생한다.", answer: "경사면", category: "자연재해", gradeGroup: "5-6" },
  { text: "재난 시 국민행동요령을 따르면 ___를 줄일 수 있다.", answer: "피해", category: "자연재해", gradeGroup: "5-6" },
  { text: "지진 이후 여진이 발생할 수 있으므로 ___한 곳에 머문다.", answer: "안전", category: "자연재해", gradeGroup: "5-6" },
  { text: "자연재해 피해 시 ___구호를 요청할 수 있다.", answer: "정부", category: "자연재해", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 8. 생활안전
// ─────────────────────────────────────────────
const DAILY_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "낯선 사람이 따라오면 큰 소리로 ___를 외치고 도망간다.", answer: "도와주세요", category: "생활안전", gradeGroup: "1-2" },
  { text: "모르는 사람이 사탕을 주면 ___하고 가야 한다.", answer: "거절", category: "생활안전", gradeGroup: "1-2" },
  { text: "집에 혼자 있을 때 낯선 사람이 문을 두드리면 ___을 열면 안 된다.", answer: "문", category: "생활안전", gradeGroup: "1-2" },
  { text: "밖에서 놀다 어두워지면 빨리 ___으로 돌아와야 한다.", answer: "집", category: "생활안전", gradeGroup: "1-2" },
  { text: "위험한 상황에서는 ___번으로 전화해야 한다.", answer: "112", category: "생활안전", gradeGroup: "1-2" },
  { text: "혼자 엘리베이터를 탈 때 모르는 사람과 같이 타면 ___해야 한다.", answer: "주의", category: "생활안전", gradeGroup: "1-2" },
  { text: "집 비밀번호는 다른 사람에게 ___하면 안 된다.", answer: "알려주", category: "생활안전", gradeGroup: "1-2" },
  { text: "길을 잃었을 때는 가까운 ___에 도움을 요청한다.", answer: "가게", category: "생활안전", gradeGroup: "1-2" },
  { text: "화장실에서 바닥이 젖으면 ___질 수 있으니 조심한다.", answer: "미끄러", category: "생활안전", gradeGroup: "1-2" },
  { text: "에스컬레이터에서는 ___을 잡고 서 있어야 한다.", answer: "손잡이", category: "생활안전", gradeGroup: "1-2" },
  { text: "모르는 차에 ___면 안 된다.", answer: "타", category: "생활안전", gradeGroup: "1-2" },
  { text: "밤에 외출할 때는 밝은 ___을 입는다.", answer: "옷", category: "생활안전", gradeGroup: "1-2" },
  { text: "위급할 때는 방범용 ___를 눌러 도움을 요청한다.", answer: "비상벨", category: "생활안전", gradeGroup: "1-2" },
  { text: "부모님의 ___를 외워 두면 긴급 시 연락할 수 있다.", answer: "전화번호", category: "생활안전", gradeGroup: "1-2" },
  { text: "아이들만 있는 곳에 모르는 ___이 오면 바로 자리를 피한다.", answer: "어른", category: "생활안전", gradeGroup: "1-2" },
  { text: "엘리베이터가 멈추면 ___버튼을 누른다.", answer: "비상", category: "생활안전", gradeGroup: "1-2" },
  { text: "집 주소와 부모님 이름을 ___고 있어야 한다.", answer: "알", category: "생활안전", gradeGroup: "1-2" },
  { text: "회전문에 손이나 옷이 ___지 않도록 주의한다.", answer: "끼", category: "생활안전", gradeGroup: "1-2" },
  { text: "에스컬레이터에서 ___면 위험하다.", answer: "뛰", category: "생활안전", gradeGroup: "1-2" },
  { text: "주차장에서는 차가 갑자기 움직일 수 있으므로 ___을 살핀다.", answer: "주위", category: "생활안전", gradeGroup: "1-2" },
  { text: "공사 현장 근처에서 ___를 하면 안 된다.", answer: "놀이", category: "생활안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "긴급 상황 시 자신의 위치를 정확하게 ___할 수 있어야 한다.", answer: "설명", category: "생활안전", gradeGroup: "3-4" },
  { text: "승강기 안에 갇히면 ___버튼을 누르고 구조를 기다린다.", answer: "비상호출", category: "생활안전", gradeGroup: "3-4" },
  { text: "지하철에서 비상시 ___를 열어 탈출할 수 있다.", answer: "비상문", category: "생활안전", gradeGroup: "3-4" },
  { text: "미아 방지를 위해 외출 시 부모님과 ___장소를 정한다.", answer: "만남", category: "생활안전", gradeGroup: "3-4" },
  { text: "야외 활동 시 ___크림을 발라 피부를 보호한다.", answer: "자외선 차단", category: "생활안전", gradeGroup: "3-4" },
  { text: "대형 마트에서 길을 잃으면 ___에게 도움을 요청한다.", answer: "직원", category: "생활안전", gradeGroup: "3-4" },
  { text: "재난 시 행동 요령을 담은 앱은 ___이다.", answer: "안전디딤돌", category: "생활안전", gradeGroup: "3-4" },
  { text: "119에 신고할 때는 ___를 침착하게 말해야 한다.", answer: "상황", category: "생활안전", gradeGroup: "3-4" },
  { text: "약을 잘못 먹었을 때는 ___센터에 전화한다.", answer: "독극물", category: "생활안전", gradeGroup: "3-4" },
  { text: "지하 주차장에서는 차량에 주의하며 ___를 살핀다.", answer: "주위", category: "생활안전", gradeGroup: "3-4" },
  { text: "빈집에 혼자 있을 때는 현관문을 반드시 ___야 한다.", answer: "잠가", category: "생활안전", gradeGroup: "3-4" },
  { text: "대중교통에서 비상 시 ___를 눌러 기관사에게 알린다.", answer: "비상벨", category: "생활안전", gradeGroup: "3-4" },
  { text: "야외에서 벌에 쏘이면 ___을 빼고 냉찜질한다.", answer: "침", category: "생활안전", gradeGroup: "3-4" },
  { text: "뱀을 발견하면 자극하지 말고 조용히 ___져야 한다.", answer: "떨어", category: "생활안전", gradeGroup: "3-4" },
  { text: "폭죽이나 불꽃놀이는 ___의 감독 아래 해야 한다.", answer: "어른", category: "생활안전", gradeGroup: "3-4" },
  { text: "다리 위에서 난간 밖으로 ___을 내밀면 위험하다.", answer: "몸", category: "생활안전", gradeGroup: "3-4" },
  { text: "공사 현장의 ___표지판을 반드시 따라야 한다.", answer: "안전", category: "생활안전", gradeGroup: "3-4" },
  { text: "지하철 스크린도어에 ___이 끼이지 않도록 주의한다.", answer: "가방", category: "생활안전", gradeGroup: "3-4" },
  { text: "야간에 자전거 도로를 걸을 때는 ___에 주의한다.", answer: "자전거", category: "생활안전", gradeGroup: "3-4" },
  { text: "비상 시 사용할 수 있는 ___약품을 가정에 비치한다.", answer: "응급", category: "생활안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "응급 상황에서는 ___조치를 시행하고 119에 신고한다.", answer: "응급", category: "생활안전", gradeGroup: "5-6" },
  { text: "심장이 멈춘 사람에게는 ___를 시행해야 한다.", answer: "심폐소생술", category: "생활안전", gradeGroup: "5-6" },
  { text: "코피가 나면 고개를 ___으로 숙이고 코를 누른다.", answer: "앞", category: "생활안전", gradeGroup: "5-6" },
  { text: "출혈이 심할 때는 깨끗한 천으로 상처를 ___해야 한다.", answer: "압박", category: "생활안전", gradeGroup: "5-6" },
  { text: "자동심장충격기(AED)는 공공장소에 비치된 ___장비이다.", answer: "응급", category: "생활안전", gradeGroup: "5-6" },
  { text: "골절이 의심되면 부상 부위를 ___시키고 병원에 간다.", answer: "고정", category: "생활안전", gradeGroup: "5-6" },
  { text: "열사병 환자는 체온이 ___도 이상으로 올라간 상태이다.", answer: "40", category: "생활안전", gradeGroup: "5-6" },
  { text: "심폐소생술 시 가슴 압박 깊이는 약 ___cm이다.", answer: "5", category: "생활안전", gradeGroup: "5-6" },
  { text: "성인 심폐소생술 시 가슴 압박 속도는 분당 ___회이다.", answer: "100~120", category: "생활안전", gradeGroup: "5-6" },
  { text: "화상 부위에 ___을 바르면 안 된다.", answer: "된장", category: "생활안전", gradeGroup: "5-6" },
  { text: "뇌진탕이 의심되면 환자를 ___시키고 관찰한다.", answer: "안정", category: "생활안전", gradeGroup: "5-6" },
  { text: "응급 상황에서 의식 확인은 환자의 ___을 두드리며 부른다.", answer: "어깨", category: "생활안전", gradeGroup: "5-6" },
  { text: "독사에 물리면 상처 부위를 ___보다 낮게 유지한다.", answer: "심장", category: "생활안전", gradeGroup: "5-6" },
  { text: "AED 사용 시 패드를 환자의 ___에 부착한다.", answer: "가슴", category: "생활안전", gradeGroup: "5-6" },
  { text: "기도가 막혔을 때 ___법을 시행하여 이물질을 제거한다.", answer: "하임리히", category: "생활안전", gradeGroup: "5-6" },
  { text: "삔 곳은 RICE 처치법(___·냉찜질·압박·거상)을 적용한다.", answer: "안정", category: "생활안전", gradeGroup: "5-6" },
  { text: "응급처치 자격증은 ___사에서 교육을 받으면 취득할 수 있다.", answer: "대한적십자", category: "생활안전", gradeGroup: "5-6" },
  { text: "벌레 물림으로 ___반응이 심하면 에피네프린 주사가 필요하다.", answer: "알레르기", category: "생활안전", gradeGroup: "5-6" },
  { text: "익수 환자를 구조한 후 ___유무를 먼저 확인한다.", answer: "호흡", category: "생활안전", gradeGroup: "5-6" },
  { text: "저체온증 환자에게는 ___를 덮어 체온을 올린다.", answer: "담요", category: "생활안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 9. 전기안전
// ─────────────────────────────────────────────
const ELECTRICAL_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "젖은 ___으로 콘센트를 만지면 안 된다.", answer: "손", category: "전기안전", gradeGroup: "1-2" },
  { text: "콘센트에 ___이나 젓가락을 넣으면 안 된다.", answer: "손가락", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기 제품 ___가 벗겨져 있으면 사용하면 안 된다.", answer: "코드", category: "전기안전", gradeGroup: "1-2" },
  { text: "사용하지 않는 전기 제품의 ___를 뽑아야 한다.", answer: "플러그", category: "전기안전", gradeGroup: "1-2" },
  { text: "콘센트에 물이 ___으면 감전될 수 있다.", answer: "닿", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기줄을 ___지 않도록 잘 정리해야 한다.", answer: "밟", category: "전기안전", gradeGroup: "1-2" },
  { text: "플러그를 뽑을 때는 ___를 잡고 빼야 한다.", answer: "플러그 머리", category: "전기안전", gradeGroup: "1-2" },
  { text: "어린이용 콘센트 ___를 사용하면 안전하다.", answer: "덮개", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기장판을 접어서 사용하면 ___가 날 수 있다.", answer: "화재", category: "전기안전", gradeGroup: "1-2" },
  { text: "번개가 칠 때 전자기기의 ___를 뽑아야 한다.", answer: "플러그", category: "전기안전", gradeGroup: "1-2" },
  { text: "전선 위의 ___을 절대 잡으면 안 된다.", answer: "연", category: "전기안전", gradeGroup: "1-2" },
  { text: "고압 ___근처에서 놀면 감전 위험이 있다.", answer: "전선", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기 제품에 물을 ___으면 안 된다.", answer: "쏟", category: "전기안전", gradeGroup: "1-2" },
  { text: "충전기를 사용하지 않을 때는 ___에서 빼 놓는다.", answer: "콘센트", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기 코드를 ___으면 안에 선이 끊어질 수 있다.", answer: "구부리", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기 난로에 종이나 ___을 올리면 불이 날 수 있다.", answer: "옷", category: "전기안전", gradeGroup: "1-2" },
  { text: "전기 기구에서 ___가 나면 바로 사용을 중단한다.", answer: "연기", category: "전기안전", gradeGroup: "1-2" },
  { text: "야외에서 끊어진 ___을 만지면 감전된다.", answer: "전선", category: "전기안전", gradeGroup: "1-2" },
  { text: "전등을 교체할 때는 먼저 ___를 끄고 한다.", answer: "스위치", category: "전기안전", gradeGroup: "1-2" },
  { text: "콘센트 주변에 ___가 쌓이면 화재 위험이 있다.", answer: "먼지", category: "전기안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "문어발식 ___사용은 과열로 화재가 날 수 있다.", answer: "콘센트", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기가 통하는 물체를 ___체라고 한다.", answer: "도", category: "전기안전", gradeGroup: "3-4" },
  { text: "감전 사고 시에는 먼저 ___를 차단해야 한다.", answer: "전원", category: "전기안전", gradeGroup: "3-4" },
  { text: "물 근처에서 ___기를 사용하면 감전 위험이 있다.", answer: "전기", category: "전기안전", gradeGroup: "3-4" },
  { text: "멀티탭에 허용 전력 이상을 사용하면 ___이 발생할 수 있다.", answer: "과부하", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 안전 마크인 ___마크가 있는 제품을 사용한다.", answer: "KC", category: "전기안전", gradeGroup: "3-4" },
  { text: "욕실에서 ___기를 사용할 때는 특히 조심해야 한다.", answer: "드라이", category: "전기안전", gradeGroup: "3-4" },
  { text: "누전 차단기는 전기 ___을 방지하는 장치이다.", answer: "사고", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 합선은 ___를 일으킬 수 있는 위험한 현상이다.", answer: "화재", category: "전기안전", gradeGroup: "3-4" },
  { text: "정전 시 ___를 사용하고 양초는 화재 위험이 있다.", answer: "손전등", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 기구의 ___을 정기적으로 점검해야 한다.", answer: "코드", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 합선을 예방하려면 오래된 ___를 교체한다.", answer: "배선", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 안전 점검은 ___에 1회 이상 받아야 한다.", answer: "년", category: "전기안전", gradeGroup: "3-4" },
  { text: "충전 중인 스마트폰을 ___위에 올려놓으면 과열될 수 있다.", answer: "이불", category: "전기안전", gradeGroup: "3-4" },
  { text: "전기 제품을 분해하거나 ___하면 안 된다.", answer: "개조", category: "전기안전", gradeGroup: "3-4" },
  { text: "비 오는 날 야외 ___기구를 사용하면 감전 위험이 있다.", answer: "전기", category: "전기안전", gradeGroup: "3-4" },
  { text: "전자레인지에 ___용기를 넣으면 불꽃이 발생한다.", answer: "금속", category: "전기안전", gradeGroup: "3-4" },
  { text: "콘센트 주변을 ___하게 유지하면 화재를 예방할 수 있다.", answer: "깨끗", category: "전기안전", gradeGroup: "3-4" },
  { text: "과전류가 흐르면 ___기가 자동으로 전기를 차단한다.", answer: "차단", category: "전기안전", gradeGroup: "3-4" },
  { text: "에어컨 필터에 ___가 쌓이면 과열 원인이 된다.", answer: "먼지", category: "전기안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "인체에 흐르는 전류가 ___mA 이상이면 생명이 위험하다.", answer: "50", category: "전기안전", gradeGroup: "5-6" },
  { text: "접지는 전기가 ___으로 흘러가게 하여 감전을 방지한다.", answer: "땅", category: "전기안전", gradeGroup: "5-6" },
  { text: "가정용 전압은 ___볼트이다.", answer: "220", category: "전기안전", gradeGroup: "5-6" },
  { text: "감전된 사람을 구할 때 ___이 통하지 않는 물건으로 분리한다.", answer: "전기", category: "전기안전", gradeGroup: "5-6" },
  { text: "절연 처리란 전기가 ___하지 못하게 막는 것이다.", answer: "통", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기 사고를 예방하기 위해 정기적으로 ___검사를 받아야 한다.", answer: "전기안전", category: "전기안전", gradeGroup: "5-6" },
  { text: "번개는 구름과 땅 사이의 ___방전 현상이다.", answer: "전기", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기 화재 시 ABC 소화기보다 ___소화기가 적합하다.", answer: "CO2", category: "전기안전", gradeGroup: "5-6" },
  { text: "낙뢰 발생 시 자동차 안에 있으면 ___효과로 안전하다.", answer: "패러데이 케이지", category: "전기안전", gradeGroup: "5-6" },
  { text: "고압 전선에 접근 시 최소 ___m 이상 거리를 유지해야 한다.", answer: "10", category: "전기안전", gradeGroup: "5-6" },
  { text: "누전은 전기가 의도하지 않은 ___로 흐르는 현상이다.", answer: "경로", category: "전기안전", gradeGroup: "5-6" },
  { text: "감전 시 심장이 멎을 수 있으므로 ___를 시행한다.", answer: "심폐소생술", category: "전기안전", gradeGroup: "5-6" },
  { text: "대용량 전기 기기는 전용 ___를 사용해야 한다.", answer: "콘센트", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기 사고 통계에서 ___이 가장 많이 발생하는 계절이다.", answer: "여름", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기설비 ___은 한국전기안전공사에서 담당한다.", answer: "점검", category: "전기안전", gradeGroup: "5-6" },
  { text: "과부하로 콘센트가 뜨거워지면 즉시 ___를 뽑아야 한다.", answer: "플러그", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기 안전을 위해 접지가 있는 ___핀 플러그를 사용한다.", answer: "3", category: "전기안전", gradeGroup: "5-6" },
  { text: "태양광 패널도 ___이 발생할 수 있으므로 함부로 만지면 안 된다.", answer: "감전", category: "전기안전", gradeGroup: "5-6" },
  { text: "배터리가 부풀어 오르면 ___위험이 있으므로 사용을 중단한다.", answer: "폭발", category: "전기안전", gradeGroup: "5-6" },
  { text: "전기 안전을 위해 정격 ___에 맞는 퓨즈를 사용한다.", answer: "용량", category: "전기안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 10. 물놀이안전
// ─────────────────────────────────────────────
const WATER_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "물놀이할 때는 반드시 ___를 입어야 한다.", answer: "구명조끼", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "수영장에 들어가기 전에 ___운동을 해야 한다.", answer: "준비", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물이 깊은 곳에서는 ___없이 들어가면 안 된다.", answer: "어른", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물에 빠진 사람을 보면 직접 들어가지 말고 ___에게 알린다.", answer: "어른", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "밥을 먹은 직후 물에 들어가면 ___가 날 수 있다.", answer: "경련", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "계곡에서 놀 때 ___가 미끄러우므로 조심한다.", answer: "바위", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "바다에서 놀 때 ___이 빠지면 옆으로 헤엄쳐 나와야 한다.", answer: "물살", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이 중 ___이 나면 즉시 물에서 나와야 한다.", answer: "오한", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이 전에 심장에서 먼 부위부터 ___을 적셔야 한다.", answer: "물", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "수영장에서 ___는 것은 위험하다.", answer: "뛰", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이를 할 때는 ___이 있는 곳에서 해야 한다.", answer: "안전요원", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "수영을 못하는 사람은 ___에서만 물놀이한다.", answer: "얕은 곳", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이 시 친구를 ___면 안 된다.", answer: "물속에 밀", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "튜브가 ___져 있으면 사용하면 안 된다.", answer: "찢어", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "계곡 물놀이 시 ___가 빠르면 들어가지 않는다.", answer: "물살", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물속에서 장난으로 친구의 ___를 잡아당기면 안 된다.", answer: "다리", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이 중 ___이 차가우면 몸에 이상이 온 것이다.", answer: "입술", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "수영장에서 ___에 다이빙하면 안 된다.", answer: "얕은 곳", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "물놀이 후에는 귀에 들어간 ___을 빼야 한다.", answer: "물", category: "물놀이안전", gradeGroup: "1-2" },
  { text: "바다에서 멀리 나가면 파도에 ___할 수 있다.", answer: "휩쓸릴", category: "물놀이안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "이안류에 빠지면 해안과 ___방향으로 헤엄쳐야 한다.", answer: "평행한", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "낚시터 근처의 ___선에 감전될 수 있으므로 주의한다.", answer: "전", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물에 빠진 사람에게 ___이나 긴 막대를 던져 준다.", answer: "줄", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "하천에서 물놀이 시 갑작스러운 ___으로 수위가 오를 수 있다.", answer: "비", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "수영 실력이 좋아도 ___에서 혼자 수영하면 안 된다.", answer: "바다", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물놀이 시 체온이 떨어지면 ___이 올 수 있다.", answer: "저체온증", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "해수욕장의 ___깃발은 수영 금지 신호이다.", answer: "빨간", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물에 빠졌을 때 옷을 입고 있으면 ___처럼 부풀려 뜨는 방법이 있다.", answer: "풍선", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "워터파크에서 미끄럼틀을 탈 때는 ___를 유지한다.", answer: "자세", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "수영 시 ___을 먹지 않도록 주의한다.", answer: "물", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물놀이 시 구명 ___의 위치를 미리 확인한다.", answer: "환", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "보트를 탈 때는 한쪽으로 ___기울이면 전복될 수 있다.", answer: "치우쳐", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "음식을 먹은 후 ___분 이상 쉬고 물에 들어간다.", answer: "30", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물놀이 시 체력이 ___지면 즉시 물에서 나와야 한다.", answer: "떨어", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "수영장 물은 ___소독을 하므로 눈을 보호하기 위해 고글을 쓴다.", answer: "염소", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "갯벌 체험 시 ___시간을 확인하고 들어가야 한다.", answer: "물때", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "급류에 빠지면 ___을 위로 향하게 하고 떠내려간다.", answer: "발", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "물놀이 시 귀중품은 ___에 보관한다.", answer: "사물함", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "카약이나 카누를 탈 때는 ___교육을 먼저 받는다.", answer: "안전", category: "물놀이안전", gradeGroup: "3-4" },
  { text: "파도가 높은 날에는 해수욕장에서 ___금지이다.", answer: "수영", category: "물놀이안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "익수자 발견 시 직접 구조보다 ___에 신고하는 것이 우선이다.", answer: "119", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "인공호흡 시 환자의 ___를 젖혀 기도를 확보한다.", answer: "턱", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "물에 빠진 사람을 구조할 때 ___을 잡히면 함께 빠질 수 있다.", answer: "손", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "잠수를 오래 하면 ___부족으로 의식을 잃을 수 있다.", answer: "산소", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "수상 안전사고 예방을 위해 ___자격증을 취득하면 좋다.", answer: "수영", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "급류에서는 발을 ___방향으로 향하게 하고 떠내려간다.", answer: "하류", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "물놀이 안전수칙을 지키지 않으면 ___사고로 이어질 수 있다.", answer: "익사", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "수상 구조 시 구조자는 ___을 확보하고 접근해야 한다.", answer: "부력", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "스쿠버다이빙 시 급격히 올라오면 ___증이 발생할 수 있다.", answer: "감압", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "해수욕장에서 ___가 변할 때 즉시 물에서 나와야 한다.", answer: "날씨", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "익수 사고 시 골든타임은 약 ___분이다.", answer: "4", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "생존 수영에서 ___뜨기 기술은 체력 소모를 줄인다.", answer: "누워", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "수상 안전법에 따라 유선장에는 ___가 배치되어야 한다.", answer: "안전요원", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "해양 사고 시 ___청에 구조를 요청한다.", answer: "해양경찰", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "물에 빠진 사람 구조 시 ___을 던져 주는 것이 안전하다.", answer: "구명환", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "수상 레저 활동 시 ___보험에 가입하면 안전하다.", answer: "보험", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "바다에서 수영 시 ___표시 밖으로 나가면 안 된다.", answer: "안전구역", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "자연 하천에서 수영하면 ___의 변화로 위험할 수 있다.", answer: "수심", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "익수 예방을 위해 학교에서 생존 ___교육을 실시한다.", answer: "수영", category: "물놀이안전", gradeGroup: "5-6" },
  { text: "여름철 물놀이 사고를 예방하기 위해 ___수칙을 숙지한다.", answer: "안전", category: "물놀이안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 11. 가정안전
// ─────────────────────────────────────────────
const HOME_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "부엌의 ___한 것은 어린이가 만지면 안 된다.", answer: "날카로운", category: "가정안전", gradeGroup: "1-2" },
  { text: "뜨거운 ___을 만지면 화상을 입을 수 있다.", answer: "냄비", category: "가정안전", gradeGroup: "1-2" },
  { text: "세제나 ___를 먹으면 안 된다.", answer: "약", category: "가정안전", gradeGroup: "1-2" },
  { text: "욕실 바닥이 미끄러우므로 ___매트를 깔아야 한다.", answer: "미끄럼 방지", category: "가정안전", gradeGroup: "1-2" },
  { text: "창문 밖으로 ___을 내밀면 위험하다.", answer: "몸", category: "가정안전", gradeGroup: "1-2" },
  { text: "가스레인지를 어린이가 ___면 안 된다.", answer: "켜", category: "가정안전", gradeGroup: "1-2" },
  { text: "높은 곳의 물건을 꺼낼 때 ___을 안정적으로 놓고 올라간다.", answer: "의자", category: "가정안전", gradeGroup: "1-2" },
  { text: "집 안에서 ___를 신으면 미끄러질 수 있다.", answer: "양말", category: "가정안전", gradeGroup: "1-2" },
  { text: "서랍장이나 책장이 ___질 수 있으므로 올라타면 안 된다.", answer: "넘어", category: "가정안전", gradeGroup: "1-2" },
  { text: "다리미를 사용한 후에는 ___를 뽑아야 한다.", answer: "코드", category: "가정안전", gradeGroup: "1-2" },
  { text: "목욕할 때 뜨거운 ___에 화상을 입지 않도록 조심한다.", answer: "물", category: "가정안전", gradeGroup: "1-2" },
  { text: "작은 물건이나 ___를 입에 넣으면 목에 걸릴 수 있다.", answer: "장난감", category: "가정안전", gradeGroup: "1-2" },
  { text: "베란다에서 ___를 던지면 아래 사람이 다칠 수 있다.", answer: "물건", category: "가정안전", gradeGroup: "1-2" },
  { text: "가정에서 ___감지기를 설치하면 화재를 조기에 발견할 수 있다.", answer: "연기", category: "가정안전", gradeGroup: "1-2" },
  { text: "화장실 문잠금이 고장나면 ___에게 도움을 요청한다.", answer: "어른", category: "가정안전", gradeGroup: "1-2" },
  { text: "계단에서 ___을 신으면 미끄러질 수 있다.", answer: "양말", category: "가정안전", gradeGroup: "1-2" },
  { text: "집에서 청소기를 사용할 때 전선에 ___지 않도록 조심한다.", answer: "걸리", category: "가정안전", gradeGroup: "1-2" },
  { text: "부엌 가위는 사용 후 ___에 안전하게 보관한다.", answer: "서랍", category: "가정안전", gradeGroup: "1-2" },
  { text: "형광등이 깜빡이면 ___에게 알려 교체해야 한다.", answer: "어른", category: "가정안전", gradeGroup: "1-2" },
  { text: "침대 위에서 ___면 떨어져 다칠 수 있다.", answer: "뛰", category: "가정안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "가스 밸브는 외출 시 반드시 ___야 한다.", answer: "잠가", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정에서 사용하는 소화기의 위치를 ___고 있어야 한다.", answer: "알", category: "가정안전", gradeGroup: "3-4" },
  { text: "가전제품 위에 ___을 올려놓으면 안 된다.", answer: "물컵", category: "가정안전", gradeGroup: "3-4" },
  { text: "환기를 위해 정기적으로 ___을 열어야 한다.", answer: "창문", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정 내 ___경보기는 일산화탄소 중독을 예방한다.", answer: "가스", category: "가정안전", gradeGroup: "3-4" },
  { text: "욕실에서 ___가 켜진 채로 잠들면 위험하다.", answer: "온수기", category: "가정안전", gradeGroup: "3-4" },
  { text: "가구를 벽에 ___으로 고정하면 전도 사고를 예방할 수 있다.", answer: "L자 금구", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정에서 ___소화기를 비치하면 초기 화재 진압에 도움된다.", answer: "소형", category: "가정안전", gradeGroup: "3-4" },
  { text: "세탁기 사용 후 ___를 닫아 어린이 사고를 예방한다.", answer: "뚜껑", category: "가정안전", gradeGroup: "3-4" },
  { text: "보일러 배기구가 ___되면 가스 중독 위험이 있다.", answer: "막히", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정용 CCTV를 설치하면 ___을 예방할 수 있다.", answer: "침입", category: "가정안전", gradeGroup: "3-4" },
  { text: "조리 중 기름이 튀면 ___으로 덮어 진화한다.", answer: "뚜껑", category: "가정안전", gradeGroup: "3-4" },
  { text: "집 안에서 인화성 물질은 ___한 곳에 보관한다.", answer: "서늘", category: "가정안전", gradeGroup: "3-4" },
  { text: "욕조에 물을 받아 놓고 ___를 떠나면 안 된다.", answer: "자리", category: "가정안전", gradeGroup: "3-4" },
  { text: "정수기의 ___는 정기적으로 교체해야 한다.", answer: "필터", category: "가정안전", gradeGroup: "3-4" },
  { text: "전기밥솥의 ___이 나올 때 손을 대면 화상을 입는다.", answer: "증기", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정에서 지진 대비를 위해 가구를 ___에 고정한다.", answer: "벽", category: "가정안전", gradeGroup: "3-4" },
  { text: "식기세척기 세제는 어린이 손이 닿지 않는 ___에 보관한다.", answer: "곳", category: "가정안전", gradeGroup: "3-4" },
  { text: "가정 내 ___경로를 2개 이상 확보해 두어야 한다.", answer: "대피", category: "가정안전", gradeGroup: "3-4" },
  { text: "집 안의 미끄러운 바닥에는 ___매트를 깔아 둔다.", answer: "미끄럼 방지", category: "가정안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "일산화탄소는 무색무취의 ___한 기체이다.", answer: "유독", category: "가정안전", gradeGroup: "5-6" },
  { text: "겨울철 보일러 사용 시 ___가스 중독에 주의해야 한다.", answer: "일산화탄소", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 내 응급 처치 ___를 비치해 두면 좋다.", answer: "키트", category: "가정안전", gradeGroup: "5-6" },
  { text: "화재 시 대피 ___를 가족과 함께 미리 계획한다.", answer: "경로", category: "가정안전", gradeGroup: "5-6" },
  { text: "아파트 화재 시 현관문을 닫고 ___으로 대피하면 연기 유입을 줄일 수 있다.", answer: "베란다", category: "가정안전", gradeGroup: "5-6" },
  { text: "실내 ___를 정기적으로 측정하면 건강을 지킬 수 있다.", answer: "공기질", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정에서 소화기를 비치할 때는 접근이 ___한 곳에 둔다.", answer: "쉬운", category: "가정안전", gradeGroup: "5-6" },
  { text: "노후 주택의 ___배관은 누수와 가스 사고의 원인이 된다.", answer: "가스", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 내 미세먼지를 줄이려면 정기적으로 ___해야 한다.", answer: "환기", category: "가정안전", gradeGroup: "5-6" },
  { text: "겨울철 동파 방지를 위해 수도관에 ___을 감아 둔다.", answer: "보온재", category: "가정안전", gradeGroup: "5-6" },
  { text: "라돈은 지하에서 올라오는 방사성 ___이다.", answer: "기체", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 내 전기 용량 초과 시 ___이 자주 내려간다.", answer: "차단기", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 화재 시 현관문을 닫으면 ___확산을 지연시킨다.", answer: "화재", category: "가정안전", gradeGroup: "5-6" },
  { text: "어린이 안전사고 예방을 위해 ___장치를 설치한다.", answer: "안전", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정에서 사용하는 LPG는 공기보다 ___아래에 모인다.", answer: "무거워", category: "가정안전", gradeGroup: "5-6" },
  { text: "도시가스(LNG)는 공기보다 ___위로 올라간다.", answer: "가벼워", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 안전 점검 체크리스트를 만들어 ___적으로 확인한다.", answer: "정기", category: "가정안전", gradeGroup: "5-6" },
  { text: "화재 시 아파트 세대 간 ___을 파괴하고 대피할 수 있다.", answer: "경량칸막이", category: "가정안전", gradeGroup: "5-6" },
  { text: "가정 내 ___중독 예방을 위해 보일러를 정기 점검한다.", answer: "일산화탄소", category: "가정안전", gradeGroup: "5-6" },
  { text: "노후 아파트의 ___시설을 정기적으로 점검하면 사고를 예방한다.", answer: "소방", category: "가정안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 12. 약물안전
// ─────────────────────────────────────────────
const DRUG_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "약은 반드시 ___의 허락 아래 먹어야 한다.", answer: "어른", category: "약물안전", gradeGroup: "1-2" },
  { text: "약을 사탕이라고 생각하고 많이 먹으면 ___하다.", answer: "위험", category: "약물안전", gradeGroup: "1-2" },
  { text: "세제나 표백제는 음식이 아니므로 ___면 안 된다.", answer: "먹", category: "약물안전", gradeGroup: "1-2" },
  { text: "모르는 액체를 ___에 넣으면 안 된다.", answer: "입", category: "약물안전", gradeGroup: "1-2" },
  { text: "약은 어린이 손이 닿지 않는 ___에 보관한다.", answer: "곳", category: "약물안전", gradeGroup: "1-2" },
  { text: "친구가 준 약을 함부로 먹으면 ___할 수 있다.", answer: "위험", category: "약물안전", gradeGroup: "1-2" },
  { text: "약을 먹고 몸이 이상하면 바로 ___에게 알린다.", answer: "부모님", category: "약물안전", gradeGroup: "1-2" },
  { text: "세제 용기에 다른 ___을 담으면 혼동할 수 있어 위험하다.", answer: "액체", category: "약물안전", gradeGroup: "1-2" },
  { text: "약은 정해진 ___만큼만 먹어야 한다.", answer: "양", category: "약물안전", gradeGroup: "1-2" },
  { text: "알록달록한 세제를 ___로 착각하면 안 된다.", answer: "음료수", category: "약물안전", gradeGroup: "1-2" },
  { text: "집에 있는 ___류는 어린이가 열 수 없는 곳에 보관한다.", answer: "화학제품", category: "약물안전", gradeGroup: "1-2" },
  { text: "약을 먹을 때는 ___과 함께 먹는다.", answer: "물", category: "약물안전", gradeGroup: "1-2" },
  { text: "약통에 있는 약이라도 어른의 ___없이 먹으면 안 된다.", answer: "허락", category: "약물안전", gradeGroup: "1-2" },
  { text: "눈약은 ___의 도움을 받아 넣어야 한다.", answer: "어른", category: "약물안전", gradeGroup: "1-2" },
  { text: "감기약을 먹으면 ___이 올 수 있으니 주의한다.", answer: "졸음", category: "약물안전", gradeGroup: "1-2" },
  { text: "향수나 방향제를 ___에 뿌리면 안 된다.", answer: "입", category: "약물안전", gradeGroup: "1-2" },
  { text: "모기약이나 살충제를 ___에 뿌리면 안 된다.", answer: "음식", category: "약물안전", gradeGroup: "1-2" },
  { text: "약은 과자나 사탕이 ___므로 함부로 먹으면 안 된다.", answer: "아니", category: "약물안전", gradeGroup: "1-2" },
  { text: "손 소독제를 ___에 넣으면 안 된다.", answer: "입", category: "약물안전", gradeGroup: "1-2" },
  { text: "반창고를 붙일 때 상처를 먼저 ___하게 한다.", answer: "깨끗", category: "약물안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "약국에서 처방전 없이 살 수 있는 약을 ___약이라고 한다.", answer: "일반", category: "약물안전", gradeGroup: "3-4" },
  { text: "약을 먹을 때 ___기한을 확인해야 한다.", answer: "유효", category: "약물안전", gradeGroup: "3-4" },
  { text: "남의 ___약을 먹으면 부작용이 생길 수 있다.", answer: "처방", category: "약물안전", gradeGroup: "3-4" },
  { text: "약 부작용이 나타나면 즉시 ___사에게 알려야 한다.", answer: "의", category: "약물안전", gradeGroup: "3-4" },
  { text: "항생제는 의사의 지시대로 끝까지 ___해야 한다.", answer: "복용", category: "약물안전", gradeGroup: "3-4" },
  { text: "약을 보관할 때 직사광선을 ___해야 한다.", answer: "피", category: "약물안전", gradeGroup: "3-4" },
  { text: "약의 ___서를 읽고 용법과 용량을 확인한다.", answer: "설명", category: "약물안전", gradeGroup: "3-4" },
  { text: "먹다 남은 약은 약국의 ___수거함에 반납한다.", answer: "폐의약품", category: "약물안전", gradeGroup: "3-4" },
  { text: "약을 복용할 때 다른 약과의 ___작용을 확인해야 한다.", answer: "상호", category: "약물안전", gradeGroup: "3-4" },
  { text: "연고는 상처 부위에만 ___게 바른다.", answer: "얇", category: "약물안전", gradeGroup: "3-4" },
  { text: "해열제는 체온이 ___도 이상일 때 복용한다.", answer: "38", category: "약물안전", gradeGroup: "3-4" },
  { text: "약의 ___반응이 나타나면 복용을 중단하고 병원에 간다.", answer: "알레르기", category: "약물안전", gradeGroup: "3-4" },
  { text: "처방약은 약사가 알려 준 ___과 시간을 지켜 먹는다.", answer: "용량", category: "약물안전", gradeGroup: "3-4" },
  { text: "가정 상비약에는 소독약, 해열제, ___이 포함된다.", answer: "반창고", category: "약물안전", gradeGroup: "3-4" },
  { text: "약을 보관할 때 ___와 습기를 피해야 한다.", answer: "고온", category: "약물안전", gradeGroup: "3-4" },
  { text: "물약은 사용 전에 ___들어 섞어야 한다.", answer: "흔", category: "약물안전", gradeGroup: "3-4" },
  { text: "냉장 보관이 필요한 약은 ___에 넣어야 한다.", answer: "냉장고", category: "약물안전", gradeGroup: "3-4" },
  { text: "약의 색이 변하거나 냄새가 이상하면 ___해야 한다.", answer: "폐기", category: "약물안전", gradeGroup: "3-4" },
  { text: "감기약을 먹고 ___을 운전하면 사고 위험이 있다.", answer: "차", category: "약물안전", gradeGroup: "3-4" },
  { text: "약을 종류별로 ___하여 보관하면 혼동을 줄일 수 있다.", answer: "분류", category: "약물안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "담배에 포함된 ___은 강한 중독성이 있는 물질이다.", answer: "니코틴", category: "약물안전", gradeGroup: "5-6" },
  { text: "청소년 음주는 뇌 ___에 심각한 영향을 미친다.", answer: "발달", category: "약물안전", gradeGroup: "5-6" },
  { text: "본드나 가스를 흡입하는 것은 ___흡입이라 하며 불법이다.", answer: "환각물질", category: "약물안전", gradeGroup: "5-6" },
  { text: "마약류는 법으로 엄격히 ___되어 있다.", answer: "금지", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 오남용 상담 전화번호는 ___번이다.", answer: "1393", category: "약물안전", gradeGroup: "5-6" },
  { text: "카페인을 과다 섭취하면 ___장이 빨리 뛰는 증상이 나타난다.", answer: "심", category: "약물안전", gradeGroup: "5-6" },
  { text: "에너지 음료의 과다 섭취는 청소년 ___에 해롭다.", answer: "건강", category: "약물안전", gradeGroup: "5-6" },
  { text: "전자담배도 일반 담배와 마찬가지로 ___에 해롭다.", answer: "건강", category: "약물안전", gradeGroup: "5-6" },
  { text: "간접흡연도 비흡연자의 ___에 해롭다.", answer: "건강", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 남용은 뇌의 ___계를 교란시킨다.", answer: "보상", category: "약물안전", gradeGroup: "5-6" },
  { text: "청소년기 음주는 ___세포 손상을 일으킨다.", answer: "뇌", category: "약물안전", gradeGroup: "5-6" },
  { text: "담배의 타르는 ___암의 주요 원인이다.", answer: "폐", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 의존성이 생기면 ___없이는 정상 생활이 어렵다.", answer: "약물", category: "약물안전", gradeGroup: "5-6" },
  { text: "처방전 없이 수면제를 복용하면 ___위험이 있다.", answer: "중독", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 오남용 예방교육은 학교에서 연 ___회 이상 실시한다.", answer: "1", category: "약물안전", gradeGroup: "5-6" },
  { text: "흡입제 남용은 뇌와 ___에 심각한 손상을 준다.", answer: "간", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 문제가 있을 때 ___센터에서 상담을 받을 수 있다.", answer: "중독관리통합지원", category: "약물안전", gradeGroup: "5-6" },
  { text: "청소년 ___방지법에 따라 미성년자에게 주류를 판매하면 처벌된다.", answer: "보호", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물에 대한 올바른 ___을 갖는 것이 예방의 첫걸음이다.", answer: "지식", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 남용 예방을 위해 또래 ___프로그램이 운영된다.", answer: "상담", category: "약물안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 13. 개인정보보호
// ─────────────────────────────────────────────
const PRIVACY_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "나의 이름, 나이, ___를 모르는 사람에게 알려 주면 안 된다.", answer: "주소", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "인터넷에 나의 ___를 올리면 안 된다.", answer: "사진", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "전화로 개인정보를 물어보는 사람에게 ___하면 안 된다.", answer: "대답", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "우리 집 ___번호는 비밀로 해야 한다.", answer: "현관", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "학교에서 나의 ___를 친구에게 함부로 보여 주면 안 된다.", answer: "시험지", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "다른 사람의 ___을 허락 없이 찍으면 안 된다.", answer: "사진", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "인터넷 회원가입 시 부모님의 ___을 받아야 한다.", answer: "동의", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "내 이름표를 ___에게 보여 주면 안 된다.", answer: "모르는 사람", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "SNS에 가족의 ___를 올리기 전에 허락을 받아야 한다.", answer: "사진", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "친구의 ___를 다른 친구에게 함부로 알려 주면 안 된다.", answer: "비밀", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "택배 상자에 적힌 ___를 폐기 전에 지워야 한다.", answer: "주소", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "학교에서 받은 가정통신문의 ___를 함부로 버리면 안 된다.", answer: "개인정보", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "내 ___은 나만 아는 비밀이어야 한다.", answer: "비밀번호", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "온라인에서 학교 이름을 알려 주면 내 ___를 알 수 있어 위험하다.", answer: "위치", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "가족의 ___을 모르는 사람에게 말하면 안 된다.", answer: "전화번호", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "친구와 찍은 사진을 인터넷에 올리려면 ___을 받아야 한다.", answer: "허락", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "나의 ___를 인터넷에 올리면 나쁜 사람이 찾아올 수 있다.", answer: "집 사진", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "이름표를 ___에 보이게 달고 다니면 위험할 수 있다.", answer: "밖", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "학원 시간표를 인터넷에 올리면 내 ___을 알 수 있다.", answer: "일정", category: "개인정보보호", gradeGroup: "1-2" },
  { text: "전화로 아빠 이름을 물어보는 사람에게 대답하면 ___하다.", answer: "위험", category: "개인정보보호", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "인터넷 사이트마다 다른 ___를 사용하면 안전하다.", answer: "비밀번호", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "공공 컴퓨터에서 사용 후 반드시 ___아웃해야 한다.", answer: "로그", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "온라인 게임에서 개인정보를 물어보면 ___이다.", answer: "사기", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "앱 설치 시 불필요한 ___권한 요청은 거부한다.", answer: "접근", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "개인정보가 유출되면 ___를 즉시 변경해야 한다.", answer: "비밀번호", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "스마트폰에 ___잠금을 설정하면 개인정보를 보호할 수 있다.", answer: "화면", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "무료 와이파이에서 개인정보를 입력하면 ___될 수 있다.", answer: "유출", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "이메일에 첨부된 의심스러운 ___을 열면 안 된다.", answer: "파일", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "비밀번호를 정기적으로 ___하면 보안이 강화된다.", answer: "변경", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "개인정보가 적힌 종이는 ___기로 파쇄한다.", answer: "문서세단", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "위치 공유 기능은 필요할 때만 ___고 평소에는 끈다.", answer: "켜", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "게임 아이디에 실명을 사용하면 ___가 노출될 수 있다.", answer: "신원", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "사진의 위치 정보(GPS)가 포함되면 촬영 ___이 노출된다.", answer: "장소", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "QR코드를 함부로 ___하면 악성 사이트로 이동할 수 있다.", answer: "스캔", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "개인정보를 요구하는 이벤트에 ___없이 참여하면 위험하다.", answer: "확인", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "친구의 개인정보를 인터넷에 올리면 ___침해이다.", answer: "개인정보", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "블루투스를 사용하지 않을 때는 ___야 한다.", answer: "꺼", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "인터넷 가입 시 필수 정보만 입력하고 ___정보는 입력하지 않는다.", answer: "선택", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "택배 송장의 개인정보는 ___후 버려야 한다.", answer: "제거", category: "개인정보보호", gradeGroup: "3-4" },
  { text: "개인정보가 담긴 USB는 ___를 설정하여 보호한다.", answer: "암호", category: "개인정보보호", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "개인정보보호법은 개인의 ___를 보호하기 위한 법률이다.", answer: "정보", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "만 ___세 미만 아동의 개인정보 수집 시 법정대리인 동의가 필요하다.", answer: "14", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "개인정보 유출 시 ___위원회에 신고할 수 있다.", answer: "개인정보보호", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "보이스피싱은 ___를 이용한 금융 사기이다.", answer: "전화", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "스미싱은 문자 ___에 포함된 링크로 개인정보를 탈취한다.", answer: "메시지", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "개인정보를 안전하게 삭제하려면 ___를 완전 소거해야 한다.", answer: "데이터", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "주민등록번호는 가장 중요한 ___이므로 절대 공개하면 안 된다.", answer: "개인정보", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "쿠키 수집 ___를 읽고 동의 여부를 결정해야 한다.", answer: "정책", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "GDPR은 유럽의 ___보호 규정이다.", answer: "개인정보", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "해킹 피해를 당하면 ___에 신고한다.", answer: "사이버수사대", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "인터넷 서비스 탈퇴 시 ___를 요청할 수 있다.", answer: "정보 삭제", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "개인정보 침해 신고는 ___번으로 할 수 있다.", answer: "118", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "이중 인증(2FA)은 비밀번호 외에 추가 ___을 요구한다.", answer: "확인", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "공인인증서 대신 사용하는 인증 수단을 ___인증서라 한다.", answer: "공동", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "개인정보 유출 시 해당 기업은 이를 ___에게 통보해야 한다.", answer: "이용자", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "빅데이터 시대에 개인정보 ___가 더욱 중요해지고 있다.", answer: "보호", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "다크웹에서 개인정보가 ___될 수 있으므로 유출에 주의한다.", answer: "거래", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "AI 서비스에 개인정보를 입력할 때 ___에 주의해야 한다.", answer: "유출", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "안면인식 기술은 ___정보를 수집하므로 동의가 필요하다.", answer: "생체", category: "개인정보보호", gradeGroup: "5-6" },
  { text: "개인정보 ___권은 자신의 정보를 관리할 권리이다.", answer: "자기결정", category: "개인정보보호", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 14. 성폭력예방
// ─────────────────────────────────────────────
const SEXUAL_VIOLENCE_PREVENTION: SafetyTemplate[] = [
  // Grade 1-2
  { text: "내 몸은 ___가 소중하므로 함부로 만지게 하면 안 된다.", answer: "나", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "누군가 싫은 ___을 하면 '싫어요!'라고 말해야 한다.", answer: "접촉", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "수영복으로 가려지는 부위는 다른 사람이 만지면 ___된다.", answer: "안", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "불편한 일이 있으면 믿을 수 있는 ___에게 이야기해야 한다.", answer: "어른", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "좋은 접촉과 나쁜 접촉을 ___할 수 있어야 한다.", answer: "구별", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "어른이 비밀을 지키라고 해도 불편하면 ___에게 알려야 한다.", answer: "부모님", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "나쁜 접촉을 당하면 내 ___이 아니다.", answer: "잘못", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "혼자 있을 때 모르는 어른이 접근하면 ___져야 한다.", answer: "떨어", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "내 몸의 ___은 나만 결정할 수 있다.", answer: "경계", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "친구의 몸도 ___하게 대해야 한다.", answer: "소중", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "나쁜 접촉을 경험하면 ___번에 전화한다.", answer: "117", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "다른 사람을 만질 때도 상대방의 ___을 받아야 한다.", answer: "동의", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "화장실에 갈 때는 친구와 ___이 가면 안전하다.", answer: "함께", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "몸의 어느 부분이든 싫으면 '___'라고 말할 수 있다.", answer: "싫어요", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "부모님이 아닌 사람이 옷을 ___달라고 하면 거절한다.", answer: "벗어", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "무서운 일이 있으면 혼자 ___지 말고 말해야 한다.", answer: "참", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "불편한 상황에서 도망가는 것은 ___한 행동이다.", answer: "용감", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "모르는 어른이 사진을 찍자고 하면 ___해야 한다.", answer: "거절", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "다른 사람의 몸을 허락 없이 ___는 것은 나쁜 행동이다.", answer: "만지", category: "성폭력예방", gradeGroup: "1-2" },
  { text: "학교에서 불편한 일이 있으면 ___선생님에게 이야기한다.", answer: "담임", category: "성폭력예방", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "성폭력 피해 상담 전화번호는 ___번이다.", answer: "117", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "온라인에서 성적인 사진을 보내달라는 요구는 ___해야 한다.", answer: "거절", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성폭력은 피해자의 ___이 절대 아니다.", answer: "잘못", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "아는 사람이라도 ___한 접촉을 하면 성폭력이다.", answer: "원치 않는", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성적 수치심을 주는 ___도 성폭력에 해당한다.", answer: "말", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "불편한 상황에서는 '안 돼요, ___요, 도와주세요'를 외친다.", answer: "싫어", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "밤길을 혼자 걸을 때는 ___이 밝은 곳으로 다닌다.", answer: "불빛", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "SNS에서 모르는 사람의 ___요청을 함부로 수락하면 안 된다.", answer: "친구", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성폭력 피해를 당하면 씻지 말고 바로 ___에 가야 한다.", answer: "병원", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성교육은 나를 ___하기 위해 배우는 것이다.", answer: "보호", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "모르는 사람의 차에 타면 ___사건에 연루될 수 있다.", answer: "유괴", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "친한 사람이라도 ___에 대한 결정은 내가 한다.", answer: "내 몸", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성적인 농담도 상대방이 불쾌하면 ___에 해당한다.", answer: "성희롱", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "위기 상황에서 주변에 ___를 요청하는 연습을 한다.", answer: "도움", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "혼자 있을 때 위험을 느끼면 사람이 ___곳으로 이동한다.", answer: "많은", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성폭력 예방교육은 매 ___기마다 실시한다.", answer: "학", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "성폭력 신고를 망설이면 피해가 ___될 수 있다.", answer: "반복", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "학교 내 성폭력 발생 시 ___에게 즉시 알려야 한다.", answer: "선생님", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "피해 사실을 말하는 것은 ___이 아니라 용기이다.", answer: "고자질", category: "성폭력예방", gradeGroup: "3-4" },
  { text: "나와 친구의 몸은 모두 ___하므로 존중해야 한다.", answer: "소중", category: "성폭력예방", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "동의 없이 타인의 신체를 촬영하는 것은 ___이다.", answer: "불법촬영", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "디지털 성범죄의 피해 영상을 유포하면 ___적 처벌을 받는다.", answer: "법", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성범죄 신고 시 증거를 ___하는 것이 중요하다.", answer: "보존", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "그루밍은 가해자가 피해자의 ___을 얻어 범죄를 저지르는 수법이다.", answer: "신뢰", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성평등 의식을 갖는 것은 성폭력 ___에 중요하다.", answer: "예방", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "불법 촬영물을 발견하면 ___에 신고한다.", answer: "경찰", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "또래 사이에서도 성적 ___은 성폭력에 해당할 수 있다.", answer: "괴롭힘", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "온라인에서 성적 대화를 유도하는 것을 온라인 ___이라 한다.", answer: "그루밍", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성범죄자의 신상정보는 ___알리미 사이트에서 확인할 수 있다.", answer: "성범죄자", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성폭력 피해자 보호를 위해 ___보호센터가 운영된다.", answer: "해바라기", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "디지털 성범죄 피해 영상 삭제 지원은 ___에서 받을 수 있다.", answer: "여성긴급전화 1366", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성인지 ___교육은 성별에 따른 차별을 줄이기 위한 것이다.", answer: "감수성", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "데이트 폭력은 연인 사이에서도 ___에 해당한다.", answer: "범죄", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성범죄 공소시효는 피해자가 ___세가 될 때까지 정지된다.", answer: "성년", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "스토킹은 상대방의 의사에 반하여 지속적으로 ___하는 행위이다.", answer: "접근", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성매매는 미성년자를 대상으로 한 ___범죄이다.", answer: "중대", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "몸캠 피싱은 ___을 이용한 사이버 성범죄이다.", answer: "영상통화", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성폭력 피해자에게는 무료 ___상담이 제공된다.", answer: "법률", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "성폭력 예방을 위해 서로의 ___을 존중하는 문화가 필요하다.", answer: "경계", category: "성폭력예방", gradeGroup: "5-6" },
  { text: "동의는 자발적이고 명확해야 하며 언제든 ___할 수 있다.", answer: "철회", category: "성폭력예방", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 15. 학교폭력예방
// ─────────────────────────────────────────────
const SCHOOL_VIOLENCE_PREVENTION: SafetyTemplate[] = [
  // Grade 1-2
  { text: "친구를 때리거나 ___는 것은 폭력이다.", answer: "밀", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구에게 ___을 하면 마음의 상처를 준다.", answer: "욕", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구의 물건을 빼앗는 것은 ___이다.", answer: "폭력", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "괴롭힘을 당하면 참지 말고 ___에게 알려야 한다.", answer: "선생님", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구를 일부러 ___시키면 안 된다.", answer: "따돌림", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "학교폭력을 목격하면 ___에게 알린다.", answer: "어른", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구와 다투었을 때는 ___으로 해결해야 한다.", answer: "대화", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "나보다 약한 친구를 ___하면 안 된다.", answer: "괴롭힘", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "다른 친구의 ___를 놀리면 안 된다.", answer: "외모", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "폭력을 당하면 부끄러워하지 말고 ___을 요청한다.", answer: "도움", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "말로 하는 폭력도 ___를 줄 수 있다.", answer: "상처", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구의 물건을 ___로 숨기면 안 된다.", answer: "장난", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구가 울고 있으면 ___를 건네야 한다.", answer: "위로", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구의 별명을 싫어하면 부르지 ___야 한다.", answer: "않아", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "혼자 있는 친구를 보면 ___이 놀자고 해야 한다.", answer: "같", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구에게 싫은 ___을 시키는 것도 폭력이다.", answer: "일", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "괴롭힘을 당하는 친구를 보면 ___주어야 한다.", answer: "도와", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "화가 나도 친구를 ___는 것은 안 된다.", answer: "때리", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구와 다투면 '___'라고 먼저 사과하면 좋다.", answer: "미안해", category: "학교폭력예방", gradeGroup: "1-2" },
  { text: "친구의 ___을 빼앗는 것은 도둑질과 같다.", answer: "간식", category: "학교폭력예방", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "학교폭력 신고 전화번호는 ___번이다.", answer: "117", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "사이버 폭력은 ___상에서 일어나는 폭력이다.", answer: "인터넷", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "친구 사이에 ___을 강요하는 것도 폭력이다.", answer: "심부름", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 피해자를 도와주는 사람을 ___라고 한다.", answer: "방관자가 아닌 지지자", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 사안이 발생하면 학교 ___위원회가 열린다.", answer: "폭력대책", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "카카오톡 등에서 특정 친구를 ___방에서 내보내는 것도 폭력이다.", answer: "단체 대화", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력을 신고하면 ___가 보장된다.", answer: "비밀", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "친구에게 ___적으로 돈을 요구하는 것은 금품갈취이다.", answer: "강제", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 피해를 당하면 ___에 기록해 두면 좋다.", answer: "일기", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 예방교육은 매 ___기마다 실시한다.", answer: "학", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "친구를 협박하여 ___을 시키면 강요죄에 해당한다.", answer: "심부름", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 피해자는 전학을 원할 경우 ___지원을 받을 수 있다.", answer: "학교", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "친구의 단점을 SNS에 올리는 것도 ___폭력이다.", answer: "사이버", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 피해를 당하면 증거로 ___을 남겨 둔다.", answer: "기록", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "폭력을 목격하고도 모른 척하면 ___가 되는 것이다.", answer: "방관자", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력은 장난이 아니라 ___를 주는 행위이다.", answer: "상처", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "사이버 폭력 증거는 ___해서 보관한다.", answer: "캡처", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 상담은 ___센터에서 무료로 받을 수 있다.", answer: "Wee", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "또래 조정 활동은 친구 사이 ___을 평화롭게 해결하는 방법이다.", answer: "갈등", category: "학교폭력예방", gradeGroup: "3-4" },
  { text: "학교폭력 예방을 위해 '___주간'을 운영하는 학교가 있다.", answer: "인성", category: "학교폭력예방", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "학교폭력예방법에 따라 학교폭력은 ___적으로 처벌받을 수 있다.", answer: "법", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력의 유형에는 신체, 언어, 사이버, ___폭력 등이 있다.", answer: "정서", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "따돌림은 집단으로 특정인을 ___하는 행위이다.", answer: "배제", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 가해자에게는 출석정지, 전학 등의 ___가 내려질 수 있다.", answer: "조치", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "피해 학생은 ___센터에서 전문 상담을 받을 수 있다.", answer: "Wee", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "방관자가 피해자를 돕지 않으면 폭력이 ___될 수 있다.", answer: "지속", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "온라인에서 허위 사실을 유포하는 것은 ___훼손에 해당한다.", answer: "명예", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 피해 학생에게는 심리 ___이 제공된다.", answer: "치료", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 가해 학생에게는 ___교육 프로그램이 제공된다.", answer: "특별", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "사이버 학교폭력은 ___법에 의해 처벌받을 수 있다.", answer: "정보통신망", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 사안 처리 시 ___권이 보장되어야 한다.", answer: "피해학생 보호", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교 내 ___문화를 만들면 폭력을 예방할 수 있다.", answer: "평화", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 목격 시 ___으로 신고할 수 있다.", answer: "익명", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "갈등 해결을 위한 ___조정 프로그램이 학교에 운영된다.", answer: "또래", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 예방을 위해 학생 ___회가 활동한다.", answer: "자치", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "가정에서도 자녀의 학교폭력 ___에 관심을 가져야 한다.", answer: "징후", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 예방 캠페인으로 '___데이'를 운영하는 학교가 많다.", answer: "프렌드", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "회복적 ___은 가해자와 피해자 간 관계 회복을 돕는 방법이다.", answer: "정의", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 대책 자치위원회는 ___인으로 구성된다.", answer: "학부모 위원 과반", category: "학교폭력예방", gradeGroup: "5-6" },
  { text: "학교폭력 근절을 위해 학생, 학부모, 교사가 ___해야 한다.", answer: "협력", category: "학교폭력예방", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 16. 약물오남용 예방 (추가)
// ─────────────────────────────────────────────
const DRUG_ABUSE_PREVENTION: SafetyTemplate[] = [
  // Grade 1-2
  { text: "약은 반드시 ___의 허락을 받고 먹어야 한다.", answer: "어른", category: "약물안전", gradeGroup: "1-2" },
  { text: "처방전 없이 약을 사서 먹으면 ___하다.", answer: "위험", category: "약물안전", gradeGroup: "1-2" },
  { text: "사탕처럼 생긴 약을 함부로 ___면 안 된다.", answer: "먹", category: "약물안전", gradeGroup: "1-2" },
  { text: "약을 먹고 이상이 생기면 바로 ___에게 알려야 한다.", answer: "부모님", category: "약물안전", gradeGroup: "1-2" },
  { text: "약은 정해진 ___만큼만 먹어야 한다.", answer: "양", category: "약물안전", gradeGroup: "1-2" },
  { text: "다른 사람의 약을 ___먹으면 안 된다.", answer: "함부로", category: "약물안전", gradeGroup: "1-2" },
  { text: "약은 어린이 손이 닿지 않는 ___에 보관한다.", answer: "곳", category: "약물안전", gradeGroup: "1-2" },
  { text: "세제나 살충제는 ___가 아니므로 절대 먹으면 안 된다.", answer: "음식", category: "약물안전", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "약물 오남용이란 약을 잘못 사용하거나 ___하게 사용하는 것이다.", answer: "과다", category: "약물안전", gradeGroup: "3-4" },
  { text: "카페인이 많이 든 음료를 마시면 ___이 빨라질 수 있다.", answer: "심장박동", category: "약물안전", gradeGroup: "3-4" },
  { text: "흡연은 ___에 매우 해롭다.", answer: "건강", category: "약물안전", gradeGroup: "3-4" },
  { text: "음주는 청소년의 ___발달에 나쁜 영향을 준다.", answer: "뇌", category: "약물안전", gradeGroup: "3-4" },
  { text: "약의 부작용이 나타나면 ___에게 알려야 한다.", answer: "의사", category: "약물안전", gradeGroup: "3-4" },
  { text: "약의 유통기한이 지나면 ___해야 한다.", answer: "폐기", category: "약물안전", gradeGroup: "3-4" },
  { text: "에너지 음료를 많이 마시면 ___장애가 올 수 있다.", answer: "수면", category: "약물안전", gradeGroup: "3-4" },
  { text: "담배 연기는 ___는 사람에게도 해롭다.", answer: "옆에 있", category: "약물안전", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "약물 의존성이란 약 없이는 ___하기 어려운 상태이다.", answer: "생활", category: "약물안전", gradeGroup: "5-6" },
  { text: "청소년 흡연은 성인보다 ___에 더 큰 피해를 준다.", answer: "폐", category: "약물안전", gradeGroup: "5-6" },
  { text: "간접흡연은 ___담배 연기를 마시는 것이다.", answer: "다른 사람의", category: "약물안전", gradeGroup: "5-6" },
  { text: "전자담배도 유해물질이 포함되어 ___에 해롭다.", answer: "건강", category: "약물안전", gradeGroup: "5-6" },
  { text: "마약류는 ___에 의해 강력히 처벌받는 불법 약물이다.", answer: "법률", category: "약물안전", gradeGroup: "5-6" },
  { text: "본드나 가스 흡입은 ___세포를 파괴하는 행위이다.", answer: "뇌", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 관련 고민은 ___상담 전화로 도움을 받을 수 있다.", answer: "1388", category: "약물안전", gradeGroup: "5-6" },
  { text: "약물 남용 예방을 위해 ___교육이 정기적으로 실시된다.", answer: "예방", category: "약물안전", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// 17. 식품 알레르기 안전 (추가)
// ─────────────────────────────────────────────
const ALLERGY_SAFETY: SafetyTemplate[] = [
  // Grade 1-2
  { text: "음식을 먹고 두드러기가 나면 ___가 있을 수 있다.", answer: "알레르기", category: "식품알레르기", gradeGroup: "1-2" },
  { text: "알레르기가 있는 음식은 먹기 전에 ___에게 알려야 한다.", answer: "어른", category: "식품알레르기", gradeGroup: "1-2" },
  { text: "급식 시 알레르기 음식이 있으면 ___에게 말해야 한다.", answer: "선생님", category: "식품알레르기", gradeGroup: "1-2" },
  { text: "음식을 먹고 입이 ___거리면 바로 어른에게 알린다.", answer: "가려", category: "식품알레르기", gradeGroup: "1-2" },
  { text: "알레르기가 있는 친구에게 음식을 ___주면 안 된다.", answer: "함부로", category: "식품알레르기", gradeGroup: "1-2" },
  { text: "음식을 먹고 숨쉬기 어려우면 바로 ___에 전화한다.", answer: "119", category: "식품알레르기", gradeGroup: "1-2" },
  // Grade 3-4
  { text: "식품 알레르기를 일으키는 대표적 식품으로 ___이 있다.", answer: "땅콩", category: "식품알레르기", gradeGroup: "3-4" },
  { text: "우유, 계란, ___은 흔한 알레르기 유발 식품이다.", answer: "밀", category: "식품알레르기", gradeGroup: "3-4" },
  { text: "식품 포장지의 ___표시를 확인하면 알레르기 유발 성분을 알 수 있다.", answer: "알레르기", category: "식품알레르기", gradeGroup: "3-4" },
  { text: "알레르기 반응으로 얼굴이 ___는 증상이 나타날 수 있다.", answer: "붓", category: "식품알레르기", gradeGroup: "3-4" },
  { text: "학교 급식 식단에 알레르기 유발 식품 ___이 표시되어 있다.", answer: "번호", category: "식품알레르기", gradeGroup: "3-4" },
  { text: "갑각류(새우, 게) 알레르기가 있으면 ___종류를 피해야 한다.", answer: "해산물", category: "식품알레르기", gradeGroup: "3-4" },
  // Grade 5-6
  { text: "심한 알레르기 반응을 ___라고 한다.", answer: "아나필락시스", category: "식품알레르기", gradeGroup: "5-6" },
  { text: "아나필락시스가 발생하면 ___을 주사해야 한다.", answer: "에피네프린", category: "식품알레르기", gradeGroup: "5-6" },
  { text: "식품 알레르기 검사는 ___과에서 받을 수 있다.", answer: "알레르기", category: "식품알레르기", gradeGroup: "5-6" },
  { text: "식품 알레르기가 있으면 응급 ___을 항상 지참해야 한다.", answer: "약", category: "식품알레르기", gradeGroup: "5-6" },
  { text: "글루텐 알레르기가 있으면 ___이 들어간 음식을 피해야 한다.", answer: "밀가루", category: "식품알레르기", gradeGroup: "5-6" },
  { text: "유당불내증은 ___를 소화하지 못하는 것이다.", answer: "우유", category: "식품알레르기", gradeGroup: "5-6" },
];

// ─────────────────────────────────────────────
// All templates combined
// ─────────────────────────────────────────────
const ALL_TEMPLATES: SafetyTemplate[] = [
  ...TRAFFIC_SAFETY,
  ...FIRE_SAFETY,
  ...INTERNET_SAFETY,
  ...SCHOOL_SAFETY,
  ...PLAY_SAFETY,
  ...FOOD_SAFETY,
  ...NATURAL_DISASTER,
  ...DAILY_SAFETY,
  ...ELECTRICAL_SAFETY,
  ...WATER_SAFETY,
  ...HOME_SAFETY,
  ...DRUG_SAFETY,
  ...PRIVACY_SAFETY,
  ...SEXUAL_VIOLENCE_PREVENTION,
  ...SCHOOL_VIOLENCE_PREVENTION,
  ...DRUG_ABUSE_PREVENTION,
  ...ALLERGY_SAFETY,
];

function getGradeGroup(grade: number): GradeGroup {
  if (grade <= 2) return "1-2";
  if (grade <= 4) return "3-4";
  return "5-6";
}

function getEligibleTemplates(grade: number): SafetyTemplate[] {
  const gradeGroup = getGradeGroup(grade);
  const eligibleGroups: GradeGroup[] = [];

  if (gradeGroup === "1-2") {
    eligibleGroups.push("1-2");
  } else if (gradeGroup === "3-4") {
    eligibleGroups.push("1-2", "3-4");
  } else {
    eligibleGroups.push("1-2", "3-4", "5-6");
  }

  return ALL_TEMPLATES.filter((t) => eligibleGroups.includes(t.gradeGroup));
}

export function generateSafetyPool(
  grade: number,
  seed: number,
): SafetyEntry[] {
  const rng = seededRandom(seed);
  const eligible = getEligibleTemplates(grade);

  // Shuffle and select 500 items
  const shuffled = shuffle(rng, eligible);

  // If we have fewer than 500, cycle through to fill
  const result: SafetyEntry[] = [];
  const targetCount = 500;

  for (let i = 0; i < targetCount; i++) {
    const template = shuffled[i % shuffled.length];
    result.push({
      text: template.text,
      answer: template.answer,
      category: template.category,
    });
  }

  // Final shuffle to mix duplicates throughout
  return shuffle(rng, result);
}
