import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
} from "@/types/curriculum";

// 1학년 1학기 교육과정 성취기준
export const grade1Semester1Standards = {
  math: [
    {
      code: "[2수01-01]",
      desc: "0과 100까지의 수 개념을 이해하고 수를 세고 읽고 쓸 수 있다",
      unit: "9까지의 수",
      difficulty: 1,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-02]",
      desc: "하나의 수를 두 수로 분해하고 두 수를 하나의 수로 합성할 수 있다",
      unit: "9까지의 수",
      difficulty: 1,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-03]",
      desc: "덧셈과 뺄셈이 이루어지는 실생활 상황을 통해 덧셈과 뺄셈의 의미를 이해한다",
      unit: "덧셈과 뺄셈",
      difficulty: 1,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수01-04]",
      desc: "한 자리 수의 덧셈과 뺄셈을 할 수 있다",
      unit: "덧셈과 뺄셈",
      difficulty: 1,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수02-01]",
      desc: "교실 및 생활 주변에서 여러 가지 물건의 모양을 관찰하고 특징을 알 수 있다",
      unit: "여러 가지 모양",
      difficulty: 1,
      weeks: [9, 11] as [number, number],
    },
    {
      code: "[2수01-05]",
      desc: "50까지의 수를 세고 읽고 쓸 수 있다",
      unit: "50까지의 수",
      difficulty: 1,
      weeks: [12, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[2국01-01]",
      desc: "상황에 어울리는 인사말을 주고받는다",
      unit: "인사말",
      difficulty: 1,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[2국02-01]",
      desc: "글자의 짜임을 알고 글자를 바르게 읽는다",
      unit: "글자",
      difficulty: 1,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[2국03-01]",
      desc: "글자를 바르게 쓴다",
      unit: "글쓰기",
      difficulty: 1,
      weeks: [8, 10] as [number, number],
    },
    {
      code: "[2국04-01]",
      desc: "한글 자모의 이름과 소릿값을 알고 정확하게 발음하고 쓴다",
      unit: "한글",
      difficulty: 1,
      weeks: [11, 14] as [number, number],
    },
  ],
};

export const grade1Semester2Standards = {
  math: [
    {
      code: "[2수01-06]",
      desc: "100까지의 수 개념을 이해하고 수를 세고 읽고 쓸 수 있다",
      unit: "100까지의 수",
      difficulty: 1,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-07]",
      desc: "덧셈과 뺄셈의 관계를 이해한다",
      unit: "덧셈과 뺄셈(2)",
      difficulty: 1,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수03-01]",
      desc: "시계를 보고 시각을 읽을 수 있다",
      unit: "시계 보기",
      difficulty: 1,
      weeks: [9, 11] as [number, number],
    },
    {
      code: "[2수02-02]",
      desc: "여러 가지 모양을 이용하여 물건의 모양을 꾸밀 수 있다",
      unit: "여러 가지 모양",
      difficulty: 1,
      weeks: [12, 14] as [number, number],
    },
  ],
  korean: [
    {
      code: "[2국01-02]",
      desc: "자신의 생각이나 겪은 일을 글로 쓸 수 있다",
      unit: "생각 쓰기",
      difficulty: 1,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2국02-02]",
      desc: "인물의 모습, 행동을 상상하며 그림책, 시나 노래, 이야기를 감상한다",
      unit: "감상",
      difficulty: 1,
      weeks: [5, 8] as [number, number],
    },
  ],
};

// ============================================================
// 맞춤법 데이터 (60 entries)
// ============================================================
export const grade1SpellingData: SpellingEntry[] = [
  // --- 기존 21개 ---
  {
    q1: "사과를 먹었다.",
    q2: "사과를 먹겄다.",
    answer: 1,
    explanation: "'먹었다'가 올바른 표현입니다.",
  },
  {
    q1: "나는 학교에 가요.",
    q2: "나는 학교에 갸요.",
    answer: 1,
    explanation: "'가요'가 맞는 표현입니다.",
  },
  {
    q1: "친구랑 놀아요.",
    q2: "친구랑 놀아여.",
    answer: 1,
    explanation: "'놀아요'가 올바른 해요체 표현입니다.",
  },
  {
    q1: "아빠가 오셨어요.",
    q2: "아빠가 오셨어여.",
    answer: 1,
    explanation: "'-요'가 맞는 종결어미입니다.",
  },
  {
    q1: "예쁜 꽃이 피었다.",
    q2: "이쁜 꽃이 피었다.",
    answer: 1,
    explanation: "'예쁜'이 표준어입니다.",
  },
  {
    q1: "나는 잘할 수 있어.",
    q2: "나는 잘 할수 있어.",
    answer: 1,
    explanation: "'할 수'처럼 의존명사 '수'는 띄어 씁니다.",
  },
  {
    q1: "물을 마셨어요.",
    q2: "물을 마시었어요.",
    answer: 1,
    explanation: "'마셨어요'가 자연스러운 줄임 표현입니다.",
  },
  {
    q1: "엄마가 좋아요.",
    q2: "엄마가 조아요.",
    answer: 1,
    explanation: "'좋아요'의 'ㅎ'을 빠뜨리면 안 됩니다.",
  },
  {
    q1: "동생이 울었다.",
    q2: "동생이 울었따.",
    answer: 1,
    explanation: "'울었다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "밥을 맛있게 먹자.",
    q2: "밥을 마싯게 먹자.",
    answer: 1,
    explanation: "'맛있게'가 올바른 표기입니다.",
  },
  {
    q1: "우리 같이 놀자.",
    q2: "우리 가치 놀자.",
    answer: 1,
    explanation: "'같이'가 올바른 표기입니다.",
  },
  {
    q1: "나비가 날아요.",
    q2: "나비가 날라요.",
    answer: 1,
    explanation: "'날아요'가 올바른 표현입니다.",
  },
  {
    q1: "책을 읽었다.",
    q2: "책을 일겄다.",
    answer: 1,
    explanation: "'읽었다'가 올바른 표기입니다.",
  },
  {
    q1: "비가 와요.",
    q2: "비가 왜요.",
    answer: 1,
    explanation: "'와요'가 올바른 표현입니다.",
  },
  {
    q1: "신발을 신었다.",
    q2: "신발을 싣었다.",
    answer: 1,
    explanation: "'신었다'가 올바른 표현입니다.",
  },
  {
    q1: "아이스크림을 먹고 싶다.",
    q2: "아이스크림을 먹고 십다.",
    answer: 1,
    explanation: "'싶다'가 올바른 표기입니다.",
  },
  {
    q1: "할머니 댁에 가요.",
    q2: "할머니 댁에 갸요.",
    answer: 1,
    explanation: "'가요'가 올바른 표현입니다.",
  },
  {
    q1: "크레파스로 색칠해요.",
    q2: "크래파스로 색칠해요.",
    answer: 1,
    explanation: "'크레파스'가 올바른 표기입니다.",
  },
  {
    q1: "바깥에서 놀아요.",
    q2: "바같에서 놀아요.",
    answer: 1,
    explanation: "'바깥'이 올바른 표기입니다.",
  },
  {
    q1: "수박이 맛있다.",
    q2: "수박이 마싯다.",
    answer: 1,
    explanation: "'맛있다'가 올바른 표기입니다.",
  },
  // --- 신규 40개 (answer: 1 / 2 혼합) ---
  {
    q1: "강아지가 귀여워요.",
    q2: "강아지가 귀여워여.",
    answer: 1,
    explanation: "'-요'가 올바른 종결어미입니다.",
  },
  {
    q1: "하늘이 맑아요.",
    q2: "하늘이 말가요.",
    answer: 1,
    explanation: "'맑아요'에서 받침 'ㄺ'을 빠뜨리면 안 됩니다.",
  },
  {
    q1: "꽃이 활짝 피었다.",
    q2: "꽃이 활짝 피었다.",
    answer: 1,
    explanation: "두 문장 모두 같지만, '활짝'이 올바른 표현입니다.",
  },
  {
    q1: "토끼가 깡충 뛰어요.",
    q2: "토끼가 깡총 뛰어요.",
    answer: 1,
    explanation: "'깡충'이 올바른 의태어입니다.",
  },
  {
    q1: "사탕을 먹고 싶다.",
    q2: "사탕을 먹고 십다.",
    answer: 1,
    explanation: "'싶다'가 올바른 표기입니다.",
  },
  {
    q1: "놀이터에서 놀았어요.",
    q2: "놀이터에서 놀앗어요.",
    answer: 1,
    explanation: "'놀았어요'가 올바른 표기입니다.",
  },
  {
    q1: "동생은 아직 어려요.",
    q2: "동생은 아직 얼여요.",
    answer: 1,
    explanation: "'어려요'가 올바른 표현입니다.",
  },
  {
    q1: "빵이 부드러워요.",
    q2: "빵이 부드러워여.",
    answer: 1,
    explanation: "'-요'가 올바른 종결어미입니다.",
  },
  {
    q1: "나는 달리기를 좋아해요.",
    q2: "나는 달리기를 조아해요.",
    answer: 1,
    explanation: "'좋아해요'의 'ㅎ'을 빠뜨리면 안 됩니다.",
  },
  {
    q1: "눈이 많이 왔어요.",
    q2: "눈이 만이 왔어요.",
    answer: 1,
    explanation: "'많이'에서 받침 'ㄶ'을 빠뜨리면 안 됩니다.",
  },
  {
    q1: "오늘은 날씨가 좋다.",
    q2: "오늘은 날시가 좋다.",
    answer: 1,
    explanation: "'날씨'는 된소리로 씁니다.",
  },
  {
    q1: "그네를 타았어요.",
    q2: "그네를 탔어요.",
    answer: 2,
    explanation: "'탔어요'가 올바른 줄임 표현입니다.",
  },
  {
    q1: "얼음이 차가워요.",
    q2: "얼름이 차가워요.",
    answer: 1,
    explanation: "'얼음'이 올바른 표기입니다.",
  },
  {
    q1: "나는 그림 그리기를 조아해.",
    q2: "나는 그림 그리기를 좋아해.",
    answer: 2,
    explanation: "'좋아해'가 올바른 표기입니다.",
  },
  {
    q1: "선생님께 인사했어요.",
    q2: "선생님게 인사했어요.",
    answer: 1,
    explanation: "'께'가 높임의 조사로 올바른 표기입니다.",
  },
  {
    q1: "우유를 마셨어요.",
    q2: "우유를 마셧어요.",
    answer: 1,
    explanation: "'마셨어요'가 올바른 표기입니다.",
  },
  {
    q1: "일찍 이러나야 해요.",
    q2: "일찍 일어나야 해요.",
    answer: 2,
    explanation: "'일어나야'가 올바른 표기입니다.",
  },
  {
    q1: "연필로 글씨를 써요.",
    q2: "연필로 글시를 써요.",
    answer: 1,
    explanation: "'글씨'는 된소리로 씁니다.",
  },
  {
    q1: "우리 반 친구들이 많아요.",
    q2: "우리 반 친구들이 만아요.",
    answer: 1,
    explanation: "'많아요'에서 받침 'ㄶ'을 빠뜨리면 안 됩니다.",
  },
  {
    q1: "방을 깨끗이 치웠어요.",
    q2: "방을 깨끄시 치웠어요.",
    answer: 1,
    explanation: "'깨끗이'가 올바른 표기입니다.",
  },
  {
    q1: "점심을 맛있게 먹었다.",
    q2: "점심을 맛잇게 먹었다.",
    answer: 1,
    explanation: "'맛있게'가 올바른 표기입니다.",
  },
  {
    q1: "소풍이 즐거웠다.",
    q2: "소풍이 즐거웟다.",
    answer: 1,
    explanation: "'즐거웠다'가 올바른 표기입니다.",
  },
  {
    q1: "할아버지가 웃으셨다.",
    q2: "할아버지가 우스셨다.",
    answer: 1,
    explanation: "'웃으셨다'가 올바른 표기입니다.",
  },
  {
    q1: "나는 키가 컸다.",
    q2: "나는 키가 컸따.",
    answer: 1,
    explanation: "'컸다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "바다에서 수영했다.",
    q2: "바다에서 수영햇다.",
    answer: 1,
    explanation: "'수영했다'가 올바른 표기입니다.",
  },
  {
    q1: "국어 시간이 제미있다.",
    q2: "국어 시간이 재미있다.",
    answer: 2,
    explanation: "'재미있다'가 올바른 표기입니다.",
  },
  {
    q1: "오렌지 주스를 마셨다.",
    q2: "오렌지 쥬스를 마셨다.",
    answer: 1,
    explanation: "'주스'가 올바른 표기입니다.",
  },
  {
    q1: "까치가 울어요.",
    q2: "까치가 우러요.",
    answer: 1,
    explanation: "'울어요'가 올바른 표현입니다.",
  },
  {
    q1: "운동하에서 뛰었다.",
    q2: "운동장에서 뛰었다.",
    answer: 2,
    explanation: "'운동장'이 올바른 표기입니다.",
  },
  {
    q1: "꿀이 달콤해요.",
    q2: "꿀이 달꼼해요.",
    answer: 1,
    explanation: "'달콤해요'가 올바른 표기입니다.",
  },
  {
    q1: "병원에 갔다 왔어요.",
    q2: "병원에 갓다 왔어요.",
    answer: 1,
    explanation: "'갔다'가 올바른 표기입니다.",
  },
  {
    q1: "겨울에는 눈이 와요.",
    q2: "겨울에는 눈이 왜요.",
    answer: 1,
    explanation: "'와요'가 올바른 표현입니다.",
  },
  {
    q1: "빨간 장미가 예뻐요.",
    q2: "빨간 장미가 이뻐요.",
    answer: 1,
    explanation: "'예뻐요'가 표준어입니다.",
  },
  {
    q1: "도서관에서 책을 빌렸다.",
    q2: "도서관에서 책을 빌렸따.",
    answer: 1,
    explanation: "'빌렸다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "나는 케잌을 좋아해.",
    q2: "나는 케이크를 좋아해.",
    answer: 2,
    explanation: "'케이크'가 올바른 표기입니다.",
  },
  {
    q1: "이가 아파서 치과에 갔다.",
    q2: "이가 아파서 치꽈에 갔다.",
    answer: 1,
    explanation: "'치과'가 올바른 표기입니다.",
  },
  {
    q1: "친구에게 편지를 썼다.",
    q2: "친구에게 편지를 썻다.",
    answer: 1,
    explanation: "'썼다'가 올바른 표기입니다.",
  },
  {
    q1: "비행기가 하늘을 날아요.",
    q2: "비행기가 하늘을 날라요.",
    answer: 1,
    explanation: "'날아요'가 올바른 표현입니다.",
  },
  {
    q1: "엄마가 요리를 하셨다.",
    q2: "엄마가 요리를 하셧다.",
    answer: 1,
    explanation: "'하셨다'가 올바른 표기입니다.",
  },
  {
    q1: "색종이로 비행기를 접었다.",
    q2: "색종이로 비행기를 저벘다.",
    answer: 1,
    explanation: "'접었다'가 올바른 표기입니다.",
  },
];

// ============================================================
// 어휘 데이터 (60 entries)
// ============================================================
export const grade1VocabData: VocabEntry[] = [
  // --- 기존 15개 ---
  { meanings: ["머리에 쓰는 것", "햇빛을 막아줘요"], answer: "모자" },
  { meanings: ["글을 쓰는 도구", "깎아서 사용해요"], answer: "연필" },
  { meanings: ["비가 올 때 쓰는 것", "접었다 펼 수 있어요"], answer: "우산" },
  { meanings: ["밤에 뜨는 것", "둥글고 밝아요"], answer: "달" },
  { meanings: ["아침에 뜨는 것", "세상을 밝게 해요"], answer: "해" },
  { meanings: ["물속에 사는 동물", "지느러미가 있어요"], answer: "물고기" },
  { meanings: ["하늘을 나는 것", "날개가 있어요"], answer: "새" },
  { meanings: ["땅에서 자라요", "물을 주면 커져요"], answer: "나무" },
  { meanings: ["엄마, 아빠가 있는 곳", "내가 사는 곳"], answer: "집" },
  { meanings: ["글을 읽을 수 있어요", "종이로 만들었어요"], answer: "책" },
  { meanings: ["발에 신는 것", "걸을 때 필요해요"], answer: "신발" },
  { meanings: ["맛있는 것을 먹는 곳", "가족이 모여요"], answer: "식탁" },
  { meanings: ["숫자를 세요", "1, 2, 3이 있어요"], answer: "수" },
  { meanings: ["봄에 피어요", "예쁜 향기가 나요"], answer: "꽃" },
  { meanings: ["하늘에서 내려요", "우산이 필요해요"], answer: "비" },
  // --- 신규 45개 ---
  { meanings: ["하얗고 차가워요", "겨울에 하늘에서 내려요"], answer: "눈" },
  { meanings: ["네 발로 걸어요", "멍멍 짖어요"], answer: "강아지" },
  { meanings: ["야옹 하고 울어요", "수염이 있어요"], answer: "고양이" },
  { meanings: ["바다에 살아요", "등껍질이 딱딱해요"], answer: "거북이" },
  { meanings: ["크고 무거워요", "코가 길어요"], answer: "코끼리" },
  { meanings: ["풀을 먹어요", "음메 하고 울어요"], answer: "소" },
  { meanings: ["알을 낳아요", "꼬꼬댁 울어요"], answer: "닭" },
  { meanings: ["음식을 담아요", "둥글고 오목해요"], answer: "그릇" },
  { meanings: ["추울 때 입어요", "겨울에 필요해요"], answer: "외투" },
  { meanings: ["뜨거운 물이에요", "차를 만들 수 있어요"], answer: "끓는 물" },
  { meanings: ["밤에 자는 곳", "이불이 있어요"], answer: "침대" },
  { meanings: ["이를 닦는 도구", "매일 사용해요"], answer: "칫솔" },
  { meanings: ["손을 닦아요", "부드러워요"], answer: "수건" },
  { meanings: ["공부하는 곳", "선생님이 계세요"], answer: "학교" },
  { meanings: ["시간을 알려줘요", "째깍째깍 소리가 나요"], answer: "시계" },
  { meanings: ["탈 수 있어요", "바퀴가 두 개예요"], answer: "자전거" },
  { meanings: ["차가 다니는 곳", "횡단보도가 있어요"], answer: "도로" },
  { meanings: ["과일이에요", "노란색이고 길쭉해요"], answer: "바나나" },
  { meanings: ["동그란 과일이에요", "빨갛고 아삭해요"], answer: "사과" },
  { meanings: ["여름 과일이에요", "초록 줄무늬가 있어요"], answer: "수박" },
  {
    meanings: ["음식을 먹을 때 사용해요", "젓가락과 함께 써요"],
    answer: "숟가락",
  },
  {
    meanings: ["색칠할 때 사용해요", "여러 가지 색이 있어요"],
    answer: "색연필",
  },
  { meanings: ["글씨를 지워요", "하얗고 작아요"], answer: "지우개" },
  { meanings: ["물건을 넣어요", "등에 메요"], answer: "가방" },
  { meanings: ["종이를 잘라요", "조심해서 사용해요"], answer: "가위" },
  { meanings: ["물을 마셔요", "투명해요"], answer: "컵" },
  { meanings: ["어두울 때 켜요", "밝은 빛이 나요"], answer: "전등" },
  { meanings: ["여름에 시원해요", "바람이 나와요"], answer: "선풍기" },
  { meanings: ["겨울에 따뜻해요", "뜨거운 바람이 나와요"], answer: "히터" },
  { meanings: ["사진을 찍어요", "추억을 남겨요"], answer: "카메라" },
  { meanings: ["노래가 나와요", "귀에 꽂아요"], answer: "이어폰" },
  { meanings: ["편지를 넣어요", "우체통에 넣어요"], answer: "봉투" },
  { meanings: ["풀로 붙여요", "종이를 이어요"], answer: "풀" },
  { meanings: ["아플 때 가는 곳", "의사 선생님이 계세요"], answer: "병원" },
  { meanings: ["책을 빌려요", "조용히 해야 해요"], answer: "도서관" },
  { meanings: ["동물들이 살아요", "구경을 가요"], answer: "동물원" },
  { meanings: ["그림을 그려요", "물감을 사용해요"], answer: "도화지" },
  { meanings: ["비 오는 날 신어요", "물이 안 들어와요"], answer: "장화" },
  { meanings: ["목에 두르는 것", "겨울에 따뜻해요"], answer: "목도리" },
  { meanings: ["손에 끼는 것", "손가락이 따뜻해요"], answer: "장갑" },
  { meanings: ["쌀로 만들어요", "매일 먹어요"], answer: "밥" },
  { meanings: ["국물이 있어요", "뜨거워요"], answer: "국" },
  { meanings: ["반찬으로 먹어요", "배추로 만들어요"], answer: "김치" },
  { meanings: ["밀가루로 만들어요", "길고 가늘어요"], answer: "국수" },
  { meanings: ["달걀로 만들어요", "프라이팬에 구워요"], answer: "계란프라이" },
];

// ============================================================
// 수학 데이터 (80 entries)
// ============================================================
export const grade1MathData: MathEntry[] = [
  // --- 기존 21개 ---
  // 한 자리 수 덧셈
  {
    type: "calculation",
    expression: "3 + 2",
    answer: 5,
    steps: ["3 + 2 = 5"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "4 + 5",
    answer: 9,
    steps: ["4 + 5 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "6 + 3",
    answer: 9,
    steps: ["6 + 3 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "2 + 7",
    answer: 9,
    steps: ["2 + 7 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "1 + 8",
    answer: 9,
    steps: ["1 + 8 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "5 + 4",
    answer: 9,
    steps: ["5 + 4 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "3 + 3",
    answer: 6,
    steps: ["3 + 3 = 6"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "7 + 2",
    answer: 9,
    steps: ["7 + 2 = 9"],
    unit: "덧셈",
  },
  // 한 자리 수 뺄셈
  {
    type: "calculation",
    expression: "9 - 3",
    answer: 6,
    steps: ["9 - 3 = 6"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 5",
    answer: 3,
    steps: ["8 - 5 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 4",
    answer: 3,
    steps: ["7 - 4 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "6 - 2",
    answer: 4,
    steps: ["6 - 2 = 4"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "5 - 1",
    answer: 4,
    steps: ["5 - 1 = 4"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 7",
    answer: 2,
    steps: ["9 - 7 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 8",
    answer: 0,
    steps: ["8 - 8 = 0"],
    unit: "뺄셈",
  },
  // 두 수 합성/분해
  {
    type: "calculation",
    expression: "4 + 1",
    answer: 5,
    steps: ["4와 1을 합하면 5"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "2 + 3",
    answer: 5,
    steps: ["2와 3을 합하면 5"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "6 + 1",
    answer: 7,
    steps: ["6과 1을 합하면 7"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "3 + 4",
    answer: 7,
    steps: ["3과 4를 합하면 7"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "5 + 3",
    answer: 8,
    steps: ["5와 3을 합하면 8"],
    unit: "수의 합성",
  },
  // --- 신규 59개 ---
  // 추가 덧셈
  {
    type: "calculation",
    expression: "1 + 1",
    answer: 2,
    steps: ["1 + 1 = 2"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "1 + 2",
    answer: 3,
    steps: ["1 + 2 = 3"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "2 + 2",
    answer: 4,
    steps: ["2 + 2 = 4"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "1 + 4",
    answer: 5,
    steps: ["1 + 4 = 5"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "2 + 6",
    answer: 8,
    steps: ["2 + 6 = 8"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "3 + 5",
    answer: 8,
    steps: ["3 + 5 = 8"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "4 + 4",
    answer: 8,
    steps: ["4 + 4 = 8"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "5 + 2",
    answer: 7,
    steps: ["5 + 2 = 7"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "6 + 2",
    answer: 8,
    steps: ["6 + 2 = 8"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "7 + 1",
    answer: 8,
    steps: ["7 + 1 = 8"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "1 + 6",
    answer: 7,
    steps: ["1 + 6 = 7"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "4 + 3",
    answer: 7,
    steps: ["4 + 3 = 7"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "2 + 5",
    answer: 7,
    steps: ["2 + 5 = 7"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "8 + 1",
    answer: 9,
    steps: ["8 + 1 = 9"],
    unit: "덧셈",
  },
  {
    type: "calculation",
    expression: "1 + 3",
    answer: 4,
    steps: ["1 + 3 = 4"],
    unit: "덧셈",
  },
  // 추가 뺄셈
  {
    type: "calculation",
    expression: "2 - 1",
    answer: 1,
    steps: ["2 - 1 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "3 - 1",
    answer: 2,
    steps: ["3 - 1 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "3 - 2",
    answer: 1,
    steps: ["3 - 2 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "4 - 1",
    answer: 3,
    steps: ["4 - 1 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "4 - 2",
    answer: 2,
    steps: ["4 - 2 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "4 - 3",
    answer: 1,
    steps: ["4 - 3 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "5 - 2",
    answer: 3,
    steps: ["5 - 2 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "5 - 3",
    answer: 2,
    steps: ["5 - 3 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "5 - 4",
    answer: 1,
    steps: ["5 - 4 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "6 - 1",
    answer: 5,
    steps: ["6 - 1 = 5"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "6 - 3",
    answer: 3,
    steps: ["6 - 3 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "6 - 4",
    answer: 2,
    steps: ["6 - 4 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "6 - 5",
    answer: 1,
    steps: ["6 - 5 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 1",
    answer: 6,
    steps: ["7 - 1 = 6"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 2",
    answer: 5,
    steps: ["7 - 2 = 5"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 3",
    answer: 4,
    steps: ["7 - 3 = 4"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 5",
    answer: 2,
    steps: ["7 - 5 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "7 - 6",
    answer: 1,
    steps: ["7 - 6 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 1",
    answer: 7,
    steps: ["8 - 1 = 7"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 2",
    answer: 6,
    steps: ["8 - 2 = 6"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 3",
    answer: 5,
    steps: ["8 - 3 = 5"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 4",
    answer: 4,
    steps: ["8 - 4 = 4"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 6",
    answer: 2,
    steps: ["8 - 6 = 2"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "8 - 7",
    answer: 1,
    steps: ["8 - 7 = 1"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 1",
    answer: 8,
    steps: ["9 - 1 = 8"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 2",
    answer: 7,
    steps: ["9 - 2 = 7"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 4",
    answer: 5,
    steps: ["9 - 4 = 5"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 5",
    answer: 4,
    steps: ["9 - 5 = 4"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 6",
    answer: 3,
    steps: ["9 - 6 = 3"],
    unit: "뺄셈",
  },
  {
    type: "calculation",
    expression: "9 - 8",
    answer: 1,
    steps: ["9 - 8 = 1"],
    unit: "뺄셈",
  },
  // 추가 수의 합성/분해
  {
    type: "calculation",
    expression: "1 + 9",
    answer: 10,
    steps: ["1과 9를 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "2 + 8",
    answer: 10,
    steps: ["2와 8을 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "3 + 7",
    answer: 10,
    steps: ["3과 7을 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "4 + 6",
    answer: 10,
    steps: ["4와 6을 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "5 + 5",
    answer: 10,
    steps: ["5와 5를 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "6 + 4",
    answer: 10,
    steps: ["6과 4를 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "7 + 3",
    answer: 10,
    steps: ["7과 3을 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "8 + 2",
    answer: 10,
    steps: ["8과 2를 합하면 10"],
    unit: "수의 합성",
  },
  {
    type: "calculation",
    expression: "9 + 1",
    answer: 10,
    steps: ["9와 1을 합하면 10"],
    unit: "수의 합성",
  },
  // 시계 보기
  {
    type: "calculation",
    expression: "3시",
    answer: 3,
    steps: ["긴 바늘이 12, 짧은 바늘이 3을 가리킵니다"],
    unit: "시계 보기",
  },
  {
    type: "calculation",
    expression: "7시",
    answer: 7,
    steps: ["긴 바늘이 12, 짧은 바늘이 7을 가리킵니다"],
    unit: "시계 보기",
  },
  {
    type: "calculation",
    expression: "12시",
    answer: 12,
    steps: ["긴 바늘과 짧은 바늘이 모두 12를 가리킵니다"],
    unit: "시계 보기",
  },
  {
    type: "calculation",
    expression: "9시",
    answer: 9,
    steps: ["긴 바늘이 12, 짧은 바늘이 9를 가리킵니다"],
    unit: "시계 보기",
  },
  {
    type: "calculation",
    expression: "6시",
    answer: 6,
    steps: ["긴 바늘이 12, 짧은 바늘이 6을 가리킵니다"],
    unit: "시계 보기",
  },
  // 50까지의 수
  {
    type: "calculation",
    expression: "10 + 5",
    answer: 15,
    steps: ["10과 5를 합하면 15"],
    unit: "50까지의 수",
  },
  {
    type: "calculation",
    expression: "20 + 10",
    answer: 30,
    steps: ["20과 10을 합하면 30"],
    unit: "50까지의 수",
  },
  {
    type: "calculation",
    expression: "30 + 20",
    answer: 50,
    steps: ["30과 20을 합하면 50"],
    unit: "50까지의 수",
  },
  {
    type: "calculation",
    expression: "40 + 5",
    answer: 45,
    steps: ["40과 5를 합하면 45"],
    unit: "50까지의 수",
  },
  {
    type: "calculation",
    expression: "25 + 10",
    answer: 35,
    steps: ["25와 10을 합하면 35"],
    unit: "50까지의 수",
  },
];

// ============================================================
// 상식 데이터 (60 entries)
// ============================================================
export const grade1KnowledgeData: KnowledgeEntry[] = [
  // --- 기존 15개 ---
  {
    text: "우리나라 국기의 이름은 ___이다.",
    answer: "태극기",
    category: "상식",
  },
  { text: "1년은 ___개월이다.", answer: "12", category: "수학" },
  { text: "무지개는 ___가지 색깔이다.", answer: "7", category: "과학" },
  { text: "일주일은 ___일이다.", answer: "7", category: "수학" },
  { text: "우리가 숨 쉬는 기체는 ___이다.", answer: "공기", category: "과학" },
  { text: "해가 뜨는 방향은 ___쪽이다.", answer: "동", category: "과학" },
  { text: "물을 얼리면 ___이 된다.", answer: "얼음", category: "과학" },
  { text: "바나나의 색깔은 ___색이다.", answer: "노란", category: "상식" },
  { text: "눈은 ___색이다.", answer: "하얀", category: "자연" },
  { text: "강아지의 새끼를 ___라고 한다.", answer: "강아지", category: "동물" },
  { text: "고양이는 '___'하고 울어요.", answer: "야옹", category: "동물" },
  { text: "개구리는 '___'하고 울어요.", answer: "개굴", category: "동물" },
  { text: "하루는 ___시간이다.", answer: "24", category: "수학" },
  { text: "사과의 색깔은 ___색이다.", answer: "빨간", category: "상식" },
  { text: "봄 다음에 오는 계절은 ___이다.", answer: "여름", category: "자연" },
  // --- 신규 45개 ---
  {
    text: "가을 다음에 오는 계절은 ___이다.",
    answer: "겨울",
    category: "자연",
  },
  { text: "겨울 다음에 오는 계절은 ___이다.", answer: "봄", category: "자연" },
  {
    text: "여름 다음에 오는 계절은 ___이다.",
    answer: "가을",
    category: "자연",
  },
  { text: "소는 '___'하고 울어요.", answer: "음메", category: "동물" },
  { text: "닭은 '___'하고 울어요.", answer: "꼬꼬댁", category: "동물" },
  { text: "돼지는 '___'하고 울어요.", answer: "꿀꿀", category: "동물" },
  { text: "양은 '___'하고 울어요.", answer: "메에", category: "동물" },
  { text: "참새는 '___'하고 울어요.", answer: "짹짹", category: "동물" },
  { text: "부엉이는 밤에 활동하는 ___이에요.", answer: "새", category: "동물" },
  { text: "토끼의 귀는 ___어요.", answer: "길", category: "동물" },
  {
    text: "사람의 손가락은 양손 합쳐서 ___개이다.",
    answer: "10",
    category: "수학",
  },
  { text: "사람의 눈은 ___개이다.", answer: "2", category: "상식" },
  { text: "사람의 코는 ___개이다.", answer: "1", category: "상식" },
  { text: "하늘의 색깔은 보통 ___색이다.", answer: "파란", category: "자연" },
  { text: "잔디의 색깔은 ___색이다.", answer: "초록", category: "자연" },
  { text: "우유의 색깔은 ___색이다.", answer: "하얀", category: "상식" },
  { text: "당근의 색깔은 ___색이다.", answer: "주황", category: "상식" },
  { text: "가지의 색깔은 ___색이다.", answer: "보라", category: "상식" },
  { text: "해가 지는 방향은 ___쪽이다.", answer: "서", category: "과학" },
  {
    text: "물은 높은 곳에서 ___곳으로 흘러요.",
    answer: "낮은",
    category: "과학",
  },
  { text: "나무에서 떨어지는 것은 ___이에요.", answer: "잎", category: "자연" },
  { text: "씨앗에 물을 주면 ___이 나와요.", answer: "싹", category: "자연" },
  {
    text: "비가 온 후 하늘에 뜨는 것은 ___이에요.",
    answer: "무지개",
    category: "자연",
  },
  { text: "밤하늘에 반짝이는 것은 ___이에요.", answer: "별", category: "자연" },
  { text: "연못에 사는 동물은 ___이에요.", answer: "개구리", category: "동물" },
  { text: "꿀을 만드는 곤충은 ___이에요.", answer: "벌", category: "동물" },
  {
    text: "거미줄을 만드는 동물은 ___이에요.",
    answer: "거미",
    category: "동물",
  },
  { text: "우리나라의 국화는 ___이에요.", answer: "무궁화", category: "상식" },
  { text: "설날에 먹는 음식은 ___이에요.", answer: "떡국", category: "상식" },
  { text: "추석에 먹는 음식은 ___이에요.", answer: "송편", category: "상식" },
  {
    text: "크리스마스에 오시는 분은 ___이에요.",
    answer: "산타",
    category: "상식",
  },
  { text: "우리나라 돈의 단위는 ___이에요.", answer: "원", category: "상식" },
  {
    text: "횡단보도의 줄무늬는 ___색이에요.",
    answer: "하얀",
    category: "상식",
  },
  { text: "소방차의 색깔은 ___색이에요.", answer: "빨간", category: "상식" },
  {
    text: "경찰차의 색깔은 ___색과 하얀색이에요.",
    answer: "검정",
    category: "상식",
  },
  {
    text: "구급차에 전화하려면 ___번을 눌러요.",
    answer: "119",
    category: "상식",
  },
  {
    text: "지구에서 가장 큰 동물은 ___이에요.",
    answer: "고래",
    category: "동물",
  },
  { text: "가장 빠른 동물은 ___이에요.", answer: "치타", category: "동물" },
  { text: "목이 가장 긴 동물은 ___이에요.", answer: "기린", category: "동물" },
  { text: "삼각형의 변은 ___개이다.", answer: "3", category: "수학" },
  { text: "사각형의 변은 ___개이다.", answer: "4", category: "수학" },
  {
    text: "동그라미를 다른 말로 ___이라고 해요.",
    answer: "원",
    category: "수학",
  },
  { text: "1시간은 ___분이다.", answer: "60", category: "수학" },
  {
    text: "오전과 오후를 나누는 시각은 ___시이다.",
    answer: "12",
    category: "수학",
  },
  { text: "물고기는 ___로 숨을 쉬어요.", answer: "아가미", category: "과학" },
];

// ============================================================
// 안전 데이터 (40 entries)
// ============================================================
export const grade1SafetyData: SafetyEntry[] = [
  // --- 기존 10개 ---
  {
    text: "횡단보도에서는 ___ 신호에 건넌다.",
    answer: "초록",
    category: "교통안전",
  },
  {
    text: "모르는 사람을 따라가면 ___.",
    answer: "안 돼요",
    category: "생활안전",
  },
  { text: "계단에서는 ___지 않는다.", answer: "뛰", category: "학교안전" },
  { text: "불이 나면 ___번에 전화한다.", answer: "119", category: "화재안전" },
  {
    text: "길을 건널 때는 좌우를 ___.",
    answer: "살핀다",
    category: "교통안전",
  },
  { text: "교실에서는 ___지 않는다.", answer: "뛰", category: "학교안전" },
  { text: "가위는 ___을 잡고 건넨다.", answer: "날", category: "생활안전" },
  {
    text: "손을 자주 ___으면 병에 안 걸려요.",
    answer: "씻",
    category: "건강안전",
  },
  { text: "밥을 먹기 전에 ___를 씻어요.", answer: "손", category: "건강안전" },
  { text: "차가 오면 ___에서 기다려요.", answer: "인도", category: "교통안전" },
  // --- 신규 30개 ---
  {
    text: "비상구는 ___색 표시를 따라가요.",
    answer: "초록",
    category: "화재안전",
  },
  {
    text: "화재 시 엘리베이터 대신 ___를 이용해요.",
    answer: "계단",
    category: "화재안전",
  },
  {
    text: "불이 나면 몸을 ___추고 이동해요.",
    answer: "낮",
    category: "화재안전",
  },
  {
    text: "연기가 나면 젖은 ___로 코를 막아요.",
    answer: "수건",
    category: "화재안전",
  },
  {
    text: "자전거를 탈 때 ___을 꼭 써요.",
    answer: "헬멧",
    category: "교통안전",
  },
  {
    text: "버스에서 내릴 때 ___을 조심해요.",
    answer: "차",
    category: "교통안전",
  },
  {
    text: "빨간 신호등에서는 ___해야 해요.",
    answer: "멈춤",
    category: "교통안전",
  },
  {
    text: "비 오는 날에는 길이 ___해서 조심해요.",
    answer: "미끄러워",
    category: "생활안전",
  },
  {
    text: "물놀이할 때 어른과 ___가야 해요.",
    answer: "함께",
    category: "물놀이안전",
  },
  { text: "수영장에서는 ___지 않아요.", answer: "뛰", category: "물놀이안전" },
  {
    text: "물에 빠진 사람을 보면 ___에게 알려요.",
    answer: "어른",
    category: "물놀이안전",
  },
  {
    text: "전기 콘센트에 ___를 넣으면 안 돼요.",
    answer: "손",
    category: "전기안전",
  },
  {
    text: "젖은 손으로 ___를 만지면 안 돼요.",
    answer: "전기",
    category: "전기안전",
  },
  {
    text: "약은 반드시 ___의 허락을 받고 먹어요.",
    answer: "어른",
    category: "건강안전",
  },
  { text: "이를 하루에 ___번 이상 닦아요.", answer: "2", category: "건강안전" },
  {
    text: "기침할 때 ___로 입을 가려요.",
    answer: "팔꿈치",
    category: "건강안전",
  },
  {
    text: "감기에 걸리면 ___을 쓰고 다녀요.",
    answer: "마스크",
    category: "건강안전",
  },
  {
    text: "놀이터에서 그네 앞에 ___지 않아요.",
    answer: "서",
    category: "학교안전",
  },
  { text: "미끄럼틀은 ___부터 내려와요.", answer: "위", category: "학교안전" },
  { text: "친구를 ___면 안 돼요.", answer: "때리", category: "학교안전" },
  {
    text: "뾰족한 물건은 ___을 향하지 않게 해요.",
    answer: "사람",
    category: "생활안전",
  },
  {
    text: "뜨거운 물에 ___면 안 돼요.",
    answer: "손을 넣",
    category: "생활안전",
  },
  {
    text: "높은 곳에서 ___면 위험해요.",
    answer: "뛰어내리",
    category: "생활안전",
  },
  {
    text: "지진이 나면 ___ 아래로 숨어요.",
    answer: "책상",
    category: "재난안전",
  },
  {
    text: "태풍이 오면 ___에 있어야 해요.",
    answer: "집 안",
    category: "재난안전",
  },
  {
    text: "천둥이 치면 나무 ___에 있으면 안 돼요.",
    answer: "아래",
    category: "재난안전",
  },
  {
    text: "모르는 사람이 과자를 주면 ___해야 해요.",
    answer: "거절",
    category: "생활안전",
  },
  {
    text: "집 비밀번호를 다른 사람에게 ___하면 안 돼요.",
    answer: "알려주",
    category: "생활안전",
  },
  {
    text: "위험한 곳을 볼 때는 ___에게 알려요.",
    answer: "부모님",
    category: "생활안전",
  },
  {
    text: "길을 잃으면 가까운 ___에게 도움을 요청해요.",
    answer: "어른",
    category: "생활안전",
  },
];

// ============================================================
// 글쓰기 프롬프트 (60 entries)
// ============================================================
export const grade1WritingPrompts: string[] = [
  // --- 기존 20개 ---
  "내가 좋아하는 동물은 무엇인가요? 왜 좋아하나요?",
  "오늘 아침에 무엇을 먹었나요?",
  "가장 좋아하는 놀이는 무엇인가요?",
  "우리 가족을 소개해 보세요.",
  "좋아하는 색깔과 그 이유를 써 보세요.",
  "비 오는 날 무엇을 하고 싶은가요?",
  "내가 만약 하늘을 날 수 있다면?",
  "가장 좋아하는 음식은 무엇인가요?",
  "학교에서 가장 재미있는 시간은 언제인가요?",
  "나의 보물은 무엇인가요?",
  "동물원에 가면 무엇을 보고 싶은가요?",
  "내가 만약 마법사라면 무엇을 할까요?",
  "가장 기억에 남는 일은 무엇인가요?",
  "친구에게 편지를 써 보세요.",
  "내가 좋아하는 계절은 무엇인가요?",
  "어른이 되면 무엇이 되고 싶은가요?",
  "제일 좋아하는 과일은 무엇인가요?",
  "학교 가는 길에 무엇을 봤나요?",
  "내가 키우고 싶은 동물은?",
  "잠자기 전에 무엇을 하나요?",
  // --- 신규 40개 ---
  "오늘 가장 기분 좋았던 일은 무엇인가요?",
  "내가 만약 물고기가 된다면 어떤 기분일까요?",
  "가장 좋아하는 색깔로 무엇을 그리고 싶나요?",
  "우리 집에서 가장 좋아하는 장소는 어디인가요?",
  "눈이 오면 무엇을 하고 싶나요?",
  "내가 좋아하는 만화 캐릭터를 소개해 보세요.",
  "선생님에게 편지를 써 보세요.",
  "나의 하루 일과를 써 보세요.",
  "내가 만약 슈퍼맨이라면?",
  "가장 맛있게 먹었던 음식은 무엇인가요?",
  "소풍을 간다면 어디로 가고 싶나요?",
  "내가 만약 동물과 이야기할 수 있다면?",
  "학교에서 가장 좋아하는 친구를 소개해 보세요.",
  "봄이 오면 무엇이 변하나요?",
  "여름에 가장 하고 싶은 일은?",
  "가을에 볼 수 있는 것을 써 보세요.",
  "겨울에 입는 옷을 소개해 보세요.",
  "내가 가장 잘하는 것은 무엇인가요?",
  "할머니(할아버지)에게 하고 싶은 말이 있나요?",
  "가장 재미있었던 놀이를 설명해 보세요.",
  "내가 만약 왕이라면 무엇을 할까요?",
  "우리 반을 소개해 보세요.",
  "내가 만약 거인이라면?",
  "내가 만약 작아진다면?",
  "제일 좋아하는 노래는 무엇인가요?",
  "오늘 날씨는 어떤가요? 기분은요?",
  "내가 만약 요리사라면 무엇을 만들까요?",
  "학교에서 배운 것 중 가장 신기한 것은?",
  "내가 좋아하는 장난감을 소개해 보세요.",
  "바다에 가면 무엇을 하고 싶나요?",
  "산에 가면 무엇을 볼 수 있나요?",
  "가장 무서웠던 일은 무엇인가요?",
  "친구와 함께 하고 싶은 놀이는?",
  "내가 만약 선생님이라면?",
  "가장 예쁜 것은 무엇인가요? 왜요?",
  "내가 만약 아기가 된다면?",
  "내가 만약 로봇을 가지고 있다면?",
  "오늘 학교에서 있었던 일을 써 보세요.",
  "세상에서 가장 맛있는 음식을 만든다면?",
  "내가 만약 100살이 된다면?",
];

// ============================================================
// 국어 데이터 - NEW (40 entries)
// ============================================================
export const grade1KoreanData: KnowledgeEntry[] = [
  {
    text: "문장의 끝에 찍는 점을 ___이라고 합니다.",
    answer: "마침표",
    category: "국어",
  },
  {
    text: "물어보는 문장 끝에 찍는 것은 ___입니다.",
    answer: "물음표",
    category: "국어",
  },
  {
    text: "놀라거나 감탄할 때 문장 끝에 찍는 것은 ___입니다.",
    answer: "느낌표",
    category: "국어",
  },
  {
    text: "ㄱ, ㄴ, ㄷ, ㄹ은 한글의 ___이에요.",
    answer: "자음",
    category: "국어",
  },
  {
    text: "ㅏ, ㅓ, ㅗ, ㅜ는 한글의 ___이에요.",
    answer: "모음",
    category: "국어",
  },
  {
    text: "자음과 모음이 합쳐져서 ___가 만들어져요.",
    answer: "글자",
    category: "국어",
  },
  {
    text: "글자의 아래에 오는 자음을 ___이라고 해요.",
    answer: "받침",
    category: "국어",
  },
  { text: "한글은 ___대왕이 만들었어요.", answer: "세종", category: "국어" },
  { text: "'나비'에서 'ㄴ'은 ___ 소리예요.", answer: "자음", category: "국어" },
  { text: "'바다'에서 'ㅏ'는 ___ 소리예요.", answer: "모음", category: "국어" },
  {
    text: "기쁠 때 느끼는 감정은 ___이에요.",
    answer: "기쁨",
    category: "말하기",
  },
  {
    text: "슬플 때 느끼는 감정은 ___이에요.",
    answer: "슬픔",
    category: "말하기",
  },
  {
    text: "화가 날 때 느끼는 감정은 ___이에요.",
    answer: "분노",
    category: "말하기",
  },
  {
    text: "무서울 때 느끼는 감정은 ___이에요.",
    answer: "공포",
    category: "말하기",
  },
  {
    text: "아침에 만나면 '___'이라고 인사해요.",
    answer: "안녕",
    category: "말하기",
  },
  {
    text: "고마울 때 '___'라고 말해요.",
    answer: "감사합니다",
    category: "말하기",
  },
  {
    text: "잘못했을 때 '___'라고 말해요.",
    answer: "미안합니다",
    category: "말하기",
  },
  {
    text: "밥을 먹기 전에 '잘 ___'이라고 해요.",
    answer: "먹겠습니다",
    category: "말하기",
  },
  {
    text: "밥을 먹은 후에 '잘 ___'이라고 해요.",
    answer: "먹었습니다",
    category: "말하기",
  },
  {
    text: "헤어질 때 '___'이라고 인사해요.",
    answer: "안녕히 가세요",
    category: "말하기",
  },
  {
    text: "동화에서 이야기를 들려주는 사람을 ___이라고 해요.",
    answer: "작가",
    category: "읽기",
  },
  {
    text: "그림책에서 그림을 그리는 사람을 ___이라고 해요.",
    answer: "화가",
    category: "읽기",
  },
  {
    text: "이야기에 나오는 사람이나 동물을 ___이라고 해요.",
    answer: "인물",
    category: "읽기",
  },
  {
    text: "이야기가 일어나는 장소를 ___이라고 해요.",
    answer: "배경",
    category: "읽기",
  },
  {
    text: "동화 '콩쥐팥쥐'에서 착한 아이는 ___이에요.",
    answer: "콩쥐",
    category: "읽기",
  },
  {
    text: "'흥부와 놀부'에서 착한 형제는 ___이에요.",
    answer: "흥부",
    category: "읽기",
  },
  {
    text: "'토끼와 거북이' 이야기에서 경주를 이긴 것은 ___이에요.",
    answer: "거북이",
    category: "읽기",
  },
  {
    text: "편지를 쓸 때 처음에 '___에게'라고 써요.",
    answer: "받는 사람 이름",
    category: "쓰기",
  },
  {
    text: "일기에는 그날의 ___, 날씨, 기분을 써요.",
    answer: "날짜",
    category: "쓰기",
  },
  {
    text: "문장은 주어와 ___로 이루어져요.",
    answer: "서술어",
    category: "국어",
  },
  {
    text: "'나는 학교에 간다'에서 '나는'이 ___이에요.",
    answer: "주어",
    category: "국어",
  },
  {
    text: "'강아지가 뛴다'에서 '뛴다'가 ___이에요.",
    answer: "서술어",
    category: "국어",
  },
  {
    text: "두 글자 이상의 낱말이 모여 ___이 돼요.",
    answer: "문장",
    category: "국어",
  },
  {
    text: "사람이나 사물의 이름을 나타내는 말을 ___이라고 해요.",
    answer: "명사",
    category: "국어",
  },
  {
    text: "글을 소리 내어 읽는 것을 ___이라고 해요.",
    answer: "낭독",
    category: "읽기",
  },
  {
    text: "같은 소리가 반복되는 말을 ___어라고 해요.",
    answer: "의성",
    category: "국어",
  },
  {
    text: "모양이나 움직임을 흉내 내는 말을 ___어라고 해요.",
    answer: "의태",
    category: "국어",
  },
  {
    text: "'멍멍', '야옹'은 ___어의 예시예요.",
    answer: "의성",
    category: "국어",
  },
  {
    text: "'살금살금', '깡충깡충'은 ___어의 예시예요.",
    answer: "의태",
    category: "국어",
  },
  {
    text: "받아쓰기에서는 선생님이 불러주는 말을 ___에 써요.",
    answer: "공책",
    category: "쓰기",
  },
];

// ============================================================
// 창의 데이터 - NEW (40 entries)
// ============================================================
export const grade1CreativeData: KnowledgeEntry[] = [
  {
    text: "빨간색과 노란색을 섞으면 ___ 색이 됩니다.",
    answer: "주황",
    category: "미술",
  },
  {
    text: "빨간색과 파란색을 섞으면 ___ 색이 됩니다.",
    answer: "보라",
    category: "미술",
  },
  {
    text: "파란색과 노란색을 섞으면 ___ 색이 됩니다.",
    answer: "초록",
    category: "미술",
  },
  {
    text: "빨강, 파랑, 노랑을 색의 ___원색이라고 해요.",
    answer: "3",
    category: "미술",
  },
  {
    text: "그림을 그릴 때 사용하는 물감을 ___이라고 해요.",
    answer: "수채화",
    category: "미술",
  },
  {
    text: "색종이를 접어서 만드는 것을 ___이라고 해요.",
    answer: "종이접기",
    category: "만들기",
  },
  {
    text: "찰흙으로 물건을 만드는 것을 ___이라고 해요.",
    answer: "찰흙놀이",
    category: "만들기",
  },
  {
    text: "크레파스는 ___을 할 때 사용해요.",
    answer: "색칠",
    category: "미술",
  },
  {
    text: "하얀색과 검정색을 섞으면 ___ 색이 됩니다.",
    answer: "회색",
    category: "미술",
  },
  {
    text: "빨간색에 하얀색을 섞으면 ___ 색이 됩니다.",
    answer: "분홍",
    category: "미술",
  },
  {
    text: "음악에서 소리의 높고 낮음을 ___이라고 해요.",
    answer: "음높이",
    category: "음악",
  },
  {
    text: "음악에서 소리의 세고 약함을 ___이라고 해요.",
    answer: "셈여림",
    category: "음악",
  },
  {
    text: "음악에서 빠르고 느린 것을 ___이라고 해요.",
    answer: "빠르기",
    category: "음악",
  },
  {
    text: "노래를 부를 때 박자에 맞추어 ___을 쳐요.",
    answer: "손뼉",
    category: "음악",
  },
  {
    text: "탬버린, 트라이앵글은 ___기의 한 종류예요.",
    answer: "타악",
    category: "음악",
  },
  {
    text: "피아노, 바이올린은 ___을 연주하는 악기예요.",
    answer: "멜로디",
    category: "음악",
  },
  { text: "리코더는 ___으로 부는 악기예요.", answer: "입", category: "음악" },
  {
    text: "북을 칠 때 사용하는 것은 ___이에요.",
    answer: "채",
    category: "음악",
  },
  {
    text: "색종이를 ___로 잘라 붙이면 꾸미기가 돼요.",
    answer: "가위",
    category: "만들기",
  },
  {
    text: "풀로 종이를 ___면 작품을 만들 수 있어요.",
    answer: "붙이",
    category: "만들기",
  },
  {
    text: "도화지에 물감으로 그림을 그리는 것을 ___이라고 해요.",
    answer: "그림 그리기",
    category: "미술",
  },
  {
    text: "검정색 크레파스로 칠한 후 긁어내는 기법을 ___이라고 해요.",
    answer: "스크래치",
    category: "미술",
  },
  {
    text: "손바닥에 물감을 묻혀 찍는 것을 ___이라고 해요.",
    answer: "핸드프린팅",
    category: "미술",
  },
  {
    text: "도장을 이용해서 찍는 놀이를 ___이라고 해요.",
    answer: "스탬핑",
    category: "미술",
  },
  {
    text: "자연에서 나뭇잎을 주워 만드는 작품을 ___라고 해요.",
    answer: "자연물 작품",
    category: "만들기",
  },
  {
    text: "빈 상자로 무언가를 만드는 놀이를 ___이라고 해요.",
    answer: "상자 만들기",
    category: "만들기",
  },
  {
    text: "노래에서 같은 부분이 반복되는 것을 ___라고 해요.",
    answer: "후렴",
    category: "음악",
  },
  {
    text: "그림에서 가까이 있는 것은 ___게 그려요.",
    answer: "크",
    category: "미술",
  },
  {
    text: "그림에서 멀리 있는 것은 ___게 그려요.",
    answer: "작",
    category: "미술",
  },
  {
    text: "따뜻한 느낌을 주는 색을 ___ 색이라고 해요.",
    answer: "따뜻한",
    category: "미술",
  },
  {
    text: "차가운 느낌을 주는 색을 ___ 색이라고 해요.",
    answer: "차가운",
    category: "미술",
  },
  {
    text: "빨강, 주황, 노랑은 ___ 느낌의 색이에요.",
    answer: "따뜻한",
    category: "미술",
  },
  {
    text: "파랑, 남색, 보라는 ___ 느낌의 색이에요.",
    answer: "차가운",
    category: "미술",
  },
  {
    text: "실을 이용해서 꿰는 놀이를 ___이라고 해요.",
    answer: "꿰기",
    category: "만들기",
  },
  {
    text: "종이를 찢어서 붙이는 미술 기법을 ___이라고 해요.",
    answer: "찢어 붙이기",
    category: "미술",
  },
  {
    text: "음악 시간에 친구들과 함께 노래 부르는 것을 ___이라고 해요.",
    answer: "합창",
    category: "음악",
  },
  {
    text: "악기를 함께 연주하는 것을 ___이라고 해요.",
    answer: "합주",
    category: "음악",
  },
  {
    text: "율동을 하며 노래 부르는 것을 ___이라고 해요.",
    answer: "율동",
    category: "음악",
  },
  {
    text: "전통 음악에서 사용하는 북을 ___이라고 해요.",
    answer: "장구",
    category: "음악",
  },
  {
    text: "우리나라 전통 악기 중 줄을 퉁기는 것은 ___이에요.",
    answer: "가야금",
    category: "음악",
  },
];
