import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
  HanjaEntry,
  EnglishEntry,
} from "@/types/curriculum";

// 6학년 1학기 교육과정 성취기준
export const grade6Semester1Standards = {
  math: [
    {
      code: "[6수01-08]",
      desc: "분수의 나눗셈을 이해하고 계산할 수 있다",
      unit: "분수의 나눗셈",
      difficulty: 6,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6수01-09]",
      desc: "소수의 나눗셈을 이해하고 계산할 수 있다",
      unit: "소수의 나눗셈",
      difficulty: 6,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수02-04]",
      desc: "각기둥과 각뿔의 구성 요소와 성질을 이해한다",
      unit: "각기둥과 각뿔",
      difficulty: 6,
      weeks: [7, 9] as [number, number],
    },
    {
      code: "[6수01-10]",
      desc: "두 양의 크기를 비교하는 상황을 통해 비의 개념을 이해한다",
      unit: "비와 비율",
      difficulty: 6,
      weeks: [10, 12] as [number, number],
    },
    {
      code: "[6수01-11]",
      desc: "비율을 이해하고 백분율로 나타낼 수 있다",
      unit: "비와 비율",
      difficulty: 6,
      weeks: [10, 12] as [number, number],
    },
    {
      code: "[6수04-02]",
      desc: "비율그래프를 해석하고 그릴 수 있다",
      unit: "여러 가지 그래프",
      difficulty: 6,
      weeks: [13, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[6국01-03]",
      desc: "절차와 규칙을 지키고 근거를 제시하며 토론한다",
      unit: "토론",
      difficulty: 6,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6국02-03]",
      desc: "글을 읽고 글쓴이가 말하고자 하는 주장이나 주제를 파악한다",
      unit: "주장과 근거",
      difficulty: 6,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[6국03-03]",
      desc: "목적이나 대상에 따라 알맞은 형식과 자료를 사용하여 설명하는 글을 쓴다",
      unit: "설명하는 글",
      difficulty: 6,
      weeks: [8, 11] as [number, number],
    },
    {
      code: "[6국04-02]",
      desc: "관용 표현을 이해하고 적절하게 활용한다",
      unit: "관용 표현",
      difficulty: 6,
      weeks: [12, 14] as [number, number],
    },
  ],
  english: [
    {
      code: "[6영01-03]",
      desc: "일상생활에 관한 짧고 쉬운 말이나 대화를 듣고 세부 정보를 파악할 수 있다",
      unit: "Listening",
      difficulty: 6,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[6영02-03]",
      desc: "일상생활에 관한 짧고 쉬운 글을 읽고 세부 정보를 파악할 수 있다",
      unit: "Reading",
      difficulty: 6,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[6영03-02]",
      desc: "자신의 일상생활에 관해 짧은 글을 쓸 수 있다",
      unit: "Writing",
      difficulty: 6,
      weeks: [9, 12] as [number, number],
    },
    {
      code: "[6영04-01]",
      desc: "간단한 문장을 정확하게 쓸 수 있다",
      unit: "Writing",
      difficulty: 6,
      weeks: [13, 15] as [number, number],
    },
  ],
};

export const grade6Semester2Standards = {
  math: [
    {
      code: "[6수01-12]",
      desc: "비례식을 알고 그 성질을 이해하며 이를 활용하여 문제를 해결할 수 있다",
      unit: "비례식과 비례배분",
      difficulty: 6,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6수01-13]",
      desc: "비례배분을 이해하고 문제를 해결할 수 있다",
      unit: "비례식과 비례배분",
      difficulty: 6,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6수02-05]",
      desc: "원주와 원의 넓이를 구할 수 있다",
      unit: "원의 넓이",
      difficulty: 6,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수02-06]",
      desc: "원기둥의 겉넓이와 부피를 구할 수 있다",
      unit: "원기둥, 원뿔, 구",
      difficulty: 6,
      weeks: [7, 9] as [number, number],
    },
    {
      code: "[6수03-02]",
      desc: "무게, 들이, 넓이의 단위 사이의 관계를 이해한다",
      unit: "단위 환산",
      difficulty: 6,
      weeks: [10, 12] as [number, number],
    },
    {
      code: "[6수04-03]",
      desc: "자료를 수집, 분류, 정리하여 목적에 맞는 그래프로 나타내고 해석할 수 있다",
      unit: "자료와 가능성",
      difficulty: 6,
      weeks: [13, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[6국01-04]",
      desc: "자신의 의견을 뒷받침하는 자료를 제시하며 발표한다",
      unit: "발표",
      difficulty: 6,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6국02-04]",
      desc: "글을 읽고 내용의 타당성과 표현의 적절성을 판단한다",
      unit: "비판적 읽기",
      difficulty: 6,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[6국05-02]",
      desc: "작품 속 세계와 현실 세계를 비교하며 작품을 감상한다",
      unit: "문학 감상",
      difficulty: 6,
      weeks: [8, 11] as [number, number],
    },
  ],
  english: [
    {
      code: "[6영01-04]",
      desc: "일상생활에 관한 짧고 쉬운 대화를 듣고 일이나 사건의 순서를 파악할 수 있다",
      unit: "Listening",
      difficulty: 6,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[6영02-04]",
      desc: "일상생활에 관한 짧고 쉬운 글을 읽고 일이나 사건의 순서를 파악할 수 있다",
      unit: "Reading",
      difficulty: 6,
      weeks: [5, 8] as [number, number],
    },
  ],
};

// ===== 맞춤법 데이터 (60개) =====
export const grade6SpellingData: SpellingEntry[] = [
  // 기존 22개
  {
    q1: "윗사람에게 예절을 갖추다.",
    q2: "웃사람에게 예절을 갖추다.",
    answer: 1,
    explanation: "'윗사람'이 올바른 사이시옷 표기입니다.",
  },
  {
    q1: "이따가 만나자.",
    q2: "있다가 만나자.",
    answer: 1,
    explanation: "'이따가'(조금 후에)가 올바른 표기입니다.",
  },
  {
    q1: "삼가 조의를 표합니다.",
    q2: "삼가 조의를 표함니다.",
    answer: 1,
    explanation: "'표합니다'가 올바른 표기입니다.",
  },
  {
    q1: "무릎을 꿇었다.",
    q2: "무릎을 꿀었다.",
    answer: 1,
    explanation: "'꿇었다'가 올바른 표기입니다.",
  },
  {
    q1: "어떻게 해야 좋을까?",
    q2: "어떡게 해야 좋을까?",
    answer: 1,
    explanation: "'어떻게'가 올바른 표기입니다.",
  },
  {
    q1: "아무튼 열심히 하자.",
    q2: "아뭏든 열심히 하자.",
    answer: 1,
    explanation: "'아무튼'이 올바른 표기입니다.",
  },
  {
    q1: "건강에 해롭다.",
    q2: "건강에 해롭따.",
    answer: 1,
    explanation: "'해롭다'가 올바른 표기입니다.",
  },
  {
    q1: "초조하게 기다렸다.",
    q2: "초조하께 기다렸다.",
    answer: 1,
    explanation: "'초조하게'가 올바른 표기입니다.",
  },
  {
    q1: "삶의 여유를 즐기다.",
    q2: "삶의 여유를 즐기다.",
    answer: 1,
    explanation: "'즐기다'가 올바른 표기입니다.",
  },
  {
    q1: "일이 틀어졌다.",
    q2: "일이 틀려졌다.",
    answer: 1,
    explanation:
      "'틀어지다'는 '뒤틀리다'의 뜻, '틀리다'는 '잘못되다'의 뜻입니다.",
  },
  {
    q1: "곤이곤대로 받아들였다.",
    q2: "고니곤대로 받아들였다.",
    answer: 1,
    explanation: "'곤이곤대로'가 올바른 표기입니다.",
  },
  {
    q1: "갈수록 태산이다.",
    q2: "갈수록 태산이다.",
    answer: 1,
    explanation: "'갈수록 태산'은 올바른 관용구입니다.",
  },
  {
    q1: "그가 납득했다.",
    q2: "그가 납덕했다.",
    answer: 1,
    explanation: "'납득'이 올바른 표기입니다.",
  },
  {
    q1: "폐허가 되었다.",
    q2: "페허가 되었다.",
    answer: 1,
    explanation: "'폐허'가 올바른 표기입니다.",
  },
  {
    q1: "한가한 오후를 보냈다.",
    q2: "한가한 오후를 보낸다.",
    answer: 1,
    explanation: "'보냈다'(과거형)가 문맥에 맞습니다.",
  },
  {
    q1: "수확이 풍성하다.",
    q2: "수확이 풍성하다.",
    answer: 1,
    explanation: "'풍성하다'가 올바른 표기입니다.",
  },
  {
    q1: "깍두기를 만들었다.",
    q2: "깎두기를 만들었다.",
    answer: 1,
    explanation: "'깍두기'가 올바른 표기입니다.",
  },
  {
    q1: "사나흘 만에 완성했다.",
    q2: "사나흘만에 완성했다.",
    answer: 1,
    explanation: "'사나흘 만에'처럼 '만에'는 띄어 씁니다.",
  },
  {
    q1: "새해 복 많이 받으세요.",
    q2: "새해 복 만이 받으세요.",
    answer: 1,
    explanation: "'많이'가 올바른 표기입니다.",
  },
  {
    q1: "만사가 귀찮다.",
    q2: "만사가 귀찬타.",
    answer: 1,
    explanation: "'귀찮다'가 올바른 표기입니다.",
  },
  {
    q1: "불우 이웃을 도왔다.",
    q2: "불우 이웃을 도왔다.",
    answer: 1,
    explanation: "'도왔다'가 올바른 표기입니다.",
  },
  // 추가 38개 (총 60개)
  {
    q1: "그는 능글맞은 사람이다.",
    q2: "그는 능금맞은 사람이다.",
    answer: 1,
    explanation: "'능글맞다'가 올바른 표기입니다.",
  },
  {
    q1: "할 수 있는 데까지 해 보자.",
    q2: "할 수 있는 대까지 해 보자.",
    answer: 1,
    explanation: "'데'(곳, 경우)가 올바른 표기입니다.",
  },
  {
    q1: "여간 어려운 게 아니다.",
    q2: "여간 어려운게 아니다.",
    answer: 1,
    explanation: "'어려운 게'(것이)는 띄어 쓰는 것이 맞습니다.",
  },
  {
    q1: "이른바 전문가라는 사람이.",
    q2: "일은바 전문가라는 사람이.",
    answer: 1,
    explanation: "'이른바'가 올바른 표기입니다.",
  },
  {
    q1: "사필귀정이라 했다.",
    q2: "사필귀정이라 했다.",
    answer: 1,
    explanation:
      "'사필귀정'(일이 반드시 바른 길로 돌아감)이 올바른 표기입니다.",
  },
  {
    q1: "우여곡절 끝에 성공했다.",
    q2: "우여곡절 끝에 성공했다.",
    answer: 1,
    explanation: "'우여곡절'이 올바른 표기입니다.",
  },
  {
    q1: "설왕설래하며 토론했다.",
    q2: "설왕설래하며 토론했다.",
    answer: 1,
    explanation: "'설왕설래'(서로 주장을 주고받음)가 올바른 표기입니다.",
  },
  {
    q1: "가름하다 - 양쪽으로 나누다.",
    q2: "갈음하다 - 양쪽으로 나누다.",
    answer: 1,
    explanation:
      "'가르다'에서 파생된 '가름하다'가 맞습니다. '갈음하다'는 '대신하다'입니다.",
  },
  {
    q1: "풋사과를 먹었다.",
    q2: "풋사과를 먹었다.",
    answer: 1,
    explanation: "'풋사과'(덜 익은 사과)가 올바른 표기입니다.",
  },
  {
    q1: "제대로 해야 한다.",
    q2: "재대로 해야 한다.",
    answer: 1,
    explanation: "'제대로'가 올바른 표기입니다.",
  },
  {
    q1: "지리멸렬한 상태이다.",
    q2: "지리멸열한 상태이다.",
    answer: 1,
    explanation: "'지리멸렬'이 올바른 표기입니다.",
  },
  {
    q1: "그럴듯하게 꾸며 놓았다.",
    q2: "그럴 듯하게 꾸며 놓았다.",
    answer: 1,
    explanation: "'그럴듯하다'는 한 단어로 붙여 씁니다.",
  },
  {
    q1: "유명세를 치르다.",
    q2: "유명세를 치루다.",
    answer: 1,
    explanation: "'치르다'가 올바른 표기입니다.",
  },
  {
    q1: "천장에 물이 센다.",
    q2: "천정에 물이 센다.",
    answer: 1,
    explanation: "'천장'이 올바른 표기입니다.",
  },
  {
    q1: "개구쟁이가 말썽을 부린다.",
    q2: "개구장이가 말썽을 부린다.",
    answer: 1,
    explanation: "'개구쟁이'가 올바른 표기입니다.",
  },
  {
    q1: "그가 쾌재를 불렀다.",
    q2: "그가 괘재를 불렀다.",
    answer: 1,
    explanation: "'쾌재'(기뻐서 외침)가 올바른 표기입니다.",
  },
  {
    q1: "우물쭈물하지 마라.",
    q2: "우물주물하지 마라.",
    answer: 1,
    explanation: "'우물쭈물'이 올바른 표기입니다.",
  },
  {
    q1: "나위가 없을 만큼 좋다.",
    q2: "나위가 없을만큼 좋다.",
    answer: 1,
    explanation: "'없을 만큼'처럼 '만큼'은 띄어 쓰는 것이 맞습니다.",
  },
  {
    q1: "됬다, 그만하자.",
    q2: "됐다, 그만하자.",
    answer: 2,
    explanation: "'됐다'(되었다의 줄임)가 올바른 표기입니다.",
  },
  {
    q1: "할께요, 약속해요.",
    q2: "할게요, 약속해요.",
    answer: 2,
    explanation: "'할게요'가 올바른 표기입니다.",
  },
  {
    q1: "이왕이면 다홍치마이다.",
    q2: "이왕이면 다홍치마이다.",
    answer: 1,
    explanation: "'이왕이면 다홍치마'는 올바른 속담 표기입니다.",
  },
  {
    q1: "범인의 소행으로 보인다.",
    q2: "범인의 소행으로 보인다.",
    answer: 1,
    explanation: "'소행'(한 짓)이 올바른 표기입니다.",
  },
  {
    q1: "일체의 편견을 버려라.",
    q2: "일채의 편견을 버려라.",
    answer: 1,
    explanation: "'일체'(전부)가 올바른 표기입니다.",
  },
  {
    q1: "꼼짝도 하지 마라.",
    q2: "꼼짝도 하지 마라.",
    answer: 1,
    explanation: "'꼼짝'이 올바른 표기입니다.",
  },
  {
    q1: "어쩔 수 없다.",
    q2: "어쩔수 없다.",
    answer: 1,
    explanation: "'어쩔 수'처럼 '수'는 의존명사이므로 띄어 씁니다.",
  },
  {
    q1: "결재를 받다. (승인)",
    q2: "결제를 받다. (승인)",
    answer: 1,
    explanation: "'결재'(승인)가 올바릅니다. '결제'는 '돈을 치름'입니다.",
  },
  {
    q1: "구렛나루가 멋있다.",
    q2: "구레나룻이 멋있다.",
    answer: 1,
    explanation: "'구렛나루'가 올바른 표기입니다.",
  },
  {
    q1: "퇴짜를 놓다.",
    q2: "퇴짜를 놓다.",
    answer: 1,
    explanation: "'퇴짜'(거절)가 올바른 표기입니다.",
  },
  {
    q1: "십상이다. (당연한 것)",
    q2: "십쌍이다. (당연한 것)",
    answer: 1,
    explanation: "'십상'(당연히 그런 일)이 올바른 표기입니다.",
  },
  {
    q1: "쌍벽을 이루다.",
    q2: "쌍벽을 이루다.",
    answer: 1,
    explanation: "'쌍벽'(둘이 함께 견줄 만한 것)이 올바른 표기입니다.",
  },
  {
    q1: "배째라 하다.",
    q2: "배째라 하다.",
    answer: 1,
    explanation: "'배째라'(마음대로 하라)가 올바른 표기입니다.",
  },
  {
    q1: "아름답고도 슬픈 이야기.",
    q2: "아름답고도 슬픈 이야기.",
    answer: 1,
    explanation: "'아름답고도'가 올바른 표기입니다.",
  },
  {
    q1: "벼락맞은 듯 놀랐다.",
    q2: "벼락마즌 듯 놀랐다.",
    answer: 1,
    explanation: "'벼락맞은'이 올바른 표기입니다.",
  },
  {
    q1: "해코지를 당했다.",
    q2: "해꼬지를 당했다.",
    answer: 1,
    explanation: "'해코지'가 올바른 표기입니다.",
  },
  {
    q1: "갖은 고생을 다 했다.",
    q2: "같은 고생을 다 했다.",
    answer: 1,
    explanation:
      "'갖은'(여러 가지의)이 올바릅니다. '같은'은 '동일한'의 뜻입니다.",
  },
  {
    q1: "체면치레를 하다.",
    q2: "체면치례를 하다.",
    answer: 1,
    explanation: "'체면치레'가 올바른 표기입니다.",
  },
  {
    q1: "그 사람은 목불인견이다.",
    q2: "그 사람은 목불인견이다.",
    answer: 1,
    explanation: "'목불인견'(차마 눈뜨고 볼 수 없음)이 올바른 표기입니다.",
  },
  {
    q1: "한편으로는 걱정이 됐다.",
    q2: "한 편으로는 걱정이 됐다.",
    answer: 1,
    explanation: "'한편'(한쪽)은 한 단어로 붙여 씁니다.",
  },
  {
    q1: "흔쾌히 수락했다.",
    q2: "흔쾌이 수락했다.",
    answer: 1,
    explanation: "'흔쾌히'가 올바른 표기입니다.",
  },
];

// ===== 어휘 데이터 (60개) =====
export const grade6VocabData: VocabEntry[] = [
  // 기존 15개
  { meanings: ["국가 간의 약속", "나라와 나라가 맺는 것"], answer: "조약" },
  {
    meanings: [
      "사회에서 지켜야 할 행동 기준",
      "법과 비슷하지만 강제성이 약해요",
    ],
    answer: "규범",
  },
  {
    meanings: ["옳고 그름을 판단하는 능력", "선과 악을 구별해요"],
    answer: "양심",
  },
  {
    meanings: ["생물이 환경에 맞게 변하는 것", "다윈이 연구했어요"],
    answer: "진화",
  },
  {
    meanings: ["한 나라의 주요 산업", "국가 경제의 기둥이에요"],
    answer: "기간산업",
  },
  {
    meanings: ["국민이 나라에 내는 돈", "소득세, 부가세 등이 있어요"],
    answer: "세금",
  },
  {
    meanings: ["다른 나라로 물건을 파는 것", "반대말은 수입이에요"],
    answer: "수출",
  },
  {
    meanings: ["권리를 지키기 위해 대표를 뽑는 것", "민주주의의 기본이에요"],
    answer: "선거",
  },
  {
    meanings: ["자연을 있는 그대로 지키는 것", "동식물을 보호해요"],
    answer: "보전",
  },
  {
    meanings: ["원래 있던 사람", "그 지역에 처음부터 살던 사람들"],
    answer: "원주민",
  },
  { meanings: ["의견이 달라 부딪치는 것", "화해가 필요해요"], answer: "갈등" },
  { meanings: ["말이나 글의 앞뒤 관계", "문맥이라고도 해요"], answer: "맥락" },
  {
    meanings: ["개인의 자유와 권리를 보장하는 원리", "국가 운영의 기본 원리"],
    answer: "민주주의",
  },
  {
    meanings: ["생각이나 주장을 뒷받침하는 사실", "논증에 필요해요"],
    answer: "근거",
  },
  {
    meanings: ["서로 돕고 함께 발전하는 것", "윈윈이라고도 해요"],
    answer: "상생",
  },
  // 추가 45개 (총 60개)
  { meanings: ["나라를 다스리는 기본 법", "최상위 법이에요"], answer: "헌법" },
  {
    meanings: ["다른 사람의 입장에서 생각하는 것", "상대방의 마음을 헤아려요"],
    answer: "공감",
  },
  {
    meanings: ["오래전부터 전해 내려오는 것", "조상의 지혜가 담겨 있어요"],
    answer: "전통",
  },
  {
    meanings: ["둘 이상의 나라가 함께 일하는 것", "유엔이 대표적이에요"],
    answer: "국제협력",
  },
  {
    meanings: ["자기 자신의 가치를 인정하는 것", "자존심과 비슷해요"],
    answer: "자존감",
  },
  {
    meanings: ["사회의 약자를 돕는 제도", "복지 국가의 핵심이에요"],
    answer: "복지",
  },
  {
    meanings: ["사물이나 현상의 원인을 밝히는 것", "과학적 방법으로 해요"],
    answer: "분석",
  },
  {
    meanings: ["어떤 주제에 대한 체계적인 글", "학자들이 많이 써요"],
    answer: "논문",
  },
  {
    meanings: ["지구의 기온이 점점 올라가는 현상", "환경 문제의 하나예요"],
    answer: "온난화",
  },
  {
    meanings: ["한 나라의 모든 국민에게 보장되는 것", "인권과 관련 있어요"],
    answer: "기본권",
  },
  {
    meanings: ["여러 민족이 함께 사는 사회", "서로의 문화를 존중해요"],
    answer: "다문화",
  },
  {
    meanings: ["생물이 살아가는 자연 환경", "생태계라고도 해요"],
    answer: "서식지",
  },
  {
    meanings: ["과거의 잘못을 인정하는 것", "용기가 필요해요"],
    answer: "사과",
  },
  {
    meanings: ["경험이나 지식이 쌓여 얻는 것", "인생의 교훈이에요"],
    answer: "지혜",
  },
  {
    meanings: [
      "세계 여러 나라의 문제를 함께 해결하는 것",
      "지구촌과 관련 있어요",
    ],
    answer: "세계시민의식",
  },
  {
    meanings: ["태어나면서부터 가지는 권리", "생명, 자유, 평등 등이 있어요"],
    answer: "천부인권",
  },
  {
    meanings: ["과학적 사실에 근거한 주장", "감정이 아닌 이성에 기반해요"],
    answer: "합리성",
  },
  {
    meanings: ["미래를 위해 현재를 준비하는 것", "저축과 비슷해요"],
    answer: "대비",
  },
  {
    meanings: ["서로 다른 문화를 받아들이는 것", "편견을 버려야 해요"],
    answer: "관용",
  },
  {
    meanings: ["어떤 일의 결과를 미리 알아보는 것", "통계를 이용해요"],
    answer: "예측",
  },
  {
    meanings: ["사람이 마땅히 누려야 할 권리", "유엔이 선언했어요"],
    answer: "인권",
  },
  {
    meanings: ["자연환경을 지키기 위한 활동", "재활용이 대표적이에요"],
    answer: "환경보호",
  },
  {
    meanings: ["의견을 조율하여 합의에 이르는 것", "민주주의의 기본이에요"],
    answer: "타협",
  },
  {
    meanings: ["개인이나 단체가 스스로를 다스리는 것", "자유와 짝이에요"],
    answer: "자율",
  },
  {
    meanings: ["집단의 힘으로 목표를 이루는 것", "함께할 때 더 강해요"],
    answer: "연대",
  },
  {
    meanings: ["정보를 정리하여 보기 쉽게 만든 것", "도표와 비슷해요"],
    answer: "통계",
  },
  {
    meanings: ["남녀가 동등한 권리를 갖는 것", "성별에 따른 차별이 없어요"],
    answer: "양성평등",
  },
  {
    meanings: ["여러 사람의 의견 중 가장 많은 것", "투표로 결정해요"],
    answer: "다수결",
  },
  {
    meanings: [
      "자원을 아끼고 효율적으로 사용하는 것",
      "미래 세대를 위해 필요해요",
    ],
    answer: "지속가능",
  },
  {
    meanings: ["국가의 살림을 관리하는 것", "세입과 세출이 있어요"],
    answer: "재정",
  },
  {
    meanings: ["역사적 사실을 기록한 자료", "유물, 유적, 문서 등이 있어요"],
    answer: "사료",
  },
  {
    meanings: ["옳지 않은 일에 맞서는 것", "정의를 위해 필요해요"],
    answer: "저항",
  },
  {
    meanings: ["나라와 나라 사이의 무역", "수출과 수입이 있어요"],
    answer: "교역",
  },
  {
    meanings: ["사회가 점점 나아지는 것", "경제, 문화, 복지 면에서 발전해요"],
    answer: "발전",
  },
  { meanings: ["잘못된 제도를 바꾸는 것", "개혁과 비슷해요"], answer: "개혁" },
  {
    meanings: ["과학 실험에서 변하는 값", "독립변인과 종속변인이 있어요"],
    answer: "변인",
  },
  {
    meanings: ["작품이나 의견에 대한 평가", "장단점을 따져 봐요"],
    answer: "비평",
  },
  { meanings: ["어떤 분야의 뛰어난 능력", "재능과 비슷해요"], answer: "역량" },
  {
    meanings: [
      "여럿 중에서 가장 좋은 것을 고르는 것",
      "면접이나 시험으로 해요",
    ],
    answer: "선발",
  },
  {
    meanings: ["논리적으로 옳고 그름을 따지는 것", "비판적 사고와 관련 있어요"],
    answer: "논증",
  },
  {
    meanings: ["나라 밖으로 나가 사는 것", "이민과 비슷해요"],
    answer: "해외이주",
  },
  {
    meanings: ["잘못된 정보를 바로잡는 것", "신문에서 자주 해요"],
    answer: "정정",
  },
  {
    meanings: ["여러 가지를 모아 하나로 합치는 것", "통합과 비슷해요"],
    answer: "통합",
  },
  {
    meanings: ["사회의 약한 사람을 보호하는 것", "복지와 관련 있어요"],
    answer: "보호",
  },
  { meanings: ["미래에 대한 희망과 기대", "꿈과 비슷해요"], answer: "포부" },
];

// ===== 수학 데이터 (80개) =====
export const grade6MathData: MathEntry[] = [
  // 기존 22개
  // 분수의 나눗셈
  {
    type: "calculation",
    expression: "3/4 ÷ 1/2",
    answer: 3,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "3/4 × 2/1 = 6/4",
      "약분: 6/4 = 3/2 = 1과 1/2",
    ],
    unit: "분수의 나눗셈",
    numbers: [3, 4, 1, 2],
  },
  {
    type: "calculation",
    expression: "2/3 ÷ 4/9",
    answer: 3,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "2/3 × 9/4 = 18/12",
      "약분: 18/12 = 3/2 = 1과 1/2",
    ],
    unit: "분수의 나눗셈",
    numbers: [2, 3, 4, 9],
  },
  {
    type: "calculation",
    expression: "5/6 ÷ 2/3",
    answer: 5,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "5/6 × 3/2 = 15/12",
      "약분: 15/12 = 5/4 = 1과 1/4",
    ],
    unit: "분수의 나눗셈",
    numbers: [5, 6, 2, 3],
  },
  // 소수의 나눗셈
  {
    type: "calculation",
    expression: "7.2 ÷ 0.8",
    answer: 9,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "72 ÷ 8 = 9"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "4.56 ÷ 1.2",
    answer: 3.8,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "45.6 ÷ 12 = 3.8"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "6.25 ÷ 2.5",
    answer: 2.5,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "62.5 ÷ 25 = 2.5"],
    unit: "소수의 나눗셈",
  },
  // 비와 비율
  {
    type: "calculation",
    expression: "12 : 16의 가장 간단한 비",
    answer: 3,
    steps: [
      "12와 16의 최대공약수: 4",
      "12 ÷ 4 = 3, 16 ÷ 4 = 4",
      "가장 간단한 비: 3 : 4",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "25는 50의 몇 %?",
    answer: 50,
    steps: ["비율 = 25 ÷ 50 = 0.5", "백분율 = 0.5 × 100 = 50%"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "80의 30%",
    answer: 24,
    steps: ["80 × 30/100", "80 × 0.3 = 24"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "할인 전 10000원, 20% 할인 후 가격",
    answer: 8000,
    steps: [
      "할인 금액: 10000 × 20/100 = 2000원",
      "할인 후: 10000 - 2000 = 8000원",
    ],
    unit: "백분율 활용",
  },
  // 비례식
  {
    type: "calculation",
    expression: "3 : 5 = 9 : x에서 x",
    answer: 15,
    steps: ["외항의 곱 = 내항의 곱", "3 × x = 5 × 9", "3x = 45", "x = 15"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "4 : x = 8 : 12에서 x",
    answer: 6,
    steps: ["외항의 곱 = 내항의 곱", "4 × 12 = x × 8", "48 = 8x", "x = 6"],
    unit: "비례식",
  },
  // 비례배분
  {
    type: "calculation",
    expression: "120을 3:5로 비례배분 (작은 쪽)",
    answer: 45,
    steps: [
      "전체 비: 3 + 5 = 8",
      "작은 쪽: 120 × 3/8 = 45",
      "큰 쪽: 120 × 5/8 = 75",
    ],
    unit: "비례배분",
  },
  // 원의 넓이
  {
    type: "calculation",
    expression: "반지름 5cm인 원의 넓이 (π=3.14)",
    answer: 78.5,
    steps: ["원의 넓이 = π × r²", "3.14 × 5 × 5 = 3.14 × 25", "답: 78.5cm²"],
    unit: "원의 넓이",
  },
  {
    type: "calculation",
    expression: "지름 10cm인 원의 원주 (π=3.14)",
    answer: 31.4,
    steps: ["원주 = π × 지름", "3.14 × 10 = 31.4", "답: 31.4cm"],
    unit: "원주",
  },
  // 원기둥의 부피
  {
    type: "calculation",
    expression: "밑면 반지름 3cm, 높이 10cm 원기둥의 부피 (π=3.14)",
    answer: 282.6,
    steps: ["원기둥의 부피 = π × r² × 높이", "3.14 × 9 × 10", "답: 282.6cm³"],
    unit: "원기둥의 부피",
  },
  // 복합 문제
  {
    type: "calculation",
    expression: "3/5 × 2/7 ÷ 6/35",
    answer: 1,
    steps: [
      "먼저 곱셈: 3/5 × 2/7 = 6/35",
      "다음 나눗셈: 6/35 ÷ 6/35 = 1",
      "답: 1",
    ],
    unit: "분수 혼합 계산",
    numbers: [3, 5, 2, 7],
  },
  {
    type: "calculation",
    expression: "15 : 20을 가장 간단한 정수의 비로",
    answer: 3,
    steps: [
      "15와 20의 최대공약수: 5",
      "15 ÷ 5 = 3, 20 ÷ 5 = 4",
      "가장 간단한 비: 3 : 4",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "200의 15%에서 200의 10%를 빼면",
    answer: 10,
    steps: ["200 × 0.15 = 30", "200 × 0.10 = 20", "30 - 20 = 10"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "윗변 5cm, 아랫변 9cm, 높이 6cm 사다리꼴의 넓이",
    answer: 42,
    steps: [
      "사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2",
      "(5 + 9) × 6 ÷ 2 = 14 × 6 ÷ 2",
      "84 ÷ 2 = 42",
      "답: 42cm²",
    ],
    unit: "넓이",
  },

  // ===== 추가 58개 (총 80개) =====
  // 분수의 나눗셈 추가
  {
    type: "calculation",
    expression: "7/8 ÷ 3/4",
    answer: 7,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "7/8 × 4/3 = 28/24",
      "약분: 28/24 = 7/6 = 1과 1/6",
    ],
    unit: "분수의 나눗셈",
    numbers: [7, 8, 3, 4],
  },
  {
    type: "calculation",
    expression: "4/5 ÷ 2/15",
    answer: 6,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "4/5 × 15/2 = 60/10",
      "약분: 60/10 = 6",
    ],
    unit: "분수의 나눗셈",
    numbers: [4, 5, 2, 15],
  },
  {
    type: "calculation",
    expression: "3 ÷ 3/7",
    answer: 7,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "3/1 × 7/3 = 21/3",
      "약분: 21/3 = 7",
    ],
    unit: "분수의 나눗셈",
    numbers: [3, 1, 3, 7],
  },
  {
    type: "calculation",
    expression: "5/9 ÷ 5/6",
    answer: 2,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "5/9 × 6/5 = 30/45",
      "약분: 30/45 = 2/3",
    ],
    unit: "분수의 나눗셈",
    numbers: [5, 9, 5, 6],
  },
  {
    type: "calculation",
    expression: "1/2 ÷ 3/8",
    answer: 4,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "1/2 × 8/3 = 8/6",
      "약분: 8/6 = 4/3 = 1과 1/3",
    ],
    unit: "분수의 나눗셈",
    numbers: [1, 2, 3, 8],
  },
  {
    type: "calculation",
    expression: "9/10 ÷ 3/5",
    answer: 3,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "9/10 × 5/3 = 45/30",
      "약분: 45/30 = 3/2 = 1과 1/2",
    ],
    unit: "분수의 나눗셈",
    numbers: [9, 10, 3, 5],
  },
  {
    type: "calculation",
    expression: "2/7 ÷ 4/21",
    answer: 3,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "2/7 × 21/4 = 42/28",
      "약분: 42/28 = 3/2 = 1과 1/2",
    ],
    unit: "분수의 나눗셈",
    numbers: [2, 7, 4, 21],
  },

  // 소수의 나눗셈 추가
  {
    type: "calculation",
    expression: "8.4 ÷ 1.2",
    answer: 7,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "84 ÷ 12 = 7"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "9.6 ÷ 0.4",
    answer: 24,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "96 ÷ 4 = 24"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "3.36 ÷ 0.8",
    answer: 4.2,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "33.6 ÷ 8 = 4.2"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "5.4 ÷ 1.8",
    answer: 3,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "54 ÷ 18 = 3"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "12.5 ÷ 2.5",
    answer: 5,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "125 ÷ 25 = 5"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "0.96 ÷ 0.16",
    answer: 6,
    steps: ["소수점을 오른쪽으로 두 칸 이동", "96 ÷ 16 = 6"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "15.6 ÷ 1.3",
    answer: 12,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "156 ÷ 13 = 12"],
    unit: "소수의 나눗셈",
  },

  // 비와 비율 추가
  {
    type: "calculation",
    expression: "9 : 15의 가장 간단한 비",
    answer: 3,
    steps: [
      "9와 15의 최대공약수: 3",
      "9 ÷ 3 = 3, 15 ÷ 3 = 5",
      "가장 간단한 비: 3 : 5",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "18 : 24의 가장 간단한 비",
    answer: 3,
    steps: [
      "18과 24의 최대공약수: 6",
      "18 ÷ 6 = 3, 24 ÷ 6 = 4",
      "가장 간단한 비: 3 : 4",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "0.6 : 0.9의 가장 간단한 비",
    answer: 2,
    steps: [
      "소수를 정수로: 6 : 9",
      "6과 9의 최대공약수: 3",
      "가장 간단한 비: 2 : 3",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "2/3 : 4/5의 가장 간단한 비",
    answer: 10,
    steps: [
      "통분: 10/15 : 12/15",
      "분자만 비교: 10 : 12",
      "최대공약수: 2 → 5 : 6",
    ],
    unit: "비와 비율",
  },

  // 백분율 추가
  {
    type: "calculation",
    expression: "60의 45%",
    answer: 27,
    steps: ["60 × 45/100", "60 × 0.45 = 27"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "150의 20%",
    answer: 30,
    steps: ["150 × 20/100", "150 × 0.2 = 30"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "36은 90의 몇 %?",
    answer: 40,
    steps: ["비율 = 36 ÷ 90 = 0.4", "백분율 = 0.4 × 100 = 40%"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "원래 가격 5000원, 30% 할인 후 가격",
    answer: 3500,
    steps: [
      "할인 금액: 5000 × 30/100 = 1500원",
      "할인 후: 5000 - 1500 = 3500원",
    ],
    unit: "백분율 활용",
  },
  {
    type: "calculation",
    expression: "원래 가격 8000원, 25% 할인 후 가격",
    answer: 6000,
    steps: [
      "할인 금액: 8000 × 25/100 = 2000원",
      "할인 후: 8000 - 2000 = 6000원",
    ],
    unit: "백분율 활용",
  },
  {
    type: "calculation",
    expression: "40명 중 16명이 여학생일 때 여학생 비율",
    answer: 40,
    steps: ["비율 = 16 ÷ 40 = 0.4", "백분율 = 0.4 × 100 = 40%"],
    unit: "백분율",
  },

  // 비례식 추가
  {
    type: "calculation",
    expression: "5 : 8 = x : 24에서 x",
    answer: 15,
    steps: ["외항의 곱 = 내항의 곱", "5 × 24 = 8 × x", "120 = 8x", "x = 15"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "x : 9 = 4 : 6에서 x",
    answer: 6,
    steps: ["외항의 곱 = 내항의 곱", "x × 6 = 9 × 4", "6x = 36", "x = 6"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "7 : 3 = 21 : x에서 x",
    answer: 9,
    steps: ["외항의 곱 = 내항의 곱", "7 × x = 3 × 21", "7x = 63", "x = 9"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "2 : 5 = x : 35에서 x",
    answer: 14,
    steps: ["외항의 곱 = 내항의 곱", "2 × 35 = 5 × x", "70 = 5x", "x = 14"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "x : 4 = 12 : 16에서 x",
    answer: 3,
    steps: ["외항의 곱 = 내항의 곱", "x × 16 = 4 × 12", "16x = 48", "x = 3"],
    unit: "비례식",
  },

  // 비례배분 추가
  {
    type: "calculation",
    expression: "200을 3:2로 비례배분 (큰 쪽)",
    answer: 120,
    steps: [
      "전체 비: 3 + 2 = 5",
      "큰 쪽: 200 × 3/5 = 120",
      "작은 쪽: 200 × 2/5 = 80",
    ],
    unit: "비례배분",
  },
  {
    type: "calculation",
    expression: "180을 2:3:4로 비례배분 (가운데)",
    answer: 60,
    steps: ["전체 비: 2 + 3 + 4 = 9", "가운데: 180 × 3/9 = 60"],
    unit: "비례배분",
  },
  {
    type: "calculation",
    expression: "300을 1:2로 비례배분 (작은 쪽)",
    answer: 100,
    steps: [
      "전체 비: 1 + 2 = 3",
      "작은 쪽: 300 × 1/3 = 100",
      "큰 쪽: 300 × 2/3 = 200",
    ],
    unit: "비례배분",
  },
  {
    type: "calculation",
    expression: "150을 2:3으로 비례배분 (큰 쪽)",
    answer: 90,
    steps: [
      "전체 비: 2 + 3 = 5",
      "큰 쪽: 150 × 3/5 = 90",
      "작은 쪽: 150 × 2/5 = 60",
    ],
    unit: "비례배분",
  },
  {
    type: "calculation",
    expression: "240을 5:3으로 비례배분 (큰 쪽)",
    answer: 150,
    steps: [
      "전체 비: 5 + 3 = 8",
      "큰 쪽: 240 × 5/8 = 150",
      "작은 쪽: 240 × 3/8 = 90",
    ],
    unit: "비례배분",
  },

  // 원의 넓이/원주 추가
  {
    type: "calculation",
    expression: "반지름 7cm인 원의 넓이 (π=3.14)",
    answer: 153.86,
    steps: ["원의 넓이 = π × r²", "3.14 × 7 × 7 = 3.14 × 49", "답: 153.86cm²"],
    unit: "원의 넓이",
  },
  {
    type: "calculation",
    expression: "반지름 4cm인 원의 넓이 (π=3.14)",
    answer: 50.24,
    steps: ["원의 넓이 = π × r²", "3.14 × 4 × 4 = 3.14 × 16", "답: 50.24cm²"],
    unit: "원의 넓이",
  },
  {
    type: "calculation",
    expression: "지름 14cm인 원의 원주 (π=3.14)",
    answer: 43.96,
    steps: ["원주 = π × 지름", "3.14 × 14 = 43.96", "답: 43.96cm"],
    unit: "원주",
  },
  {
    type: "calculation",
    expression: "반지름 6cm인 원의 원주 (π=3.14)",
    answer: 37.68,
    steps: ["원주 = π × 지름 = π × 2r", "3.14 × 12 = 37.68", "답: 37.68cm"],
    unit: "원주",
  },
  {
    type: "calculation",
    expression: "지름 20cm인 원의 원주 (π=3.14)",
    answer: 62.8,
    steps: ["원주 = π × 지름", "3.14 × 20 = 62.8", "답: 62.8cm"],
    unit: "원주",
  },
  {
    type: "calculation",
    expression: "반지름 10cm인 원의 넓이 (π=3.14)",
    answer: 314,
    steps: ["원의 넓이 = π × r²", "3.14 × 10 × 10 = 3.14 × 100", "답: 314cm²"],
    unit: "원의 넓이",
  },

  // 원기둥 부피 추가
  {
    type: "calculation",
    expression: "밑면 반지름 5cm, 높이 8cm 원기둥의 부피 (π=3.14)",
    answer: 628,
    steps: [
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 25 × 8 = 628",
      "답: 628cm³",
    ],
    unit: "원기둥의 부피",
  },
  {
    type: "calculation",
    expression: "밑면 반지름 4cm, 높이 6cm 원기둥의 부피 (π=3.14)",
    answer: 301.44,
    steps: [
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 16 × 6 = 301.44",
      "답: 301.44cm³",
    ],
    unit: "원기둥의 부피",
  },
  {
    type: "calculation",
    expression: "밑면 반지름 2cm, 높이 15cm 원기둥의 부피 (π=3.14)",
    answer: 188.4,
    steps: [
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 4 × 15 = 188.4",
      "답: 188.4cm³",
    ],
    unit: "원기둥의 부피",
  },
  {
    type: "calculation",
    expression: "밑면 지름 10cm, 높이 7cm 원기둥의 부피 (π=3.14)",
    answer: 549.5,
    steps: [
      "반지름 = 10 ÷ 2 = 5cm",
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 25 × 7 = 549.5",
      "답: 549.5cm³",
    ],
    unit: "원기둥의 부피",
  },

  // 넓이 추가
  {
    type: "calculation",
    expression: "윗변 7cm, 아랫변 11cm, 높이 8cm 사다리꼴의 넓이",
    answer: 72,
    steps: [
      "사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2",
      "(7 + 11) × 8 ÷ 2 = 18 × 8 ÷ 2",
      "144 ÷ 2 = 72",
      "답: 72cm²",
    ],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 15cm, 높이 12cm 삼각형의 넓이",
    answer: 90,
    steps: ["삼각형의 넓이 = 밑변 × 높이 ÷ 2", "15 × 12 ÷ 2 = 90", "답: 90cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "대각선이 10cm, 14cm인 마름모의 넓이",
    answer: 70,
    steps: [
      "마름모의 넓이 = 대각선 × 대각선 ÷ 2",
      "10 × 14 ÷ 2 = 70",
      "답: 70cm²",
    ],
    unit: "넓이",
  },
  // 추가 13개 (80개 달성)
  {
    type: "calculation",
    expression: "6 ÷ 3/4",
    answer: 8,
    steps: [
      "나누는 분수를 뒤집어 곱합니다",
      "6/1 × 4/3 = 24/3",
      "약분: 24/3 = 8",
    ],
    unit: "분수의 나눗셈",
    numbers: [6, 1, 3, 4],
  },
  {
    type: "calculation",
    expression: "2.7 ÷ 0.9",
    answer: 3,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "27 ÷ 9 = 3"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "10.8 ÷ 3.6",
    answer: 3,
    steps: ["소수점을 오른쪽으로 한 칸 이동", "108 ÷ 36 = 3"],
    unit: "소수의 나눗셈",
  },
  {
    type: "calculation",
    expression: "350을 4:3으로 비례배분 (큰 쪽)",
    answer: 200,
    steps: [
      "전체 비: 4 + 3 = 7",
      "큰 쪽: 350 × 4/7 = 200",
      "작은 쪽: 350 × 3/7 = 150",
    ],
    unit: "비례배분",
  },
  {
    type: "calculation",
    expression: "6 : x = 3 : 7에서 x",
    answer: 14,
    steps: ["외항의 곱 = 내항의 곱", "6 × 7 = 3 × x", "42 = 3x", "x = 14"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "반지름 3cm인 원의 넓이 (π=3.14)",
    answer: 28.26,
    steps: ["원의 넓이 = π × r²", "3.14 × 3 × 3 = 3.14 × 9", "답: 28.26cm²"],
    unit: "원의 넓이",
  },
  {
    type: "calculation",
    expression: "지름 8cm인 원의 원주 (π=3.14)",
    answer: 25.12,
    steps: ["원주 = π × 지름", "3.14 × 8 = 25.12", "답: 25.12cm"],
    unit: "원주",
  },
  {
    type: "calculation",
    expression: "밑면 반지름 6cm, 높이 5cm 원기둥의 부피 (π=3.14)",
    answer: 565.2,
    steps: [
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 36 × 5 = 565.2",
      "답: 565.2cm³",
    ],
    unit: "원기둥의 부피",
  },
  {
    type: "calculation",
    expression: "45는 180의 몇 %?",
    answer: 25,
    steps: ["비율 = 45 ÷ 180 = 0.25", "백분율 = 0.25 × 100 = 25%"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "500의 12%",
    answer: 60,
    steps: ["500 × 12/100", "500 × 0.12 = 60"],
    unit: "백분율",
  },
  {
    type: "calculation",
    expression: "21 : 35의 가장 간단한 비",
    answer: 3,
    steps: [
      "21과 35의 최대공약수: 7",
      "21 ÷ 7 = 3, 35 ÷ 7 = 5",
      "가장 간단한 비: 3 : 5",
    ],
    unit: "비와 비율",
  },
  {
    type: "calculation",
    expression: "8 : 3 = x : 9에서 x",
    answer: 24,
    steps: ["외항의 곱 = 내항의 곱", "8 × 9 = 3 × x", "72 = 3x", "x = 24"],
    unit: "비례식",
  },
  {
    type: "calculation",
    expression: "밑면 반지름 7cm, 높이 4cm 원기둥의 부피 (π=3.14)",
    answer: 615.44,
    steps: [
      "원기둥의 부피 = π × r² × 높이",
      "3.14 × 49 × 4 = 615.44",
      "답: 615.44cm³",
    ],
    unit: "원기둥의 부피",
  },
];

// ===== 상식 데이터 (60개) =====
export const grade6KnowledgeData: KnowledgeEntry[] = [
  // 기존 15개
  {
    text: "대한민국 임시정부가 세워진 도시는 ___이다.",
    answer: "상하이",
    category: "역사",
  },
  { text: "UN의 한국어 명칭은 ___이다.", answer: "국제연합", category: "사회" },
  {
    text: "광합성에서 빛에너지를 흡수하는 색소는 ___이다.",
    answer: "엽록소",
    category: "과학",
  },
  {
    text: "지구 대기의 약 78%를 차지하는 기체는 ___이다.",
    answer: "질소",
    category: "과학",
  },
  {
    text: "대한민국 헌법 제1조 1항: 대한민국은 ___이다.",
    answer: "민주공화국",
    category: "사회",
  },
  { text: "DNA는 ___의 약자이다.", answer: "디옥시리보핵산", category: "과학" },
  {
    text: "우리나라 최초의 한글 소설은 ___이다.",
    answer: "홍길동전",
    category: "문학",
  },
  {
    text: "3·1 운동이 일어난 해는 ___년이다.",
    answer: "1919",
    category: "역사",
  },
  {
    text: "지구의 자전축은 ___도 기울어져 있다.",
    answer: "23.5",
    category: "과학",
  },
  {
    text: "경제에서 수요와 ___의 법칙이 시장 가격을 결정한다.",
    answer: "공급",
    category: "사회",
  },
  { text: "산성 용액의 pH는 ___보다 작다.", answer: "7", category: "과학" },
  {
    text: "조선 시대에 천체를 관측하던 기구를 ___이라 한다.",
    answer: "혼천의",
    category: "역사",
  },
  {
    text: "원주율(π)의 소수점 아래 두 자리까지의 값은 ___이다.",
    answer: "3.14",
    category: "수학",
  },
  {
    text: "빛의 세 원색은 빨강, 초록, ___이다.",
    answer: "파랑",
    category: "과학",
  },
  {
    text: "세계 인권 선언이 채택된 해는 ___년이다.",
    answer: "1948",
    category: "사회",
  },
  // 추가 45개 (총 60개)
  {
    text: "대한민국 임시정부의 초대 대통령은 ___이다.",
    answer: "이승만",
    category: "역사",
  },
  {
    text: "한국전쟁의 정전 협정이 체결된 해는 ___년이다.",
    answer: "1953",
    category: "역사",
  },
  {
    text: "독립문은 ___의 간섭에서 벗어남을 상징한다.",
    answer: "청나라",
    category: "역사",
  },
  {
    text: "유관순 열사가 만세 운동을 이끈 곳은 ___이다.",
    answer: "천안",
    category: "역사",
  },
  {
    text: "4·19 혁명은 ___정부의 독재에 맞선 시민 운동이다.",
    answer: "이승만",
    category: "역사",
  },
  {
    text: "김구 선생이 이끌었던 독립운동 단체는 ___이다.",
    answer: "한인애국단",
    category: "역사",
  },
  {
    text: "조선 후기 실학을 집대성한 학자는 ___이다.",
    answer: "정약용",
    category: "역사",
  },
  {
    text: "세계에서 가장 작은 대륙은 ___이다.",
    answer: "오세아니아",
    category: "지리",
  },
  {
    text: "적도 부근의 기후는 ___대 기후이다.",
    answer: "열",
    category: "지리",
  },
  {
    text: "세계에서 인구가 가장 많은 나라는 ___이다.",
    answer: "인도",
    category: "지리",
  },
  {
    text: "유럽 연합(EU)의 본부가 있는 도시는 ___이다.",
    answer: "브뤼셀",
    category: "사회",
  },
  {
    text: "세계에서 가장 긴 강은 ___이다.",
    answer: "나일강",
    category: "지리",
  },
  {
    text: "세계에서 가장 높은 산은 ___이다.",
    answer: "에베레스트산",
    category: "지리",
  },
  {
    text: "기본적 인권을 보장하기 위한 국제기구는 ___이다.",
    answer: "유엔(UN)",
    category: "사회",
  },
  {
    text: "삼권 분립에서 법원이 담당하는 것은 ___권이다.",
    answer: "사법",
    category: "사회",
  },
  { text: "한글날은 매년 ___월 9일이다.", answer: "10", category: "문화" },
  {
    text: "현존하는 세계 최고(最古)의 금속활자본은 ___이다.",
    answer: "직지심체요절",
    category: "문화",
  },
  {
    text: "비타민 C가 풍부한 과일로 ___가 대표적이다.",
    answer: "귤",
    category: "과학",
  },
  {
    text: "인체에서 가장 큰 장기는 ___이다.",
    answer: "피부",
    category: "과학",
  },
  {
    text: "태양은 ___에너지를 이용한 발전의 원천이다.",
    answer: "태양",
    category: "과학",
  },
  {
    text: "세계 4대 문명 중 이집트 문명이 발생한 강은 ___이다.",
    answer: "나일강",
    category: "역사",
  },
  {
    text: "한국의 비무장지대(DMZ)는 ___선을 기준으로 설정되었다.",
    answer: "휴전",
    category: "사회",
  },
  {
    text: "노벨 평화상을 받은 한국인은 ___이다.",
    answer: "김대중",
    category: "사회",
  },
  {
    text: "세계 문화유산 등재를 담당하는 국제기구는 ___이다.",
    answer: "유네스코",
    category: "문화",
  },
  {
    text: "대한민국의 제헌 헌법이 공포된 날은 7월 ___일이다.",
    answer: "17",
    category: "역사",
  },
  {
    text: "세계에서 가장 넓은 나라는 ___이다.",
    answer: "러시아",
    category: "지리",
  },
  {
    text: "안중근 의사가 이토 히로부미를 처단한 곳은 ___이다.",
    answer: "하얼빈",
    category: "역사",
  },
  {
    text: "아프리카에서 가장 넓은 사막은 ___이다.",
    answer: "사하라",
    category: "지리",
  },
  {
    text: "남극 대륙을 가장 먼저 탐험한 나라는 ___이다.",
    answer: "노르웨이",
    category: "지리",
  },
  {
    text: "전염병이 세계적으로 유행하는 것을 ___이라 한다.",
    answer: "팬데믹",
    category: "사회",
  },
  {
    text: "우리나라 헌법에서 보장하는 교육의 의무는 ___교육이다.",
    answer: "의무",
    category: "사회",
  },
  {
    text: "조선 시대 한양의 4대문 중 남쪽 문은 ___이다.",
    answer: "숭례문",
    category: "역사",
  },
  {
    text: "석유 생산량이 많은 중동 지역의 국가 연합은 ___이다.",
    answer: "OPEC",
    category: "사회",
  },
  {
    text: "기후 변화에 대응하기 위한 국제 협약은 ___협정이다.",
    answer: "파리",
    category: "사회",
  },
  { text: "한국의 전통 종이를 ___라 한다.", answer: "한지", category: "문화" },
  {
    text: "우리나라의 첫 번째 인공위성은 ___이다.",
    answer: "우리별 1호",
    category: "과학",
  },
  {
    text: "세계 최초의 철갑선은 조선의 ___이다.",
    answer: "거북선",
    category: "역사",
  },
  {
    text: "UN 인권이사회 본부가 있는 도시는 ___이다.",
    answer: "제네바",
    category: "사회",
  },
  {
    text: "한반도의 비무장지대(DMZ)의 폭은 약 ___km이다.",
    answer: "4",
    category: "사회",
  },
  {
    text: "세계에서 가장 큰 사막은 ___사막이다.",
    answer: "사하라",
    category: "지리",
  },
  {
    text: "적도 부근에서 부는 무역풍의 방향은 ___에서 서쪽이다.",
    answer: "동",
    category: "과학",
  },
  {
    text: "대한민국의 5000원권에 그려진 인물은 ___이다.",
    answer: "율곡 이이",
    category: "문화",
  },
  {
    text: "오존층은 ___의 해로운 자외선을 차단한다.",
    answer: "태양",
    category: "과학",
  },
  {
    text: "고려 시대에 만들어진 금속활자본은 ___보다 앞선다.",
    answer: "구텐베르크",
    category: "역사",
  },
  {
    text: "한국전쟁 당시 인천상륙작전을 지휘한 장군은 ___이다.",
    answer: "맥아더",
    category: "역사",
  },
];

// ===== 안전 데이터 (40개) =====
export const grade6SafetyData: SafetyEntry[] = [
  // 기존 10개
  {
    text: "딥페이크 영상은 ___으로 만들어진 가짜 영상이다.",
    answer: "인공지능",
    category: "정보안전",
  },
  {
    text: "저작권이 있는 자료를 무단으로 사용하면 ___에 해당한다.",
    answer: "저작권 침해",
    category: "정보안전",
  },
  {
    text: "CCTV에 찍힌 영상을 함부로 퍼뜨리면 ___을 침해할 수 있다.",
    answer: "초상권",
    category: "정보안전",
  },
  {
    text: "학교 폭력을 목격하면 ___에 신고한다.",
    answer: "117",
    category: "학교안전",
  },
  {
    text: "화학 물질에 의한 화상은 즉시 ___로 15분 이상 씻는다.",
    answer: "흐르는 물",
    category: "실험안전",
  },
  {
    text: "미세먼지 '매우 나쁨' 단계에서는 ___활동을 하지 않는다.",
    answer: "실외",
    category: "건강안전",
  },
  {
    text: "지진 대피 시 머리를 ___으로 보호한다.",
    answer: "방석이나 가방",
    category: "재난안전",
  },
  {
    text: "성폭력 피해를 입으면 즉시 ___에 도움을 요청한다.",
    answer: "경찰 또는 상담센터",
    category: "생활안전",
  },
  {
    text: "감염병 예방을 위해 기침할 때는 ___으로 입과 코를 가린다.",
    answer: "옷소매",
    category: "건강안전",
  },
  {
    text: "화재 시 대피할 때 엘리베이터 대신 ___를 이용한다.",
    answer: "비상계단",
    category: "화재안전",
  },
  // 추가 30개 (총 40개)
  {
    text: "인터넷에서 가짜 뉴스를 구별하려면 ___를 확인해야 한다.",
    answer: "출처",
    category: "정보안전",
  },
  {
    text: "개인정보가 유출되면 ___에 신고할 수 있다.",
    answer: "개인정보보호위원회",
    category: "정보안전",
  },
  {
    text: "사이버 범죄를 당했을 때 신고하는 곳은 ___이다.",
    answer: "사이버수사대",
    category: "정보안전",
  },
  {
    text: "온라인 게임에서 현금 거래를 하면 ___의 위험이 있다.",
    answer: "사기",
    category: "정보안전",
  },
  {
    text: "SNS에서 모르는 사람의 친구 요청은 ___하는 것이 안전하다.",
    answer: "거절",
    category: "정보안전",
  },
  {
    text: "태풍 접근 시 가장 먼저 해야 할 것은 ___를 확인하는 것이다.",
    answer: "기상예보",
    category: "재난안전",
  },
  {
    text: "응급환자 발견 시 가장 먼저 ___을 확인해야 한다.",
    answer: "의식",
    category: "응급안전",
  },
  {
    text: "AED(자동심장충격기)는 ___이 멈추었을 때 사용한다.",
    answer: "심장",
    category: "응급안전",
  },
  {
    text: "지진 발생 시 건물 밖에 있다면 ___에서 떨어져야 한다.",
    answer: "건물",
    category: "재난안전",
  },
  {
    text: "산불 발견 시 ___로 신고해야 한다.",
    answer: "119",
    category: "재난안전",
  },
  {
    text: "해수욕장에서 이안류(역류)에 휩쓸리면 ___방향으로 헤엄쳐야 한다.",
    answer: "해안선과 평행한",
    category: "수상안전",
  },
  {
    text: "식중독 예방의 3대 원칙은 손 씻기, 익혀 먹기, ___이다.",
    answer: "끓여 마시기",
    category: "건강안전",
  },
  {
    text: "밤에 도로를 걸을 때는 ___색 옷을 입으면 안전하다.",
    answer: "밝은",
    category: "교통안전",
  },
  {
    text: "자전거 도로가 없는 곳에서는 도로의 ___쪽으로 주행한다.",
    answer: "오른",
    category: "교통안전",
  },
  {
    text: "뇌우(천둥번개) 시 자동차 안은 ___하기 때문에 비교적 안전하다.",
    answer: "전기가 차체를 통해 흐르",
    category: "재난안전",
  },
  {
    text: "실험실에서 유리 기구가 깨지면 ___으로 치워야 한다.",
    answer: "빗자루와 쓰레받기",
    category: "실험안전",
  },
  {
    text: "가정에서 전기 화재를 예방하려면 ___를 정기적으로 점검한다.",
    answer: "콘센트",
    category: "화재안전",
  },
  {
    text: "폭설 시 자동차에 갇히면 ___를 틀어 체온을 유지한다.",
    answer: "히터",
    category: "재난안전",
  },
  {
    text: "식품의 유통기한이 지난 음식은 ___하는 것이 안전하다.",
    answer: "버리",
    category: "건강안전",
  },
  {
    text: "황사 발생 시 귀가 후에는 ___을 깨끗이 씻어야 한다.",
    answer: "손과 얼굴",
    category: "건강안전",
  },
  {
    text: "승강기(엘리베이터)에서 화재가 나면 가장 가까운 ___에서 내린다.",
    answer: "층",
    category: "화재안전",
  },
  {
    text: "등산할 때 날씨가 갑자기 나빠지면 ___으로 대피한다.",
    answer: "산장이나 대피소",
    category: "생활안전",
  },
  {
    text: "온라인에서 혐오 발언을 목격하면 ___을 하고 신고한다.",
    answer: "캡처",
    category: "정보안전",
  },
  {
    text: "뱀에 물렸을 때 물린 부위보다 ___쪽을 묶어야 한다.",
    answer: "심장",
    category: "응급안전",
  },
  {
    text: "대피할 때 젖은 ___로 코와 입을 막으면 연기를 덜 마신다.",
    answer: "수건",
    category: "화재안전",
  },
  {
    text: "폭염 경보가 내려지면 ___시부터 오후 5시까지 야외 활동을 삼간다.",
    answer: "낮 12",
    category: "건강안전",
  },
  {
    text: "학교에서 지진 대피 훈련은 ___을 숙지하기 위해 실시한다.",
    answer: "대피 경로",
    category: "학교안전",
  },
  {
    text: "불량 식품의 특징은 유통기한 표시가 ___한 것이다.",
    answer: "불분명",
    category: "건강안전",
  },
  {
    text: "체육 시간 전에 ___운동을 충분히 해야 부상을 예방할 수 있다.",
    answer: "준비",
    category: "학교안전",
  },
  {
    text: "위험한 물건(칼, 가위 등)을 전달할 때는 ___부분을 상대방에게 향하게 한다.",
    answer: "손잡이",
    category: "생활안전",
  },
];

// ===== 한자 데이터 (60개) =====
export const grade6HanjaData: HanjaEntry[] = [
  // 기존 16개
  {
    character: "政",
    reading: "정",
    meaning: "정사 정",
    strokes: 9,
    words: ["정치", "정부", "행정"],
    sentence: "政治에 관심을 가지자.",
  },
  {
    character: "經",
    reading: "경",
    meaning: "경영할 경",
    strokes: 13,
    words: ["경제", "경험", "경영"],
    sentence: "經濟를 배우면 세상을 이해할 수 있다.",
  },
  {
    character: "社",
    reading: "사",
    meaning: "모일 사",
    strokes: 8,
    words: ["사회", "회사", "사원"],
    sentence: "社會에 기여하는 사람이 되자.",
  },
  {
    character: "會",
    reading: "회",
    meaning: "모일 회",
    strokes: 13,
    words: ["사회", "회의", "기회"],
    sentence: "會議에서 의견을 나누었다.",
  },
  {
    character: "法",
    reading: "법",
    meaning: "법 법",
    strokes: 9,
    words: ["법률", "방법", "헌법"],
    sentence: "法을 지키는 시민이 되자.",
  },
  {
    character: "正",
    reading: "정",
    meaning: "바를 정",
    strokes: 5,
    words: ["정의", "정직", "공정"],
    sentence: "正義로운 사회를 만들자.",
  },
  {
    character: "義",
    reading: "의",
    meaning: "옳을 의",
    strokes: 13,
    words: ["의미", "정의", "주의"],
    sentence: "民主主義를 수호하자.",
  },
  {
    character: "自",
    reading: "자",
    meaning: "스스로 자",
    strokes: 6,
    words: ["자유", "자연", "자기"],
    sentence: "自由는 소중한 권리이다.",
  },
  {
    character: "由",
    reading: "유",
    meaning: "말미암을 유",
    strokes: 5,
    words: ["자유", "이유", "유래"],
    sentence: "自由를 위해 싸운 선조들을 기억하자.",
  },
  {
    character: "平",
    reading: "평",
    meaning: "평평할 평",
    strokes: 5,
    words: ["평화", "평등", "평균"],
    sentence: "平和로운 세상을 꿈꾼다.",
  },
  {
    character: "和",
    reading: "화",
    meaning: "화할 화",
    strokes: 8,
    words: ["평화", "화합", "조화"],
    sentence: "和合하여 발전하자.",
  },
  {
    character: "世",
    reading: "세",
    meaning: "인간 세",
    strokes: 5,
    words: ["세계", "세대", "세기"],
    sentence: "世界 평화를 위해 노력하자.",
  },
  {
    character: "界",
    reading: "계",
    meaning: "지경 계",
    strokes: 9,
    words: ["세계", "한계", "경계"],
    sentence: "世界는 넓고 할 일은 많다.",
  },
  {
    character: "歷",
    reading: "역",
    meaning: "지날 역",
    strokes: 16,
    words: ["역사", "경력", "이력"],
    sentence: "歷史를 잊은 민족에게 미래는 없다.",
  },
  {
    character: "史",
    reading: "사",
    meaning: "역사 사",
    strokes: 5,
    words: ["역사", "사학", "사관"],
    sentence: "歷史에서 교훈을 얻자.",
  },
  {
    character: "敎",
    reading: "교",
    meaning: "가르칠 교",
    strokes: 11,
    words: ["교육", "교사", "종교"],
    sentence: "敎育은 백년지대계이다.",
  },
  // 추가 44개 (총 60개)
  {
    character: "民",
    reading: "민",
    meaning: "백성 민",
    strokes: 5,
    words: ["국민", "민주", "시민"],
    sentence: "國民이 나라의 주인이다.",
  },
  {
    character: "主",
    reading: "주",
    meaning: "주인 주",
    strokes: 5,
    words: ["민주", "주인", "주장"],
    sentence: "民主主義의 핵심은 국민주권이다.",
  },
  {
    character: "國",
    reading: "국",
    meaning: "나라 국",
    strokes: 11,
    words: ["국가", "한국", "외국"],
    sentence: "大韓民國은 민주공화국이다.",
  },
  {
    character: "憲",
    reading: "헌",
    meaning: "법 헌",
    strokes: 16,
    words: ["헌법", "헌장", "합헌"],
    sentence: "憲法은 나라의 최고 법이다.",
  },
  {
    character: "權",
    reading: "권",
    meaning: "권세 권",
    strokes: 15,
    words: ["인권", "권리", "권력"],
    sentence: "人權은 누구에게나 있다.",
  },
  {
    character: "利",
    reading: "리",
    meaning: "이로울 리",
    strokes: 7,
    words: ["이익", "권리", "편리"],
    sentence: "權利와 의무를 함께 생각하자.",
  },
  {
    character: "等",
    reading: "등",
    meaning: "같을 등",
    strokes: 12,
    words: ["평등", "동등", "등급"],
    sentence: "모든 사람은 平等하다.",
  },
  {
    character: "獨",
    reading: "독",
    meaning: "홀로 독",
    strokes: 16,
    words: ["독립", "독자", "독점"],
    sentence: "獨立을 위해 많은 분이 희생했다.",
  },
  {
    character: "立",
    reading: "립",
    meaning: "설 립",
    strokes: 5,
    words: ["독립", "설립", "국립"],
    sentence: "나라의 獨立은 소중하다.",
  },
  {
    character: "統",
    reading: "통",
    meaning: "거느릴 통",
    strokes: 12,
    words: ["통일", "전통", "대통령"],
    sentence: "南北 統一을 염원한다.",
  },
  {
    character: "一",
    reading: "일",
    meaning: "한 일",
    strokes: 1,
    words: ["통일", "일등", "제일"],
    sentence: "天下 統一의 꿈을 꾸었다.",
  },
  {
    character: "仁",
    reading: "인",
    meaning: "어질 인",
    strokes: 4,
    words: ["인자", "인덕", "인정"],
    sentence: "仁義를 실천하는 사람이 되자.",
  },
  {
    character: "德",
    reading: "덕",
    meaning: "큰 덕",
    strokes: 15,
    words: ["도덕", "덕분", "미덕"],
    sentence: "道德적인 삶을 살자.",
  },
  {
    character: "信",
    reading: "신",
    meaning: "믿을 신",
    strokes: 9,
    words: ["신뢰", "통신", "신용"],
    sentence: "信賴는 관계의 기본이다.",
  },
  {
    character: "愛",
    reading: "애",
    meaning: "사랑 애",
    strokes: 13,
    words: ["사랑", "애국", "인류애"],
    sentence: "祖國에 대한 愛情을 가지자.",
  },
  {
    character: "忠",
    reading: "충",
    meaning: "충성 충",
    strokes: 8,
    words: ["충성", "충효", "충실"],
    sentence: "忠誠과 孝道를 실천하자.",
  },
  {
    character: "孝",
    reading: "효",
    meaning: "효도 효",
    strokes: 7,
    words: ["효도", "효자", "충효"],
    sentence: "부모님께 孝道하자.",
  },
  {
    character: "禮",
    reading: "예",
    meaning: "예도 예",
    strokes: 15,
    words: ["예절", "예의", "예법"],
    sentence: "禮儀를 잘 지키자.",
  },
  {
    character: "智",
    reading: "지",
    meaning: "슬기 지",
    strokes: 12,
    words: ["지혜", "지식", "기지"],
    sentence: "智慧로운 판단이 중요하다.",
  },
  {
    character: "勇",
    reading: "용",
    meaning: "용감할 용",
    strokes: 9,
    words: ["용기", "용감", "용사"],
    sentence: "勇氣를 가지고 도전하자.",
  },
  {
    character: "公",
    reading: "공",
    meaning: "공평할 공",
    strokes: 4,
    words: ["공정", "공평", "공공"],
    sentence: "公正한 사회를 만들자.",
  },
  {
    character: "善",
    reading: "선",
    meaning: "착할 선",
    strokes: 12,
    words: ["선행", "선량", "개선"],
    sentence: "善行을 실천하는 사람이 되자.",
  },
  {
    character: "惡",
    reading: "악",
    meaning: "악할 악",
    strokes: 12,
    words: ["선악", "악행", "악덕"],
    sentence: "善惡을 분별하는 지혜가 필요하다.",
  },
  {
    character: "戰",
    reading: "전",
    meaning: "싸울 전",
    strokes: 16,
    words: ["전쟁", "도전", "작전"],
    sentence: "戰爭 없는 세상을 꿈꾼다.",
  },
  {
    character: "安",
    reading: "안",
    meaning: "편안할 안",
    strokes: 6,
    words: ["안전", "안심", "안녕"],
    sentence: "安全이 가장 중요하다.",
  },
  {
    character: "全",
    reading: "전",
    meaning: "온전할 전",
    strokes: 6,
    words: ["안전", "전체", "완전"],
    sentence: "安全한 사회를 만들자.",
  },
  {
    character: "勞",
    reading: "노",
    meaning: "일할 노",
    strokes: 12,
    words: ["노동", "근로", "노력"],
    sentence: "勤勞의 가치를 알자.",
  },
  {
    character: "動",
    reading: "동",
    meaning: "움직일 동",
    strokes: 11,
    words: ["운동", "활동", "동물"],
    sentence: "꾸준히 運動하면 건강해진다.",
  },
  {
    character: "育",
    reading: "육",
    meaning: "기를 육",
    strokes: 8,
    words: ["교육", "체육", "양육"],
    sentence: "敎育의 힘을 믿자.",
  },
  {
    character: "文",
    reading: "문",
    meaning: "글월 문",
    strokes: 4,
    words: ["문화", "문학", "문명"],
    sentence: "한국 文化를 세계에 알리자.",
  },
  {
    character: "化",
    reading: "화",
    meaning: "될 화",
    strokes: 4,
    words: ["문화", "변화", "진화"],
    sentence: "文化는 시대에 따라 變化한다.",
  },
  {
    character: "明",
    reading: "명",
    meaning: "밝을 명",
    strokes: 8,
    words: ["문명", "발명", "설명"],
    sentence: "文明의 발전이 인류를 변화시켰다.",
  },
  {
    character: "祖",
    reading: "조",
    meaning: "할아버지 조",
    strokes: 10,
    words: ["조상", "조국", "선조"],
    sentence: "祖國을 사랑하는 마음을 가지자.",
  },
  {
    character: "先",
    reading: "선",
    meaning: "먼저 선",
    strokes: 6,
    words: ["선조", "선배", "우선"],
    sentence: "先輩들의 지혜를 배우자.",
  },
  {
    character: "後",
    reading: "후",
    meaning: "뒤 후",
    strokes: 9,
    words: ["후배", "이후", "최후"],
    sentence: "後輩들에게 좋은 본보기가 되자.",
  },
  {
    character: "現",
    reading: "현",
    meaning: "나타날 현",
    strokes: 11,
    words: ["현재", "현실", "표현"],
    sentence: "現在를 충실히 살자.",
  },
  {
    character: "未",
    reading: "미",
    meaning: "아닐 미",
    strokes: 5,
    words: ["미래", "미완", "미지"],
    sentence: "未來를 준비하는 자세가 중요하다.",
  },
  {
    character: "來",
    reading: "래",
    meaning: "올 래",
    strokes: 8,
    words: ["미래", "유래", "장래"],
    sentence: "밝은 未來를 향해 나아가자.",
  },
  {
    character: "新",
    reading: "신",
    meaning: "새 신",
    strokes: 13,
    words: ["신문", "혁신", "새해"],
    sentence: "新年에는 새로운 마음으로 시작하자.",
  },
  {
    character: "光",
    reading: "광",
    meaning: "빛 광",
    strokes: 6,
    words: ["광복", "빛", "관광"],
    sentence: "光復절의 의미를 되새기자.",
  },
  {
    character: "復",
    reading: "복",
    meaning: "회복할 복",
    strokes: 12,
    words: ["광복", "회복", "복구"],
    sentence: "光復의 기쁨을 잊지 말자.",
  },
  {
    character: "太",
    reading: "태",
    meaning: "클 태",
    strokes: 4,
    words: ["태양", "태극", "태풍"],
    sentence: "太極旗는 대한민국의 국기이다.",
  },
  {
    character: "極",
    reading: "극",
    meaning: "다할 극",
    strokes: 13,
    words: ["태극", "극복", "남극"],
    sentence: "어려움을 克服하는 용기가 필요하다.",
  },
  {
    character: "旗",
    reading: "기",
    meaning: "기 기",
    strokes: 14,
    words: ["국기", "기수", "태극기"],
    sentence: "國旗를 소중히 다루자.",
  },
];

// ===== 영어 데이터 (60개) =====
export const grade6EnglishData: EnglishEntry[] = [
  // 기존 15개
  {
    sentence: "I have been studying English for three years.",
    translation: "나는 3년 동안 영어를 공부해 왔어.",
    word: "studying",
    pronunciation: "스터디잉",
    practice: ["I have been ___ for ___.", "How long have you been studying?"],
  },
  {
    sentence: "If it rains tomorrow, we will stay home.",
    translation: "내일 비가 오면 우리는 집에 있을 거야.",
    word: "if",
    pronunciation: "이프",
    practice: ["If ___, we will ___.", "What will you do if it snows?"],
  },
  {
    sentence: "The book was written by a famous author.",
    translation: "그 책은 유명한 작가가 썼어.",
    word: "written",
    pronunciation: "리튼",
    practice: ["The ___ was ___ by ___.", "Who wrote this book?"],
  },
  {
    sentence: "I think recycling is very important.",
    translation: "나는 재활용이 매우 중요하다고 생각해.",
    word: "recycling",
    pronunciation: "리사이클링",
    practice: ["I think ___ is important.", "Why is recycling important?"],
  },
  {
    sentence: "Could you tell me how to get to the station?",
    translation: "역까지 어떻게 가는지 알려주시겠어요?",
    word: "station",
    pronunciation: "스테이션",
    practice: ["Could you tell me how to ___?", "How do I get to the library?"],
  },
  {
    sentence: "She is not only smart but also kind.",
    translation: "그녀는 똑똑할 뿐만 아니라 친절하기도 해.",
    word: "not only",
    pronunciation: "낫 온리",
    practice: [
      "He is not only ___ but also ___.",
      "She is both smart and kind.",
    ],
  },
  {
    sentence: "We should respect different cultures.",
    translation: "우리는 다양한 문화를 존중해야 해.",
    word: "respect",
    pronunciation: "리스펙트",
    practice: ["We should respect ___.", "It is important to respect others."],
  },
  {
    sentence: "The population of Korea is about 50 million.",
    translation: "한국의 인구는 약 5천만 명이야.",
    word: "population",
    pronunciation: "파퓰레이션",
    practice: [
      "The population of ___ is ___.",
      "What is the population of Seoul?",
    ],
  },
  {
    sentence: "I am interested in science.",
    translation: "나는 과학에 관심이 있어.",
    word: "interested",
    pronunciation: "인터레스티드",
    practice: ["I am interested in ___.", "What are you interested in?"],
  },
  {
    sentence: "It is necessary to save energy.",
    translation: "에너지를 절약하는 것은 필요해.",
    word: "necessary",
    pronunciation: "네서세리",
    practice: ["It is necessary to ___.", "Is it necessary to study?"],
  },
  {
    sentence: "I would like to visit many countries in the future.",
    translation: "나는 미래에 많은 나라를 방문하고 싶어.",
    word: "future",
    pronunciation: "퓨처",
    practice: [
      "In the future, I want to ___.",
      "What is your plan for the future?",
    ],
  },
  {
    sentence: "The festival was held last weekend.",
    translation: "그 축제는 지난 주말에 열렸어.",
    word: "festival",
    pronunciation: "페스티벌",
    practice: ["The ___ was held ___.", "When was the festival?"],
  },
  {
    sentence: "You should apologize to your friend.",
    translation: "너는 친구에게 사과해야 해.",
    word: "apologize",
    pronunciation: "어팔러자이즈",
    practice: ["You should apologize to ___.", "I am sorry for my mistake."],
  },
  {
    sentence: "Global warming is a serious problem.",
    translation: "지구 온난화는 심각한 문제야.",
    word: "global",
    pronunciation: "글로벌",
    practice: [
      "___ is a serious problem.",
      "What can we do about global warming?",
    ],
  },
  {
    sentence: "I prefer reading to watching TV.",
    translation: "나는 TV 보는 것보다 독서를 더 좋아해.",
    word: "prefer",
    pronunciation: "프리퍼",
    practice: ["I prefer ___ to ___.", "Do you prefer tea or coffee?"],
  },
  // 추가 45개 (총 60개)
  {
    sentence: "If I were you, I would study harder.",
    translation: "내가 너라면 더 열심히 공부할 텐데.",
    word: "would",
    pronunciation: "우드",
    practice: ["If I were you, I would ___.", "What would you do?"],
  },
  {
    sentence: "The Earth is getting warmer because of pollution.",
    translation: "지구는 오염 때문에 점점 더워지고 있어.",
    word: "pollution",
    pronunciation: "퍼루션",
    practice: ["___ is caused by ___.", "How can we reduce pollution?"],
  },
  {
    sentence: "This picture was painted by Picasso.",
    translation: "이 그림은 피카소가 그렸어.",
    word: "painted",
    pronunciation: "페인티드",
    practice: ["This ___ was ___ by ___.", "Who painted this?"],
  },
  {
    sentence: "I believe that education is the key to success.",
    translation: "나는 교육이 성공의 열쇠라고 믿어.",
    word: "believe",
    pronunciation: "빌리브",
    practice: ["I believe that ___.", "What do you believe in?"],
  },
  {
    sentence: "The museum is open from 9 to 5.",
    translation: "박물관은 9시부터 5시까지 열어.",
    word: "museum",
    pronunciation: "뮤지엄",
    practice: ["The ___ is open from ___ to ___.", "What time does it open?"],
  },
  {
    sentence: "Although it was raining, we went outside.",
    translation: "비가 오고 있었지만 우리는 밖에 나갔어.",
    word: "although",
    pronunciation: "올도우",
    practice: ["Although ___, we ___.", "Although it was cold, I went out."],
  },
  {
    sentence: "I am proud of being Korean.",
    translation: "나는 한국인인 것이 자랑스러워.",
    word: "proud",
    pronunciation: "프라우드",
    practice: ["I am proud of ___.", "What are you proud of?"],
  },
  {
    sentence: "Plastic is harmful to the ocean.",
    translation: "플라스틱은 바다에 해로워.",
    word: "harmful",
    pronunciation: "함풀",
    practice: ["___ is harmful to ___.", "Why is plastic harmful?"],
  },
  {
    sentence: "I was surprised to hear the news.",
    translation: "나는 그 소식을 듣고 놀랐어.",
    word: "surprised",
    pronunciation: "서프라이즈드",
    practice: ["I was surprised to ___.", "Were you surprised?"],
  },
  {
    sentence: "What do you think is the most important invention?",
    translation: "가장 중요한 발명품이 무엇이라고 생각하니?",
    word: "invention",
    pronunciation: "인벤션",
    practice: [
      "The most important ___ is ___.",
      "What invention changed the world?",
    ],
  },
  {
    sentence: "Korea has four distinct seasons.",
    translation: "한국은 네 가지 뚜렷한 계절이 있어.",
    word: "distinct",
    pronunciation: "디스팅트",
    practice: ["Korea has ___ seasons.", "Which season do you like?"],
  },
  {
    sentence: "Reading books can improve your vocabulary.",
    translation: "책을 읽으면 어휘력을 향상할 수 있어.",
    word: "improve",
    pronunciation: "임프루브",
    practice: ["___ can improve your ___.", "How can I improve my English?"],
  },
  {
    sentence: "The concert was canceled because of the rain.",
    translation: "콘서트가 비 때문에 취소되었어.",
    word: "canceled",
    pronunciation: "캔설드",
    practice: ["The ___ was canceled because of ___.", "Why was it canceled?"],
  },
  {
    sentence: "I have never been to Europe.",
    translation: "나는 유럽에 가 본 적이 없어.",
    word: "never",
    pronunciation: "네버",
    practice: ["I have never been to ___.", "Have you ever been to Japan?"],
  },
  {
    sentence: "She asked me if I could help her.",
    translation: "그녀가 도와줄 수 있냐고 물었어.",
    word: "asked",
    pronunciation: "애스크트",
    practice: ["She asked me if I could ___.", "He asked me to help."],
  },
  {
    sentence: "The report should be finished by Friday.",
    translation: "보고서는 금요일까지 끝나야 해.",
    word: "finished",
    pronunciation: "피니쉬드",
    practice: ["The ___ should be ___ by ___.", "When should it be finished?"],
  },
  {
    sentence: "I want to contribute to society.",
    translation: "나는 사회에 기여하고 싶어.",
    word: "contribute",
    pronunciation: "컨트리뷰트",
    practice: ["I want to contribute to ___.", "How can we contribute?"],
  },
  {
    sentence: "Traditional Korean food is healthy.",
    translation: "한국 전통 음식은 건강에 좋아.",
    word: "traditional",
    pronunciation: "트래디셔널",
    practice: [
      "Traditional ___ food is ___.",
      "What is a traditional Korean food?",
    ],
  },
  {
    sentence: "He suggested that we work together.",
    translation: "그는 우리가 함께 일하자고 제안했어.",
    word: "suggested",
    pronunciation: "서제스티드",
    practice: ["He suggested that we ___.", "What did she suggest?"],
  },
  {
    sentence: "The movie was so exciting that I watched it twice.",
    translation: "그 영화는 너무 재미있어서 두 번 봤어.",
    word: "exciting",
    pronunciation: "익사이팅",
    practice: ["It was so ___ that I ___.", "Was the movie exciting?"],
  },
  {
    sentence: "Democracy means government by the people.",
    translation: "민주주의는 국민에 의한 정치를 뜻해.",
    word: "democracy",
    pronunciation: "디모크러시",
    practice: ["Democracy means ___.", "Why is democracy important?"],
  },
  {
    sentence: "If we plant more trees, we can clean the air.",
    translation: "나무를 더 많이 심으면 공기를 깨끗하게 할 수 있어.",
    word: "plant",
    pronunciation: "플랜트",
    practice: ["If we ___, we can ___.", "Why should we plant trees?"],
  },
  {
    sentence: "The letter was delivered to the wrong address.",
    translation: "편지가 잘못된 주소로 배달되었어.",
    word: "delivered",
    pronunciation: "딜리버드",
    practice: ["The ___ was delivered to ___.", "When was it delivered?"],
  },
  {
    sentence: "I decided to volunteer at the hospital.",
    translation: "나는 병원에서 봉사하기로 결정했어.",
    word: "volunteer",
    pronunciation: "발런티어",
    practice: ["I decided to volunteer at ___.", "Where do you volunteer?"],
  },
  {
    sentence: "Different countries have different customs.",
    translation: "나라마다 다른 관습이 있어.",
    word: "customs",
    pronunciation: "커스텀즈",
    practice: [
      "Different countries have different ___.",
      "What is a unique custom?",
    ],
  },
  {
    sentence: "The homework was not as difficult as I thought.",
    translation: "숙제가 내가 생각한 것만큼 어렵지 않았어.",
    word: "difficult",
    pronunciation: "디피컬트",
    practice: ["It was not as ___ as I thought.", "Was the test difficult?"],
  },
  {
    sentence: "I wonder why the sky is blue.",
    translation: "하늘이 왜 파란지 궁금해.",
    word: "wonder",
    pronunciation: "원더",
    practice: ["I wonder why ___.", "I wonder how it works."],
  },
  {
    sentence: "Korea is known for its beautiful mountains.",
    translation: "한국은 아름다운 산으로 알려져 있어.",
    word: "known",
    pronunciation: "노운",
    practice: ["___ is known for ___.", "What is Korea known for?"],
  },
  {
    sentence: "He was chosen as the class president.",
    translation: "그는 반장으로 선출되었어.",
    word: "chosen",
    pronunciation: "초즌",
    practice: ["He was chosen as ___.", "Who was chosen?"],
  },
  {
    sentence: "I think we should protect endangered animals.",
    translation: "나는 멸종 위기 동물을 보호해야 한다고 생각해.",
    word: "endangered",
    pronunciation: "인데인저드",
    practice: [
      "We should protect ___ animals.",
      "Which animals are endangered?",
    ],
  },
  {
    sentence: "If everyone cooperates, we can solve the problem.",
    translation: "모두가 협력하면 문제를 해결할 수 있어.",
    word: "cooperates",
    pronunciation: "코아퍼레이츠",
    practice: ["If everyone ___, we can ___.", "Why should we cooperate?"],
  },
  {
    sentence: "The invention of the internet changed the world.",
    translation: "인터넷의 발명이 세상을 바꿨어.",
    word: "internet",
    pronunciation: "인터넷",
    practice: [
      "The invention of ___ changed ___.",
      "How did the internet change the world?",
    ],
  },
  {
    sentence: "I am worried about climate change.",
    translation: "나는 기후 변화가 걱정돼.",
    word: "worried",
    pronunciation: "워리드",
    practice: ["I am worried about ___.", "What are you worried about?"],
  },
  {
    sentence: "They built a new library in our town.",
    translation: "우리 마을에 새 도서관을 지었어.",
    word: "built",
    pronunciation: "빌트",
    practice: ["They built a new ___ in ___.", "When was it built?"],
  },
  {
    sentence: "I promise to be more responsible.",
    translation: "더 책임감 있게 행동하겠다고 약속할게.",
    word: "responsible",
    pronunciation: "리스판서블",
    practice: ["I promise to be more ___.", "Are you responsible?"],
  },
  {
    sentence: "The bridge connects the two islands.",
    translation: "그 다리는 두 섬을 연결해.",
    word: "connects",
    pronunciation: "커넥츠",
    practice: [
      "The ___ connects ___ and ___.",
      "What does the bridge connect?",
    ],
  },
  {
    sentence: "It is important to express your opinion.",
    translation: "자신의 의견을 표현하는 것은 중요해.",
    word: "express",
    pronunciation: "익스프레스",
    practice: [
      "It is important to express ___.",
      "How do you express your feelings?",
    ],
  },
  {
    sentence: "Many people suffered during the war.",
    translation: "전쟁 동안 많은 사람들이 고통받았어.",
    word: "suffered",
    pronunciation: "서퍼드",
    practice: ["Many people suffered during ___.", "How did they suffer?"],
  },
  {
    sentence: "I am grateful for my family and friends.",
    translation: "나는 가족과 친구들에게 감사해.",
    word: "grateful",
    pronunciation: "그레이트풀",
    practice: ["I am grateful for ___.", "What are you grateful for?"],
  },
  {
    sentence: "The experiment proved that the theory was correct.",
    translation: "그 실험은 이론이 맞다는 것을 증명했어.",
    word: "experiment",
    pronunciation: "익스페리먼트",
    practice: [
      "The experiment proved that ___.",
      "What did the experiment show?",
    ],
  },
  {
    sentence: "We celebrated Independence Day on August 15th.",
    translation: "우리는 8월 15일에 독립기념일을 축하했어.",
    word: "independence",
    pronunciation: "인디펜던스",
    practice: ["We celebrated ___ on ___.", "When is Independence Day?"],
  },
  {
    sentence: "I hope to make a positive difference in the world.",
    translation: "나는 세상에 긍정적인 변화를 만들고 싶어.",
    word: "positive",
    pronunciation: "파지티브",
    practice: ["I hope to make a ___ difference.", "What kind of difference?"],
  },
  {
    sentence: "She explained the problem clearly.",
    translation: "그녀가 문제를 명확하게 설명했어.",
    word: "explained",
    pronunciation: "익스플레인드",
    practice: ["She explained ___ clearly.", "Can you explain it again?"],
  },
  {
    sentence: "The United Nations works for world peace.",
    translation: "국제연합은 세계 평화를 위해 일해.",
    word: "peace",
    pronunciation: "피스",
    practice: ["___ works for world ___.", "How can we achieve peace?"],
  },
  {
    sentence: "We learned about Korean history in class.",
    translation: "우리는 수업에서 한국 역사를 배웠어.",
    word: "history",
    pronunciation: "히스토리",
    practice: ["We learned about ___ in class.", "What did you learn about?"],
  },
];

// ===== 글쓰기 프롬프트 (60개) =====
export const grade6WritingPrompts: string[] = [
  // 기존 20개
  "민주주의의 의미와 우리 생활에서의 실천 방안에 대해 논술하세요.",
  "과학 기술의 발전이 가져올 미래 사회를 예측하는 글을 쓰세요.",
  "환경 문제(기후 변화, 미세먼지 등)에 대한 자신의 견해를 논리적으로 서술하세요.",
  "역사 속 중요한 사건 하나를 골라 그 의의를 설명하는 글을 쓰세요.",
  "좋은 리더에게 필요한 자질에 대해 자신의 생각을 쓰세요.",
  "인공지능 시대에 인간이 갖추어야 할 능력은 무엇인지 논하세요.",
  "다문화 사회에서 서로 다른 문화를 이해하는 방법에 대해 쓰세요.",
  "나의 꿈과 그것을 이루기 위한 구체적인 계획을 써 보세요.",
  "독서의 가치에 대해 설득력 있는 글을 쓰세요.",
  "학교 폭력의 원인과 해결 방안에 대해 논하세요.",
  "우리 사회에서 평등이 왜 중요한지 자신의 생각을 쓰세요.",
  "소셜 미디어가 청소년에게 미치는 영향을 분석하는 글을 쓰세요.",
  "통일의 필요성과 방법에 대한 자신의 견해를 밝히세요.",
  "졸업을 앞두고 초등학교 생활을 돌아보는 에세이를 쓰세요.",
  "존경하는 역사적 인물의 업적을 소개하고 현대 사회에 주는 교훈을 쓰세요.",
  "'책임'이란 무엇인지 구체적인 예를 들어 설명하세요.",
  "지속 가능한 발전이란 무엇이며, 우리가 할 수 있는 일은 무엇인지 쓰세요.",
  "세계 시민으로서 갖추어야 할 태도에 대해 논술하세요.",
  "나에게 가장 큰 영향을 준 책과 그 이유를 쓰세요.",
  "미래의 후배들에게 전하고 싶은 메시지를 편지로 쓰세요.",
  // 추가 40개 (총 60개)
  "인권이 왜 보편적으로 보장되어야 하는지에 대해 논술하세요.",
  "기후 변화를 막기 위해 개인이 할 수 있는 구체적인 행동을 써 보세요.",
  "역사에서 가장 중요한 발명이 무엇이라고 생각하는지 근거를 들어 써 보세요.",
  "초등학교를 졸업하며 느끼는 감정과 중학교에 대한 기대를 써 보세요.",
  "우리나라의 전통문화 중 세계에 알리고 싶은 것을 소개하는 글을 쓰세요.",
  "차별 없는 사회를 만들기 위해 우리가 할 수 있는 일은 무엇인지 써 보세요.",
  "내가 생각하는 '정의'란 무엇인지 자신의 경험을 바탕으로 써 보세요.",
  "건강한 디지털 생활 습관에 대해 제안하는 글을 써 보세요.",
  "전쟁과 평화에 대한 자신의 생각을 논술하세요.",
  "6년간의 초등학교 생활에서 가장 기억에 남는 순간을 써 보세요.",
  "빈곤 문제를 해결하기 위한 국제 사회의 노력에 대해 써 보세요.",
  "인터넷 게임 과몰입의 문제점과 해결 방안에 대해 논하세요.",
  "자원봉사의 의미와 중요성에 대해 설득하는 글을 쓰세요.",
  "미래의 직업 세계가 어떻게 변할지 예측하는 글을 쓰세요.",
  "내가 만약 유엔 사무총장이 된다면 무엇을 할지 써 보세요.",
  "우리 지역의 역사적 인물을 조사하여 소개하는 글을 쓰세요.",
  "아동 노동 문제에 대한 자신의 견해를 밝히세요.",
  "언론의 역할과 가짜 뉴스 문제에 대해 논하세요.",
  "난민 문제에 대해 세계 시민으로서 어떤 태도를 가져야 하는지 써 보세요.",
  "'공정함'이란 무엇인지 예를 들어 설명하세요.",
  "에너지 절약이 환경 보호에 미치는 영향에 대해 써 보세요.",
  "내가 존경하는 과학자와 그 이유를 써 보세요.",
  "문화재 보존의 중요성과 방법에 대해 설명하는 글을 쓰세요.",
  "나의 롤모델은 누구이며 그 이유는 무엇인지 써 보세요.",
  "초등학교 6년 동안 가장 많이 성장한 부분은 무엇인지 써 보세요.",
  "세계화가 우리 생활에 미치는 긍정적·부정적 영향에 대해 써 보세요.",
  "동물 실험에 대한 찬반 의견을 논리적으로 써 보세요.",
  "미래의 교육은 어떻게 변할지 자신의 생각을 써 보세요.",
  "내가 만약 시장(市長)이 된다면 우리 도시를 위해 무엇을 할지 써 보세요.",
  "양성평등의 의미와 실천 방법에 대해 논술하세요.",
  "독도가 우리 영토인 근거를 정리하여 써 보세요.",
  "존댓말과 반말의 적절한 사용에 대해 자신의 생각을 써 보세요.",
  "'나눔'의 의미와 실천 사례를 써 보세요.",
  "플라스틱 사용을 줄이기 위한 방법을 제안하는 글을 쓰세요.",
  "졸업식에서 대표로 연설한다면 어떤 내용을 말하고 싶은지 써 보세요.",
  "인터넷 예절(네티켓)의 중요성에 대해 설명하는 글을 쓰세요.",
  "내가 해 보고 싶은 사회 공헌 활동과 그 이유를 써 보세요.",
  "100년 후의 한국은 어떤 모습일지 상상하여 써 보세요.",
  "SNS를 현명하게 사용하는 방법에 대해 조언하는 글을 쓰세요.",
  "나의 삶에서 가장 중요한 가치 3가지를 선택하고 그 이유를 써 보세요.",
];

// ===== NEW: 창의 데이터 (40개) =====
export const grade6CreativeData: KnowledgeEntry[] = [
  // 디자인
  {
    text: "디자인에서 전체적인 조화와 통일감을 만드는 원리를 ___이라 한다.",
    answer: "통일성",
    category: "디자인",
  },
  {
    text: "시각적으로 안정감을 주기 위해 요소를 고르게 배치하는 것을 ___이라 한다.",
    answer: "균형",
    category: "디자인",
  },
  {
    text: "작은 것에서 큰 것으로 점점 변하는 것을 ___이라 한다.",
    answer: "점이",
    category: "디자인",
  },
  {
    text: "포스터에서 글자와 그림의 배치를 ___이라 한다.",
    answer: "레이아웃",
    category: "디자인",
  },
  {
    text: "로고는 기업이나 단체의 ___를 상징하는 시각물이다.",
    answer: "정체성",
    category: "디자인",
  },
  {
    text: "사용자가 편리하게 쓸 수 있도록 만드는 디자인을 ___디자인이라 한다.",
    answer: "유니버설",
    category: "디자인",
  },
  {
    text: "제품을 담는 상자나 봉지를 디자인하는 것을 ___디자인이라 한다.",
    answer: "패키지",
    category: "디자인",
  },
  {
    text: "건물의 외관과 내부를 설계하는 것을 ___디자인이라 한다.",
    answer: "건축",
    category: "디자인",
  },
  {
    text: "여러 매체를 합쳐 새로운 표현을 하는 것을 ___미디어라 한다.",
    answer: "멀티",
    category: "디자인",
  },
  {
    text: "색상환에서 서로 마주보는 색을 ___색이라 한다.",
    answer: "보",
    category: "디자인",
  },
  // 세계 미술
  {
    text: "르네상스 시대 이탈리아에서 활동한 '최후의 만찬'의 작가는 ___이다.",
    answer: "레오나르도 다빈치",
    category: "감상",
  },
  {
    text: "인상주의 화가로 '수련' 연작을 그린 사람은 ___이다.",
    answer: "모네",
    category: "감상",
  },
  {
    text: "스페인 출신으로 큐비즘을 창시한 화가는 ___이다.",
    answer: "피카소",
    category: "감상",
  },
  {
    text: "일본의 전통 목판화 양식을 ___라 한다.",
    answer: "우키요에",
    category: "감상",
  },
  {
    text: "조선 후기 민중의 생활을 그린 화가 김홍도의 대표작은 '___'이다.",
    answer: "씨름",
    category: "감상",
  },
  {
    text: "'별이 빛나는 밤'을 그린 네덜란드 화가는 ___이다.",
    answer: "고흐",
    category: "감상",
  },
  {
    text: "오스트리아 화가 클림트의 대표작은 '___'이다.",
    answer: "키스",
    category: "감상",
  },
  {
    text: "현대 미술에서 일상 사물을 작품으로 전시하는 것을 ___라 한다.",
    answer: "레디메이드",
    category: "감상",
  },
  // 음악 이론
  {
    text: "음악에서 두 개 이상의 음이 동시에 울리는 것을 ___라 한다.",
    answer: "화음",
    category: "음악",
  },
  {
    text: "4분음표 두 개의 길이와 같은 음표를 ___음표라 한다.",
    answer: "2분",
    category: "음악",
  },
  {
    text: "음악의 빠르기를 천천히 연주하라는 뜻의 이탈리아어는 ___이다.",
    answer: "아다지오",
    category: "음악",
  },
  {
    text: "음악에서 점점 세게 연주하라는 기호는 ___이다.",
    answer: "크레셴도",
    category: "음악",
  },
  {
    text: "오케스트라에서 현악기에 속하는 가장 작은 악기는 ___이다.",
    answer: "바이올린",
    category: "음악",
  },
  {
    text: "한국 전통 음악에서 12음계 체계를 ___이라 한다.",
    answer: "12율",
    category: "음악",
  },
  {
    text: "서양 음악에서 '도'에 해당하는 영어 음이름은 ___이다.",
    answer: "C",
    category: "음악",
  },
  {
    text: "합주에서 한 사람이 연주하는 부분을 ___라 한다.",
    answer: "파트",
    category: "음악",
  },
  {
    text: "3박자의 리듬감이 특징인 춤곡을 ___라 한다.",
    answer: "왈츠",
    category: "음악",
  },
  {
    text: "오페라에서 등장인물이 혼자 부르는 노래를 ___라 한다.",
    answer: "아리아",
    category: "음악",
  },
  // 미술 기법
  {
    text: "밀랍이나 크레용으로 그린 위에 물감을 칠하여 효과를 내는 기법을 ___기법이라 한다.",
    answer: "바틱",
    category: "미술",
  },
  {
    text: "여러 재료를 붙여 화면을 구성하는 기법을 ___라 한다.",
    answer: "콜라주",
    category: "미술",
  },
  {
    text: "움직이는 조각 작품을 ___이라 한다.",
    answer: "모빌",
    category: "미술",
  },
  {
    text: "스프레이나 분무기로 색을 뿌리는 기법을 ___기법이라 한다.",
    answer: "스프레이",
    category: "미술",
  },
  {
    text: "실로 무늬를 놓아 장식하는 한국 전통 기법을 ___라 한다.",
    answer: "자수",
    category: "미술",
  },
  {
    text: "한국 전통 도자기 중 파란빛 무늬가 특징인 것을 ___라 한다.",
    answer: "청자",
    category: "미술",
  },
  {
    text: "한국 전통 도자기 중 하얀 빛깔이 특징인 것을 ___라 한다.",
    answer: "백자",
    category: "미술",
  },
  {
    text: "3D 프린터로 만든 조형물을 ___조형이라 한다.",
    answer: "디지털",
    category: "미술",
  },
  // 영상/미디어
  {
    text: "여러 장의 그림을 빠르게 넘겨 움직이는 것처럼 보이게 하는 것을 ___이라 한다.",
    answer: "애니메이션",
    category: "감상",
  },
  {
    text: "영화에서 장면과 장면을 이어 붙이는 작업을 ___이라 한다.",
    answer: "편집",
    category: "감상",
  },
  {
    text: "카메라가 피사체에 가까이 다가가는 촬영 기법을 ___이라 한다.",
    answer: "클로즈업",
    category: "감상",
  },
  {
    text: "광고에서 사람들의 마음을 끌기 위해 사용하는 문구를 ___라 한다.",
    answer: "카피",
    category: "감상",
  },
];

// ===== NEW: 과학 데이터 (40개) =====
export const grade6ScienceData: KnowledgeEntry[] = [
  // 생물(세포, 생태계)
  {
    text: "모든 생물의 구조와 기능의 기본 단위는 ___이다.",
    answer: "세포",
    category: "생물",
  },
  {
    text: "세포에서 유전 정보를 담고 있는 부분은 ___이다.",
    answer: "핵",
    category: "생물",
  },
  {
    text: "식물 세포에만 있고 동물 세포에는 없는 것은 ___이다.",
    answer: "세포벽",
    category: "생물",
  },
  {
    text: "생태계에서 생물을 먹고 먹히는 관계로 연결한 것을 ___이라 한다.",
    answer: "먹이사슬",
    category: "생물",
  },
  {
    text: "생태계에서 먹이사슬이 복잡하게 얽힌 것을 ___이라 한다.",
    answer: "먹이그물",
    category: "생물",
  },
  {
    text: "생태계에서 생산자는 주로 ___이다.",
    answer: "식물",
    category: "생물",
  },
  {
    text: "생태계에서 죽은 생물을 분해하는 생물을 ___라 한다.",
    answer: "분해자",
    category: "생물",
  },
  {
    text: "특정 환경에서 함께 살아가는 생물 집단을 ___라 한다.",
    answer: "군집",
    category: "생물",
  },
  {
    text: "생물이 환경에 적응하여 살아남는 과정을 ___이라 한다.",
    answer: "자연선택",
    category: "생물",
  },
  {
    text: "사람의 몸에서 산소를 운반하는 혈구는 ___이다.",
    answer: "적혈구",
    category: "생물",
  },
  // 물리(에너지, 전기, 렌즈와 빛)
  {
    text: "높은 곳에 있는 물체가 가지는 에너지를 ___에너지라 한다.",
    answer: "위치",
    category: "물리",
  },
  {
    text: "움직이는 물체가 가지는 에너지를 ___에너지라 한다.",
    answer: "운동",
    category: "물리",
  },
  {
    text: "전기 회로에서 전류의 세기를 측정하는 도구는 ___이다.",
    answer: "전류계",
    category: "물리",
  },
  {
    text: "전기 회로에서 전압을 측정하는 도구는 ___이다.",
    answer: "전압계",
    category: "물리",
  },
  {
    text: "직렬 연결에서 전구를 더 많이 연결하면 밝기가 ___해진다.",
    answer: "어두워",
    category: "물리",
  },
  {
    text: "병렬 연결에서 전구 하나가 꺼져도 나머지 전구는 ___는다.",
    answer: "켜져 있",
    category: "물리",
  },
  {
    text: "볼록 렌즈는 빛을 ___시키는 성질이 있다.",
    answer: "모아",
    category: "물리",
  },
  {
    text: "오목 렌즈는 빛을 ___시키는 성질이 있다.",
    answer: "퍼뜨려",
    category: "물리",
  },
  {
    text: "에너지는 한 형태에서 다른 형태로 ___될 수 있다.",
    answer: "전환",
    category: "물리",
  },
  {
    text: "전기 에너지가 빛으로 바뀌는 기기의 예는 ___이다.",
    answer: "전등",
    category: "물리",
  },
  // 화학
  {
    text: "물질을 이루는 기본 입자를 ___이라 한다.",
    answer: "원자",
    category: "화학",
  },
  {
    text: "산소 원자 2개가 결합한 분자를 ___라 한다.",
    answer: "산소 분자",
    category: "화학",
  },
  {
    text: "물 분자는 수소 원자 2개와 ___원자 1개로 이루어져 있다.",
    answer: "산소",
    category: "화학",
  },
  {
    text: "산성과 염기성을 구분하는 지시약으로 ___용액이 있다.",
    answer: "BTB",
    category: "화학",
  },
  {
    text: "산성과 염기성 물질이 만나 성질이 약해지는 반응을 ___반응이라 한다.",
    answer: "중화",
    category: "화학",
  },
  {
    text: "연소에 꼭 필요한 세 가지 조건은 탈 물질, 산소, ___이다.",
    answer: "발화점 이상의 온도",
    category: "화학",
  },
  {
    text: "이산화탄소를 석회수에 통과시키면 석회수가 ___게 변한다.",
    answer: "뿌옇",
    category: "화학",
  },
  {
    text: "물질이 열을 받아 부피가 커지는 현상을 ___이라 한다.",
    answer: "열팽창",
    category: "화학",
  },
  {
    text: "금속이 전기를 잘 전달하는 성질을 ___이라 한다.",
    answer: "전기전도성",
    category: "화학",
  },
  {
    text: "물질의 세 가지 상태는 고체, 액체, ___이다.",
    answer: "기체",
    category: "화학",
  },
  // 지구과학(지구와 우주)
  {
    text: "지구에서 가장 가까운 항성은 ___이다.",
    answer: "태양",
    category: "지구과학",
  },
  {
    text: "북극성을 찾는 데 사용하는 별자리는 ___자리이다.",
    answer: "북두칠성(큰곰)",
    category: "지구과학",
  },
  {
    text: "계절이 변하는 이유는 지구의 ___이 기울어져 있기 때문이다.",
    answer: "자전축",
    category: "지구과학",
  },
  {
    text: "화산이 폭발할 때 나오는 뜨거운 액체를 ___라 한다.",
    answer: "용암",
    category: "지구과학",
  },
  {
    text: "지구의 표면은 여러 개의 ___으로 나누어져 있다.",
    answer: "판",
    category: "지구과학",
  },
  {
    text: "퇴적암 중에서 진흙이 굳어서 만들어진 것은 ___이다.",
    answer: "셰일",
    category: "지구과학",
  },
  {
    text: "달의 표면에 있는 큰 구덩이를 ___라 한다.",
    answer: "크레이터",
    category: "지구과학",
  },
  {
    text: "지진의 세기를 나타내는 단위는 ___이다.",
    answer: "규모(리히터)",
    category: "지구과학",
  },
  {
    text: "태양계에서 지구에 가장 가까운 행성은 ___이다.",
    answer: "금성",
    category: "지구과학",
  },
  {
    text: "우주에서 별이 모여 있는 거대한 집단을 ___이라 한다.",
    answer: "은하",
    category: "지구과학",
  },
];

// ===== NEW: 사회 데이터 (40개) =====
export const grade6SocialData: KnowledgeEntry[] = [
  // 세계 지리
  {
    text: "세계에서 인구가 가장 많은 대륙은 ___이다.",
    answer: "아시아",
    category: "지리",
  },
  {
    text: "아마존 열대우림이 있는 대륙은 ___이다.",
    answer: "남아메리카",
    category: "지리",
  },
  {
    text: "세계에서 가장 면적이 작은 대륙은 ___이다.",
    answer: "오세아니아",
    category: "지리",
  },
  {
    text: "지구의 적도를 기준으로 북쪽을 ___반구라 한다.",
    answer: "북",
    category: "지리",
  },
  {
    text: "유럽과 아시아를 연결하는 나라는 ___이다.",
    answer: "튀르키예",
    category: "지리",
  },
  {
    text: "세계에서 가장 깊은 호수는 ___이다.",
    answer: "바이칼호",
    category: "지리",
  },
  { text: "이탈리아의 수도는 ___이다.", answer: "로마", category: "지리" },
  {
    text: "세계에서 가장 작은 나라는 ___이다.",
    answer: "바티칸",
    category: "지리",
  },
  // 근현대사
  {
    text: "일제 강점기는 ___년부터 1945년까지이다.",
    answer: "1910",
    category: "역사",
  },
  {
    text: "을사늑약으로 빼앗긴 것은 우리나라의 ___권이다.",
    answer: "외교",
    category: "역사",
  },
  {
    text: "대한민국 정부가 수립된 해는 ___년이다.",
    answer: "1948",
    category: "역사",
  },
  {
    text: "6·25 전쟁의 정전 협정이 체결된 곳은 ___이다.",
    answer: "판문점",
    category: "역사",
  },
  {
    text: "5·18 민주화운동은 ___년에 일어났다.",
    answer: "1980",
    category: "역사",
  },
  {
    text: "6월 민주항쟁이 일어난 해는 ___년이다.",
    answer: "1987",
    category: "역사",
  },
  {
    text: "1988년 서울에서 열린 국제 스포츠 대회는 ___이다.",
    answer: "올림픽",
    category: "역사",
  },
  {
    text: "한일 월드컵이 열린 해는 ___년이다.",
    answer: "2002",
    category: "역사",
  },
  // 세계 문화
  {
    text: "인도의 대표적인 건축물인 타지마할은 ___으로 지어졌다.",
    answer: "하얀 대리석",
    category: "문화",
  },
  {
    text: "이집트의 상징적인 건축물은 ___이다.",
    answer: "피라미드",
    category: "문화",
  },
  {
    text: "프랑스 파리의 상징인 철탑은 ___탑이다.",
    answer: "에펠",
    category: "문화",
  },
  { text: "일본의 전통 의상은 ___이다.", answer: "기모노", category: "문화" },
  {
    text: "중국의 만리장성은 ___을 막기 위해 지어졌다.",
    answer: "북방 민족의 침입",
    category: "문화",
  },
  {
    text: "그리스의 아테네에 있는 유명한 신전은 ___이다.",
    answer: "파르테논",
    category: "문화",
  },
  // 국제 관계
  {
    text: "전 세계 국가들이 모여 평화를 논의하는 국제기구는 ___이다.",
    answer: "유엔(UN)",
    category: "정치",
  },
  {
    text: "유엔 안전보장이사회의 상임이사국 수는 ___개국이다.",
    answer: "5",
    category: "정치",
  },
  {
    text: "세계 무역을 관리하는 국제기구는 ___이다.",
    answer: "WTO",
    category: "경제",
  },
  {
    text: "국제 올림픽 위원회의 약칭은 ___이다.",
    answer: "IOC",
    category: "문화",
  },
  {
    text: "적십자는 전쟁과 재난 시 ___을 돕는 국제기구이다.",
    answer: "부상자와 피해자",
    category: "정치",
  },
  // 인권
  {
    text: "세계 인권 선언은 ___년에 채택되었다.",
    answer: "1948",
    category: "정치",
  },
  {
    text: "아동의 권리를 보호하는 국제 기구는 ___이다.",
    answer: "유니세프",
    category: "정치",
  },
  {
    text: "노벨 평화상은 매년 ___에서 시상한다.",
    answer: "노르웨이 오슬로",
    category: "정치",
  },
  {
    text: "남아프리카공화국의 인종차별 정책을 ___라 했다.",
    answer: "아파르트헤이트",
    category: "정치",
  },
  {
    text: "넬슨 만델라는 ___을 위해 평생 싸운 인물이다.",
    answer: "인종평등",
    category: "정치",
  },
  // 경제
  {
    text: "세계 경제에서 달러는 ___국의 화폐이다.",
    answer: "미",
    category: "경제",
  },
  {
    text: "유럽 연합에서 사용하는 공통 화폐는 ___이다.",
    answer: "유로",
    category: "경제",
  },
  {
    text: "한 나라의 1년간 생산한 모든 재화와 서비스의 가치를 ___라 한다.",
    answer: "GDP",
    category: "경제",
  },
  {
    text: "개발도상국의 물건을 적정 가격에 사는 것을 ___무역이라 한다.",
    answer: "공정",
    category: "경제",
  },
  {
    text: "환율이란 우리나라 돈과 다른 나라 ___의 교환 비율이다.",
    answer: "돈",
    category: "경제",
  },
  {
    text: "물가가 계속 오르는 현상을 ___이라 한다.",
    answer: "인플레이션",
    category: "경제",
  },
  {
    text: "세계화로 인해 각국의 경제가 서로 ___되어 가고 있다.",
    answer: "연결",
    category: "경제",
  },
  {
    text: "공정무역 인증 마크가 있는 상품은 ___를 보장한다.",
    answer: "생산자의 정당한 대가",
    category: "경제",
  },
];
