import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
} from "@/types/curriculum";

// 2학년 1학기 교육과정 성취기준
export const grade2Semester1Standards = {
  math: [
    {
      code: "[2수01-08]",
      desc: "세 자리 수의 자릿값과 위치적 기수법을 이해하고 읽고 쓸 수 있다",
      unit: "세 자리 수",
      difficulty: 2,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-09]",
      desc: "뛰어 세기를 할 수 있다",
      unit: "세 자리 수",
      difficulty: 2,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-10]",
      desc: "두 자리 수의 범위에서 덧셈과 뺄셈의 계산 원리를 이해하고 계산할 수 있다",
      unit: "덧셈과 뺄셈",
      difficulty: 2,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수01-11]",
      desc: "덧셈과 뺄셈의 관계를 이해한다",
      unit: "덧셈과 뺄셈",
      difficulty: 2,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수03-02]",
      desc: "시각을 읽고 시간의 흐름을 이해한다",
      unit: "시각과 시간",
      difficulty: 2,
      weeks: [9, 11] as [number, number],
    },
    {
      code: "[2수04-01]",
      desc: "분류 기준에 따라 자료를 분류하여 표로 나타낼 수 있다",
      unit: "분류하기",
      difficulty: 2,
      weeks: [12, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[2국01-03]",
      desc: "자신의 감정을 표현하며 대화를 나눈다",
      unit: "감정 표현",
      difficulty: 2,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[2국02-03]",
      desc: "글을 읽고 주요 내용을 확인한다",
      unit: "읽기",
      difficulty: 2,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[2국03-02]",
      desc: "자신의 생각을 문장으로 표현한다",
      unit: "문장 쓰기",
      difficulty: 2,
      weeks: [8, 11] as [number, number],
    },
    {
      code: "[2국04-02]",
      desc: "소리와 표기가 다를 수 있음을 알고 낱말을 바르게 읽고 쓴다",
      unit: "소리와 표기",
      difficulty: 2,
      weeks: [12, 14] as [number, number],
    },
  ],
};

export const grade2Semester2Standards = {
  math: [
    {
      code: "[2수01-12]",
      desc: "곱셈이 이루어지는 실생활 상황을 통해 곱셈의 의미를 이해한다",
      unit: "곱셈구구",
      difficulty: 2,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-13]",
      desc: "곱셈구구를 이해하고 곱셈표를 만들 수 있다",
      unit: "곱셈구구",
      difficulty: 2,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수03-03]",
      desc: "길이를 나타내는 표준 단위의 필요성을 인식하고 1cm와 1m를 안다",
      unit: "길이 재기",
      difficulty: 2,
      weeks: [9, 11] as [number, number],
    },
    {
      code: "[2수04-02]",
      desc: "자료를 그래프로 나타내고 해석할 수 있다",
      unit: "그래프",
      difficulty: 2,
      weeks: [12, 14] as [number, number],
    },
  ],
  korean: [
    {
      code: "[2국01-04]",
      desc: "듣는 이를 바라보며 자신 있게 말한다",
      unit: "자신 있게 말하기",
      difficulty: 2,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2국02-04]",
      desc: "글을 읽고 인물의 처지와 마음을 짐작한다",
      unit: "인물의 마음",
      difficulty: 2,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2국03-03]",
      desc: "주변의 사람이나 사물에 대해 짧은 글을 쓴다",
      unit: "관찰 글쓰기",
      difficulty: 2,
      weeks: [9, 12] as [number, number],
    },
  ],
};

// ============================================================
// 맞춤법 데이터 (60 entries)
// ============================================================
export const grade2SpellingData: SpellingEntry[] = [
  // --- 기존 21개 ---
  {
    q1: "공부를 열심히 했다.",
    q2: "공부를 열심이 했다.",
    answer: 1,
    explanation: "'열심히'는 부사로 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "깨끗하게 청소했다.",
    q2: "깨끗히 청소했다.",
    answer: 1,
    explanation: "'깨끗하게'가 올바른 표현입니다. '-하게'로 씁니다.",
  },
  {
    q1: "넓은 운동장에서 뛰었다.",
    q2: "널분 운동장에서 뛰었다.",
    answer: 1,
    explanation: "'넓은'이 올바른 표기입니다.",
  },
  {
    q1: "나뭇잎이 떨어졌다.",
    q2: "나뭇닢이 떨어졌다.",
    answer: 1,
    explanation: "'나뭇잎'이 올바른 표기입니다.",
  },
  {
    q1: "지붕 위에 고양이가 있다.",
    q2: "지붕 위에 고양이가 잇다.",
    answer: 1,
    explanation: "'있다'가 올바른 표기입니다.",
  },
  {
    q1: "돌멩이를 주웠다.",
    q2: "돌맹이를 주웠다.",
    answer: 1,
    explanation: "'돌멩이'가 올바른 표기입니다.",
  },
  {
    q1: "할아버지께서 오셨다.",
    q2: "할아버지께서 오셧다.",
    answer: 1,
    explanation: "'오셨다'가 올바른 표기입니다.",
  },
  {
    q1: "내일 소풍을 갈 거예요.",
    q2: "내일 소풍을 갈 거에요.",
    answer: 1,
    explanation: "'갈 거예요'가 올바른 표기입니다.",
  },
  {
    q1: "그림을 잘 그렸다.",
    q2: "그림을 잘 그렸따.",
    answer: 1,
    explanation: "'그렸다'가 올바른 종결입니다.",
  },
  {
    q1: "무엇이든지 할 수 있다.",
    q2: "무엇이든지 할수 있다.",
    answer: 1,
    explanation: "'할 수'처럼 의존명사는 띄어 씁니다.",
  },
  {
    q1: "오랜만에 만났다.",
    q2: "오랫만에 만났다.",
    answer: 2,
    explanation:
      "'오랫만에'가 아니라 '오랜만에'가 올바른 표기입니다. (주의: 둘 다 틀린 표현이지만, 여기서는 '오랜만에'가 더 가까운 표현)",
  },
  {
    q1: "웃어른께 인사했다.",
    q2: "우서른께 인사했다.",
    answer: 1,
    explanation: "'웃어른'이 올바른 표기입니다.",
  },
  {
    q1: "바닷가에서 놀았다.",
    q2: "바다가에서 놀았다.",
    answer: 1,
    explanation: "'바닷가'가 올바른 사이시옷 표기입니다.",
  },
  {
    q1: "설거지를 도왔다.",
    q2: "설겆이를 도왔다.",
    answer: 1,
    explanation: "'설거지'가 올바른 표기입니다.",
  },
  {
    q1: "따뜻한 국을 먹었다.",
    q2: "따듯한 국을 먹었다.",
    answer: 1,
    explanation: "'따뜻한'이 올바른 표기입니다.",
  },
  {
    q1: "숙제를 다 했어요.",
    q2: "숙제를 다 핬어요.",
    answer: 1,
    explanation: "'했어요'가 올바른 표기입니다.",
  },
  {
    q1: "꽃잎이 예쁘다.",
    q2: "꼰닢이 예쁘다.",
    answer: 1,
    explanation: "'꽃잎'이 올바른 표기입니다.",
  },
  {
    q1: "시험을 잘 봤으면 좋겠다.",
    q2: "시험을 잘 봣으면 좋겠다.",
    answer: 1,
    explanation: "'봤으면'이 올바른 표기입니다.",
  },
  {
    q1: "안녕히 가세요.",
    q2: "안녕이 가세요.",
    answer: 1,
    explanation: "'안녕히'는 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "다같이 노래를 불렀다.",
    q2: "다 같이 노래를 불렀다.",
    answer: 2,
    explanation: "'다 같이'는 띄어 쓰는 것이 맞습니다.",
  },
  // --- 신규 40개 (answer: 1 / 2 혼합) ---
  {
    q1: "연필을 깎았다.",
    q2: "연필을 깍았다.",
    answer: 1,
    explanation: "'깎았다'가 올바른 표기입니다. 받침 'ㄲ'이 아니라 'ㄱ'입니다.",
  },
  {
    q1: "꼭 잊지 마세요.",
    q2: "꼭 잊지 마세여.",
    answer: 1,
    explanation: "'-요'가 올바른 종결어미입니다.",
  },
  {
    q1: "친구에게 빌려줬다.",
    q2: "친구에게 빌려줬따.",
    answer: 1,
    explanation: "'빌려줬다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "가방이 무겁다.",
    q2: "가방이 무겁따.",
    answer: 1,
    explanation: "'무겁다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "빗을 빌려주세요.",
    q2: "빛을 빌려주세요.",
    answer: 1,
    explanation: "'빗'은 머리를 빗는 도구이고, '빛'은 불빛입니다.",
  },
  {
    q1: "낱말을 외우었다.",
    q2: "낱말을 외웠다.",
    answer: 2,
    explanation: "'외웠다'가 올바른 줄임 표현입니다.",
  },
  {
    q1: "오늘은 날씨가 흐리다.",
    q2: "오늘은 날시가 흐리다.",
    answer: 1,
    explanation: "'날씨'는 된소리로 씁니다.",
  },
  {
    q1: "고구마를 구었다.",
    q2: "고구마를 구웠다.",
    answer: 2,
    explanation: "'구웠다'가 올바른 표기입니다.",
  },
  {
    q1: "줄넘기를 잘한다.",
    q2: "줄넘기를 잘 한다.",
    answer: 1,
    explanation: "'잘한다'는 한 단어로 붙여 씁니다.",
  },
  {
    q1: "문을 닫았다.",
    q2: "문을 다탔다.",
    answer: 1,
    explanation: "'닫았다'가 올바른 표기입니다.",
  },
  {
    q1: "이야기가 재밋다.",
    q2: "이야기가 재밌다.",
    answer: 2,
    explanation: "'재밌다'가 올바른 표기입니다.",
  },
  {
    q1: "선생님이 칭찬해 주셨다.",
    q2: "선생님이 칭찬해 주셧다.",
    answer: 1,
    explanation: "'주셨다'가 올바른 표기입니다.",
  },
  {
    q1: "내일은 토요일이에요.",
    q2: "내일은 토요일이예요.",
    answer: 1,
    explanation: "'이에요'가 올바른 표기입니다.",
  },
  {
    q1: "구름이 뭉게뭉게 떠 있다.",
    q2: "구름이 뭉계뭉계 떠 있다.",
    answer: 1,
    explanation: "'뭉게뭉게'가 올바른 표기입니다.",
  },
  {
    q1: "옷걸이에 옷을 걸었다.",
    q2: "옫걸이에 옷을 걸었다.",
    answer: 1,
    explanation: "'옷걸이'가 올바른 표기입니다.",
  },
  {
    q1: "일기 예보를 봤다.",
    q2: "일기 예보를 봣다.",
    answer: 1,
    explanation: "'봤다'가 올바른 표기입니다.",
  },
  {
    q1: "화분에 물을 주었다.",
    q2: "화분에 물을 줬다.",
    answer: 2,
    explanation: "'줬다'도 '주었다'의 줄임으로 올바른 표현입니다.",
  },
  {
    q1: "조용히 해 주세요.",
    q2: "조용이 해 주세요.",
    answer: 1,
    explanation: "'조용히'는 부사로 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "꾸준이 공부하자.",
    q2: "꾸준히 공부하자.",
    answer: 2,
    explanation: "'꾸준히'는 부사로 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "나란이 서세요.",
    q2: "나란히 서세요.",
    answer: 2,
    explanation: "'나란히'는 부사로 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "특별히 잘했어요.",
    q2: "특별이 잘했어요.",
    answer: 1,
    explanation: "'특별히'는 부사로 'ㅎ'이 들어갑니다.",
  },
  {
    q1: "정확하게 말해 주세요.",
    q2: "정확히 말해 주세요.",
    answer: 2,
    explanation: "'정확히'도 올바른 표현입니다.",
  },
  {
    q1: "반듯하게 앉으세요.",
    q2: "반듯히 앉으세요.",
    answer: 1,
    explanation: "'반듯하게'가 올바른 표현입니다.",
  },
  {
    q1: "길거리에서 놀면 안 된다.",
    q2: "길거리에서 놀면 안 됀다.",
    answer: 1,
    explanation: "'안 된다'가 올바른 표기입니다.",
  },
  {
    q1: "축하해!",
    q2: "축하헤!",
    answer: 1,
    explanation: "'축하해'가 올바른 표기입니다.",
  },
  {
    q1: "떡볶이를 먹었다.",
    q2: "떡볶기를 먹었다.",
    answer: 1,
    explanation: "'떡볶이'가 올바른 표기입니다.",
  },
  {
    q1: "햄버거가 맛없다.",
    q2: "햄버거가 맛업다.",
    answer: 1,
    explanation: "'맛없다'가 올바른 표기입니다.",
  },
  {
    q1: "잠깐만 기다려 주세요.",
    q2: "잠간만 기다려 주세요.",
    answer: 1,
    explanation: "'잠깐만'이 올바른 표기입니다.",
  },
  {
    q1: "강남콩이 자랐다.",
    q2: "강낭콩이 자랐다.",
    answer: 2,
    explanation: "'강낭콩'이 올바른 표기입니다.",
  },
  {
    q1: "과자가 짭짤하다.",
    q2: "과자가 짭잘하다.",
    answer: 1,
    explanation: "'짭짤하다'가 올바른 된소리 표기입니다.",
  },
  {
    q1: "공원에서 산책했다.",
    q2: "공원에서 산첵했다.",
    answer: 1,
    explanation: "'산책'이 올바른 표기입니다.",
  },
  {
    q1: "역활을 나누어 했다.",
    q2: "역할을 나누어 했다.",
    answer: 2,
    explanation: "'역할'이 올바른 표기입니다.",
  },
  {
    q1: "한복을 입었다.",
    q2: "한복을 이벘다.",
    answer: 1,
    explanation: "'입었다'가 올바른 표기입니다.",
  },
  {
    q1: "쓰래기를 줍자.",
    q2: "쓰레기를 줍자.",
    answer: 2,
    explanation: "'쓰레기'가 올바른 표기입니다.",
  },
  {
    q1: "개나리가 핀다.",
    q2: "개나리가 핀따.",
    answer: 1,
    explanation: "'핀다'에서 종결어미는 '-다'입니다.",
  },
  {
    q1: "풍선이 하늘로 날아갔다.",
    q2: "풍선이 하늘로 날아갓다.",
    answer: 1,
    explanation: "'날아갔다'가 올바른 표기입니다.",
  },
  {
    q1: "수족관에서 물고기를 봤다.",
    q2: "수족관에서 물고기를 봣다.",
    answer: 1,
    explanation: "'봤다'가 올바른 표기입니다.",
  },
  {
    q1: "과학 시간에 실험했다.",
    q2: "과학 시간에 실험핬다.",
    answer: 1,
    explanation: "'실험했다'가 올바른 표기입니다.",
  },
  {
    q1: "도서관에서 책을 빌렸다.",
    q2: "도서관에서 책을 빌렷다.",
    answer: 1,
    explanation: "'빌렸다'가 올바른 표기입니다.",
  },
  {
    q1: "우리 집 강아지는 귀엽다.",
    q2: "우리 집 강아지는 귀엽따.",
    answer: 1,
    explanation: "'귀엽다'에서 종결어미는 '-다'입니다.",
  },
];

// ============================================================
// 어휘 데이터 (60 entries)
// ============================================================
export const grade2VocabData: VocabEntry[] = [
  // --- 기존 15개 ---
  { meanings: ["종이를 자르는 도구", "두 개의 날이 있어요"], answer: "가위" },
  { meanings: ["비가 올 때 입는 옷", "물이 안 스며들어요"], answer: "우비" },
  { meanings: ["음식을 차갑게 보관해요", "부엌에 있어요"], answer: "냉장고" },
  { meanings: ["시간을 알려줘요", "벽에 걸어요"], answer: "시계" },
  {
    meanings: ["글을 지울 때 사용해요", "연필 위에 달려 있어요"],
    answer: "지우개",
  },
  { meanings: ["눈이 올 때 만들어요", "둥근 공 모양이에요"], answer: "눈사람" },
  { meanings: ["병원에서 일해요", "아픈 사람을 치료해요"], answer: "의사" },
  { meanings: ["편지를 넣어요", "우체통에 넣어요"], answer: "봉투" },
  { meanings: ["발을 따뜻하게 해요", "짝이 있어요"], answer: "양말" },
  { meanings: ["물건을 사는 곳", "여러 가지를 팔아요"], answer: "가게" },
  { meanings: ["밤하늘에 빛나요", "반짝반짝 빛나요"], answer: "별" },
  { meanings: ["동물이 사는 곳", "숲에 있어요"], answer: "둥지" },
  { meanings: ["씻을 때 사용해요", "거품이 나요"], answer: "비누" },
  { meanings: ["여러 사람이 타요", "정류장에서 기다려요"], answer: "버스" },
  { meanings: ["운동할 때 신어요", "끈이 있어요"], answer: "운동화" },
  // --- 신규 45개 ---
  {
    meanings: ["음식을 데워요", "전자레인지라고도 해요"],
    answer: "전자레인지",
  },
  { meanings: ["빨래를 해줘요", "세탁기라고 해요"], answer: "세탁기" },
  { meanings: ["방을 시원하게 해요", "여름에 사용해요"], answer: "에어컨" },
  {
    meanings: ["텔레비전을 줄여서 부르는 말", "프로그램을 봐요"],
    answer: "TV",
  },
  { meanings: ["길을 안내해 줘요", "차에 달려 있어요"], answer: "내비게이션" },
  { meanings: ["소리를 크게 해요", "음악을 들어요"], answer: "스피커" },
  { meanings: ["밤에 밝혀줘요", "책상 위에 놓아요"], answer: "스탠드" },
  {
    meanings: ["음식을 만드는 곳", "냄비와 프라이팬이 있어요"],
    answer: "부엌",
  },
  { meanings: ["자동차가 다니는 길", "신호등이 있어요"], answer: "도로" },
  { meanings: ["배가 다니는 곳", "물이 넓게 있어요"], answer: "바다" },
  { meanings: ["비행기가 뜨고 내리는 곳", "여행을 떠나요"], answer: "공항" },
  { meanings: ["기차가 서는 곳", "표를 사요"], answer: "역" },
  {
    meanings: ["아픈 사람이 입원해요", "의사와 간호사가 있어요"],
    answer: "병원",
  },
  { meanings: ["약을 사는 곳", "약사가 있어요"], answer: "약국" },
  { meanings: ["돈을 맡기는 곳", "저금을 해요"], answer: "은행" },
  { meanings: ["머리를 자르는 곳", "미용사가 있어요"], answer: "미용실" },
  { meanings: ["편지를 보내는 곳", "빨간 상자가 있어요"], answer: "우체국" },
  { meanings: ["불을 끄는 사람", "빨간 차를 타요"], answer: "소방관" },
  { meanings: ["범인을 잡아요", "나라를 지켜요"], answer: "경찰" },
  { meanings: ["하늘을 나는 탈것", "날개가 있어요"], answer: "비행기" },
  { meanings: ["물 위를 달려요", "돛이 있기도 해요"], answer: "배" },
  { meanings: ["땅속을 달려요", "전기로 움직여요"], answer: "지하철" },
  { meanings: ["봄에 피는 노란 꽃", "가지에 먼저 피어요"], answer: "개나리" },
  { meanings: ["가을에 빨갛게 물들어요", "나뭇잎이 변해요"], answer: "단풍" },
  { meanings: ["겨울에 내려요", "하얗고 차가워요"], answer: "눈" },
  { meanings: ["여름에 많이 와요", "천둥 번개가 쳐요"], answer: "소나기" },
  { meanings: ["바람이 강하게 불어요", "나무가 흔들려요"], answer: "태풍" },
  { meanings: ["땅이 흔들려요", "건물이 무너질 수 있어요"], answer: "지진" },
  { meanings: ["과일이 열려요", "나무에서 따요"], answer: "열매" },
  { meanings: ["꿀을 모아요", "노란 줄무늬가 있어요"], answer: "꿀벌" },
  { meanings: ["밤에 빛을 내요", "여름에 볼 수 있어요"], answer: "반딧불이" },
  { meanings: ["등딱지가 있어요", "느리게 기어가요"], answer: "달팽이" },
  { meanings: ["나뭇가지에 매달려요", "번데기에서 나와요"], answer: "나비" },
  { meanings: ["여덟 개의 다리가 있어요", "바다에 살아요"], answer: "문어" },
  { meanings: ["단단한 껍질이 있어요", "집게발이 있어요"], answer: "게" },
  { meanings: ["우유에서 만들어요", "노란색이에요"], answer: "치즈" },
  { meanings: ["밀가루로 만들어요", "오븐에서 구워요"], answer: "빵" },
  { meanings: ["콩으로 만들어요", "하얗고 부드러워요"], answer: "두부" },
  { meanings: ["바다에서 나요", "짭짤해요"], answer: "소금" },
  { meanings: ["달콤한 맛이 나요", "카카오로 만들어요"], answer: "초콜릿" },
  { meanings: ["종이를 묶을 때 써요", "둥글게 생겼어요"], answer: "고무줄" },
  { meanings: ["무언가를 잴 때 써요", "cm, m를 알려줘요"], answer: "자" },
  {
    meanings: ["아이들이 노는 곳", "그네와 미끄럼틀이 있어요"],
    answer: "놀이터",
  },
  { meanings: ["운동을 하는 넓은 곳", "달리기를 해요"], answer: "운동장" },
  {
    meanings: ["그림을 그리는 넓은 종이", "미술 시간에 사용해요"],
    answer: "도화지",
  },
];

// ============================================================
// 수학 데이터 (80 entries)
// ============================================================
export const grade2MathData: MathEntry[] = [
  // --- 기존 20개 ---
  // 두 자리 수 덧셈 (받아올림 없음)
  {
    type: "calculation",
    expression: "23 + 15",
    answer: 38,
    steps: ["20 + 10 = 30", "3 + 5 = 8", "30 + 8 = 38"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "34 + 21",
    answer: 55,
    steps: ["30 + 20 = 50", "4 + 1 = 5", "50 + 5 = 55"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "42 + 36",
    answer: 78,
    steps: ["40 + 30 = 70", "2 + 6 = 8", "70 + 8 = 78"],
    unit: "두 자리 수 덧셈",
  },
  // 두 자리 수 덧셈 (받아올림 있음)
  {
    type: "calculation",
    expression: "27 + 15",
    answer: 42,
    steps: [
      "7 + 5 = 12, 일의 자리 2, 받아올림 1",
      "2 + 1 + 1 = 4 (십의 자리)",
      "답: 42",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "38 + 24",
    answer: 62,
    steps: [
      "8 + 4 = 12, 일의 자리 2, 받아올림 1",
      "3 + 2 + 1 = 6 (십의 자리)",
      "답: 62",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "46 + 37",
    answer: 83,
    steps: [
      "6 + 7 = 13, 일의 자리 3, 받아올림 1",
      "4 + 3 + 1 = 8 (십의 자리)",
      "답: 83",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  // 두 자리 수 뺄셈
  {
    type: "calculation",
    expression: "58 - 23",
    answer: 35,
    steps: ["50 - 20 = 30", "8 - 3 = 5", "30 + 5 = 35"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "67 - 34",
    answer: 33,
    steps: ["60 - 30 = 30", "7 - 4 = 3", "30 + 3 = 33"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "45 - 18",
    answer: 27,
    steps: [
      "5에서 8을 뺄 수 없으므로 받아내림",
      "15 - 8 = 7 (일의 자리)",
      "3 - 1 = 2 (십의 자리)",
      "답: 27",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "73 - 29",
    answer: 44,
    steps: [
      "3에서 9를 뺄 수 없으므로 받아내림",
      "13 - 9 = 4 (일의 자리)",
      "6 - 2 = 4 (십의 자리)",
      "답: 44",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  // 곱셈구구
  {
    type: "calculation",
    expression: "2 × 3",
    answer: 6,
    steps: ["2를 3번 더하면: 2 + 2 + 2 = 6"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "2 × 7",
    answer: 14,
    steps: ["2를 7번 더하면: 14"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "3 × 4",
    answer: 12,
    steps: ["3을 4번 더하면: 3 + 3 + 3 + 3 = 12"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "4 × 5",
    answer: 20,
    steps: ["4를 5번 더하면: 4 + 4 + 4 + 4 + 4 = 20"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "5 × 6",
    answer: 30,
    steps: ["5를 6번 더하면: 30"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "6 × 3",
    answer: 18,
    steps: ["6을 3번 더하면: 6 + 6 + 6 = 18"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "7 × 4",
    answer: 28,
    steps: ["7을 4번 더하면: 7 + 7 + 7 + 7 = 28"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "8 × 3",
    answer: 24,
    steps: ["8을 3번 더하면: 8 + 8 + 8 = 24"],
    unit: "곱셈구구 8단",
  },
  {
    type: "calculation",
    expression: "9 × 2",
    answer: 18,
    steps: ["9를 2번 더하면: 9 + 9 = 18"],
    unit: "곱셈구구 9단",
  },
  {
    type: "calculation",
    expression: "5 × 5",
    answer: 25,
    steps: ["5를 5번 더하면: 25"],
    unit: "곱셈구구 5단",
  },
  // --- 신규 60개 ---
  // 추가 두 자리 수 덧셈 (받아올림 없음)
  {
    type: "calculation",
    expression: "11 + 23",
    answer: 34,
    steps: ["10 + 20 = 30", "1 + 3 = 4", "30 + 4 = 34"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "52 + 14",
    answer: 66,
    steps: ["50 + 10 = 60", "2 + 4 = 6", "60 + 6 = 66"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "31 + 45",
    answer: 76,
    steps: ["30 + 40 = 70", "1 + 5 = 6", "70 + 6 = 76"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "60 + 25",
    answer: 85,
    steps: ["60 + 20 = 80", "0 + 5 = 5", "80 + 5 = 85"],
    unit: "두 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "44 + 33",
    answer: 77,
    steps: ["40 + 30 = 70", "4 + 3 = 7", "70 + 7 = 77"],
    unit: "두 자리 수 덧셈",
  },
  // 추가 두 자리 수 덧셈 (받아올림 있음)
  {
    type: "calculation",
    expression: "19 + 13",
    answer: 32,
    steps: [
      "9 + 3 = 12, 일의 자리 2, 받아올림 1",
      "1 + 1 + 1 = 3 (십의 자리)",
      "답: 32",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "25 + 28",
    answer: 53,
    steps: [
      "5 + 8 = 13, 일의 자리 3, 받아올림 1",
      "2 + 2 + 1 = 5 (십의 자리)",
      "답: 53",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "36 + 47",
    answer: 83,
    steps: [
      "6 + 7 = 13, 일의 자리 3, 받아올림 1",
      "3 + 4 + 1 = 8 (십의 자리)",
      "답: 83",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "48 + 35",
    answer: 83,
    steps: [
      "8 + 5 = 13, 일의 자리 3, 받아올림 1",
      "4 + 3 + 1 = 8 (십의 자리)",
      "답: 83",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "57 + 26",
    answer: 83,
    steps: [
      "7 + 6 = 13, 일의 자리 3, 받아올림 1",
      "5 + 2 + 1 = 8 (십의 자리)",
      "답: 83",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "29 + 34",
    answer: 63,
    steps: [
      "9 + 4 = 13, 일의 자리 3, 받아올림 1",
      "2 + 3 + 1 = 6 (십의 자리)",
      "답: 63",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "15 + 67",
    answer: 82,
    steps: [
      "5 + 7 = 12, 일의 자리 2, 받아올림 1",
      "1 + 6 + 1 = 8 (십의 자리)",
      "답: 82",
    ],
    unit: "두 자리 수 덧셈",
    hasCarry: true,
  },
  // 추가 두 자리 수 뺄셈 (받아내림 없음)
  {
    type: "calculation",
    expression: "78 - 32",
    answer: 46,
    steps: ["70 - 30 = 40", "8 - 2 = 6", "40 + 6 = 46"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "95 - 41",
    answer: 54,
    steps: ["90 - 40 = 50", "5 - 1 = 4", "50 + 4 = 54"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "86 - 53",
    answer: 33,
    steps: ["80 - 50 = 30", "6 - 3 = 3", "30 + 3 = 33"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "49 - 26",
    answer: 23,
    steps: ["40 - 20 = 20", "9 - 6 = 3", "20 + 3 = 23"],
    unit: "두 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "77 - 44",
    answer: 33,
    steps: ["70 - 40 = 30", "7 - 4 = 3", "30 + 3 = 33"],
    unit: "두 자리 수 뺄셈",
  },
  // 추가 두 자리 수 뺄셈 (받아내림 있음)
  {
    type: "calculation",
    expression: "52 - 17",
    answer: 35,
    steps: [
      "2에서 7을 뺄 수 없으므로 받아내림",
      "12 - 7 = 5 (일의 자리)",
      "4 - 1 = 3 (십의 자리)",
      "답: 35",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "64 - 38",
    answer: 26,
    steps: [
      "4에서 8을 뺄 수 없으므로 받아내림",
      "14 - 8 = 6 (일의 자리)",
      "5 - 3 = 2 (십의 자리)",
      "답: 26",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "81 - 45",
    answer: 36,
    steps: [
      "1에서 5를 뺄 수 없으므로 받아내림",
      "11 - 5 = 6 (일의 자리)",
      "7 - 4 = 3 (십의 자리)",
      "답: 36",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "93 - 56",
    answer: 37,
    steps: [
      "3에서 6을 뺄 수 없으므로 받아내림",
      "13 - 6 = 7 (일의 자리)",
      "8 - 5 = 3 (십의 자리)",
      "답: 37",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "70 - 23",
    answer: 47,
    steps: [
      "0에서 3을 뺄 수 없으므로 받아내림",
      "10 - 3 = 7 (일의 자리)",
      "6 - 2 = 4 (십의 자리)",
      "답: 47",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "40 - 16",
    answer: 24,
    steps: [
      "0에서 6을 뺄 수 없으므로 받아내림",
      "10 - 6 = 4 (일의 자리)",
      "3 - 1 = 2 (십의 자리)",
      "답: 24",
    ],
    unit: "두 자리 수 뺄셈",
    hasBorrow: true,
  },
  // 추가 곱셈구구
  {
    type: "calculation",
    expression: "2 × 4",
    answer: 8,
    steps: ["2를 4번 더하면: 2 + 2 + 2 + 2 = 8"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "2 × 5",
    answer: 10,
    steps: ["2를 5번 더하면: 2 + 2 + 2 + 2 + 2 = 10"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "2 × 6",
    answer: 12,
    steps: ["2를 6번 더하면: 12"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "2 × 8",
    answer: 16,
    steps: ["2를 8번 더하면: 16"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "2 × 9",
    answer: 18,
    steps: ["2를 9번 더하면: 18"],
    unit: "곱셈구구 2단",
  },
  {
    type: "calculation",
    expression: "3 × 2",
    answer: 6,
    steps: ["3을 2번 더하면: 3 + 3 = 6"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "3 × 5",
    answer: 15,
    steps: ["3을 5번 더하면: 15"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "3 × 6",
    answer: 18,
    steps: ["3을 6번 더하면: 18"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "3 × 7",
    answer: 21,
    steps: ["3을 7번 더하면: 21"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "3 × 8",
    answer: 24,
    steps: ["3을 8번 더하면: 24"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "3 × 9",
    answer: 27,
    steps: ["3을 9번 더하면: 27"],
    unit: "곱셈구구 3단",
  },
  {
    type: "calculation",
    expression: "4 × 2",
    answer: 8,
    steps: ["4를 2번 더하면: 4 + 4 = 8"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "4 × 3",
    answer: 12,
    steps: ["4를 3번 더하면: 4 + 4 + 4 = 12"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "4 × 6",
    answer: 24,
    steps: ["4를 6번 더하면: 24"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "4 × 7",
    answer: 28,
    steps: ["4를 7번 더하면: 28"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "4 × 8",
    answer: 32,
    steps: ["4를 8번 더하면: 32"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "4 × 9",
    answer: 36,
    steps: ["4를 9번 더하면: 36"],
    unit: "곱셈구구 4단",
  },
  {
    type: "calculation",
    expression: "5 × 2",
    answer: 10,
    steps: ["5를 2번 더하면: 5 + 5 = 10"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "5 × 3",
    answer: 15,
    steps: ["5를 3번 더하면: 5 + 5 + 5 = 15"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "5 × 4",
    answer: 20,
    steps: ["5를 4번 더하면: 20"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "5 × 7",
    answer: 35,
    steps: ["5를 7번 더하면: 35"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "5 × 8",
    answer: 40,
    steps: ["5를 8번 더하면: 40"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "5 × 9",
    answer: 45,
    steps: ["5를 9번 더하면: 45"],
    unit: "곱셈구구 5단",
  },
  {
    type: "calculation",
    expression: "6 × 4",
    answer: 24,
    steps: ["6을 4번 더하면: 24"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "6 × 6",
    answer: 36,
    steps: ["6을 6번 더하면: 36"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "6 × 7",
    answer: 42,
    steps: ["6을 7번 더하면: 42"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "6 × 8",
    answer: 48,
    steps: ["6을 8번 더하면: 48"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "6 × 9",
    answer: 54,
    steps: ["6을 9번 더하면: 54"],
    unit: "곱셈구구 6단",
  },
  {
    type: "calculation",
    expression: "7 × 2",
    answer: 14,
    steps: ["7을 2번 더하면: 7 + 7 = 14"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 3",
    answer: 21,
    steps: ["7을 3번 더하면: 21"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 5",
    answer: 35,
    steps: ["7을 5번 더하면: 35"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 6",
    answer: 42,
    steps: ["7을 6번 더하면: 42"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 7",
    answer: 49,
    steps: ["7을 7번 더하면: 49"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 8",
    answer: 56,
    steps: ["7을 8번 더하면: 56"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "7 × 9",
    answer: 63,
    steps: ["7을 9번 더하면: 63"],
    unit: "곱셈구구 7단",
  },
  {
    type: "calculation",
    expression: "8 × 4",
    answer: 32,
    steps: ["8을 4번 더하면: 32"],
    unit: "곱셈구구 8단",
  },
  {
    type: "calculation",
    expression: "8 × 5",
    answer: 40,
    steps: ["8을 5번 더하면: 40"],
    unit: "곱셈구구 8단",
  },
  {
    type: "calculation",
    expression: "8 × 7",
    answer: 56,
    steps: ["8을 7번 더하면: 56"],
    unit: "곱셈구구 8단",
  },
  {
    type: "calculation",
    expression: "8 × 8",
    answer: 64,
    steps: ["8을 8번 더하면: 64"],
    unit: "곱셈구구 8단",
  },
  {
    type: "calculation",
    expression: "9 × 3",
    answer: 27,
    steps: ["9를 3번 더하면: 27"],
    unit: "곱셈구구 9단",
  },
  {
    type: "calculation",
    expression: "9 × 5",
    answer: 45,
    steps: ["9를 5번 더하면: 45"],
    unit: "곱셈구구 9단",
  },
  {
    type: "calculation",
    expression: "9 × 7",
    answer: 63,
    steps: ["9를 7번 더하면: 63"],
    unit: "곱셈구구 9단",
  },
  {
    type: "calculation",
    expression: "9 × 9",
    answer: 81,
    steps: ["9를 9번 더하면: 81"],
    unit: "곱셈구구 9단",
  },
];

// ============================================================
// 상식 데이터 (60 entries)
// ============================================================
export const grade2KnowledgeData: KnowledgeEntry[] = [
  // --- 기존 15개 ---
  { text: "우리나라의 수도는 ___이다.", answer: "서울", category: "사회" },
  {
    text: "지구에서 가장 큰 바다는 ___양이다.",
    answer: "태평",
    category: "지리",
  },
  {
    text: "식물이 자라려면 물, 햇빛, ___이 필요하다.",
    answer: "흙",
    category: "과학",
  },
  { text: "자석은 ___을 끌어당긴다.", answer: "철", category: "과학" },
  {
    text: "우리 몸에서 피를 온몸에 보내주는 장기는 ___이다.",
    answer: "심장",
    category: "과학",
  },
  { text: "한글을 만든 사람은 ___이다.", answer: "세종대왕", category: "역사" },
  { text: "1m는 ___cm이다.", answer: "100", category: "수학" },
  { text: "공룡은 ___에 살았다.", answer: "옛날", category: "과학" },
  { text: "곤충의 다리는 ___개이다.", answer: "6", category: "과학" },
  { text: "지구는 ___ 모양이다.", answer: "둥근", category: "과학" },
  { text: "우리나라 돈의 단위는 ___이다.", answer: "원", category: "사회" },
  {
    text: "비가 오기 전에 하늘에 ___이 끼낀다.",
    answer: "구름",
    category: "자연",
  },
  {
    text: "초록색 잎에서 햇빛으로 양분을 만드는 것을 ___이라 한다.",
    answer: "광합성",
    category: "과학",
  },
  { text: "사람의 뼈는 약 ___개이다.", answer: "206", category: "과학" },
  { text: "물이 끓으면 ___가 된다.", answer: "수증기", category: "과학" },
  // --- 신규 45개 ---
  {
    text: "태양계에서 가장 큰 행성은 ___이다.",
    answer: "목성",
    category: "과학",
  },
  {
    text: "지구에서 달까지는 약 38만 ___이다.",
    answer: "km",
    category: "과학",
  },
  {
    text: "식물의 뿌리는 ___에서 물을 흡수한다.",
    answer: "땅",
    category: "과학",
  },
  {
    text: "나비는 처음에 ___이었다가 변한다.",
    answer: "애벌레",
    category: "과학",
  },
  { text: "올챙이는 자라면 ___가 된다.", answer: "개구리", category: "과학" },
  { text: "거미의 다리는 ___개이다.", answer: "8", category: "과학" },
  { text: "낙타에는 ___ 위에 혹이 있다.", answer: "등", category: "동물" },
  { text: "펭귄은 날지 못하는 ___이다.", answer: "새", category: "동물" },
  { text: "코알라는 ___ 잎을 먹는다.", answer: "유칼립투스", category: "동물" },
  { text: "판다의 주식은 ___이다.", answer: "대나무", category: "동물" },
  {
    text: "우리나라의 국가 이름은 ___이다.",
    answer: "대한민국",
    category: "사회",
  },
  {
    text: "우리나라의 수도 서울을 가로지르는 강은 ___이다.",
    answer: "한강",
    category: "지리",
  },
  {
    text: "제주도에 있는 가장 높은 산은 ___이다.",
    answer: "한라산",
    category: "지리",
  },
  {
    text: "우리나라에서 가장 긴 강은 ___이다.",
    answer: "낙동강",
    category: "지리",
  },
  {
    text: "설날에 어른들께 하는 인사를 ___라고 한다.",
    answer: "세배",
    category: "사회",
  },
  { text: "추석의 다른 이름은 ___이다.", answer: "한가위", category: "사회" },
  {
    text: "대한민국의 건국 기념일은 ___월 3일이다.",
    answer: "10",
    category: "사회",
  },
  { text: "어린이날은 ___월 5일이다.", answer: "5", category: "사회" },
  { text: "크리스마스는 ___월 25일이다.", answer: "12", category: "사회" },
  { text: "한글날은 ___월 9일이다.", answer: "10", category: "사회" },
  {
    text: "물의 세 가지 상태는 고체, 액체, ___이다.",
    answer: "기체",
    category: "과학",
  },
  { text: "얼음이 녹으면 ___이 된다.", answer: "물", category: "과학" },
  { text: "무당벌레의 등에는 ___이 있다.", answer: "점", category: "과학" },
  {
    text: "해바라기는 ___을 향해 고개를 돌린다.",
    answer: "해",
    category: "과학",
  },
  {
    text: "식물의 씨앗을 심으면 먼저 ___가 나온다.",
    answer: "뿌리",
    category: "과학",
  },
  {
    text: "사람의 몸에서 가장 큰 장기는 ___이다.",
    answer: "간",
    category: "과학",
  },
  { text: "사람의 체온은 보통 ___도쯤이다.", answer: "36.5", category: "과학" },
  {
    text: "지구는 태양 주위를 1년에 ___바퀴 돈다.",
    answer: "1",
    category: "과학",
  },
  { text: "하루에 지구는 ___바퀴 자전한다.", answer: "1", category: "과학" },
  {
    text: "바다에 사는 가장 큰 포유류는 ___이다.",
    answer: "고래",
    category: "동물",
  },
  {
    text: "호랑이와 사자는 같은 ___ 과 동물이다.",
    answer: "고양이",
    category: "동물",
  },
  {
    text: "박쥐는 날 수 있는 유일한 ___이다.",
    answer: "포유류",
    category: "동물",
  },
  { text: "삼각형의 꼭짓점은 ___개이다.", answer: "3", category: "수학" },
  { text: "원에는 꼭짓점이 ___개이다.", answer: "0", category: "수학" },
  { text: "1kg은 ___g이다.", answer: "1000", category: "수학" },
  { text: "1시간은 ___분이다.", answer: "60", category: "수학" },
  { text: "1분은 ___초이다.", answer: "60", category: "수학" },
  {
    text: "100원짜리 동전 10개는 ___원이다.",
    answer: "1000",
    category: "수학",
  },
  { text: "500원짜리 동전 2개는 ___원이다.", answer: "1000", category: "수학" },
  {
    text: "온도를 재는 도구를 ___이라고 한다.",
    answer: "온도계",
    category: "과학",
  },
  {
    text: "무게를 재는 도구를 ___라고 한다.",
    answer: "저울",
    category: "과학",
  },
  {
    text: "물체가 땅으로 떨어지는 힘을 ___이라고 한다.",
    answer: "중력",
    category: "과학",
  },
  {
    text: "빛의 세 가지 기본 색은 빨강, 초록, ___이다.",
    answer: "파랑",
    category: "과학",
  },
  { text: "소금을 물에 넣으면 ___는다.", answer: "녹", category: "과학" },
  {
    text: "나침반의 빨간 바늘은 항상 ___쪽을 가리킨다.",
    answer: "북",
    category: "과학",
  },
];

// ============================================================
// 안전 데이터 (40 entries)
// ============================================================
export const grade2SafetyData: SafetyEntry[] = [
  // --- 기존 10개 ---
  {
    text: "지진이 나면 ___아래로 들어간다.",
    answer: "책상",
    category: "재난안전",
  },
  {
    text: "물놀이할 때는 반드시 ___를 입어야 한다.",
    answer: "구명조끼",
    category: "물놀이안전",
  },
  {
    text: "엘리베이터에 갇히면 ___를 누른다.",
    answer: "비상벨",
    category: "생활안전",
  },
  {
    text: "교통사고가 나면 ___번에 전화한다.",
    answer: "112",
    category: "교통안전",
  },
  {
    text: "음식을 먹기 전에 ___를 확인한다.",
    answer: "유통기한",
    category: "건강안전",
  },
  {
    text: "자전거를 탈 때는 ___을 꼭 쓴다.",
    answer: "헬멧",
    category: "교통안전",
  },
  {
    text: "전기 콘센트에 ___를 넣으면 안 된다.",
    answer: "손",
    category: "전기안전",
  },
  {
    text: "눈이 오면 길이 ___해서 조심해야 한다.",
    answer: "미끄러워",
    category: "생활안전",
  },
  {
    text: "약은 ___의 허락 없이 먹으면 안 된다.",
    answer: "어른",
    category: "건강안전",
  },
  {
    text: "화재 시 ___를 막고 낮은 자세로 이동한다.",
    answer: "코와 입",
    category: "화재안전",
  },
  // --- 신규 30개 ---
  { text: "비상구 표시는 ___ 색이다.", answer: "초록", category: "화재안전" },
  {
    text: "화재 시 엘리베이터 대신 ___를 이용한다.",
    answer: "계단",
    category: "화재안전",
  },
  {
    text: "불장난을 하면 ___이 날 수 있다.",
    answer: "화재",
    category: "화재안전",
  },
  {
    text: "소화기를 사용할 때 안전핀을 ___야 한다.",
    answer: "뽑",
    category: "화재안전",
  },
  {
    text: "횡단보도를 건널 때 손을 ___어야 한다.",
    answer: "들",
    category: "교통안전",
  },
  {
    text: "도로에서 공놀이를 하면 ___하다.",
    answer: "위험",
    category: "교통안전",
  },
  {
    text: "안전벨트는 차에 타면 반드시 ___야 한다.",
    answer: "매",
    category: "교통안전",
  },
  {
    text: "어두운 곳에서는 ___색 옷이 눈에 잘 띈다.",
    answer: "밝은",
    category: "교통안전",
  },
  {
    text: "수영하기 전에 ___운동을 해야 한다.",
    answer: "준비",
    category: "물놀이안전",
  },
  {
    text: "물이 깊은 곳에 혼자 ___면 안 된다.",
    answer: "가",
    category: "물놀이안전",
  },
  {
    text: "바다에서 파도가 세면 물에 ___면 안 된다.",
    answer: "들어가",
    category: "물놀이안전",
  },
  {
    text: "계곡에서 갑자기 물이 불어나면 높은 곳으로 ___야 한다.",
    answer: "올라가",
    category: "물놀이안전",
  },
  {
    text: "음식을 먹다 목에 걸리면 ___을 해야 한다.",
    answer: "기침",
    category: "건강안전",
  },
  { text: "열이 나면 ___에 가야 한다.", answer: "병원", category: "건강안전" },
  {
    text: "손을 씻을 때 ___로 꼼꼼히 씻어야 한다.",
    answer: "비누",
    category: "건강안전",
  },
  {
    text: "상처가 나면 먼저 ___으로 씻어야 한다.",
    answer: "깨끗한 물",
    category: "건강안전",
  },
  {
    text: "가스 냄새가 나면 창문을 ___야 한다.",
    answer: "열",
    category: "생활안전",
  },
  {
    text: "가스 냄새가 나면 ___를 사용하면 안 된다.",
    answer: "전기",
    category: "생활안전",
  },
  {
    text: "칼이나 가위를 사용할 때는 ___해야 한다.",
    answer: "조심",
    category: "생활안전",
  },
  {
    text: "빗길에서 뛰면 ___질 수 있다.",
    answer: "넘어",
    category: "생활안전",
  },
  {
    text: "무거운 물건을 들 때는 ___을 굽혀야 한다.",
    answer: "무릎",
    category: "생활안전",
  },
  {
    text: "놀이기구를 탈 때 안전 ___를 지켜야 한다.",
    answer: "수칙",
    category: "학교안전",
  },
  {
    text: "교실에서 창문 밖으로 몸을 ___면 안 된다.",
    answer: "내밀",
    category: "학교안전",
  },
  {
    text: "복도에서는 ___쪽으로 걸어야 한다.",
    answer: "오른",
    category: "학교안전",
  },
  {
    text: "실험할 때 안전 ___을 써야 한다.",
    answer: "안경",
    category: "학교안전",
  },
  {
    text: "모르는 사람이 차에 태워준다고 하면 ___해야 한다.",
    answer: "거절",
    category: "생활안전",
  },
  {
    text: "집 열쇠를 다른 사람에게 ___면 안 된다.",
    answer: "보여주",
    category: "생활안전",
  },
  {
    text: "비상시에 가족 연락처를 ___해 두어야 한다.",
    answer: "외워",
    category: "재난안전",
  },
  {
    text: "지진이 나면 가스 밸브를 ___아야 한다.",
    answer: "잠그",
    category: "재난안전",
  },
  {
    text: "태풍이 오면 밖에 있는 물건을 ___에 들여놔야 한다.",
    answer: "안",
    category: "재난안전",
  },
];

// ============================================================
// 글쓰기 프롬프트 (60 entries)
// ============================================================
export const grade2WritingPrompts: string[] = [
  // --- 기존 20개 ---
  "주말에 가족과 함께 한 일을 써 보세요.",
  "내가 키우는 (키우고 싶은) 동물에 대해 써 보세요.",
  "가장 재미있었던 수업 시간을 써 보세요.",
  "친구와 함께 놀았던 일을 써 보세요.",
  "내가 좋아하는 책 이야기를 해 보세요.",
  "봄(여름/가을/겨울)에 하고 싶은 일을 써 보세요.",
  "우리 동네를 소개해 보세요.",
  "내가 만약 거인이 된다면 무엇을 할까요?",
  "가장 감사한 사람에게 편지를 써 보세요.",
  "내가 잘하는 것에 대해 써 보세요.",
  "학교에서 있었던 재미있는 일을 써 보세요.",
  "내가 만든 음식(요리)에 대해 써 보세요.",
  "소풍에서 있었던 일을 써 보세요.",
  "나의 꿈에 대해 써 보세요.",
  "일기 쓰기: 오늘 하루를 돌아보세요.",
  "내가 가장 좋아하는 장소는 어디인가요?",
  "엄마(아빠)에게 하고 싶은 말을 써 보세요.",
  "비가 오는 날의 이야기를 만들어 보세요.",
  "내가 만약 투명인간이 된다면?",
  "동생(형, 누나, 언니, 오빠)에게 하고 싶은 말을 써 보세요.",
  // --- 신규 40개 ---
  "오늘 아침에 일어나서 학교 오기까지의 일을 써 보세요.",
  "가장 좋아하는 운동에 대해 써 보세요.",
  "학교 급식에서 가장 맛있었던 메뉴는 무엇인가요?",
  "우리 반에서 가장 재미있었던 일을 써 보세요.",
  "방학에 하고 싶은 일을 써 보세요.",
  "내가 만약 동물의 왕이 된다면?",
  "슈퍼마켓에 가면 무엇을 사고 싶은가요?",
  "비행기를 타고 가고 싶은 나라는 어디인가요?",
  "내가 만약 시간을 되돌릴 수 있다면?",
  "학교에서 가장 좋아하는 과목과 그 이유를 써 보세요.",
  "오늘 친구에게 고마웠던 일을 써 보세요.",
  "내가 만든 작품(미술, 공작 등)에 대해 써 보세요.",
  "운동회에서 있었던 일을 써 보세요.",
  "도서관에서 읽은 책 이야기를 해 보세요.",
  "내가 선생님이 된다면 어떤 수업을 할까요?",
  "우리 학교를 소개해 보세요.",
  "가족 여행에서 가장 재미있었던 일을 써 보세요.",
  "내가 만약 요리사가 된다면 무엇을 만들까요?",
  "내가 좋아하는 노래를 소개해 보세요.",
  "제일 무서웠던 경험을 써 보세요.",
  "친구에게 생일 축하 편지를 써 보세요.",
  "반려동물(또는 키우고 싶은 동물)과의 하루를 상상해 보세요.",
  "내가 만약 우주에 간다면?",
  "가장 기뻤던 순간을 자세히 써 보세요.",
  "내가 만약 나라의 대통령이 된다면?",
  "좋아하는 계절에 대해 감각(보이는 것, 들리는 것, 느낌)을 써 보세요.",
  "이웃 어른에게 감사 편지를 써 보세요.",
  "내가 만약 바다 속에 살 수 있다면?",
  "우리 집 근처에서 가장 좋아하는 곳을 소개해 보세요.",
  "내가 만약 마법 지팡이가 있다면?",
  "오늘 배운 것 중 가장 기억에 남는 것은?",
  "동화 속 인물이 된다면 누가 되고 싶은가요?",
  "가장 아꼈던 물건에 대해 써 보세요.",
  "내가 만약 동물과 대화할 수 있다면?",
  "지구를 깨끗하게 하려면 어떻게 해야 할까요?",
  "내가 만약 시간여행을 할 수 있다면 어디로 갈까요?",
  "세상에서 가장 맛있는 간식을 발명한다면?",
  "다른 나라 친구에게 한국을 소개하는 편지를 써 보세요.",
  "내가 만약 슈퍼 히어로라면 어떤 능력이 있을까요?",
  "100년 후의 학교는 어떤 모습일까요? 상상해서 써 보세요.",
];

// ============================================================
// 국어 데이터 - NEW (40 entries)
// ============================================================
export const grade2KoreanData: KnowledgeEntry[] = [
  {
    text: "문장에서 '누가'에 해당하는 것을 ___라고 합니다.",
    answer: "주어",
    category: "국어",
  },
  {
    text: "문장에서 '어떻게 한다'에 해당하는 것을 ___라고 합니다.",
    answer: "서술어",
    category: "국어",
  },
  {
    text: "문장에서 '무엇을'에 해당하는 것을 ___라고 합니다.",
    answer: "목적어",
    category: "국어",
  },
  {
    text: "소리와 표기가 다른 것을 ___이라고 합니다.",
    answer: "음운 변동",
    category: "국어",
  },
  {
    text: "'국물'을 소리 나는 대로 쓰면 '___'이 됩니다.",
    answer: "궁물",
    category: "국어",
  },
  {
    text: "'읽다'를 소리 나는 대로 쓰면 '___'이 됩니다.",
    answer: "익다",
    category: "국어",
  },
  {
    text: "글을 읽고 중심 내용을 파악하는 것을 ___이라고 해요.",
    answer: "요약",
    category: "읽기",
  },
  {
    text: "이야기의 처음, 가운데, 끝을 ___이라고 해요.",
    answer: "구성",
    category: "읽기",
  },
  {
    text: "글에서 가장 중요한 문장을 ___ 문장이라고 해요.",
    answer: "중심",
    category: "읽기",
  },
  {
    text: "중심 문장을 도와주는 문장을 ___ 문장이라고 해요.",
    answer: "뒷받침",
    category: "읽기",
  },
  {
    text: "이야기에서 사건이 일어나는 때를 ___이라고 해요.",
    answer: "시간적 배경",
    category: "읽기",
  },
  {
    text: "이야기에서 사건이 일어나는 곳을 ___이라고 해요.",
    answer: "공간적 배경",
    category: "읽기",
  },
  {
    text: "글을 쓸 때 떠오르는 생각을 모으는 것을 ___이라고 해요.",
    answer: "생각 모으기",
    category: "쓰기",
  },
  {
    text: "일기의 첫 줄에는 ___, 날씨, 요일을 써요.",
    answer: "날짜",
    category: "쓰기",
  },
  {
    text: "관찰 글을 쓸 때는 오감(보기, 듣기, 만지기, 맡기, ___)을 사용해요.",
    answer: "맛보기",
    category: "쓰기",
  },
  {
    text: "편지에서 받는 사람 다음에 쓰는 인사를 ___이라고 해요.",
    answer: "첫인사",
    category: "쓰기",
  },
  {
    text: "편지의 마지막에 보내는 사람의 ___을 써요.",
    answer: "이름",
    category: "쓰기",
  },
  {
    text: "다른 사람의 말을 듣고 되풀이하는 것을 ___이라고 해요.",
    answer: "따라 말하기",
    category: "말하기",
  },
  {
    text: "발표할 때는 듣는 사람을 ___야 해요.",
    answer: "바라봐",
    category: "말하기",
  },
  {
    text: "상대방의 이야기를 끝까지 ___어야 해요.",
    answer: "들",
    category: "말하기",
  },
  {
    text: "자신의 생각을 다른 사람에게 말하는 것을 ___라고 해요.",
    answer: "발표",
    category: "말하기",
  },
  {
    text: "높임말을 사용하는 상대는 ___이에요.",
    answer: "어른",
    category: "말하기",
  },
  {
    text: "동시에서 같은 소리가 반복되는 것을 ___이라고 해요.",
    answer: "운",
    category: "국어",
  },
  {
    text: "뜻이 비슷한 말을 ___어라고 해요.",
    answer: "비슷한 말(유의)",
    category: "국어",
  },
  {
    text: "뜻이 반대인 말을 ___어라고 해요.",
    answer: "반대말(반의)",
    category: "국어",
  },
  { text: "'크다'의 반대말은 '___'이에요.", answer: "작다", category: "국어" },
  { text: "'많다'의 반대말은 '___'이에요.", answer: "적다", category: "국어" },
  { text: "'높다'의 반대말은 '___'이에요.", answer: "낮다", category: "국어" },
  { text: "'길다'의 반대말은 '___'이에요.", answer: "짧다", category: "국어" },
  {
    text: "'밝다'의 반대말은 '___'이에요.",
    answer: "어둡다",
    category: "국어",
  },
  {
    text: "글을 쓰기 전에 글의 순서를 정하는 것을 ___이라고 해요.",
    answer: "개요",
    category: "쓰기",
  },
  {
    text: "상상해서 이야기를 지어 쓰는 것을 ___ 글이라고 해요.",
    answer: "상상",
    category: "쓰기",
  },
  {
    text: "실제로 겪은 일을 쓰는 것을 ___ 글이라고 해요.",
    answer: "경험",
    category: "쓰기",
  },
  {
    text: "동화 '해님달님'에서 호랑이를 피해 올라간 곳은 ___이에요.",
    answer: "하늘",
    category: "읽기",
  },
  {
    text: "'혹부리 영감'에서 혹을 떼어간 것은 ___이에요.",
    answer: "도깨비",
    category: "읽기",
  },
  {
    text: "글의 내용을 그림으로 표현한 것을 ___이라고 해요.",
    answer: "삽화",
    category: "읽기",
  },
  { text: "'ㄱ'의 이름은 '___'이에요.", answer: "기역", category: "국어" },
  { text: "'ㄴ'의 이름은 '___'이에요.", answer: "니은", category: "국어" },
  { text: "'ㅁ'의 이름은 '___'이에요.", answer: "미음", category: "국어" },
  { text: "'ㅅ'의 이름은 '___'이에요.", answer: "시옷", category: "국어" },
];

// ============================================================
// 창의 데이터 - NEW (40 entries)
// ============================================================
export const grade2CreativeData: KnowledgeEntry[] = [
  {
    text: "빨간색과 노란색을 섞으면 ___ 색이 됩니다.",
    answer: "주황",
    category: "미술",
  },
  {
    text: "빨간색과 파란색을 섞으면 ___ 색이 됩니다.",
    answer: "보라",
    category: "미술",
  },
  {
    text: "파란색과 노란색을 섞으면 ___ 색이 됩니다.",
    answer: "초록",
    category: "미술",
  },
  {
    text: "색을 섞지 않고 그대로 사용하는 색을 ___이라고 해요.",
    answer: "원색",
    category: "미술",
  },
  {
    text: "물감에 물을 많이 타면 색이 ___아져요.",
    answer: "연해(옅)",
    category: "미술",
  },
  {
    text: "물감에 검정을 섞으면 색이 ___아져요.",
    answer: "어두워",
    category: "미술",
  },
  {
    text: "물감에 하양을 섞으면 색이 ___아져요.",
    answer: "밝",
    category: "미술",
  },
  {
    text: "데칼코마니는 종이를 반으로 접어 ___한 그림을 만드는 기법이에요.",
    answer: "대칭",
    category: "미술",
  },
  {
    text: "마블링은 물 위에 물감을 떨어뜨려 ___을 만드는 기법이에요.",
    answer: "무늬",
    category: "미술",
  },
  {
    text: "콜라주는 여러 가지 재료를 ___서 작품을 만드는 기법이에요.",
    answer: "붙여",
    category: "미술",
  },
  {
    text: "판화는 판에 그림을 새겨서 ___는 미술 기법이에요.",
    answer: "찍",
    category: "미술",
  },
  {
    text: "점토로 만든 작품을 가마에 구우면 ___이 됩니다.",
    answer: "도자기",
    category: "만들기",
  },
  {
    text: "리코더에서 구멍을 많이 막으면 소리가 ___아져요.",
    answer: "낮",
    category: "음악",
  },
  {
    text: "리코더에서 구멍을 적게 막으면 소리가 ___아져요.",
    answer: "높",
    category: "음악",
  },
  {
    text: "음악에서 '도레미파솔라시'를 ___이라고 해요.",
    answer: "음계",
    category: "음악",
  },
  {
    text: "4분의 4박자에서 한 마디에 ___박이 들어가요.",
    answer: "4",
    category: "음악",
  },
  {
    text: "음악에서 쉬는 것을 나타내는 표시를 ___라고 해요.",
    answer: "쉼표",
    category: "음악",
  },
  {
    text: "음악에서 소리의 길이를 나타내는 표시를 ___라고 해요.",
    answer: "음표",
    category: "음악",
  },
  { text: "4분음표 하나의 길이는 ___박이에요.", answer: "1", category: "음악" },
  { text: "2분음표 하나의 길이는 ___박이에요.", answer: "2", category: "음악" },
  {
    text: "색종이를 접어 만드는 종이학은 ___ 접기의 하나예요.",
    answer: "종이",
    category: "만들기",
  },
  {
    text: "빈 페트병으로 만드는 것을 ___ 미술이라고 해요.",
    answer: "재활용",
    category: "만들기",
  },
  {
    text: "실과 바늘로 천에 무늬를 넣는 것을 ___이라고 해요.",
    answer: "자수",
    category: "만들기",
  },
  {
    text: "털실로 짜는 것을 ___이라고 해요.",
    answer: "뜨개질",
    category: "만들기",
  },
  {
    text: "그림에서 명암은 밝은 부분과 ___ 부분을 표현하는 것이에요.",
    answer: "어두운",
    category: "미술",
  },
  {
    text: "음악에서 여러 사람이 돌아가며 부르는 노래를 ___이라고 해요.",
    answer: "돌림노래",
    category: "음악",
  },
  {
    text: "피아노 건반에서 검은 건반과 ___ 건반이 있어요.",
    answer: "하얀",
    category: "음악",
  },
  {
    text: "오케스트라를 지휘하는 사람을 ___라고 해요.",
    answer: "지휘자",
    category: "음악",
  },
  {
    text: "전통 탈을 쓰고 하는 놀이를 ___이라고 해요.",
    answer: "탈춤",
    category: "만들기",
  },
  {
    text: "우리나라 전통 부채에 그림을 그리는 것을 ___ 그리기라고 해요.",
    answer: "부채",
    category: "미술",
  },
  {
    text: "미술에서 똑같은 모양이 반복되는 것을 ___이라고 해요.",
    answer: "패턴",
    category: "미술",
  },
  {
    text: "건축물을 작게 만든 모형을 ___이라고 해요.",
    answer: "미니어처",
    category: "만들기",
  },
  {
    text: "움직이는 그림을 ___이라고 해요.",
    answer: "애니메이션",
    category: "미술",
  },
  {
    text: "사물놀이에서 사용하는 네 가지 악기는 꽹과리, 징, 장구, ___이에요.",
    answer: "북",
    category: "음악",
  },
  {
    text: "가야금은 줄을 ___어서 소리를 내요.",
    answer: "뜯",
    category: "음악",
  },
  { text: "피리는 ___을 불어서 소리를 내요.", answer: "입", category: "음악" },
  {
    text: "그림을 그릴 때 가장 먼저 하는 것은 ___이에요.",
    answer: "밑그림",
    category: "미술",
  },
  {
    text: "여러 색 실을 교차시켜 천을 만드는 것을 ___이라고 해요.",
    answer: "직조",
    category: "만들기",
  },
  {
    text: "그림을 액자에 넣어 벽에 거는 것을 ___이라고 해요.",
    answer: "전시",
    category: "미술",
  },
  {
    text: "음악회에서 관객이 박수를 치는 것을 ___이라고 해요.",
    answer: "박수갈채",
    category: "음악",
  },
];
