import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
  HanjaEntry,
  EnglishEntry,
} from "@/types/curriculum";

// 4학년 1학기 교육과정 성취기준
export const grade4Semester1Standards = {
  math: [
    {
      code: "[4수01-01]",
      desc: "큰 수의 자릿값과 위치적 기수법을 이해하고 수를 읽고 쓸 수 있다",
      unit: "큰 수",
      difficulty: 4,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4수01-02]",
      desc: "곱셈과 나눗셈의 계산 원리를 이해하고 그 계산을 할 수 있다",
      unit: "곱셈과 나눗셈",
      difficulty: 4,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4수01-03]",
      desc: "분모가 같은 분수의 크기를 비교할 수 있다",
      unit: "분수의 덧셈과 뺄셈",
      difficulty: 4,
      weeks: [8, 10] as [number, number],
    },
    {
      code: "[4수02-01]",
      desc: "각의 크기의 단위를 알고 각도를 측정할 수 있다",
      unit: "각도",
      difficulty: 4,
      weeks: [11, 13] as [number, number],
    },
    {
      code: "[4수02-02]",
      desc: "삼각형의 세 각의 크기의 합이 180°임을 안다",
      unit: "삼각형",
      difficulty: 4,
      weeks: [14, 16] as [number, number],
    },
  ],
  korean: [
    {
      code: "[4국01-03]",
      desc: "원인과 결과의 관계를 고려하며 듣고 말한다",
      unit: "원인과 결과",
      difficulty: 4,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4국02-03]",
      desc: "글을 읽고 중심 생각과 뒷받침하는 내용을 파악한다",
      unit: "중심 생각",
      difficulty: 4,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4국03-02]",
      desc: "읽는 이를 고려하며 자신의 마음을 표현하는 글을 쓴다",
      unit: "마음 표현",
      difficulty: 4,
      weeks: [8, 11] as [number, number],
    },
    {
      code: "[4국04-02]",
      desc: "높임법을 알고 언어 예절에 맞게 사용한다",
      unit: "높임법",
      difficulty: 4,
      weeks: [12, 14] as [number, number],
    },
  ],
  english: [
    {
      code: "[4영01-03]",
      desc: "쉽고 간단한 문장을 강세, 리듬, 억양에 맞게 소리 내어 읽을 수 있다",
      unit: "Reading Aloud",
      difficulty: 4,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[4영02-03]",
      desc: "일상생활에 관한 쉽고 간단한 말이나 대화를 듣고 세부 정보를 파악할 수 있다",
      unit: "Listening",
      difficulty: 4,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[4영03-02]",
      desc: "실물이나 그림을 보고 쉽고 간단한 문장으로 표현할 수 있다",
      unit: "Speaking",
      difficulty: 4,
      weeks: [9, 12] as [number, number],
    },
  ],
};

export const grade4Semester2Standards = {
  math: [
    {
      code: "[4수01-04]",
      desc: "소수의 크기를 비교할 수 있다",
      unit: "소수",
      difficulty: 4,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4수01-05]",
      desc: "분모가 같은 분수의 덧셈과 뺄셈을 할 수 있다",
      unit: "분수의 덧셈과 뺄셈",
      difficulty: 4,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4수02-03]",
      desc: "다각형의 성질을 이해하고 그릴 수 있다",
      unit: "다각형",
      difficulty: 4,
      weeks: [8, 10] as [number, number],
    },
    {
      code: "[4수04-01]",
      desc: "실생활 자료를 수집하여 막대그래프나 꺾은선그래프로 나타내고 해석할 수 있다",
      unit: "꺾은선그래프",
      difficulty: 4,
      weeks: [11, 13] as [number, number],
    },
    {
      code: "[4수03-01]",
      desc: "어림하기를 통해 실생활 문제를 해결할 수 있다",
      unit: "어림하기",
      difficulty: 4,
      weeks: [14, 16] as [number, number],
    },
  ],
  korean: [
    {
      code: "[4국01-04]",
      desc: "적절한 표정, 몸짓, 말투로 말한다",
      unit: "표현하기",
      difficulty: 4,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4국02-04]",
      desc: "글을 읽고 사실과 의견을 구별한다",
      unit: "사실과 의견",
      difficulty: 4,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4국03-03]",
      desc: "관심 있는 주제에 대해 자신의 의견이 드러나게 글을 쓴다",
      unit: "의견 글쓰기",
      difficulty: 4,
      weeks: [8, 11] as [number, number],
    },
  ],
  english: [
    {
      code: "[4영01-04]",
      desc: "쉽고 간단한 낱말이나 어구, 문장을 따라 쓸 수 있다",
      unit: "Writing",
      difficulty: 4,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[4영02-04]",
      desc: "일상생활에 관한 쉽고 간단한 대화에 참여할 수 있다",
      unit: "Conversation",
      difficulty: 4,
      weeks: [5, 8] as [number, number],
    },
  ],
};

export const grade4SpellingData: SpellingEntry[] = [
  // 기존 22개
  {
    q1: "가르치다 - 선생님이 학생을 가르친다.",
    q2: "가리키다 - 선생님이 학생을 가리킨다.",
    answer: 1,
    explanation:
      "'가르치다'는 지식을 알려주는 것, '가리키다'는 방향을 보여주는 것입니다.",
  },
  {
    q1: "부치다 - 편지를 부쳤다.",
    q2: "붙이다 - 편지를 붙였다.",
    answer: 1,
    explanation: "'부치다'는 보내는 것이고, '붙이다'는 달라붙게 하는 것입니다.",
  },
  {
    q1: "바치다 - 나라에 목숨을 바쳤다.",
    q2: "받치다 - 나라에 목숨을 받쳤다.",
    answer: 1,
    explanation: "'바치다'는 드리는 것이고, '받치다'는 밑에 대는 것입니다.",
  },
  {
    q1: "낫다 - 감기가 나았다.",
    q2: "낳다 - 감기가 낳았다.",
    answer: 1,
    explanation: "'낫다'는 회복되는 것이고, '낳다'는 출산하는 것입니다.",
  },
  {
    q1: "맞히다 - 정답을 맞혔다.",
    q2: "맞추다 - 정답을 맞쳤다.",
    answer: 1,
    explanation: "'맞히다'는 적중시키는 것이고, '맞추다'는 비교하는 것입니다.",
  },
  {
    q1: "그러므로 열심히 해야 한다.",
    q2: "그럼으로 열심히 해야 한다.",
    answer: 1,
    explanation: "'그러므로'는 '그래서'의 뜻인 접속부사입니다.",
  },
  {
    q1: "일찍이 깨달았다.",
    q2: "일찌기 깨달았다.",
    answer: 1,
    explanation: "'일찍이'가 올바른 표기입니다.",
  },
  {
    q1: "오랫동안 기다렸다.",
    q2: "오래동안 기다렸다.",
    answer: 1,
    explanation: "'오랫동안'이 올바른 사이시옷 표기입니다.",
  },
  {
    q1: "서슴지 않고 도왔다.",
    q2: "서슴치 않고 도왔다.",
    answer: 1,
    explanation: "'서슴지'가 올바른 표기입니다.",
  },
  {
    q1: "형편없이 망했다.",
    q2: "형편업이 망했다.",
    answer: 1,
    explanation: "'형편없이'가 올바른 표기입니다.",
  },
  {
    q1: "널찍한 운동장에서 놀았다.",
    q2: "널직한 운동장에서 놀았다.",
    answer: 1,
    explanation: "'널찍한'이 올바른 표기입니다.",
  },
  {
    q1: "그 사실을 깨닫다.",
    q2: "그 사실을 깨닿다.",
    answer: 1,
    explanation: "'깨닫다'가 올바른 표기입니다.",
  },
  {
    q1: "연기가 자욱하다.",
    q2: "연기가 자육하다.",
    answer: 1,
    explanation: "'자욱하다'가 올바른 표기입니다.",
  },
  {
    q1: "숙맥이다.",
    q2: "숙맹이다.",
    answer: 1,
    explanation: "'숙맥'이 올바른 표기입니다.",
  },
  {
    q1: "미루나무가 길가에 있다.",
    q2: "미류나무가 길가에 있다.",
    answer: 1,
    explanation: "'미루나무'가 올바른 표기입니다.",
  },
  {
    q1: "삼가 조의를 표합니다.",
    q2: "삼가 조의를 표함니다.",
    answer: 1,
    explanation: "'표합니다'가 올바른 표기입니다.",
  },
  {
    q1: "답변이 궁색하다.",
    q2: "답변이 궁섹하다.",
    answer: 1,
    explanation: "'궁색하다'가 올바른 표기입니다.",
  },
  {
    q1: "어른을 뵙다.",
    q2: "어른을 봽다.",
    answer: 1,
    explanation: "'뵙다'가 올바른 표기입니다.",
  },
  {
    q1: "풋사과가 시다.",
    q2: "풋사과가 씨다.",
    answer: 1,
    explanation: "'시다'가 올바른 표기입니다.",
  },
  {
    q1: "얼마큼 왔을까?",
    q2: "얼마만큼 왔을까?",
    answer: 2,
    explanation: "'얼마만큼'이 올바른 표기입니다.",
  },
  // 신규 40개 (총 60개)
  {
    q1: "과연 그럴까?",
    q2: "과연 그럴가?",
    answer: 1,
    explanation: "'그럴까'가 올바른 표기입니다. 의문형 어미 '-ㄹ까'를 씁니다.",
  },
  {
    q1: "뜻밖에 좋은 소식이 왔다.",
    q2: "뜻밖의 좋은 소식이 왔다.",
    answer: 2,
    explanation: "'뜻밖의'가 올바른 표기입니다. '의'가 맞는 관형격 조사입니다.",
  },
  {
    q1: "사글세를 내다.",
    q2: "삭월세를 내다.",
    answer: 2,
    explanation: "'삭월세'가 올바른 표기입니다.",
  },
  {
    q1: "윗사람에게 예의를 갖추다.",
    q2: "윗사람에게 예의를 갖추다.",
    answer: 1,
    explanation: "'윗사람'은 사이시옷이 들어가는 올바른 표기입니다.",
  },
  {
    q1: "아무튼 열심히 하자.",
    q2: "아뭏든 열심히 하자.",
    answer: 1,
    explanation: "'아무튼'이 올바른 표기입니다.",
  },
  {
    q1: "넉넉히 준비했다.",
    q2: "넉넉이 준비했다.",
    answer: 1,
    explanation: "'ㄱ' 받침 뒤에는 '-히'가 옵니다. '넉넉히'가 맞습니다.",
  },
  {
    q1: "고기를 알맞게 구웠다.",
    q2: "고기를 알맞개 구웠다.",
    answer: 1,
    explanation: "'-게'가 올바른 부사형 어미입니다.",
  },
  {
    q1: "뜻깊은 행사에 참여했다.",
    q2: "뜻기픈 행사에 참여했다.",
    answer: 1,
    explanation: "'뜻깊은'이 올바른 표기입니다.",
  },
  {
    q1: "건강에 이롭다.",
    q2: "건강에 이롲다.",
    answer: 1,
    explanation: "'이롭다'가 올바른 표기입니다.",
  },
  {
    q1: "그릇이 깨졌다.",
    q2: "그릇이 깨젔다.",
    answer: 1,
    explanation: "'깨졌다'가 올바른 표기입니다.",
  },
  {
    q1: "인사말씀 드리겠습니다.",
    q2: "인사말슴 드리겠습니다.",
    answer: 1,
    explanation: "'말씀'이 올바른 표기입니다.",
  },
  {
    q1: "참으로 대단하다.",
    q2: "참으로 대단하따.",
    answer: 1,
    explanation: "'-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "시합에 지고도 담담하다.",
    q2: "시합에 지고도 담담하따.",
    answer: 1,
    explanation: "'담담하다'에서 '-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "힘껏 뛰었다.",
    q2: "힘것 뛰었다.",
    answer: 1,
    explanation: "'힘껏'이 올바른 표기입니다. 된소리 접미사 '-껏'을 씁니다.",
  },
  {
    q1: "맞은편에 약국이 있다.",
    q2: "맞은 편에 약국이 있다.",
    answer: 1,
    explanation: "'맞은편'은 한 단어로 붙여 씁니다.",
  },
  {
    q1: "흔쾌히 수락했다.",
    q2: "흔쾌이 수락했다.",
    answer: 1,
    explanation: "'흔쾌히'가 올바른 표기입니다.",
  },
  {
    q1: "이번 시험은 쉬었다.",
    q2: "이번 시험은 쉬웠다.",
    answer: 1,
    explanation: "'쉬었다'(쉽다의 과거형)가 올바른 표기입니다.",
  },
  {
    q1: "역활을 나누었다.",
    q2: "역할을 나누었다.",
    answer: 2,
    explanation: "'역할'이 올바른 표기입니다. '역활'은 잘못된 표기입니다.",
  },
  {
    q1: "주의를 기울였다.",
    q2: "주의를 기우렸다.",
    answer: 1,
    explanation: "'기울였다'(기울이다의 과거형)가 올바른 표기입니다.",
  },
  {
    q1: "바라건대 평화를 원한다.",
    q2: "바라건데 평화를 원한다.",
    answer: 1,
    explanation: "'바라건대'가 올바른 표기입니다.",
  },
  {
    q1: "선생님께서 칭찬해 주셨다.",
    q2: "선생님게서 칭찬해 주셨다.",
    answer: 1,
    explanation: "'께서'가 올바른 높임 조사입니다.",
  },
  {
    q1: "부모님의 은혜에 감사드린다.",
    q2: "부모님에 은혜에 감사드린다.",
    answer: 1,
    explanation: "'부모님의'에서 '의'가 올바른 소유격 조사입니다.",
  },
  {
    q1: "다름이 아니라 부탁이 있다.",
    q2: "다름이 아니라 부탁이 잇다.",
    answer: 1,
    explanation: "'있다'가 올바른 표기입니다.",
  },
  {
    q1: "일이 틀어졌다.",
    q2: "일이 틀려졌다.",
    answer: 1,
    explanation: "'틀어졌다'가 올바른 표기입니다. '틀다'의 활용형입니다.",
  },
  {
    q1: "그에 대해 잘 안다.",
    q2: "그에 대해 잘 앉다.",
    answer: 1,
    explanation: "'안다'(알다의 활용형)가 올바른 표기입니다.",
  },
  {
    q1: "성적이 떨어졌다.",
    q2: "성적이 떠러졌다.",
    answer: 1,
    explanation: "'떨어졌다'가 올바른 표기입니다.",
  },
  {
    q1: "병이 낫다.",
    q2: "병이 났다.",
    answer: 1,
    explanation:
      "'낫다'(회복되다)가 올바른 표기입니다. '났다'는 '나다'의 과거형입니다.",
  },
  {
    q1: "시간이 됬다.",
    q2: "시간이 됐다.",
    answer: 2,
    explanation: "'됐다'(되었다)가 올바른 표기입니다.",
  },
  {
    q1: "문제를 풀었다.",
    q2: "문제를 풀렀다.",
    answer: 1,
    explanation: "'풀었다'(풀다의 과거형)가 올바른 표기입니다.",
  },
  {
    q1: "안절부절 못했다.",
    q2: "안절부절못했다.",
    answer: 1,
    explanation: "'안절부절'과 '못했다'는 띄어 씁니다.",
  },
  {
    q1: "하마트면 늦을 뻔했다.",
    q2: "하마터면 늦을 뻔했다.",
    answer: 2,
    explanation: "'하마터면'이 올바른 표기입니다.",
  },
  {
    q1: "마치 꿈만 같았다.",
    q2: "맞치 꿈만 같았다.",
    answer: 1,
    explanation: "'마치'가 올바른 표기입니다. '마치 ~처럼'으로 씁니다.",
  },
  {
    q1: "환경을 개선시키다.",
    q2: "환경을 개선하다.",
    answer: 2,
    explanation:
      "'개선하다'가 더 올바른 표현입니다. '-시키다'의 불필요한 사용을 줄입니다.",
  },
  {
    q1: "나름대로 노력했다.",
    q2: "나름데로 노력했다.",
    answer: 1,
    explanation: "'나름대로'가 올바른 표기입니다.",
  },
  {
    q1: "곧이곧대로 말했다.",
    q2: "곧이 곧대로 말했다.",
    answer: 1,
    explanation: "'곧이곧대로'는 붙여 씁니다.",
  },
  {
    q1: "한참 만에 도착했다.",
    q2: "한참 만의 도착했다.",
    answer: 1,
    explanation: "'한참 만에'가 올바른 표기입니다.",
  },
  {
    q1: "어쩔 수 없었다.",
    q2: "어쩔수 없었다.",
    answer: 1,
    explanation: "'어쩔 수 없었다'에서 '수'는 의존명사이므로 띄어 씁니다.",
  },
  {
    q1: "며칠째 비가 내린다.",
    q2: "몇일째 비가 내린다.",
    answer: 1,
    explanation: "'며칠째'가 올바른 표기입니다.",
  },
  {
    q1: "깜짝 놀랐다.",
    q2: "깜작 놀랐다.",
    answer: 1,
    explanation: "'깜짝'이 올바른 표기입니다.",
  },
  {
    q1: "결재를 올리다.",
    q2: "결제를 올리다.",
    answer: 1,
    explanation: "'결재'는 승인을 받는 것이고, '결제'는 돈을 치르는 것입니다.",
  },
];

export const grade4VocabData: VocabEntry[] = [
  // 기존 15개
  { meanings: ["나라를 지키는 사람", "군복을 입어요"], answer: "군인" },
  {
    meanings: ["옛날 물건을 보관하는 곳", "역사를 배울 수 있어요"],
    answer: "박물관",
  },
  {
    meanings: ["전기로 움직이는 기계", "시원한 바람을 만들어요"],
    answer: "선풍기",
  },
  { meanings: ["말이나 글의 뜻", "사전에서 찾아볼 수 있어요"], answer: "의미" },
  {
    meanings: ["다른 사람의 입장에서 생각하는 것", "마음을 이해하는 것"],
    answer: "공감",
  },
  {
    meanings: ["서로 의견을 나누는 것", "결론을 내리기 위해 해요"],
    answer: "토론",
  },
  {
    meanings: ["땅속에서 나오는 뜨거운 물", "몸을 담그면 건강에 좋아요"],
    answer: "온천",
  },
  {
    meanings: ["어떤 일이 일어난 까닭", "왜 그런지 알려주는 것"],
    answer: "원인",
  },
  {
    meanings: ["원인 때문에 생긴 일", "원인 다음에 나타나는 것"],
    answer: "결과",
  },
  { meanings: ["눈에 쓰는 도구", "시력이 나쁠 때 써요"], answer: "안경" },
  {
    meanings: ["나라를 다스리는 기본 법", "가장 높은 법이에요"],
    answer: "헌법",
  },
  { meanings: ["비행기가 뜨고 내리는 곳", "여행할 때 가요"], answer: "공항" },
  { meanings: ["나라와 나라 사이의 관계", "외교라고도 해요"], answer: "국제" },
  { meanings: ["정해진 규칙이나 법", "지켜야 하는 것"], answer: "규칙" },
  {
    meanings: ["물질이 타서 빛과 열을 내는 현상", "불이라고도 해요"],
    answer: "연소",
  },
  // 신규 45개 (총 60개)
  { meanings: ["지구 밖의 넓은 공간", "별이 있는 곳이에요"], answer: "우주" },
  {
    meanings: ["몸의 온도를 재는 도구", "열이 날 때 사용해요"],
    answer: "체온계",
  },
  {
    meanings: ["과거에 있었던 일의 기록", "옛 시대를 알 수 있어요"],
    answer: "역사",
  },
  { meanings: ["투명하고 단단한 물질", "창문에 쓰여요"], answer: "유리" },
  { meanings: ["나라를 대표하는 깃발", "국경일에 걸어요"], answer: "국기" },
  {
    meanings: ["한 해를 네 부분으로 나눈 것", "봄, 여름, 가을, 겨울이에요"],
    answer: "계절",
  },
  { meanings: ["땅이 갈라지는 자연 재해", "건물이 흔들려요"], answer: "지진" },
  {
    meanings: ["어떤 일에 대한 자기 생각", "찬성이나 반대의 ___이에요"],
    answer: "의견",
  },
  {
    meanings: ["새로운 것을 처음 만들어 내는 것", "에디슨은 전구를 ___했어요"],
    answer: "발명",
  },
  {
    meanings: ["여러 나라의 사람들이 모여 사는 곳", "다양한 문화가 있어요"],
    answer: "다문화",
  },
  { meanings: ["생물이 살아가는 자연환경", "보호해야 해요"], answer: "생태계" },
  {
    meanings: ["국민이 뽑는 것", "대통령이나 국회의원을 뽑아요"],
    answer: "선거",
  },
  {
    meanings: ["다수의 의견을 따르는 것", "투표로 결정해요"],
    answer: "민주주의",
  },
  { meanings: ["물건을 만드는 곳", "기계가 많아요"], answer: "공장" },
  { meanings: ["돈을 모아 두는 곳", "통장을 만들어요"], answer: "은행" },
  {
    meanings: ["다른 나라에서 물건을 사 오는 것", "반대말은 수출이에요"],
    answer: "수입",
  },
  {
    meanings: ["우리나라 물건을 다른 나라에 파는 것", "반대말은 수입이에요"],
    answer: "수출",
  },
  {
    meanings: ["자연에서 얻는 쓸 수 있는 것", "석유, 철광석 같은 것이에요"],
    answer: "자원",
  },
  {
    meanings: ["사람이나 물건을 옮기는 것", "버스, 기차, 비행기 등이에요"],
    answer: "교통",
  },
  {
    meanings: ["먹을 수 있는 식물을 기르는 일", "농부가 하는 일이에요"],
    answer: "농업",
  },
  {
    meanings: ["바다에서 물고기를 잡는 일", "어부가 하는 일이에요"],
    answer: "어업",
  },
  { meanings: ["지식을 전달하는 일", "학교에서 이루어져요"], answer: "교육" },
  {
    meanings: ["잘못을 바로잡는 것", "틀린 부분을 고치는 것이에요"],
    answer: "수정",
  },
  {
    meanings: ["어떤 일을 계획적으로 하는 것", "실천이 중요해요"],
    answer: "계획",
  },
  {
    meanings: ["경험이나 지식을 글로 적는 것", "일기도 ___의 한 종류예요"],
    answer: "기록",
  },
  {
    meanings: ["일정한 기준에 따라 나누는 것", "종류별로 ___해요"],
    answer: "분류",
  },
  {
    meanings: ["두 가지 이상을 견주어 보는 것", "차이점을 찾아요"],
    answer: "비교",
  },
  {
    meanings: ["여러 가지를 합치는 것", "하나로 모으는 것이에요"],
    answer: "종합",
  },
  {
    meanings: ["눈으로 자세히 살펴보는 것", "현미경으로 ___해요"],
    answer: "관찰",
  },
  {
    meanings: ["궁금한 것을 알아보기 위해 해 보는 것", "과학 시간에 해요"],
    answer: "실험",
  },
  {
    meanings: ["새로운 사실을 찾아내는 것", "콜럼버스의 신대륙 ___이에요"],
    answer: "발견",
  },
  {
    meanings: ["변화하여 더 좋아지는 것", "과학 기술의 ___이에요"],
    answer: "발전",
  },
  {
    meanings: ["서로 도우며 함께하는 것", "친구와의 ___이 중요해요"],
    answer: "협동",
  },
  {
    meanings: ["자기의 생각을 남에게 알리는 것", "말이나 글로 ___해요"],
    answer: "표현",
  },
  {
    meanings: ["안다는 것, 배워서 아는 것", "학교에서 ___을 쌓아요"],
    answer: "지식",
  },
  {
    meanings: ["사물에 대해 궁금해하는 마음", "___이 많은 아이가 잘 배워요"],
    answer: "호기심",
  },
  {
    meanings: ["약속을 반드시 지키는 것", "___있는 사람이 되자"],
    answer: "신용",
  },
  {
    meanings: ["남을 배려하고 생각하는 마음", "친구에게 ___을 베풀자"],
    answer: "친절",
  },
  {
    meanings: ["잘못을 뉘우치는 것", "___하고 다시는 그러지 않겠다고 다짐해요"],
    answer: "반성",
  },
  {
    meanings: ["힘든 일을 참고 이겨내는 것", "끈기 있게 ___해야 해요"],
    answer: "인내",
  },
  {
    meanings: ["물건이나 돈을 아끼는 것", "낭비의 반대말이에요"],
    answer: "절약",
  },
  {
    meanings: ["다른 사람을 도와주는 것", "어려운 사람에게 ___을 줘요"],
    answer: "도움",
  },
  {
    meanings: ["새로운 것을 찾아내는 것", "탐험과 비슷해요"],
    answer: "탐구",
  },
  {
    meanings: ["스스로 판단하고 행동하는 것", "남에게 의지하지 않아요"],
    answer: "자립",
  },
  {
    meanings: ["여러 사람이 모여 하나의 목표를 이루는 것", "팀워크라고도 해요"],
    answer: "협력",
  },
];

export const grade4MathData: MathEntry[] = [
  // 기존 21개
  {
    type: "calculation",
    expression: "23456 + 34521",
    answer: 57977,
    steps: [
      "일의 자리부터 차례로 더합니다",
      "6+1=7, 5+2=7, 4+5=9, 3+4=7, 2+3=5",
      "답: 57977",
    ],
    unit: "큰 수 덧셈",
  },
  {
    type: "calculation",
    expression: "234 × 12",
    answer: 2808,
    steps: ["234 × 2 = 468", "234 × 10 = 2340", "468 + 2340 = 2808"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "156 × 23",
    answer: 3588,
    steps: ["156 × 3 = 468", "156 × 20 = 3120", "468 + 3120 = 3588"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "345 × 15",
    answer: 5175,
    steps: ["345 × 5 = 1725", "345 × 10 = 3450", "1725 + 3450 = 5175"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "96 ÷ 12",
    answer: 8,
    steps: ["12 × 8 = 96", "96 ÷ 12 = 8"],
    unit: "나눗셈",
    dividend: 96,
    divisor: 12,
    quotient: 8,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "75 ÷ 15",
    answer: 5,
    steps: ["15 × 5 = 75", "75 ÷ 15 = 5"],
    unit: "나눗셈",
    dividend: 75,
    divisor: 15,
    quotient: 5,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "156 ÷ 12",
    answer: 13,
    steps: ["12 × 13 = 156", "156 ÷ 12 = 13"],
    unit: "나눗셈",
    dividend: 156,
    divisor: 12,
    quotient: 13,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "89 ÷ 7",
    answer: 12,
    steps: ["7 × 12 = 84", "89 - 84 = 5", "89 ÷ 7 = 12 나머지 5"],
    unit: "나머지가 있는 나눗셈",
    dividend: 89,
    divisor: 7,
    quotient: 12,
    remainder: 5,
  },
  {
    type: "calculation",
    expression: "3/8 + 2/8",
    answer: 5,
    steps: ["분모가 같으므로 분자끼리 더합니다", "3 + 2 = 5", "답: 5/8"],
    unit: "분수 덧셈",
    numbers: [3, 8, 2, 8],
  },
  {
    type: "calculation",
    expression: "5/6 - 2/6",
    answer: 3,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "5 - 2 = 3", "답: 3/6 = 1/2"],
    unit: "분수 뺄셈",
    numbers: [5, 6, 2, 6],
  },
  {
    type: "calculation",
    expression: "7/10 + 4/10",
    answer: 11,
    steps: [
      "분모가 같으므로 분자끼리 더합니다",
      "7 + 4 = 11",
      "답: 11/10 = 1과 1/10",
    ],
    unit: "분수 덧셈",
    numbers: [7, 10, 4, 10],
  },
  {
    type: "calculation",
    expression: "2.5 + 1.3",
    answer: 3.8,
    steps: [
      "소수점을 맞춰 더합니다",
      "5 + 3 = 8 (소수 첫째 자리)",
      "2 + 1 = 3 (일의 자리)",
      "답: 3.8",
    ],
    unit: "소수 덧셈",
  },
  {
    type: "calculation",
    expression: "4.7 - 2.3",
    answer: 2.4,
    steps: [
      "소수점을 맞춰 뺍니다",
      "7 - 3 = 4 (소수 첫째 자리)",
      "4 - 2 = 2 (일의 자리)",
      "답: 2.4",
    ],
    unit: "소수 뺄셈",
  },
  {
    type: "calculation",
    expression: "180 - 60 - 70",
    answer: 50,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 60 - 70 = 50",
      "나머지 한 각은 50°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "360 - 90 - 90 - 90",
    answer: 90,
    steps: [
      "사각형의 네 각의 합은 360°",
      "360 - 90 - 90 - 90 = 90",
      "나머지 한 각은 90°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "24 + 36 × 2",
    answer: 96,
    steps: ["곱셈을 먼저 계산합니다", "36 × 2 = 72", "24 + 72 = 96"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "(15 + 25) × 3",
    answer: 120,
    steps: ["괄호 안을 먼저 계산합니다", "15 + 25 = 40", "40 × 3 = 120"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "100 - 48 ÷ 6",
    answer: 92,
    steps: ["나눗셈을 먼저 계산합니다", "48 ÷ 6 = 8", "100 - 8 = 92"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "3.6 + 2.8",
    answer: 6.4,
    steps: [
      "6 + 8 = 14, 소수 첫째 자리 4, 받아올림 1",
      "3 + 2 + 1 = 6 (일의 자리)",
      "답: 6.4",
    ],
    unit: "소수 덧셈",
  },
  {
    type: "calculation",
    expression: "5.2 - 1.7",
    answer: 3.5,
    steps: [
      "2에서 7을 뺄 수 없으므로 받아내림",
      "12 - 7 = 5 (소수 첫째 자리)",
      "4 - 1 = 3 (일의 자리)",
      "답: 3.5",
    ],
    unit: "소수 뺄셈",
  },
  // 신규 59개 (총 80개)
  // 큰 수 덧셈/뺄셈 추가
  {
    type: "calculation",
    expression: "45678 + 23456",
    answer: 69134,
    steps: [
      "일의 자리부터 차례로 더합니다",
      "8+6=14, 받아올림 1",
      "7+5+1=13, 받아올림 1",
      "6+4+1=11, 받아올림 1",
      "5+3+1=9, 4+2=6",
      "답: 69134",
    ],
    unit: "큰 수 덧셈",
  },
  {
    type: "calculation",
    expression: "87654 - 32178",
    answer: 55476,
    steps: [
      "일의 자리부터 차례로 뺍니다",
      "4-8: 받아내림, 14-8=6",
      "5-7: 받아내림, 15-7-1=7",
      "6-1=5 (받아내림 후 조정)",
      "7-2=5",
      "8-3=5",
      "답: 55476",
    ],
    unit: "큰 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "50000 - 12345",
    answer: 37655,
    steps: [
      "0에서 5를 뺄 수 없으므로 연속 받아내림",
      "10-5=5, 9-4=5, 9-3=6, 9-2=7, 4-1=3",
      "답: 37655",
    ],
    unit: "큰 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "36789 + 45321",
    answer: 82110,
    steps: [
      "9+1=10, 받아올림 1",
      "8+2+1=11, 받아올림 1",
      "7+3+1=11, 받아올림 1",
      "6+5+1=12, 받아올림 1",
      "3+4+1=8",
      "답: 82110",
    ],
    unit: "큰 수 덧셈",
  },
  // 세 자리 × 두 자리 곱셈 추가
  {
    type: "calculation",
    expression: "213 × 14",
    answer: 2982,
    steps: ["213 × 4 = 852", "213 × 10 = 2130", "852 + 2130 = 2982"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "327 × 21",
    answer: 6867,
    steps: ["327 × 1 = 327", "327 × 20 = 6540", "327 + 6540 = 6867"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "456 × 13",
    answer: 5928,
    steps: ["456 × 3 = 1368", "456 × 10 = 4560", "1368 + 4560 = 5928"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "189 × 32",
    answer: 6048,
    steps: ["189 × 2 = 378", "189 × 30 = 5670", "378 + 5670 = 6048"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "275 × 24",
    answer: 6600,
    steps: ["275 × 4 = 1100", "275 × 20 = 5500", "1100 + 5500 = 6600"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "418 × 16",
    answer: 6688,
    steps: ["418 × 6 = 2508", "418 × 10 = 4180", "2508 + 4180 = 6688"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "362 × 25",
    answer: 9050,
    steps: ["362 × 5 = 1810", "362 × 20 = 7240", "1810 + 7240 = 9050"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "504 × 18",
    answer: 9072,
    steps: ["504 × 8 = 4032", "504 × 10 = 5040", "4032 + 5040 = 9072"],
    unit: "곱셈",
  },
  // 나눗셈 추가
  {
    type: "calculation",
    expression: "144 ÷ 12",
    answer: 12,
    steps: ["12 × 12 = 144", "144 ÷ 12 = 12"],
    unit: "나눗셈",
    dividend: 144,
    divisor: 12,
    quotient: 12,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "225 ÷ 15",
    answer: 15,
    steps: ["15 × 15 = 225", "225 ÷ 15 = 15"],
    unit: "나눗셈",
    dividend: 225,
    divisor: 15,
    quotient: 15,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "336 ÷ 14",
    answer: 24,
    steps: ["14 × 24 = 336", "336 ÷ 14 = 24"],
    unit: "나눗셈",
    dividend: 336,
    divisor: 14,
    quotient: 24,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "468 ÷ 18",
    answer: 26,
    steps: ["18 × 26 = 468", "468 ÷ 18 = 26"],
    unit: "나눗셈",
    dividend: 468,
    divisor: 18,
    quotient: 26,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "504 ÷ 21",
    answer: 24,
    steps: ["21 × 24 = 504", "504 ÷ 21 = 24"],
    unit: "나눗셈",
    dividend: 504,
    divisor: 21,
    quotient: 24,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "175 ÷ 25",
    answer: 7,
    steps: ["25 × 7 = 175", "175 ÷ 25 = 7"],
    unit: "나눗셈",
    dividend: 175,
    divisor: 25,
    quotient: 7,
    remainder: 0,
  },
  // 나머지 있는 나눗셈 추가
  {
    type: "calculation",
    expression: "100 ÷ 13",
    answer: 7,
    steps: ["13 × 7 = 91", "100 - 91 = 9", "100 ÷ 13 = 7 나머지 9"],
    unit: "나머지가 있는 나눗셈",
    dividend: 100,
    divisor: 13,
    quotient: 7,
    remainder: 9,
  },
  {
    type: "calculation",
    expression: "200 ÷ 17",
    answer: 11,
    steps: ["17 × 11 = 187", "200 - 187 = 13", "200 ÷ 17 = 11 나머지 13"],
    unit: "나머지가 있는 나눗셈",
    dividend: 200,
    divisor: 17,
    quotient: 11,
    remainder: 13,
  },
  {
    type: "calculation",
    expression: "150 ÷ 11",
    answer: 13,
    steps: ["11 × 13 = 143", "150 - 143 = 7", "150 ÷ 11 = 13 나머지 7"],
    unit: "나머지가 있는 나눗셈",
    dividend: 150,
    divisor: 11,
    quotient: 13,
    remainder: 7,
  },
  {
    type: "calculation",
    expression: "250 ÷ 16",
    answer: 15,
    steps: ["16 × 15 = 240", "250 - 240 = 10", "250 ÷ 16 = 15 나머지 10"],
    unit: "나머지가 있는 나눗셈",
    dividend: 250,
    divisor: 16,
    quotient: 15,
    remainder: 10,
  },
  {
    type: "calculation",
    expression: "300 ÷ 23",
    answer: 13,
    steps: ["23 × 13 = 299", "300 - 299 = 1", "300 ÷ 23 = 13 나머지 1"],
    unit: "나머지가 있는 나눗셈",
    dividend: 300,
    divisor: 23,
    quotient: 13,
    remainder: 1,
  },
  // 분수 추가
  {
    type: "calculation",
    expression: "4/9 + 3/9",
    answer: 7,
    steps: ["분모가 같으므로 분자끼리 더합니다", "4 + 3 = 7", "답: 7/9"],
    unit: "분수 덧셈",
    numbers: [4, 9, 3, 9],
  },
  {
    type: "calculation",
    expression: "8/12 - 5/12",
    answer: 3,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "8 - 5 = 3", "답: 3/12 = 1/4"],
    unit: "분수 뺄셈",
    numbers: [8, 12, 5, 12],
  },
  {
    type: "calculation",
    expression: "5/7 + 4/7",
    answer: 9,
    steps: [
      "분모가 같으므로 분자끼리 더합니다",
      "5 + 4 = 9",
      "답: 9/7 = 1과 2/7",
    ],
    unit: "분수 덧셈",
    numbers: [5, 7, 4, 7],
  },
  {
    type: "calculation",
    expression: "9/10 - 3/10",
    answer: 6,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "9 - 3 = 6", "답: 6/10 = 3/5"],
    unit: "분수 뺄셈",
    numbers: [9, 10, 3, 10],
  },
  {
    type: "calculation",
    expression: "6/8 + 5/8",
    answer: 11,
    steps: [
      "분모가 같으므로 분자끼리 더합니다",
      "6 + 5 = 11",
      "답: 11/8 = 1과 3/8",
    ],
    unit: "분수 덧셈",
    numbers: [6, 8, 5, 8],
  },
  {
    type: "calculation",
    expression: "7/11 - 2/11",
    answer: 5,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "7 - 2 = 5", "답: 5/11"],
    unit: "분수 뺄셈",
    numbers: [7, 11, 2, 11],
  },
  {
    type: "calculation",
    expression: "3/5 + 4/5",
    answer: 7,
    steps: [
      "분모가 같으므로 분자끼리 더합니다",
      "3 + 4 = 7",
      "답: 7/5 = 1과 2/5",
    ],
    unit: "분수 덧셈",
    numbers: [3, 5, 4, 5],
  },
  {
    type: "calculation",
    expression: "11/15 - 4/15",
    answer: 7,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "11 - 4 = 7", "답: 7/15"],
    unit: "분수 뺄셈",
    numbers: [11, 15, 4, 15],
  },
  // 소수 추가
  {
    type: "calculation",
    expression: "1.5 + 2.7",
    answer: 4.2,
    steps: [
      "5 + 7 = 12, 소수 첫째 자리 2, 받아올림 1",
      "1 + 2 + 1 = 4 (일의 자리)",
      "답: 4.2",
    ],
    unit: "소수 덧셈",
  },
  {
    type: "calculation",
    expression: "6.3 - 2.8",
    answer: 3.5,
    steps: [
      "3에서 8을 뺄 수 없으므로 받아내림",
      "13 - 8 = 5 (소수 첫째 자리)",
      "5 - 2 = 3 (일의 자리)",
      "답: 3.5",
    ],
    unit: "소수 뺄셈",
  },
  {
    type: "calculation",
    expression: "4.25 + 3.18",
    answer: 7.43,
    steps: [
      "5 + 8 = 13, 소수 둘째 자리 3, 받아올림 1",
      "2 + 1 + 1 = 4 (소수 첫째 자리)",
      "4 + 3 = 7 (일의 자리)",
      "답: 7.43",
    ],
    unit: "소수 덧셈",
  },
  {
    type: "calculation",
    expression: "8.52 - 3.67",
    answer: 4.85,
    steps: [
      "2에서 7을 뺄 수 없으므로 받아내림",
      "12 - 7 = 5 (소수 둘째 자리)",
      "4에서 6을 뺄 수 없으므로 받아내림",
      "14 - 6 = 8 (소수 첫째 자리)",
      "7 - 3 = 4 (일의 자리)",
      "답: 4.85",
    ],
    unit: "소수 뺄셈",
  },
  {
    type: "calculation",
    expression: "0.5 + 0.8",
    answer: 1.3,
    steps: [
      "5 + 8 = 13, 소수 첫째 자리 3, 받아올림 1",
      "0 + 0 + 1 = 1 (일의 자리)",
      "답: 1.3",
    ],
    unit: "소수 덧셈",
  },
  {
    type: "calculation",
    expression: "3.0 - 1.4",
    answer: 1.6,
    steps: [
      "0에서 4를 뺄 수 없으므로 받아내림",
      "10 - 4 = 6 (소수 첫째 자리)",
      "2 - 1 = 1 (일의 자리)",
      "답: 1.6",
    ],
    unit: "소수 뺄셈",
  },
  // 각도 추가
  {
    type: "calculation",
    expression: "180 - 45 - 90",
    answer: 45,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 45 - 90 = 45",
      "나머지 한 각은 45°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "180 - 30 - 80",
    answer: 70,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 30 - 80 = 70",
      "나머지 한 각은 70°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "180 - 55 - 55",
    answer: 70,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 55 - 55 = 70",
      "나머지 한 각은 70°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "180 - 90 - 35",
    answer: 55,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 90 - 35 = 55",
      "나머지 한 각은 55°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "360 - 120 - 80 - 70",
    answer: 90,
    steps: [
      "사각형의 네 각의 합은 360°",
      "360 - 120 - 80 - 70 = 90",
      "나머지 한 각은 90°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "360 - 100 - 100 - 80",
    answer: 80,
    steps: [
      "사각형의 네 각의 합은 360°",
      "360 - 100 - 100 - 80 = 80",
      "나머지 한 각은 80°",
    ],
    unit: "각도",
  },
  {
    type: "calculation",
    expression: "180 - 60 - 60",
    answer: 60,
    steps: [
      "삼각형의 세 각의 합은 180°",
      "180 - 60 - 60 = 60",
      "정삼각형: 세 각이 모두 60°",
    ],
    unit: "각도",
  },
  // 혼합 계산 추가
  {
    type: "calculation",
    expression: "50 - 4 × 8",
    answer: 18,
    steps: ["곱셈을 먼저 계산합니다", "4 × 8 = 32", "50 - 32 = 18"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "(20 - 8) × 5",
    answer: 60,
    steps: ["괄호 안을 먼저 계산합니다", "20 - 8 = 12", "12 × 5 = 60"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "72 ÷ 8 + 15",
    answer: 24,
    steps: ["나눗셈을 먼저 계산합니다", "72 ÷ 8 = 9", "9 + 15 = 24"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "36 ÷ (3 + 6)",
    answer: 4,
    steps: ["괄호 안을 먼저 계산합니다", "3 + 6 = 9", "36 ÷ 9 = 4"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "5 × 6 + 3 × 4",
    answer: 42,
    steps: [
      "곱셈을 먼저 계산합니다",
      "5 × 6 = 30",
      "3 × 4 = 12",
      "30 + 12 = 42",
    ],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "80 - (12 + 8) × 3",
    answer: 20,
    steps: [
      "괄호 안을 먼저 계산합니다",
      "12 + 8 = 20",
      "20 × 3 = 60",
      "80 - 60 = 20",
    ],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "(100 - 64) ÷ 4",
    answer: 9,
    steps: ["괄호 안을 먼저 계산합니다", "100 - 64 = 36", "36 ÷ 4 = 9"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "15 × 4 - 72 ÷ 9",
    answer: 52,
    steps: [
      "곱셈과 나눗셈을 먼저 계산합니다",
      "15 × 4 = 60",
      "72 ÷ 9 = 8",
      "60 - 8 = 52",
    ],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "2 × (30 + 20) - 45",
    answer: 55,
    steps: [
      "괄호 안을 먼저 계산합니다",
      "30 + 20 = 50",
      "2 × 50 = 100",
      "100 - 45 = 55",
    ],
    unit: "혼합 계산",
  },
  // 곱셈 추가
  {
    type: "calculation",
    expression: "125 × 32",
    answer: 4000,
    steps: ["125 × 2 = 250", "125 × 30 = 3750", "250 + 3750 = 4000"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "248 × 15",
    answer: 3720,
    steps: ["248 × 5 = 1240", "248 × 10 = 2480", "1240 + 2480 = 3720"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "673 × 11",
    answer: 7403,
    steps: ["673 × 1 = 673", "673 × 10 = 6730", "673 + 6730 = 7403"],
    unit: "곱셈",
  },
  // 큰 수 응용
  {
    type: "calculation",
    expression: "10000 - 3456",
    answer: 6544,
    steps: [
      "0에서 6을 뺄 수 없으므로 연속 받아내림",
      "10-6=4, 9-5=4, 9-4=5, 9-3=6",
      "답: 6544",
    ],
    unit: "큰 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "72000 + 18500",
    answer: 90500,
    steps: [
      "0+0=0, 0+0=0, 0+5=5",
      "2+8=10, 받아올림 1",
      "7+1+1=9",
      "답: 90500",
    ],
    unit: "큰 수 덧셈",
  },
  {
    type: "calculation",
    expression: "99999 - 11111",
    answer: 88888,
    steps: ["9-1=8 (각 자리)", "답: 88888"],
    unit: "큰 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "396 × 17",
    answer: 6732,
    steps: ["396 × 7 = 2772", "396 × 10 = 3960", "2772 + 3960 = 6732"],
    unit: "곱셈",
  },
];

export const grade4KnowledgeData: KnowledgeEntry[] = [
  // 기존 15개
  {
    text: "우리나라 최초의 금속활자 인쇄본은 ___이다.",
    answer: "직지심체요절",
    category: "역사",
  },
  {
    text: "한반도의 가장 높은 산은 ___이다.",
    answer: "백두산",
    category: "지리",
  },
  {
    text: "식물의 꽃가루를 옮기는 역할을 하는 곤충은 ___이다.",
    answer: "벌",
    category: "과학",
  },
  {
    text: "지구가 태양을 한 바퀴 도는 데 걸리는 시간은 약 ___일이다.",
    answer: "365",
    category: "과학",
  },
  {
    text: "우리나라 행정구역 중 특별시는 ___이다.",
    answer: "서울",
    category: "사회",
  },
  { text: "삼각형의 세 각의 합은 ___도이다.", answer: "180", category: "수학" },
  {
    text: "혈액 속에서 산소를 운반하는 것은 ___이다.",
    answer: "적혈구",
    category: "과학",
  },
  {
    text: "임진왜란 때 거북선을 만든 사람은 ___이다.",
    answer: "이순신",
    category: "역사",
  },
  {
    text: "자전은 지구가 ___을 중심으로 도는 것이다.",
    answer: "자전축",
    category: "과학",
  },
  { text: "사각형의 네 각의 합은 ___도이다.", answer: "360", category: "수학" },
  {
    text: "물이 증발하여 하늘로 올라가 만들어지는 것은 ___이다.",
    answer: "구름",
    category: "과학",
  },
  {
    text: "우리나라의 전통 집을 ___이라 한다.",
    answer: "한옥",
    category: "문화",
  },
  {
    text: "뼈와 뼈가 만나는 곳을 ___이라 한다.",
    answer: "관절",
    category: "과학",
  },
  { text: "조선을 세운 사람은 ___이다.", answer: "이성계", category: "역사" },
  { text: "소리의 빠르기를 ___이라 한다.", answer: "음속", category: "과학" },
  // 신규 45개 (총 60개)
  {
    text: "빛이 물에서 공기로 나갈 때 꺾이는 현상을 ___이라 한다.",
    answer: "굴절",
    category: "과학",
  },
  {
    text: "지구가 하루에 한 바퀴 도는 것을 ___이라 한다.",
    answer: "자전",
    category: "과학",
  },
  {
    text: "지구가 1년에 태양을 한 바퀴 도는 것을 ___이라 한다.",
    answer: "공전",
    category: "과학",
  },
  {
    text: "달의 모양이 변하는 것을 달의 ___라 한다.",
    answer: "위상 변화",
    category: "과학",
  },
  {
    text: "태양계에서 가장 큰 행성은 ___이다.",
    answer: "목성",
    category: "과학",
  },
  {
    text: "태양계에서 고리가 있는 행성은 ___이다.",
    answer: "토성",
    category: "과학",
  },
  {
    text: "한반도를 가장 긴 강은 ___이다.",
    answer: "압록강",
    category: "지리",
  },
  {
    text: "남한에서 가장 긴 강은 ___이다.",
    answer: "낙동강",
    category: "지리",
  },
  {
    text: "우리나라 면적이 가장 큰 도는 ___이다.",
    answer: "경상북도",
    category: "지리",
  },
  {
    text: "세종대왕이 만든 측우기는 ___를 재는 도구이다.",
    answer: "강수량",
    category: "역사",
  },
  { text: "독도는 ___도에 속한다.", answer: "경상북", category: "지리" },
  {
    text: "우리나라의 전통 음악을 ___이라 한다.",
    answer: "국악",
    category: "문화",
  },
  {
    text: "우리나라의 전통 춤을 ___이라 한다.",
    answer: "한국 무용",
    category: "문화",
  },
  {
    text: "전기를 만드는 자연의 힘에는 수력, 풍력, ___력이 있다.",
    answer: "태양",
    category: "과학",
  },
  {
    text: "식물이 번식하기 위해 만드는 것은 ___이다.",
    answer: "씨앗",
    category: "과학",
  },
  {
    text: "소금은 바닷물을 ___시켜서 얻는다.",
    answer: "증발",
    category: "과학",
  },
  {
    text: "암석이 오랜 시간 부서져 만들어진 것을 ___이라 한다.",
    answer: "흙",
    category: "과학",
  },
  {
    text: "화석은 옛날 ___의 흔적이 돌에 남은 것이다.",
    answer: "생물",
    category: "과학",
  },
  {
    text: "조선 시대 신분 제도에서 가장 높은 계층은 ___이다.",
    answer: "양반",
    category: "역사",
  },
  { text: "고려를 세운 사람은 ___이다.", answer: "왕건", category: "역사" },
  {
    text: "고려 시대에 만들어진 우리나라 도자기를 ___이라 한다.",
    answer: "청자",
    category: "역사",
  },
  {
    text: "조선 시대 도자기를 ___이라 한다.",
    answer: "백자",
    category: "역사",
  },
  {
    text: "광합성에서 식물이 내보내는 기체는 ___이다.",
    answer: "산소",
    category: "과학",
  },
  {
    text: "물의 순환 과정은 증발 → 응결 → ___ → 증발이다.",
    answer: "강수",
    category: "과학",
  },
  {
    text: "우리나라 제주도에 있는 세계자연유산은 ___이다.",
    answer: "한라산",
    category: "지리",
  },
  { text: "소리는 ___을 통해 전달된다.", answer: "매질", category: "과학" },
  { text: "전기가 흐르는 길을 ___라 한다.", answer: "회로", category: "과학" },
  {
    text: "전기가 잘 흐르는 물질을 ___체라 한다.",
    answer: "도",
    category: "과학",
  },
  {
    text: "전기가 잘 흐르지 않는 물질을 ___체라 한다.",
    answer: "부도",
    category: "과학",
  },
  {
    text: "지구 표면의 약 30%를 차지하는 것은 ___이다.",
    answer: "육지",
    category: "과학",
  },
  {
    text: "별들이 모여 있는 모양을 ___이라 한다.",
    answer: "별자리",
    category: "과학",
  },
  {
    text: "북쪽 하늘에서 항상 볼 수 있는 별자리는 ___이다.",
    answer: "북두칠성",
    category: "과학",
  },
  {
    text: "무역에서 수출이 수입보다 많은 것을 ___이라 한다.",
    answer: "무역 흑자",
    category: "사회",
  },
  {
    text: "1만 원 지폐에 있는 인물은 ___이다.",
    answer: "세종대왕",
    category: "사회",
  },
  {
    text: "5만 원 지폐에 있는 인물은 ___이다.",
    answer: "신사임당",
    category: "사회",
  },
  {
    text: "5천 원 지폐에 있는 인물은 ___이다.",
    answer: "율곡 이이",
    category: "사회",
  },
  {
    text: "천 원 지폐에 있는 인물은 ___이다.",
    answer: "퇴계 이황",
    category: "사회",
  },
  {
    text: "온도계에서 사용하는 단위는 ___이다.",
    answer: "도(°C)",
    category: "과학",
  },
  {
    text: "체온이 37.5도 이상이면 ___이 있다고 한다.",
    answer: "열",
    category: "과학",
  },
  {
    text: "다각형 중 변이 5개인 것을 ___이라 한다.",
    answer: "오각형",
    category: "수학",
  },
  {
    text: "다각형 중 변이 6개인 것을 ___이라 한다.",
    answer: "육각형",
    category: "수학",
  },
  {
    text: "직선이 만나서 생기는 꼭짓점의 각도가 90도인 각을 ___이라 한다.",
    answer: "직각",
    category: "수학",
  },
  {
    text: "90도보다 작은 각을 ___이라 한다.",
    answer: "예각",
    category: "수학",
  },
  { text: "90도보다 큰 각을 ___이라 한다.", answer: "둔각", category: "수학" },
  { text: "훈민정음은 ___년에 반포되었다.", answer: "1446", category: "역사" },
];

export const grade4SafetyData: SafetyEntry[] = [
  // 기존 10개
  {
    text: "인터넷에서 모르는 사람이 만나자고 하면 ___해야 한다.",
    answer: "거절",
    category: "정보안전",
  },
  {
    text: "사이버 폭력을 당하면 ___을 남기고 신고한다.",
    answer: "증거",
    category: "정보안전",
  },
  {
    text: "실험할 때는 반드시 ___을 착용한다.",
    answer: "보안경",
    category: "실험안전",
  },
  {
    text: "비상시 학교에서는 ___에 따라 대피한다.",
    answer: "대피 경로",
    category: "재난안전",
  },
  {
    text: "전기 제품이 물에 젖으면 ___가 날 수 있다.",
    answer: "감전 사고",
    category: "전기안전",
  },
  {
    text: "여름철 무더위에는 ___을 충분히 마셔야 한다.",
    answer: "물",
    category: "건강안전",
  },
  {
    text: "가정에서 ___기를 사용하면 화재를 조기에 발견할 수 있다.",
    answer: "화재 감지",
    category: "화재안전",
  },
  {
    text: "자전거를 탈 때 야간에는 ___을 켜야 한다.",
    answer: "전조등",
    category: "교통안전",
  },
  {
    text: "식중독을 예방하려면 음식을 충분히 ___해서 먹는다.",
    answer: "익혀",
    category: "건강안전",
  },
  {
    text: "지진 시 엘리베이터 대신 ___를 이용한다.",
    answer: "계단",
    category: "재난안전",
  },
  // 신규 30개 (총 40개)
  {
    text: "비밀번호는 ___와 숫자를 섞어 만들면 안전하다.",
    answer: "문자",
    category: "정보안전",
  },
  {
    text: "과학 실험에서 화학 약품을 다룰 때는 ___을 착용한다.",
    answer: "장갑",
    category: "실험안전",
  },
  {
    text: "실험 후 사용한 약품은 ___에 따라 처리한다.",
    answer: "지침",
    category: "실험안전",
  },
  {
    text: "횡단보도가 없는 곳에서는 길을 ___하면 안 된다.",
    answer: "건너",
    category: "교통안전",
  },
  {
    text: "교통사고가 나면 ___에 신고한다.",
    answer: "112",
    category: "교통안전",
  },
  {
    text: "화재 시 젖은 수건으로 ___를 막고 대피한다.",
    answer: "코와 입",
    category: "화재안전",
  },
  {
    text: "소화기 사용 순서는 안전핀 빼기 → 호스 잡기 → ___이다.",
    answer: "손잡이 누르기",
    category: "화재안전",
  },
  {
    text: "태풍이 올 때 밖에 있는 물건은 ___으로 옮긴다.",
    answer: "실내",
    category: "재난안전",
  },
  {
    text: "폭설 시에는 ___을 예방하기 위해 모래나 소금을 뿌린다.",
    answer: "미끄러짐",
    category: "재난안전",
  },
  {
    text: "온라인 게임에서 개인정보를 요구하면 ___해야 한다.",
    answer: "거부",
    category: "정보안전",
  },
  {
    text: "인터넷에서 허위 정보를 퍼뜨리는 것을 ___이라 한다.",
    answer: "가짜 뉴스",
    category: "정보안전",
  },
  {
    text: "응급처치에서 심장이 멈췄을 때 하는 것은 ___이다.",
    answer: "심폐소생술",
    category: "건강안전",
  },
  {
    text: "코피가 나면 고개를 ___으로 숙이고 코를 잡는다.",
    answer: "앞",
    category: "건강안전",
  },
  {
    text: "화상을 입으면 ___에 15분 이상 식혀야 한다.",
    answer: "흐르는 물",
    category: "건강안전",
  },
  {
    text: "캠핑 시 텐트는 ___가에서 떨어진 곳에 설치한다.",
    answer: "물",
    category: "생활안전",
  },
  {
    text: "등산할 때는 ___을 벗어나지 않는다.",
    answer: "등산로",
    category: "생활안전",
  },
  {
    text: "수영할 때 ___을 한 후에 물에 들어간다.",
    answer: "준비 운동",
    category: "생활안전",
  },
  {
    text: "전기 콘센트에 ___를 너무 많이 꽂으면 위험하다.",
    answer: "멀티탭",
    category: "전기안전",
  },
  {
    text: "번개가 칠 때 ___가 있는 곳으로 대피한다.",
    answer: "건물",
    category: "재난안전",
  },
  {
    text: "황사가 심한 날에는 ___를 착용한다.",
    answer: "마스크",
    category: "건강안전",
  },
  {
    text: "학교에서 비상벨이 울리면 ___의 지시를 따른다.",
    answer: "선생님",
    category: "학교안전",
  },
  {
    text: "놀이기구를 탈 때는 ___벨트를 반드시 맨다.",
    answer: "안전",
    category: "생활안전",
  },
  {
    text: "자전거를 타기 전에 ___가 잘 되는지 확인한다.",
    answer: "브레이크",
    category: "교통안전",
  },
  {
    text: "급식실에서 뜨거운 국을 옮길 때는 ___히 걸어야 한다.",
    answer: "천천",
    category: "학교안전",
  },
  {
    text: "인터넷에서 의심스러운 링크를 ___하면 안 된다.",
    answer: "클릭",
    category: "정보안전",
  },
  {
    text: "미세먼지 농도가 '매우 나쁨'이면 ___에서 활동한다.",
    answer: "실내",
    category: "건강안전",
  },
  {
    text: "엘리베이터에 갇히면 ___를 울리고 구조를 기다린다.",
    answer: "비상벨",
    category: "생활안전",
  },
  {
    text: "운동 전에는 반드시 ___을 해야 부상을 예방할 수 있다.",
    answer: "스트레칭",
    category: "건강안전",
  },
  {
    text: "가스레인지 사용 후에는 ___를 반드시 잠근다.",
    answer: "밸브",
    category: "화재안전",
  },
  {
    text: "물에 빠진 사람을 보면 직접 구하지 말고 ___에 신고한다.",
    answer: "119",
    category: "생활안전",
  },
];

export const grade4HanjaData: HanjaEntry[] = [
  // 기존 15개
  {
    character: "學",
    reading: "학",
    meaning: "배울 학",
    strokes: 16,
    words: ["학교", "학생", "학습"],
    sentence: "學問에 힘쓰자.",
  },
  {
    character: "校",
    reading: "교",
    meaning: "학교 교",
    strokes: 10,
    words: ["학교", "교실", "교장"],
    sentence: "學校에 매일 간다.",
  },
  {
    character: "先",
    reading: "선",
    meaning: "먼저 선",
    strokes: 6,
    words: ["선생", "선배", "우선"],
    sentence: "先生님께 인사했다.",
  },
  {
    character: "生",
    reading: "생",
    meaning: "날 생",
    strokes: 5,
    words: ["생일", "학생", "생활"],
    sentence: "生日 축하합니다.",
  },
  {
    character: "父",
    reading: "부",
    meaning: "아버지 부",
    strokes: 4,
    words: ["부모", "조부", "부친"],
    sentence: "父母님의 은혜에 감사한다.",
  },
  {
    character: "母",
    reading: "모",
    meaning: "어머니 모",
    strokes: 5,
    words: ["모친", "부모", "조모"],
    sentence: "母의 사랑은 바다와 같다.",
  },
  {
    character: "王",
    reading: "왕",
    meaning: "임금 왕",
    strokes: 4,
    words: ["왕국", "국왕", "여왕"],
    sentence: "세종대王은 한글을 만들었다.",
  },
  {
    character: "國",
    reading: "국",
    meaning: "나라 국",
    strokes: 11,
    words: ["국가", "한국", "국기"],
    sentence: "대한민國 만세!",
  },
  {
    character: "民",
    reading: "민",
    meaning: "백성 민",
    strokes: 5,
    words: ["국민", "시민", "민주"],
    sentence: "國民의 의무를 다하자.",
  },
  {
    character: "花",
    reading: "화",
    meaning: "꽃 화",
    strokes: 8,
    words: ["꽃", "화분", "개화"],
    sentence: "봄에 花가 피었다.",
  },
  {
    character: "草",
    reading: "초",
    meaning: "풀 초",
    strokes: 10,
    words: ["풀밭", "초원", "잡초"],
    sentence: "草원에서 뛰어놀았다.",
  },
  {
    character: "春",
    reading: "춘",
    meaning: "봄 춘",
    strokes: 9,
    words: ["춘분", "입춘", "청춘"],
    sentence: "春이 되면 꽃이 핀다.",
  },
  {
    character: "夏",
    reading: "하",
    meaning: "여름 하",
    strokes: 10,
    words: ["하계", "초여름", "하절기"],
    sentence: "夏에는 바다에 간다.",
  },
  {
    character: "秋",
    reading: "추",
    meaning: "가을 추",
    strokes: 9,
    words: ["추분", "만추", "추석"],
    sentence: "秋에는 단풍이 아름답다.",
  },
  {
    character: "冬",
    reading: "동",
    meaning: "겨울 동",
    strokes: 5,
    words: ["동계", "동지", "동절기"],
    sentence: "冬에는 눈이 온다.",
  },
  // 신규 45개 (총 60개)
  {
    character: "敎",
    reading: "교",
    meaning: "가르칠 교",
    strokes: 11,
    words: ["교육", "교사", "종교"],
    sentence: "敎育은 나라의 근본이다.",
  },
  {
    character: "室",
    reading: "실",
    meaning: "집 실",
    strokes: 9,
    words: ["교실", "실내", "실험실"],
    sentence: "敎室에서 공부한다.",
  },
  {
    character: "文",
    reading: "문",
    meaning: "글월 문",
    strokes: 4,
    words: ["문학", "문화", "작문"],
    sentence: "文學을 사랑한다.",
  },
  {
    character: "字",
    reading: "자",
    meaning: "글자 자",
    strokes: 6,
    words: ["문자", "글자", "한자"],
    sentence: "漢字를 배우자.",
  },
  {
    character: "書",
    reading: "서",
    meaning: "글 서",
    strokes: 10,
    words: ["서점", "도서", "서예"],
    sentence: "圖書館에서 책을 빌렸다.",
  },
  {
    character: "讀",
    reading: "독",
    meaning: "읽을 독",
    strokes: 14,
    words: ["독서", "독해", "독자"],
    sentence: "讀書는 지혜의 샘이다.",
  },
  {
    character: "白",
    reading: "백",
    meaning: "흰 백",
    strokes: 5,
    words: ["백색", "백설", "백조"],
    sentence: "白雪이 온 세상을 덮었다.",
  },
  {
    character: "靑",
    reading: "청",
    meaning: "푸를 청",
    strokes: 8,
    words: ["청소년", "청색", "청춘"],
    sentence: "靑春을 즐기자.",
  },
  {
    character: "赤",
    reading: "적",
    meaning: "붉을 적",
    strokes: 7,
    words: ["적색", "적십자", "적도"],
    sentence: "赤十字에 기부했다.",
  },
  {
    character: "黃",
    reading: "황",
    meaning: "누를 황",
    strokes: 12,
    words: ["황금", "황색", "황토"],
    sentence: "黃金보다 귀한 것은 건강이다.",
  },
  {
    character: "黑",
    reading: "흑",
    meaning: "검을 흑",
    strokes: 12,
    words: ["흑백", "흑색", "암흑"],
    sentence: "黑白 사진을 찍었다.",
  },
  {
    character: "東",
    reading: "동",
    meaning: "동녘 동",
    strokes: 8,
    words: ["동쪽", "동해", "동양"],
    sentence: "해는 東에서 뜬다.",
  },
  {
    character: "西",
    reading: "서",
    meaning: "서녘 서",
    strokes: 6,
    words: ["서쪽", "서양", "서해"],
    sentence: "해는 西에서 진다.",
  },
  {
    character: "南",
    reading: "남",
    meaning: "남녘 남",
    strokes: 9,
    words: ["남쪽", "남산", "남해"],
    sentence: "南山타워에 올라갔다.",
  },
  {
    character: "北",
    reading: "북",
    meaning: "북녘 북",
    strokes: 5,
    words: ["북쪽", "북극", "이북"],
    sentence: "北極에는 북극곰이 산다.",
  },
  {
    character: "正",
    reading: "정",
    meaning: "바를 정",
    strokes: 5,
    words: ["정직", "정확", "정의"],
    sentence: "正直하게 살자.",
  },
  {
    character: "直",
    reading: "직",
    meaning: "곧을 직",
    strokes: 8,
    words: ["직선", "정직", "직접"],
    sentence: "直線을 그었다.",
  },
  {
    character: "心",
    reading: "심",
    meaning: "마음 심",
    strokes: 4,
    words: ["심장", "관심", "결심"],
    sentence: "마음을 다해 感謝한다.",
  },
  {
    character: "思",
    reading: "사",
    meaning: "생각 사",
    strokes: 9,
    words: ["사고", "사상", "의사"],
    sentence: "깊이 思考하자.",
  },
  {
    character: "友",
    reading: "우",
    meaning: "벗 우",
    strokes: 4,
    words: ["친우", "우정", "우호"],
    sentence: "좋은 友情은 보물이다.",
  },
  {
    character: "愛",
    reading: "애",
    meaning: "사랑 애",
    strokes: 13,
    words: ["사랑", "애국", "자애"],
    sentence: "家族을 愛한다.",
  },
  {
    character: "孝",
    reading: "효",
    meaning: "효도 효",
    strokes: 7,
    words: ["효도", "효자", "효녀"],
    sentence: "부모님께 孝道하자.",
  },
  {
    character: "忠",
    reading: "충",
    meaning: "충성 충",
    strokes: 8,
    words: ["충성", "충신", "충고"],
    sentence: "나라에 忠誠을 다한다.",
  },
  {
    character: "仁",
    reading: "인",
    meaning: "어질 인",
    strokes: 4,
    words: ["인자", "인덕", "인의"],
    sentence: "仁德을 베풀자.",
  },
  {
    character: "義",
    reading: "의",
    meaning: "옳을 의",
    strokes: 13,
    words: ["정의", "의리", "의무"],
    sentence: "正義를 지키자.",
  },
  {
    character: "禮",
    reading: "예",
    meaning: "예도 예",
    strokes: 13,
    words: ["예의", "예절", "혼례"],
    sentence: "禮儀를 지키자.",
  },
  {
    character: "信",
    reading: "신",
    meaning: "믿을 신",
    strokes: 9,
    words: ["신뢰", "자신", "신용"],
    sentence: "信用을 지키는 사람이 되자.",
  },
  {
    character: "力",
    reading: "력",
    meaning: "힘 력",
    strokes: 2,
    words: ["노력", "체력", "능력"],
    sentence: "努力은 배신하지 않는다.",
  },
  {
    character: "勉",
    reading: "면",
    meaning: "힘쓸 면",
    strokes: 10,
    words: ["면학", "근면", "권면"],
    sentence: "勉學에 힘쓰자.",
  },
  {
    character: "工",
    reading: "공",
    meaning: "장인 공",
    strokes: 3,
    words: ["공장", "공업", "공사"],
    sentence: "工場에서 물건을 만든다.",
  },
  {
    character: "農",
    reading: "농",
    meaning: "농사 농",
    strokes: 13,
    words: ["농업", "농부", "농촌"],
    sentence: "農夫가 벼를 심었다.",
  },
  {
    character: "漁",
    reading: "어",
    meaning: "물고기 잡을 어",
    strokes: 14,
    words: ["어업", "어부", "어촌"],
    sentence: "漁夫가 바다에 나갔다.",
  },
  {
    character: "林",
    reading: "림",
    meaning: "수풀 림",
    strokes: 8,
    words: ["산림", "삼림", "임업"],
    sentence: "山林을 보호하자.",
  },
  {
    character: "海",
    reading: "해",
    meaning: "바다 해",
    strokes: 10,
    words: ["해양", "해변", "해수"],
    sentence: "푸른 海가 아름답다.",
  },
  {
    character: "河",
    reading: "하",
    meaning: "물 하",
    strokes: 8,
    words: ["하천", "은하수", "운하"],
    sentence: "河川에서 물고기를 잡았다.",
  },
  {
    character: "雨",
    reading: "우",
    meaning: "비 우",
    strokes: 8,
    words: ["우산", "폭우", "우기"],
    sentence: "雨가 내려 우산을 썼다.",
  },
  {
    character: "雪",
    reading: "설",
    meaning: "눈 설",
    strokes: 11,
    words: ["설경", "폭설", "제설"],
    sentence: "白雪이 펑펑 내렸다.",
  },
  {
    character: "風",
    reading: "풍",
    meaning: "바람 풍",
    strokes: 9,
    words: ["풍경", "태풍", "풍력"],
    sentence: "시원한 風이 불었다.",
  },
  {
    character: "雲",
    reading: "운",
    meaning: "구름 운",
    strokes: 12,
    words: ["운해", "풍운", "행운"],
    sentence: "하늘에 白雲이 떠 있다.",
  },
  {
    character: "光",
    reading: "광",
    meaning: "빛 광",
    strokes: 6,
    words: ["광선", "관광", "영광"],
    sentence: "태양의 光이 밝다.",
  },
  {
    character: "電",
    reading: "전",
    meaning: "번개 전",
    strokes: 13,
    words: ["전기", "전화", "전자"],
    sentence: "電氣를 아껴 쓰자.",
  },
  {
    character: "氣",
    reading: "기",
    meaning: "기운 기",
    strokes: 6,
    words: ["기분", "천기", "인기"],
    sentence: "오늘은 天氣가 좋다.",
  },
  {
    character: "道",
    reading: "도",
    meaning: "길 도",
    strokes: 13,
    words: ["도로", "도덕", "도리"],
    sentence: "바른 道를 걷자.",
  },
  {
    character: "里",
    reading: "리",
    meaning: "마을 리",
    strokes: 7,
    words: ["마을", "만리", "고리"],
    sentence: "千里 길도 한 걸음부터.",
  },
  {
    character: "市",
    reading: "시",
    meaning: "저자 시",
    strokes: 5,
    words: ["시장", "도시", "시민"],
    sentence: "都市에서 생활한다.",
  },
];

export const grade4EnglishData: EnglishEntry[] = [
  // 기존 15개
  {
    sentence: "What time is it?",
    translation: "몇 시예요?",
    word: "time",
    pronunciation: "타임",
    practice: ["What time is it?", "It is 3 o'clock."],
  },
  {
    sentence: "I want some water.",
    translation: "물 좀 주세요.",
    word: "water",
    pronunciation: "워터",
    practice: ["I want some ___.", "Can I have water?"],
  },
  {
    sentence: "Where is the library?",
    translation: "도서관이 어디에 있나요?",
    word: "library",
    pronunciation: "라이브러리",
    practice: ["Where is the ___?", "The library is over there."],
  },
  {
    sentence: "How much is this?",
    translation: "이것은 얼마예요?",
    word: "much",
    pronunciation: "머치",
    practice: ["How much is this?", "It is five dollars."],
  },
  {
    sentence: "I like to play soccer.",
    translation: "나는 축구하는 것을 좋아해.",
    word: "play",
    pronunciation: "플레이",
    practice: ["I like to play ___.", "Do you like to play?"],
  },
  {
    sentence: "My favorite color is blue.",
    translation: "내가 가장 좋아하는 색은 파란색이야.",
    word: "favorite",
    pronunciation: "페이버릿",
    practice: ["My favorite ___ is ___.", "What is your favorite color?"],
  },
  {
    sentence: "Can you help me?",
    translation: "도와줄 수 있어?",
    word: "help",
    pronunciation: "헬프",
    practice: ["Can you ___?", "Yes, I can help you."],
  },
  {
    sentence: "I am in the fourth grade.",
    translation: "나는 4학년이야.",
    word: "grade",
    pronunciation: "그레이드",
    practice: ["I am in the ___ grade.", "What grade are you in?"],
  },
  {
    sentence: "Let's go to the park.",
    translation: "공원에 가자.",
    word: "park",
    pronunciation: "파크",
    practice: ["Let's go to the ___.", "Do you want to go?"],
  },
  {
    sentence: "She is wearing a red hat.",
    translation: "그녀는 빨간 모자를 쓰고 있어.",
    word: "wearing",
    pronunciation: "웨어링",
    practice: ["She is wearing ___.", "He is wearing a blue shirt."],
  },
  {
    sentence: "How old are you?",
    translation: "너는 몇 살이니?",
    word: "old",
    pronunciation: "올드",
    practice: ["How old are you?", "I am ten years old."],
  },
  {
    sentence: "I have a big family.",
    translation: "나는 대가족이야.",
    word: "family",
    pronunciation: "패밀리",
    practice: ["I have a ___ family.", "How many people are in your family?"],
  },
  {
    sentence: "It is raining outside.",
    translation: "밖에 비가 오고 있어.",
    word: "raining",
    pronunciation: "레이닝",
    practice: ["It is ___ outside.", "Is it snowing?"],
  },
  {
    sentence: "Please open your book.",
    translation: "책을 펴 주세요.",
    word: "open",
    pronunciation: "오픈",
    practice: ["Please ___ your book.", "Close the window."],
  },
  {
    sentence: "I study math every day.",
    translation: "나는 매일 수학을 공부해.",
    word: "study",
    pronunciation: "스터디",
    practice: ["I study ___ every day.", "Do you study English?"],
  },
  // 신규 45개 (총 60개)
  {
    sentence: "When is your birthday?",
    translation: "네 생일이 언제야?",
    word: "birthday",
    pronunciation: "버스데이",
    practice: ["When is your ___?", "My birthday is in May."],
  },
  {
    sentence: "How many books do you have?",
    translation: "너는 책이 몇 권 있어?",
    word: "many",
    pronunciation: "메니",
    practice: ["How ___ do you have?", "I have three books."],
  },
  {
    sentence: "I go to bed at nine.",
    translation: "나는 9시에 잠자리에 들어.",
    word: "bed",
    pronunciation: "베드",
    practice: ["I go to ___ at nine.", "When do you go to bed?"],
  },
  {
    sentence: "She is taller than me.",
    translation: "그녀는 나보다 키가 커.",
    word: "taller",
    pronunciation: "톨러",
    practice: ["She is ___ than me.", "He is shorter than her."],
  },
  {
    sentence: "This is bigger than that.",
    translation: "이것이 저것보다 더 커.",
    word: "bigger",
    pronunciation: "비거",
    practice: ["This is ___ than that.", "Which is bigger?"],
  },
  {
    sentence: "I wake up at seven.",
    translation: "나는 7시에 일어나.",
    word: "wake",
    pronunciation: "웨이크",
    practice: ["I ___ up at seven.", "When do you wake up?"],
  },
  {
    sentence: "Turn right at the corner.",
    translation: "모퉁이에서 오른쪽으로 돌아.",
    word: "right",
    pronunciation: "라이트",
    practice: ["Turn ___ at the corner.", "Go straight."],
  },
  {
    sentence: "Go straight two blocks.",
    translation: "두 블록 직진해.",
    word: "straight",
    pronunciation: "스트레이트",
    practice: ["Go ___ two blocks.", "Turn left."],
  },
  {
    sentence: "I need a pencil.",
    translation: "나는 연필이 필요해.",
    word: "need",
    pronunciation: "니드",
    practice: ["I ___ a pencil.", "Do you need help?"],
  },
  {
    sentence: "What day is it today?",
    translation: "오늘은 무슨 요일이야?",
    word: "day",
    pronunciation: "데이",
    practice: ["What ___ is it today?", "It is Monday."],
  },
  {
    sentence: "I brush my teeth.",
    translation: "나는 이를 닦아.",
    word: "brush",
    pronunciation: "브러시",
    practice: ["I ___ my teeth.", "Brush your teeth."],
  },
  {
    sentence: "The pizza is delicious.",
    translation: "피자가 맛있어.",
    word: "delicious",
    pronunciation: "딜리셔스",
    practice: ["The pizza is ___.", "This food is delicious."],
  },
  {
    sentence: "I am wearing a jacket.",
    translation: "나는 재킷을 입고 있어.",
    word: "jacket",
    pronunciation: "재킷",
    practice: ["I am wearing a ___.", "Take off your jacket."],
  },
  {
    sentence: "How is the weather?",
    translation: "날씨가 어때?",
    word: "weather",
    pronunciation: "웨더",
    practice: ["How is the ___?", "The weather is nice."],
  },
  {
    sentence: "May I go to the restroom?",
    translation: "화장실에 가도 될까요?",
    word: "restroom",
    pronunciation: "레스트룸",
    practice: ["May I go to the ___?", "Yes, you may."],
  },
  {
    sentence: "She can play the piano.",
    translation: "그녀는 피아노를 칠 수 있어.",
    word: "piano",
    pronunciation: "피아노",
    practice: ["She can play the ___.", "Can you play the guitar?"],
  },
  {
    sentence: "I visited my grandma.",
    translation: "나는 할머니를 방문했어.",
    word: "visited",
    pronunciation: "비지티드",
    practice: ["I ___ my grandma.", "Did you visit your friend?"],
  },
  {
    sentence: "The movie was exciting.",
    translation: "그 영화는 흥미진진했어.",
    word: "exciting",
    pronunciation: "익사이팅",
    practice: ["The movie was ___.", "It was boring."],
  },
  {
    sentence: "I want to be a doctor.",
    translation: "나는 의사가 되고 싶어.",
    word: "doctor",
    pronunciation: "닥터",
    practice: ["I want to be a ___.", "What do you want to be?"],
  },
  {
    sentence: "Please pass me the salt.",
    translation: "소금 좀 건네주세요.",
    word: "salt",
    pronunciation: "솔트",
    practice: ["Please pass me the ___.", "Here you are."],
  },
  {
    sentence: "I made a card for mom.",
    translation: "나는 엄마를 위해 카드를 만들었어.",
    word: "made",
    pronunciation: "메이드",
    practice: ["I ___ a card.", "What did you make?"],
  },
  {
    sentence: "He runs faster than me.",
    translation: "그는 나보다 빨리 달려.",
    word: "faster",
    pronunciation: "패스터",
    practice: ["He runs ___ than me.", "She runs slowly."],
  },
  {
    sentence: "I ate lunch at noon.",
    translation: "나는 정오에 점심을 먹었어.",
    word: "noon",
    pronunciation: "눈",
    practice: ["I ate lunch at ___.", "What did you eat?"],
  },
  {
    sentence: "There are many clouds.",
    translation: "구름이 많아.",
    word: "clouds",
    pronunciation: "클라우즈",
    practice: ["There are many ___.", "The sky is cloudy."],
  },
  {
    sentence: "I am good at drawing.",
    translation: "나는 그림을 잘 그려.",
    word: "drawing",
    pronunciation: "드로잉",
    practice: ["I am good at ___.", "What are you good at?"],
  },
  {
    sentence: "The test was easy.",
    translation: "시험이 쉬웠어.",
    word: "easy",
    pronunciation: "이지",
    practice: ["The test was ___.", "It was difficult."],
  },
  {
    sentence: "I bought a new notebook.",
    translation: "나는 새 공책을 샀어.",
    word: "bought",
    pronunciation: "보트",
    practice: ["I ___ a new notebook.", "Where did you buy it?"],
  },
  {
    sentence: "My hobby is reading.",
    translation: "나의 취미는 독서야.",
    word: "hobby",
    pronunciation: "하비",
    practice: ["My ___ is reading.", "What is your hobby?"],
  },
  {
    sentence: "She speaks English well.",
    translation: "그녀는 영어를 잘해.",
    word: "speaks",
    pronunciation: "스픽스",
    practice: ["She ___ English well.", "Do you speak Korean?"],
  },
  {
    sentence: "I take a bus to school.",
    translation: "나는 버스를 타고 학교에 가.",
    word: "bus",
    pronunciation: "버스",
    practice: ["I take a ___ to school.", "How do you go to school?"],
  },
  {
    sentence: "The flower smells nice.",
    translation: "그 꽃은 냄새가 좋아.",
    word: "smells",
    pronunciation: "스멜즈",
    practice: ["The flower ___ nice.", "It smells bad."],
  },
  {
    sentence: "I usually eat rice.",
    translation: "나는 보통 밥을 먹어.",
    word: "usually",
    pronunciation: "유주얼리",
    practice: ["I ___ eat rice.", "I sometimes eat bread."],
  },
  {
    sentence: "We played together.",
    translation: "우리는 함께 놀았어.",
    word: "together",
    pronunciation: "투게더",
    practice: ["We played ___.", "Let's study together."],
  },
  {
    sentence: "I have a headache.",
    translation: "나는 두통이 있어.",
    word: "headache",
    pronunciation: "헤데이크",
    practice: ["I have a ___.", "Do you feel sick?"],
  },
  {
    sentence: "The store is next to the bank.",
    translation: "가게는 은행 옆에 있어.",
    word: "next",
    pronunciation: "넥스트",
    practice: ["It is ___ to the bank.", "What is next to your house?"],
  },
  {
    sentence: "I finished my homework.",
    translation: "나는 숙제를 끝냈어.",
    word: "finished",
    pronunciation: "피니시드",
    practice: ["I ___ my homework.", "Did you finish?"],
  },
  {
    sentence: "Please be quiet.",
    translation: "조용히 해 주세요.",
    word: "quiet",
    pronunciation: "콰이엇",
    practice: ["Please be ___.", "The library is quiet."],
  },
  {
    sentence: "I feel happy today.",
    translation: "오늘 기분이 좋아.",
    word: "feel",
    pronunciation: "필",
    practice: ["I ___ happy today.", "How do you feel?"],
  },
  {
    sentence: "She is a kind person.",
    translation: "그녀는 친절한 사람이야.",
    word: "person",
    pronunciation: "퍼슨",
    practice: ["She is a kind ___.", "He is a nice person."],
  },
  {
    sentence: "I exercise every morning.",
    translation: "나는 매일 아침 운동해.",
    word: "exercise",
    pronunciation: "엑서사이즈",
    practice: ["I ___ every morning.", "Do you exercise?"],
  },
  {
    sentence: "The soup is too hot.",
    translation: "국이 너무 뜨거워.",
    word: "hot",
    pronunciation: "핫",
    practice: ["The soup is too ___.", "It is too cold."],
  },
  {
    sentence: "I will try my best.",
    translation: "나는 최선을 다할 거야.",
    word: "try",
    pronunciation: "트라이",
    practice: ["I will ___ my best.", "Let's try again."],
  },
  {
    sentence: "We learned about animals.",
    translation: "우리는 동물에 대해 배웠어.",
    word: "learned",
    pronunciation: "런드",
    practice: ["We ___ about animals.", "What did you learn?"],
  },
  {
    sentence: "I live near the school.",
    translation: "나는 학교 근처에 살아.",
    word: "near",
    pronunciation: "니어",
    practice: ["I live ___ the school.", "Is it far or near?"],
  },
  {
    sentence: "Happy New Year!",
    translation: "새해 복 많이 받으세요!",
    word: "year",
    pronunciation: "이어",
    practice: ["Happy New ___!", "What year is it?"],
  },
];

export const grade4WritingPrompts: string[] = [
  // 기존 20개
  "내가 존경하는 인물과 그 이유를 설명하는 글을 써 보세요.",
  "우리 지역의 문화유산을 소개하는 글을 써 보세요.",
  "좋은 친구란 어떤 친구인지 자신의 생각을 써 보세요.",
  "내가 경험한 가장 어려웠던 일과 극복 과정을 써 보세요.",
  "환경 보호를 위해 우리가 할 수 있는 일을 제안하는 글을 써 보세요.",
  "내가 읽은 책을 친구에게 추천하는 글을 써 보세요.",
  "우리 학교의 급식에 대해 의견을 써 보세요.",
  "스마트폰 사용에 대한 나의 생각을 써 보세요.",
  "내가 만약 100년 전으로 시간 여행을 한다면?",
  "학급 회의에서 발표할 안건을 작성해 보세요.",
  "가장 기억에 남는 선물과 그 이유를 써 보세요.",
  "내가 잘못한 일을 반성하는 글을 써 보세요.",
  "우리 반의 좋은 전통을 만들자는 제안 글을 써 보세요.",
  "내가 가장 감동받은 이야기를 소개해 보세요.",
  "만약 동물과 대화할 수 있다면 누구와 무슨 이야기를 할까요?",
  "내가 생각하는 행복이란 무엇인지 써 보세요.",
  "편지 형식으로 감사의 마음을 전해 보세요.",
  "나만의 발명품을 설명하는 글을 써 보세요.",
  "우리 마을을 더 좋게 만들기 위한 방법을 제안해 보세요.",
  "10년 후의 나에게 편지를 써 보세요.",
  // 신규 40개 (총 60개)
  "뉴스에서 본 사건에 대한 나의 의견을 써 보세요.",
  "학교에서 일어난 갈등을 해결한 경험을 써 보세요.",
  "내가 살고 싶은 미래의 도시를 상상해서 써 보세요.",
  "역사 속 인물에게 편지를 써 보세요.",
  "우리 반 규칙을 바꾸고 싶다면 어떤 규칙을, 왜 바꾸고 싶은지 써 보세요.",
  "인터넷을 안전하게 사용하는 방법을 설명하는 글을 써 보세요.",
  "내가 만약 마법을 쓸 수 있다면 무엇을 하고 싶은지 써 보세요.",
  "가장 인상 깊었던 체험학습에 대해 써 보세요.",
  "우리 가족만의 특별한 규칙이나 전통을 소개해 보세요.",
  "지구 온난화가 우리 생활에 미치는 영향에 대해 써 보세요.",
  "내가 좋아하는 운동 선수와 그 이유를 써 보세요.",
  "학교 도서관에서 가장 좋아하는 책을 소개해 보세요.",
  "친구에게 사과하는 편지를 써 보세요.",
  "만약 외계인을 만난다면 어떤 이야기를 하고 싶은지 써 보세요.",
  "내가 경험한 봉사 활동에 대해 써 보세요.",
  "우리나라의 자랑거리를 외국인 친구에게 소개하는 글을 써 보세요.",
  "일기 예보를 듣고 주말 계획을 세우는 글을 써 보세요.",
  "가장 재미있었던 방학 경험을 써 보세요.",
  "만약 슈퍼 히어로가 된다면 어떤 능력을 갖고 싶은지 써 보세요.",
  "옛날과 오늘날의 학교를 비교하는 글을 써 보세요.",
  "내가 만든 요리 레시피를 설명하는 글을 써 보세요.",
  "학급 신문에 실을 기사를 써 보세요.",
  "감동적인 영화나 드라마를 소개하는 글을 써 보세요.",
  "우리 동네의 문제점과 해결 방안을 제안해 보세요.",
  "가장 갖고 싶은 직업과 그 이유를 설명해 보세요.",
  "사계절의 특징을 비교하여 설명하는 글을 써 보세요.",
  "반려동물과의 에피소드를 재미있게 써 보세요.",
  "내가 대통령이라면 어떤 정책을 펼지 써 보세요.",
  "공정한 것이란 무엇인지 자신의 생각을 써 보세요.",
  "전통 시장과 대형 마트의 장단점을 비교해 보세요.",
  "가장 기억에 남는 선생님과의 이야기를 써 보세요.",
  "만약 무인도에 간다면 무엇을 가져갈지 써 보세요.",
  "용기를 냈던 경험에 대해 써 보세요.",
  "다른 나라의 문화 중 배우고 싶은 것을 써 보세요.",
  "우리 학교를 더 좋게 만들기 위한 아이디어를 써 보세요.",
  "AI(인공지능)에 대해 내가 아는 것과 느끼는 점을 써 보세요.",
  "내가 만약 1억 원이 생긴다면 어떻게 쓸지 계획을 써 보세요.",
  "소중한 약속을 지켰던 경험을 써 보세요.",
  "내가 좋아하는 계절에 하고 싶은 일을 계획해 보세요.",
  "나의 하루를 시간 순서대로 일기 형식으로 써 보세요.",
];

export const grade4CreativeData: KnowledgeEntry[] = [
  // 미술 (15개)
  {
    text: "가까운 것은 크게, 먼 것은 작게 그리는 것을 ___이라 한다.",
    answer: "원근법",
    category: "미술",
  },
  {
    text: "좌우가 똑같은 것을 대칭, 다른 것을 ___이라 한다.",
    answer: "비대칭",
    category: "미술",
  },
  {
    text: "색의 삼원색은 빨강, 파랑, ___이다.",
    answer: "노랑",
    category: "미술",
  },
  {
    text: "빛의 삼원색은 빨강, 초록, ___이다.",
    answer: "파랑",
    category: "미술",
  },
  {
    text: "따뜻한 느낌의 색을 ___색이라 한다.",
    answer: "난",
    category: "미술",
  },
  {
    text: "차가운 느낌의 색을 ___색이라 한다.",
    answer: "한",
    category: "미술",
  },
  {
    text: "색상환에서 서로 반대편에 있는 색을 ___색이라 한다.",
    answer: "보",
    category: "미술",
  },
  {
    text: "물감에 흰색을 섞으면 색의 ___가 높아진다.",
    answer: "명도",
    category: "미술",
  },
  { text: "색이 선명한 정도를 ___라 한다.", answer: "채도", category: "미술" },
  {
    text: "그림의 구도를 정하는 것을 ___이라 한다.",
    answer: "구성",
    category: "미술",
  },
  {
    text: "실제 사물을 보고 그리는 것을 ___이라 한다.",
    answer: "사생",
    category: "미술",
  },
  {
    text: "머릿속으로 상상해서 그리는 것을 ___화라 한다.",
    answer: "상상",
    category: "미술",
  },
  {
    text: "고흐가 그린 유명한 그림은 '___'이다.",
    answer: "별이 빛나는 밤",
    category: "미술",
  },
  {
    text: "도자기를 만들 때 흙을 빚고 ___에서 구운다.",
    answer: "가마",
    category: "미술",
  },
  {
    text: "전통 문양 중 반복되는 기하학적 무늬를 ___이라 한다.",
    answer: "기하 문양",
    category: "미술",
  },
  // 음악 (13개)
  {
    text: "리코더에서 '도'음을 낼 때 왼손으로 ___개의 구멍을 막는다.",
    answer: "4",
    category: "음악",
  },
  {
    text: "음악에서 점점 세게 연주하라는 기호는 ___이다.",
    answer: "크레셴도",
    category: "음악",
  },
  {
    text: "음악에서 점점 여리게 연주하라는 기호는 ___이다.",
    answer: "데크레셴도",
    category: "음악",
  },
  {
    text: "음악에서 보통 빠르기를 나타내는 말은 ___이다.",
    answer: "모데라토",
    category: "음악",
  },
  {
    text: "음악에서 느리게 연주하라는 말은 ___이다.",
    answer: "아다지오",
    category: "음악",
  },
  { text: "8분음표는 ___박자를 나타낸다.", answer: "반", category: "음악" },
  { text: "점4분음표는 ___박자를 나타낸다.", answer: "1.5", category: "음악" },
  {
    text: "같은 높이의 음을 이어주는 줄을 ___이라 한다.",
    answer: "붙임줄",
    category: "음악",
  },
  {
    text: "음의 높낮이를 나타내는 5개의 줄을 ___이라 한다.",
    answer: "오선",
    category: "음악",
  },
  {
    text: "우리나라 전통 악기 중 치는 악기인 ___은 나무통으로 만든다.",
    answer: "북",
    category: "음악",
  },
  {
    text: "사물놀이에 사용되는 네 가지 악기는 꽹과리, 장구, 북, ___이다.",
    answer: "징",
    category: "음악",
  },
  {
    text: "노래를 부르기 전에 목을 풀기 위해 하는 것을 ___이라 한다.",
    answer: "발성 연습",
    category: "음악",
  },
  {
    text: "여러 가지 악기로 함께 연주하는 것을 ___이라 한다.",
    answer: "합주",
    category: "음악",
  },
  // 만들기 (6개)
  {
    text: "설계도를 그린 후 재료를 ___하여 만든다.",
    answer: "조립",
    category: "만들기",
  },
  {
    text: "종이를 여러 겹 붙여 단단하게 만드는 기법을 ___이라 한다.",
    answer: "종이죽",
    category: "만들기",
  },
  {
    text: "바느질에서 천과 천을 잇는 것을 ___이라 한다.",
    answer: "박음질",
    category: "만들기",
  },
  {
    text: "3D 프린터는 ___으로 입체 물건을 만든다.",
    answer: "플라스틱",
    category: "만들기",
  },
  {
    text: "전시회에 출품할 작품에는 작품명과 ___를 적는다.",
    answer: "작가명",
    category: "만들기",
  },
  {
    text: "나무를 조각할 때 사용하는 도구를 ___이라 한다.",
    answer: "조각칼",
    category: "만들기",
  },
  // 감상 (6개)
  {
    text: "작품을 감상할 때 색감, 구도, ___을 살펴본다.",
    answer: "표현 기법",
    category: "감상",
  },
  {
    text: "음악을 들을 때 빠르기, 셈여림, ___을 느껴본다.",
    answer: "분위기",
    category: "감상",
  },
  {
    text: "전통 미술에서 산수를 그린 그림을 ___이라 한다.",
    answer: "산수화",
    category: "감상",
  },
  {
    text: "미술 작품에 대한 자신의 느낌을 글로 적는 것을 ___이라 한다.",
    answer: "감상문",
    category: "감상",
  },
  {
    text: "한국 전통 건축에서 지붕의 곡선미를 ___이라 한다.",
    answer: "처마 곡선",
    category: "감상",
  },
  {
    text: "공연이 끝난 후 관객이 보내는 박수를 ___이라 한다.",
    answer: "갈채",
    category: "감상",
  },
];
