import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
  HanjaEntry,
  EnglishEntry,
} from "@/types/curriculum";

// 5학년 1학기 교육과정 성취기준
export const grade5Semester1Standards = {
  math: [
    {
      code: "[6수01-01]",
      desc: "자연수의 혼합 계산에서 계산 순서를 알고 혼합 계산을 할 수 있다",
      unit: "자연수의 혼합 계산",
      difficulty: 5,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6수01-02]",
      desc: "약수와 배수의 관계를 이해한다",
      unit: "약수와 배수",
      difficulty: 5,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수01-03]",
      desc: "최대공약수와 최소공배수를 구할 수 있다",
      unit: "약수와 배수",
      difficulty: 5,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수01-04]",
      desc: "약분과 통분을 할 수 있다",
      unit: "약분과 통분",
      difficulty: 5,
      weeks: [7, 9] as [number, number],
    },
    {
      code: "[6수01-05]",
      desc: "분모가 다른 분수의 덧셈과 뺄셈을 할 수 있다",
      unit: "분수의 덧셈과 뺄셈",
      difficulty: 5,
      weeks: [10, 12] as [number, number],
    },
    {
      code: "[6수02-01]",
      desc: "직육면체와 정육면체를 이해하고 구성 요소를 안다",
      unit: "직육면체",
      difficulty: 5,
      weeks: [13, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[6국01-01]",
      desc: "구어 의사소통의 특성을 바탕으로 하여 듣기·말하기 활동을 한다",
      unit: "의사소통",
      difficulty: 5,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6국02-01]",
      desc: "읽기는 배경지식과 글에 있는 정보를 활용하여 의미를 구성하는 과정임을 안다",
      unit: "읽기 과정",
      difficulty: 5,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[6국03-01]",
      desc: "쓰기는 절차에 따라 의미를 구성하고 표현하는 과정임을 이해하고 글을 쓴다",
      unit: "글쓰기 과정",
      difficulty: 5,
      weeks: [8, 11] as [number, number],
    },
    {
      code: "[6국04-01]",
      desc: "낱말이 상황에 따라 다양하게 해석됨을 탐구한다",
      unit: "낱말의 의미",
      difficulty: 5,
      weeks: [12, 14] as [number, number],
    },
  ],
  english: [
    {
      code: "[6영01-01]",
      desc: "쉽고 간단한 문장을 듣고 세부 정보를 파악할 수 있다",
      unit: "Listening",
      difficulty: 5,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[6영02-01]",
      desc: "일상생활에 관한 짧고 쉬운 글을 읽고 세부 정보를 파악할 수 있다",
      unit: "Reading",
      difficulty: 5,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[6영03-01]",
      desc: "일상생활에 관한 주제에 대해 짧고 간단하게 쓸 수 있다",
      unit: "Writing",
      difficulty: 5,
      weeks: [9, 12] as [number, number],
    },
  ],
};

export const grade5Semester2Standards = {
  math: [
    {
      code: "[6수01-06]",
      desc: "분수의 곱셈을 할 수 있다",
      unit: "분수의 곱셈",
      difficulty: 5,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6수02-02]",
      desc: "합동의 의미를 알고 합동인 도형의 성질을 이해한다",
      unit: "합동과 대칭",
      difficulty: 5,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수02-03]",
      desc: "선대칭도형과 점대칭도형을 이해한다",
      unit: "합동과 대칭",
      difficulty: 5,
      weeks: [4, 6] as [number, number],
    },
    {
      code: "[6수01-07]",
      desc: "소수의 곱셈을 할 수 있다",
      unit: "소수의 곱셈",
      difficulty: 5,
      weeks: [7, 9] as [number, number],
    },
    {
      code: "[6수03-01]",
      desc: "넓이의 단위를 알고 직사각형의 넓이를 구할 수 있다",
      unit: "넓이",
      difficulty: 5,
      weeks: [10, 12] as [number, number],
    },
    {
      code: "[6수04-01]",
      desc: "평균의 의미를 알고 구할 수 있다",
      unit: "평균과 가능성",
      difficulty: 5,
      weeks: [13, 15] as [number, number],
    },
  ],
  korean: [
    {
      code: "[6국01-02]",
      desc: "의견을 제시하고 함께 조정하며 토의한다",
      unit: "토의",
      difficulty: 5,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[6국02-02]",
      desc: "글의 구조를 고려하여 글 전체의 내용을 요약한다",
      unit: "요약",
      difficulty: 5,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[6국03-02]",
      desc: "목적이나 주제에 따라 알맞은 내용과 매체를 선정하여 글을 쓴다",
      unit: "목적에 맞게 쓰기",
      difficulty: 5,
      weeks: [8, 11] as [number, number],
    },
  ],
  english: [
    {
      code: "[6영01-02]",
      desc: "일상생활에 관한 쉽고 간단한 말이나 대화를 듣고 주제 및 요지를 파악할 수 있다",
      unit: "Listening",
      difficulty: 5,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[6영02-02]",
      desc: "짧고 쉬운 글을 읽고 주제 및 요지를 파악할 수 있다",
      unit: "Reading",
      difficulty: 5,
      weeks: [5, 8] as [number, number],
    },
  ],
};

// ===== 맞춤법 데이터 (60개) =====
export const grade5SpellingData: SpellingEntry[] = [
  // 기존 22개
  {
    q1: "역할을 충실히 했다.",
    q2: "역활을 충실히 했다.",
    answer: 1,
    explanation: "'역할'이 올바른 표기입니다.",
  },
  {
    q1: "왠지 불안하다.",
    q2: "웬지 불안하다.",
    answer: 1,
    explanation: "'왠지'(왜인지의 줄임)가 올바른 표기입니다.",
  },
  {
    q1: "어떡해, 큰일이다.",
    q2: "어떻해, 큰일이다.",
    answer: 1,
    explanation: "'어떡해'(어떻게 해의 줄임)가 올바른 표기입니다.",
  },
  {
    q1: "더 이상 참을 수 없다.",
    q2: "더이상 참을 수 없다.",
    answer: 1,
    explanation: "'더 이상'은 띄어 쓰는 것이 맞습니다.",
  },
  {
    q1: "안 되겠다.",
    q2: "안되겠다.",
    answer: 1,
    explanation: "'안 되다'는 띄어 씁니다. '안되다'(불쌍하다)와 구분합니다.",
  },
  {
    q1: "며칠째 비가 온다.",
    q2: "몇일째 비가 온다.",
    answer: 1,
    explanation: "'며칠'이 올바른 표기입니다.",
  },
  {
    q1: "수수께끼를 풀었다.",
    q2: "수수깨끼를 풀었다.",
    answer: 1,
    explanation: "'수수께끼'가 올바른 표기입니다.",
  },
  {
    q1: "귀띔해 주었다.",
    q2: "귀뜀해 주었다.",
    answer: 1,
    explanation: "'귀띔'이 올바른 표기입니다.",
  },
  {
    q1: "짜장면을 먹었다.",
    q2: "자장면을 먹었다.",
    answer: 1,
    explanation: "'짜장면'이 현재 표준어입니다. (2011년 복수 표준어 인정)",
  },
  {
    q1: "주위 환경을 살폈다.",
    q2: "주위 환경을 살폈다.",
    answer: 1,
    explanation: "'살폈다'가 올바른 표기입니다.",
  },
  {
    q1: "물음에 대답했다.",
    q2: "물읨에 대답했다.",
    answer: 1,
    explanation: "'물음'이 올바른 표기입니다.",
  },
  {
    q1: "사달이 나다.",
    q2: "사달이 나다.",
    answer: 1,
    explanation: "'사달'이 올바른 표기입니다.",
  },
  {
    q1: "한참 동안 걸었다.",
    q2: "한참동안 걸었다.",
    answer: 1,
    explanation: "'한참 동안'은 띄어 쓰는 것이 맞습니다.",
  },
  {
    q1: "뒤처지지 않도록 노력했다.",
    q2: "뒤쳐지지 않도록 노력했다.",
    answer: 1,
    explanation: "'뒤처지다'가 올바른 표기입니다.",
  },
  {
    q1: "들이켜다 - 물을 벌컥 들이켰다.",
    q2: "들이키다 - 물을 벌컥 들이켰다.",
    answer: 1,
    explanation: "'들이켜다'가 올바른 표기입니다.",
  },
  {
    q1: "눈꼽이 끼었다.",
    q2: "눈곱이 끼었다.",
    answer: 2,
    explanation: "'눈곱'이 올바른 표기입니다.",
  },
  {
    q1: "벌써 가을이다.",
    q2: "벌서 가을이다.",
    answer: 1,
    explanation: "'벌써'가 올바른 표기입니다.",
  },
  {
    q1: "소나기가 그쳤다.",
    q2: "소나기가 그쳣다.",
    answer: 1,
    explanation: "'그쳤다'가 올바른 표기입니다.",
  },
  {
    q1: "축구 시합에서 이겼다.",
    q2: "축구 시합에서 이겼따.",
    answer: 1,
    explanation: "'이겼다'가 올바른 표기입니다.",
  },
  {
    q1: "맨 나중에 왔다.",
    q2: "맨나중에 왔다.",
    answer: 1,
    explanation: "'맨 나중'은 띄어 쓰는 것이 맞습니다.",
  },
  {
    q1: "조금이나마 도움이 되었다.",
    q2: "조금이라마 도움이 되었다.",
    answer: 1,
    explanation: "'조금이나마'가 올바른 표기입니다.",
  },
  // 추가 39개 (총 60개)
  {
    q1: "설거지를 했다.",
    q2: "설겆이를 했다.",
    answer: 1,
    explanation: "'설거지'가 올바른 표기입니다.",
  },
  {
    q1: "넓직한 마당이다.",
    q2: "널직한 마당이다.",
    answer: 1,
    explanation: "'넓직하다'가 올바른 표기입니다. '넓다'에서 파생된 말입니다.",
  },
  {
    q1: "오랫동안 기다렸다.",
    q2: "오랜동안 기다렸다.",
    answer: 1,
    explanation: "'오랫동안'이 올바른 표기입니다. 사이시옷이 들어갑니다.",
  },
  {
    q1: "일일이 확인했다.",
    q2: "일일히 확인했다.",
    answer: 1,
    explanation: "'일일이'가 올바른 표기입니다.",
  },
  {
    q1: "요컨대 중요한 것은 노력이다.",
    q2: "요컨데 중요한 것은 노력이다.",
    answer: 1,
    explanation: "'요컨대'가 올바른 표기입니다.",
  },
  {
    q1: "금세 해가 졌다.",
    q2: "금새 해가 졌다.",
    answer: 1,
    explanation: "'금세'(금시에의 줄임)가 올바른 표기입니다.",
  },
  {
    q1: "문안하다 - 어른께 인사드리다.",
    q2: "무난하다 - 어른께 인사드리다.",
    answer: 1,
    explanation: "'문안하다'는 '어른에게 안부를 여쭙다'는 뜻입니다.",
  },
  {
    q1: "깨끗히 정리했다.",
    q2: "깨끗이 정리했다.",
    answer: 2,
    explanation:
      "'깨끗이'가 올바른 표기입니다. 'ㅅ' 받침 뒤에는 '-이'를 씁니다.",
  },
  {
    q1: "댓가를 치르다.",
    q2: "대가를 치르다.",
    answer: 2,
    explanation: "'대가'가 올바른 표기입니다. 사이시옷을 쓰지 않습니다.",
  },
  {
    q1: "바라건대 성공하길 빈다.",
    q2: "바라건데 성공하길 빈다.",
    answer: 1,
    explanation: "'바라건대'가 올바른 표기입니다.",
  },
  {
    q1: "구시렁거리다.",
    q2: "구시렁거리다.",
    answer: 1,
    explanation: "'구시렁거리다'(투덜대다)가 올바른 표기입니다.",
  },
  {
    q1: "흐리멍텅한 하늘이다.",
    q2: "흐리멍텅한 하늘이다.",
    answer: 1,
    explanation: "'흐리멍텅하다'가 올바른 표기입니다.",
  },
  {
    q1: "예쁘장하다.",
    q2: "이쁘장하다.",
    answer: 1,
    explanation: "'예쁘다'가 표준어입니다. '이쁘다'는 비표준어입니다.",
  },
  {
    q1: "곰곰히 생각했다.",
    q2: "곰곰이 생각했다.",
    answer: 2,
    explanation:
      "'곰곰이'가 올바른 표기입니다. 'ㅁ' 받침 뒤에는 '-이'를 씁니다.",
  },
  {
    q1: "어이없는 일이다.",
    q2: "어의없는 일이다.",
    answer: 1,
    explanation: "'어이없다'가 올바른 표기입니다.",
  },
  {
    q1: "그러고 나서 밥을 먹었다.",
    q2: "그리고 나서 밥을 먹었다.",
    answer: 1,
    explanation:
      "'그러고 나서'가 올바른 표기입니다. '그러고'는 '그리하고'의 줄임말입니다.",
  },
  {
    q1: "삼가 감사드립니다.",
    q2: "삼가 감사드림니다.",
    answer: 1,
    explanation: "'드립니다'가 올바른 표기입니다.",
  },
  {
    q1: "희안한 일이다.",
    q2: "희한한 일이다.",
    answer: 2,
    explanation: "'희한하다'가 올바른 표기입니다.",
  },
  {
    q1: "되물림하다.",
    q2: "대물림하다.",
    answer: 2,
    explanation: "'대물림'이 올바른 표기입니다.",
  },
  {
    q1: "건듯 잠이 깼다.",
    q2: "건듯이 잠이 깼다.",
    answer: 1,
    explanation: "'건듯'이 올바른 표기입니다.",
  },
  {
    q1: "움켜쥐다.",
    q2: "움켜쥐다.",
    answer: 1,
    explanation: "'움켜쥐다'가 올바른 표기입니다.",
  },
  {
    q1: "통째로 삼키다.",
    q2: "통채로 삼키다.",
    answer: 1,
    explanation: "'통째로'가 올바른 표기입니다.",
  },
  {
    q1: "할 수 밖에 없다.",
    q2: "할 수밖에 없다.",
    answer: 2,
    explanation: "'수밖에'는 붙여 쓰는 것이 맞습니다.",
  },
  {
    q1: "뒤적뒤적 찾았다.",
    q2: "뒤적뒤적 찿았다.",
    answer: 1,
    explanation: "'찾았다'가 올바른 표기입니다.",
  },
  {
    q1: "너머로 해가 진다.",
    q2: "넘어로 해가 진다.",
    answer: 1,
    explanation: "'너머'가 올바른 표기입니다. 명사로 '저쪽'을 뜻합니다.",
  },
  {
    q1: "낫다 - 이 방법이 더 낫다.",
    q2: "낳다 - 이 방법이 더 낳다.",
    answer: 1,
    explanation: "'낫다'(더 좋다)가 맞습니다. '낳다'는 '아이를 낳다'에 씁니다.",
  },
  {
    q1: "왠만하면 참아라.",
    q2: "웬만하면 참아라.",
    answer: 2,
    explanation: "'웬만하면'이 올바른 표기입니다.",
  },
  {
    q1: "안절부절못하다.",
    q2: "안절부절 못하다.",
    answer: 1,
    explanation: "'안절부절못하다'는 한 단어로 붙여 씁니다.",
  },
  {
    q1: "강냉이를 먹었다.",
    q2: "강낭이를 먹었다.",
    answer: 1,
    explanation: "'강냉이'가 올바른 표기입니다.",
  },
  {
    q1: "깍쟁이 같다.",
    q2: "깍장이 같다.",
    answer: 1,
    explanation: "'깍쟁이'가 올바른 표기입니다.",
  },
  {
    q1: "한턱 내다.",
    q2: "한턱 내다.",
    answer: 1,
    explanation: "'한턱'이 올바른 표기입니다.",
  },
  {
    q1: "겉잡을 수 없다.",
    q2: "걷잡을 수 없다.",
    answer: 2,
    explanation: "'걷잡을 수 없다'가 올바른 표기입니다.",
  },
  {
    q1: "매무새가 단정하다.",
    q2: "매무시가 단정하다.",
    answer: 1,
    explanation: "'매무새'가 올바른 표기입니다.",
  },
  {
    q1: "연거푸 세 잔을 마셨다.",
    q2: "연거퓨 세 잔을 마셨다.",
    answer: 1,
    explanation: "'연거푸'가 올바른 표기입니다.",
  },
  {
    q1: "당췌 모르겠다.",
    q2: "당최 모르겠다.",
    answer: 1,
    explanation: "'당췌'가 올바른 표기입니다.",
  },
  {
    q1: "일찌기 도착했다.",
    q2: "일찍이 도착했다.",
    answer: 2,
    explanation: "'일찍이'가 올바른 표기입니다.",
  },
  {
    q1: "객적다.",
    q2: "객쩍다.",
    answer: 1,
    explanation: "'객적다'(쑥스럽다)가 올바른 표기입니다.",
  },
  {
    q1: "눈쌀을 찌푸리다.",
    q2: "눈살을 찌푸리다.",
    answer: 2,
    explanation: "'눈살'이 올바른 표기입니다.",
  },
  {
    q1: "아지랑이가 피어오른다.",
    q2: "아지랭이가 피어오른다.",
    answer: 1,
    explanation: "'아지랑이'가 올바른 표기입니다.",
  },
];

// ===== 어휘 데이터 (60개) =====
export const grade5VocabData: VocabEntry[] = [
  // 기존 15개
  {
    meanings: ["자기 잘못을 깨닫고 뉘우치는 것", "반성과 비슷해요"],
    answer: "성찰",
  },
  { meanings: ["처음 시작하는 것", "새로운 제도를 만드는 것"], answer: "창시" },
  {
    meanings: ["어떤 사실을 널리 알리는 것", "광고와 비슷해요"],
    answer: "홍보",
  },
  { meanings: ["힘을 합쳐 일하는 것", "함께 노력하는 것"], answer: "협력" },
  { meanings: ["갈등을 평화롭게 푸는 것", "합의와 비슷해요"], answer: "타협" },
  {
    meanings: ["새로운 것을 만들어 내는 것", "발명과 비슷해요"],
    answer: "창조",
  },
  {
    meanings: ["어떤 것에 마음이 끌리는 것", "호기심과 비슷해요"],
    answer: "관심",
  },
  {
    meanings: ["과학에서 가설을 증명하는 과정", "실험실에서 해요"],
    answer: "실험",
  },
  {
    meanings: ["여러 사람의 의견을 모으는 것", "투표와 관련 있어요"],
    answer: "여론",
  },
  {
    meanings: ["나라를 위해 목숨을 바친 사람", "독립운동가가 해당돼요"],
    answer: "순국",
  },
  {
    meanings: ["물체가 움직이는 빠르기", "시간 대비 거리로 구해요"],
    answer: "속력",
  },
  {
    meanings: ["다른 나라와 물건을 사고파는 것", "수출과 수입이 있어요"],
    answer: "무역",
  },
  {
    meanings: ["편견 없이 공정하게 판단하는 것", "법과 관련 있어요"],
    answer: "공정",
  },
  {
    meanings: ["자연 현상을 연구하는 학문", "실험과 관찰로 탐구해요"],
    answer: "과학",
  },
  {
    meanings: ["어떤 문제를 깊이 생각하는 것", "탐구와 비슷해요"],
    answer: "고찰",
  },
  // 추가 45개 (총 60개)
  {
    meanings: [
      "다른 사람의 처지를 헤아리는 마음",
      "남의 아픔을 함께 느끼는 것",
    ],
    answer: "공감",
  },
  {
    meanings: [
      "여러 가지를 한데 모아 정리하는 것",
      "보고서를 만들 때 필요해요",
    ],
    answer: "종합",
  },
  { meanings: ["처음 보거나 겪는 것", "새로운 경험이에요"], answer: "체험" },
  {
    meanings: ["차근차근 순서대로 하는 것", "일을 처리하는 순서예요"],
    answer: "절차",
  },
  {
    meanings: [
      "다른 의견을 가진 사람들이 말로 겨루는 것",
      "찬성과 반대로 나뉘어요",
    ],
    answer: "토론",
  },
  {
    meanings: ["나라에서 국민에게 보장하는 자유", "헌법에 적혀 있어요"],
    answer: "권리",
  },
  {
    meanings: ["어떤 결과를 가져오는 원인", "왜 그렇게 되었는지 설명해요"],
    answer: "요인",
  },
  {
    meanings: ["지나온 과거의 사건과 기록", "옛날 일을 배워요"],
    answer: "역사",
  },
  {
    meanings: ["자연에서 얻는 쓸모 있는 것", "석유, 석탄, 물 등이 있어요"],
    answer: "자원",
  },
  {
    meanings: ["사회에서 서로 지켜야 할 약속", "질서를 위해 필요해요"],
    answer: "규칙",
  },
  {
    meanings: ["어떤 일의 좋은 점과 나쁜 점", "결정을 내리기 전에 따져 봐요"],
    answer: "장단점",
  },
  {
    meanings: [
      "미리 어떤 일이 일어날 것을 짐작하는 것",
      "날씨 예보가 대표적이에요",
    ],
    answer: "예측",
  },
  {
    meanings: ["사물의 겉에 나타나는 모양", "빙산은 이것만 보여요"],
    answer: "표면",
  },
  { meanings: ["깨달아 아는 것", "공부를 통해 얻는 것"], answer: "지식" },
  {
    meanings: ["음식물을 몸에서 분해하는 과정", "위장에서 일어나요"],
    answer: "소화",
  },
  {
    meanings: ["바닷물이 들어오고 나가는 것", "밀물과 썰물이에요"],
    answer: "조수",
  },
  {
    meanings: ["다른 사람을 돌보고 보살피는 것", "사랑과 비슷해요"],
    answer: "배려",
  },
  {
    meanings: ["실수를 줄이기 위해 다시 살펴보는 것", "시험 후에 꼭 해요"],
    answer: "검토",
  },
  {
    meanings: ["한곳에 여러 사람이 모이는 것", "행사나 회의 때 해요"],
    answer: "집합",
  },
  {
    meanings: ["물건이나 돈을 아끼는 것", "불필요한 소비를 줄여요"],
    answer: "절약",
  },
  {
    meanings: ["눈으로 직접 보고 조사하는 것", "과학 수업에서 자주 해요"],
    answer: "관찰",
  },
  {
    meanings: ["앞으로 일어날 일에 대한 걱정", "미래가 불확실할 때 느껴요"],
    answer: "불안",
  },
  {
    meanings: ["어떤 일에 끈기 있게 매달리는 것", "포기하지 않는 것"],
    answer: "인내",
  },
  {
    meanings: ["모양이나 성질이 서로 같은 것", "쌍둥이가 이것이에요"],
    answer: "동일",
  },
  {
    meanings: ["한쪽으로 치우치지 않고 고르게 하는 것", "저울로 맞추는 것"],
    answer: "균형",
  },
  {
    meanings: ["다른 사람에게 자기 생각을 알리는 것", "말이나 글로 해요"],
    answer: "표현",
  },
  { meanings: ["물질이 불에 타는 현상", "산소가 필요해요"], answer: "연소" },
  {
    meanings: ["다른 것과 견주어 보는 것", "차이점을 찾을 때 해요"],
    answer: "비교",
  },
  {
    meanings: ["나쁜 영향을 주는 물질", "공장에서 나오기도 해요"],
    answer: "오염",
  },
  {
    meanings: ["서로 도움을 주고받는 것", "사회는 이것으로 유지돼요"],
    answer: "상호작용",
  },
  {
    meanings: ["오래전부터 전해 내려오는 풍습", "명절에 볼 수 있어요"],
    answer: "전통",
  },
  {
    meanings: ["어떤 대상에 대해 미리 갖는 생각", "사실과 다를 수 있어요"],
    answer: "편견",
  },
  {
    meanings: ["과거의 잘못을 고치는 것", "더 나은 방향으로 바꿔요"],
    answer: "개선",
  },
  {
    meanings: [
      "자연의 아름다움이나 문화적 가치가 있는 곳",
      "나라에서 보호해요",
    ],
    answer: "유산",
  },
  {
    meanings: ["여러 사람이 함께 힘을 합치는 것", "팀워크와 비슷해요"],
    answer: "협동",
  },
  {
    meanings: ["배운 것을 되풀이하여 익히는 것", "실력 향상에 꼭 필요해요"],
    answer: "연습",
  },
  {
    meanings: ["원래 모습을 그대로 유지하는 것", "문화재에 필요해요"],
    answer: "보존",
  },
  {
    meanings: ["모르는 것을 찾아 알아내는 것", "호기심에서 시작해요"],
    answer: "탐구",
  },
  {
    meanings: ["시대의 변화에 맞게 바꾸는 것", "기술 발전이 이끌어요"],
    answer: "혁신",
  },
  {
    meanings: ["나라 사이의 교류", "문화나 경제에서 이루어져요"],
    answer: "국제",
  },
  { meanings: ["사물의 참된 모습", "거짓의 반대예요"], answer: "진실" },
  {
    meanings: ["목표를 이루기 위해 세우는 방법", "계획을 짤 때 필요해요"],
    answer: "전략",
  },
  {
    meanings: ["여러 사람 앞에서 의견을 말하는 것", "학교에서 자주 해요"],
    answer: "발표",
  },
  { meanings: ["물건을 만드는 과정", "공장에서 이루어져요"], answer: "생산" },
  {
    meanings: ["잘못된 것을 바로잡는 것", "오답을 고치는 것도 이것이에요"],
    answer: "수정",
  },
];

// ===== 수학 데이터 (80개) =====
export const grade5MathData: MathEntry[] = [
  // 기존 22개
  // 약수와 배수
  {
    type: "calculation",
    expression: "24의 약수",
    answer: 8,
    steps: ["1, 2, 3, 4, 6, 8, 12, 24", "약수의 개수: 8개"],
    unit: "약수와 배수",
  },
  {
    type: "calculation",
    expression: "12와 18의 최대공약수",
    answer: 6,
    steps: [
      "12의 약수: 1, 2, 3, 4, 6, 12",
      "18의 약수: 1, 2, 3, 6, 9, 18",
      "공약수: 1, 2, 3, 6",
      "최대공약수: 6",
    ],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "4와 6의 최소공배수",
    answer: 12,
    steps: [
      "4의 배수: 4, 8, 12, 16, ...",
      "6의 배수: 6, 12, 18, ...",
      "최소공배수: 12",
    ],
    unit: "최소공배수",
  },
  {
    type: "calculation",
    expression: "15와 20의 최대공약수",
    answer: 5,
    steps: ["15 = 3 × 5", "20 = 2 × 2 × 5", "공통 소인수: 5", "최대공약수: 5"],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "8과 12의 최소공배수",
    answer: 24,
    steps: [
      "8 = 2 × 2 × 2",
      "12 = 2 × 2 × 3",
      "최소공배수: 2 × 2 × 2 × 3 = 24",
    ],
    unit: "최소공배수",
  },
  // 분모가 다른 분수 덧셈/뺄셈
  {
    type: "calculation",
    expression: "1/3 + 1/4",
    answer: 7,
    steps: ["통분: 4/12 + 3/12", "분자끼리 더하기: 4 + 3 = 7", "답: 7/12"],
    unit: "분수 덧셈",
    numbers: [1, 3, 1, 4],
  },
  {
    type: "calculation",
    expression: "2/5 + 1/3",
    answer: 11,
    steps: ["통분: 6/15 + 5/15", "분자끼리 더하기: 6 + 5 = 11", "답: 11/15"],
    unit: "분수 덧셈",
    numbers: [2, 5, 1, 3],
  },
  {
    type: "calculation",
    expression: "3/4 - 1/6",
    answer: 7,
    steps: ["통분: 9/12 - 2/12", "분자끼리 빼기: 9 - 2 = 7", "답: 7/12"],
    unit: "분수 뺄셈",
    numbers: [3, 4, 1, 6],
  },
  {
    type: "calculation",
    expression: "5/6 - 2/9",
    answer: 11,
    steps: ["통분: 15/18 - 4/18", "분자끼리 빼기: 15 - 4 = 11", "답: 11/18"],
    unit: "분수 뺄셈",
    numbers: [5, 6, 2, 9],
  },
  // 분수의 곱셈
  {
    type: "calculation",
    expression: "2/3 × 3/4",
    answer: 6,
    steps: [
      "분자끼리 곱하기: 2 × 3 = 6",
      "분모끼리 곱하기: 3 × 4 = 12",
      "6/12 = 1/2",
      "약분한 답: 1/2",
    ],
    unit: "분수의 곱셈",
    numbers: [2, 3, 3, 4],
  },
  {
    type: "calculation",
    expression: "4/5 × 5/8",
    answer: 20,
    steps: [
      "분자끼리 곱하기: 4 × 5 = 20",
      "분모끼리 곱하기: 5 × 8 = 40",
      "20/40 = 1/2",
    ],
    unit: "분수의 곱셈",
    numbers: [4, 5, 5, 8],
  },
  {
    type: "calculation",
    expression: "3 × 2/5",
    answer: 6,
    steps: [
      "3/1 × 2/5",
      "분자끼리 곱하기: 3 × 2 = 6",
      "분모: 5",
      "답: 6/5 = 1과 1/5",
    ],
    unit: "분수의 곱셈",
    numbers: [3, 1, 2, 5],
  },
  // 소수의 곱셈
  {
    type: "calculation",
    expression: "2.4 × 3",
    answer: 7.2,
    steps: ["24 × 3 = 72", "소수점 한 자리이므로", "답: 7.2"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "1.5 × 2.4",
    answer: 3.6,
    steps: [
      "15 × 24 = 360",
      "소수점 아래 자릿수의 합: 2자리",
      "답: 3.60 = 3.6",
    ],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "0.7 × 0.8",
    answer: 0.56,
    steps: ["7 × 8 = 56", "소수점 아래 자릿수의 합: 2자리", "답: 0.56"],
    unit: "소수의 곱셈",
  },
  // 넓이
  {
    type: "calculation",
    expression: "가로 8cm, 세로 5cm 직사각형의 넓이",
    answer: 40,
    steps: ["직사각형의 넓이 = 가로 × 세로", "8 × 5 = 40", "답: 40cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 10cm, 높이 6cm 삼각형의 넓이",
    answer: 30,
    steps: ["삼각형의 넓이 = 밑변 × 높이 ÷ 2", "10 × 6 ÷ 2 = 30", "답: 30cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 12cm, 높이 8cm 평행사변형의 넓이",
    answer: 96,
    steps: ["평행사변형의 넓이 = 밑변 × 높이", "12 × 8 = 96", "답: 96cm²"],
    unit: "넓이",
  },
  // 평균
  {
    type: "calculation",
    expression: "85, 90, 75, 80, 70의 평균",
    answer: 80,
    steps: [
      "합계: 85 + 90 + 75 + 80 + 70 = 400",
      "개수: 5개",
      "평균: 400 ÷ 5 = 80",
    ],
    unit: "평균",
  },
  {
    type: "calculation",
    expression: "92, 88, 76, 84의 평균",
    answer: 85,
    steps: ["합계: 92 + 88 + 76 + 84 = 340", "개수: 4개", "평균: 340 ÷ 4 = 85"],
    unit: "평균",
  },

  // ===== 추가 58개 (총 80개) =====
  // 약수와 배수 추가
  {
    type: "calculation",
    expression: "36의 약수의 개수",
    answer: 9,
    steps: ["1, 2, 3, 4, 6, 9, 12, 18, 36", "약수의 개수: 9개"],
    unit: "약수와 배수",
  },
  {
    type: "calculation",
    expression: "42의 약수의 개수",
    answer: 8,
    steps: ["1, 2, 3, 6, 7, 14, 21, 42", "약수의 개수: 8개"],
    unit: "약수와 배수",
  },
  {
    type: "calculation",
    expression: "18과 24의 최대공약수",
    answer: 6,
    steps: ["18 = 2 × 3 × 3", "24 = 2 × 2 × 2 × 3", "공통 소인수: 2 × 3 = 6"],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "16과 24의 최대공약수",
    answer: 8,
    steps: [
      "16 = 2 × 2 × 2 × 2",
      "24 = 2 × 2 × 2 × 3",
      "공통 소인수: 2 × 2 × 2 = 8",
    ],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "9와 12의 최소공배수",
    answer: 36,
    steps: ["9 = 3 × 3", "12 = 2 × 2 × 3", "최소공배수: 2 × 2 × 3 × 3 = 36"],
    unit: "최소공배수",
  },
  {
    type: "calculation",
    expression: "6과 10의 최소공배수",
    answer: 30,
    steps: ["6 = 2 × 3", "10 = 2 × 5", "최소공배수: 2 × 3 × 5 = 30"],
    unit: "최소공배수",
  },
  {
    type: "calculation",
    expression: "14와 21의 최대공약수",
    answer: 7,
    steps: ["14 = 2 × 7", "21 = 3 × 7", "공통 소인수: 7"],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "10과 15의 최소공배수",
    answer: 30,
    steps: ["10 = 2 × 5", "15 = 3 × 5", "최소공배수: 2 × 3 × 5 = 30"],
    unit: "최소공배수",
  },
  {
    type: "calculation",
    expression: "20과 30의 최대공약수",
    answer: 10,
    steps: ["20 = 2 × 2 × 5", "30 = 2 × 3 × 5", "공통 소인수: 2 × 5 = 10"],
    unit: "최대공약수",
  },
  {
    type: "calculation",
    expression: "12와 15와 18의 최소공배수",
    answer: 180,
    steps: [
      "12 = 2² × 3",
      "15 = 3 × 5",
      "18 = 2 × 3²",
      "최소공배수: 2² × 3² × 5 = 180",
    ],
    unit: "최소공배수",
  },

  // 분수 덧셈/뺄셈 추가
  {
    type: "calculation",
    expression: "1/2 + 1/5",
    answer: 7,
    steps: ["통분: 5/10 + 2/10", "분자끼리 더하기: 5 + 2 = 7", "답: 7/10"],
    unit: "분수 덧셈",
    numbers: [1, 2, 1, 5],
  },
  {
    type: "calculation",
    expression: "3/8 + 1/4",
    answer: 5,
    steps: ["통분: 3/8 + 2/8", "분자끼리 더하기: 3 + 2 = 5", "답: 5/8"],
    unit: "분수 덧셈",
    numbers: [3, 8, 1, 4],
  },
  {
    type: "calculation",
    expression: "2/3 + 3/5",
    answer: 19,
    steps: [
      "통분: 10/15 + 9/15",
      "분자끼리 더하기: 10 + 9 = 19",
      "답: 19/15 = 1과 4/15",
    ],
    unit: "분수 덧셈",
    numbers: [2, 3, 3, 5],
  },
  {
    type: "calculation",
    expression: "5/8 - 1/3",
    answer: 7,
    steps: ["통분: 15/24 - 8/24", "분자끼리 빼기: 15 - 8 = 7", "답: 7/24"],
    unit: "분수 뺄셈",
    numbers: [5, 8, 1, 3],
  },
  {
    type: "calculation",
    expression: "7/10 - 2/5",
    answer: 3,
    steps: ["통분: 7/10 - 4/10", "분자끼리 빼기: 7 - 4 = 3", "답: 3/10"],
    unit: "분수 뺄셈",
    numbers: [7, 10, 2, 5],
  },
  {
    type: "calculation",
    expression: "4/7 + 2/3",
    answer: 26,
    steps: [
      "통분: 12/21 + 14/21",
      "분자끼리 더하기: 12 + 14 = 26",
      "답: 26/21 = 1과 5/21",
    ],
    unit: "분수 덧셈",
    numbers: [4, 7, 2, 3],
  },
  {
    type: "calculation",
    expression: "11/12 - 3/4",
    answer: 2,
    steps: [
      "통분: 11/12 - 9/12",
      "분자끼리 빼기: 11 - 9 = 2",
      "답: 2/12 = 1/6",
    ],
    unit: "분수 뺄셈",
    numbers: [11, 12, 3, 4],
  },
  {
    type: "calculation",
    expression: "1/6 + 3/8",
    answer: 13,
    steps: ["통분: 4/24 + 9/24", "분자끼리 더하기: 4 + 9 = 13", "답: 13/24"],
    unit: "분수 덧셈",
    numbers: [1, 6, 3, 8],
  },

  // 분수의 곱셈 추가
  {
    type: "calculation",
    expression: "1/4 × 2/3",
    answer: 2,
    steps: [
      "분자끼리 곱하기: 1 × 2 = 2",
      "분모끼리 곱하기: 4 × 3 = 12",
      "2/12 = 1/6",
    ],
    unit: "분수의 곱셈",
    numbers: [1, 4, 2, 3],
  },
  {
    type: "calculation",
    expression: "5/6 × 3/10",
    answer: 15,
    steps: [
      "분자끼리 곱하기: 5 × 3 = 15",
      "분모끼리 곱하기: 6 × 10 = 60",
      "15/60 = 1/4",
    ],
    unit: "분수의 곱셈",
    numbers: [5, 6, 3, 10],
  },
  {
    type: "calculation",
    expression: "7 × 3/14",
    answer: 21,
    steps: [
      "7/1 × 3/14",
      "분자끼리 곱하기: 7 × 3 = 21",
      "분모: 14",
      "답: 21/14 = 3/2 = 1과 1/2",
    ],
    unit: "분수의 곱셈",
    numbers: [7, 1, 3, 14],
  },
  {
    type: "calculation",
    expression: "2/9 × 3/4",
    answer: 6,
    steps: [
      "분자끼리 곱하기: 2 × 3 = 6",
      "분모끼리 곱하기: 9 × 4 = 36",
      "6/36 = 1/6",
    ],
    unit: "분수의 곱셈",
    numbers: [2, 9, 3, 4],
  },
  {
    type: "calculation",
    expression: "5 × 4/15",
    answer: 20,
    steps: [
      "5/1 × 4/15",
      "분자끼리 곱하기: 5 × 4 = 20",
      "분모: 15",
      "답: 20/15 = 4/3 = 1과 1/3",
    ],
    unit: "분수의 곱셈",
    numbers: [5, 1, 4, 15],
  },
  {
    type: "calculation",
    expression: "3/7 × 7/9",
    answer: 21,
    steps: [
      "분자끼리 곱하기: 3 × 7 = 21",
      "분모끼리 곱하기: 7 × 9 = 63",
      "21/63 = 1/3",
    ],
    unit: "분수의 곱셈",
    numbers: [3, 7, 7, 9],
  },

  // 소수의 곱셈 추가
  {
    type: "calculation",
    expression: "3.5 × 4",
    answer: 14,
    steps: ["35 × 4 = 140", "소수점 한 자리이므로", "답: 14.0 = 14"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "0.25 × 4",
    answer: 1,
    steps: ["25 × 4 = 100", "소수점 아래 자릿수: 2자리", "답: 1.00 = 1"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "1.2 × 1.5",
    answer: 1.8,
    steps: [
      "12 × 15 = 180",
      "소수점 아래 자릿수의 합: 2자리",
      "답: 1.80 = 1.8",
    ],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "0.6 × 0.5",
    answer: 0.3,
    steps: ["6 × 5 = 30", "소수점 아래 자릿수의 합: 2자리", "답: 0.30 = 0.3"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "4.2 × 2.1",
    answer: 8.82,
    steps: ["42 × 21 = 882", "소수점 아래 자릿수의 합: 2자리", "답: 8.82"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "0.12 × 5",
    answer: 0.6,
    steps: ["12 × 5 = 60", "소수점 아래 자릿수: 2자리", "답: 0.60 = 0.6"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "2.5 × 2.5",
    answer: 6.25,
    steps: ["25 × 25 = 625", "소수점 아래 자릿수의 합: 2자리", "답: 6.25"],
    unit: "소수의 곱셈",
  },
  {
    type: "calculation",
    expression: "0.3 × 0.3",
    answer: 0.09,
    steps: ["3 × 3 = 9", "소수점 아래 자릿수의 합: 2자리", "답: 0.09"],
    unit: "소수의 곱셈",
  },

  // 넓이 추가
  {
    type: "calculation",
    expression: "가로 15cm, 세로 9cm 직사각형의 넓이",
    answer: 135,
    steps: ["직사각형의 넓이 = 가로 × 세로", "15 × 9 = 135", "답: 135cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 14cm, 높이 10cm 삼각형의 넓이",
    answer: 70,
    steps: ["삼각형의 넓이 = 밑변 × 높이 ÷ 2", "14 × 10 ÷ 2 = 70", "답: 70cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 9cm, 높이 7cm 평행사변형의 넓이",
    answer: 63,
    steps: ["평행사변형의 넓이 = 밑변 × 높이", "9 × 7 = 63", "답: 63cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "윗변 4cm, 아랫변 8cm, 높이 5cm 사다리꼴의 넓이",
    answer: 30,
    steps: [
      "사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2",
      "(4 + 8) × 5 ÷ 2 = 30",
      "답: 30cm²",
    ],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "대각선이 6cm, 10cm인 마름모의 넓이",
    answer: 30,
    steps: [
      "마름모의 넓이 = 대각선 × 대각선 ÷ 2",
      "6 × 10 ÷ 2 = 30",
      "답: 30cm²",
    ],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "가로 20cm, 세로 12cm 직사각형의 넓이",
    answer: 240,
    steps: ["직사각형의 넓이 = 가로 × 세로", "20 × 12 = 240", "답: 240cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "밑변 16cm, 높이 9cm 삼각형의 넓이",
    answer: 72,
    steps: ["삼각형의 넓이 = 밑변 × 높이 ÷ 2", "16 × 9 ÷ 2 = 72", "답: 72cm²"],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "윗변 6cm, 아랫변 10cm, 높이 8cm 사다리꼴의 넓이",
    answer: 64,
    steps: [
      "사다리꼴의 넓이 = (윗변 + 아랫변) × 높이 ÷ 2",
      "(6 + 10) × 8 ÷ 2 = 64",
      "답: 64cm²",
    ],
    unit: "넓이",
  },
  {
    type: "calculation",
    expression: "대각선이 8cm, 12cm인 마름모의 넓이",
    answer: 48,
    steps: [
      "마름모의 넓이 = 대각선 × 대각선 ÷ 2",
      "8 × 12 ÷ 2 = 48",
      "답: 48cm²",
    ],
    unit: "넓이",
  },

  // 평균 추가
  {
    type: "calculation",
    expression: "78, 82, 90, 86, 94의 평균",
    answer: 86,
    steps: [
      "합계: 78 + 82 + 90 + 86 + 94 = 430",
      "개수: 5개",
      "평균: 430 ÷ 5 = 86",
    ],
    unit: "평균",
  },
  {
    type: "calculation",
    expression: "60, 70, 80, 90의 평균",
    answer: 75,
    steps: ["합계: 60 + 70 + 80 + 90 = 300", "개수: 4개", "평균: 300 ÷ 4 = 75"],
    unit: "평균",
  },
  {
    type: "calculation",
    expression: "95, 85, 75, 100, 70, 75의 평균",
    answer: 83,
    steps: [
      "합계: 95 + 85 + 75 + 100 + 70 + 75 = 500",
      "개수: 6개",
      "평균: 500 ÷ 6 ≈ 83.3 → 83",
    ],
    unit: "평균",
  },
  {
    type: "calculation",
    expression: "88, 92, 96, 84의 평균",
    answer: 90,
    steps: ["합계: 88 + 92 + 96 + 84 = 360", "개수: 4개", "평균: 360 ÷ 4 = 90"],
    unit: "평균",
  },
  {
    type: "calculation",
    expression: "45, 55, 65, 75, 60의 평균",
    answer: 60,
    steps: [
      "합계: 45 + 55 + 65 + 75 + 60 = 300",
      "개수: 5개",
      "평균: 300 ÷ 5 = 60",
    ],
    unit: "평균",
  },

  // 혼합 계산
  {
    type: "calculation",
    expression: "3 + 4 × 5",
    answer: 23,
    steps: ["곱셈을 먼저 계산: 4 × 5 = 20", "덧셈: 3 + 20 = 23"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "48 ÷ 6 + 7 × 2",
    answer: 22,
    steps: ["나눗셈: 48 ÷ 6 = 8", "곱셈: 7 × 2 = 14", "덧셈: 8 + 14 = 22"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "(15 + 9) ÷ 6",
    answer: 4,
    steps: ["괄호 먼저: 15 + 9 = 24", "나눗셈: 24 ÷ 6 = 4"],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "100 - 3 × (8 + 12)",
    answer: 40,
    steps: [
      "괄호 먼저: 8 + 12 = 20",
      "곱셈: 3 × 20 = 60",
      "뺄셈: 100 - 60 = 40",
    ],
    unit: "혼합 계산",
  },
  {
    type: "calculation",
    expression: "72 ÷ (4 + 5) × 2",
    answer: 16,
    steps: ["괄호 먼저: 4 + 5 = 9", "나눗셈: 72 ÷ 9 = 8", "곱셈: 8 × 2 = 16"],
    unit: "혼합 계산",
  },

  // 약분과 통분
  {
    type: "calculation",
    expression: "8/12을 약분하면 분자는?",
    answer: 2,
    steps: ["8과 12의 최대공약수: 4", "8 ÷ 4 = 2, 12 ÷ 4 = 3", "답: 2/3"],
    unit: "약분과 통분",
  },
  {
    type: "calculation",
    expression: "15/25를 약분하면 분자는?",
    answer: 3,
    steps: ["15와 25의 최대공약수: 5", "15 ÷ 5 = 3, 25 ÷ 5 = 5", "답: 3/5"],
    unit: "약분과 통분",
  },
  {
    type: "calculation",
    expression: "2/3과 3/4의 통분 (공통분모)",
    answer: 12,
    steps: ["3과 4의 최소공배수: 12", "2/3 = 8/12, 3/4 = 9/12", "공통분모: 12"],
    unit: "약분과 통분",
  },
  {
    type: "calculation",
    expression: "1/6과 2/9의 통분 (공통분모)",
    answer: 18,
    steps: ["6과 9의 최소공배수: 18", "1/6 = 3/18, 2/9 = 4/18", "공통분모: 18"],
    unit: "약분과 통분",
  },

  // 선대칭, 점대칭
  {
    type: "calculation",
    expression: "정사각형의 대칭축의 수",
    answer: 4,
    steps: [
      "가로 대칭축 1개",
      "세로 대칭축 1개",
      "대각선 대칭축 2개",
      "총 4개",
    ],
    unit: "합동과 대칭",
  },
  {
    type: "calculation",
    expression: "정삼각형의 대칭축의 수",
    answer: 3,
    steps: ["각 꼭짓점에서 대변의 중점으로 1개씩", "총 3개"],
    unit: "합동과 대칭",
  },
  {
    type: "calculation",
    expression: "정오각형의 대칭축의 수",
    answer: 5,
    steps: ["정n각형의 대칭축의 수 = n", "정오각형: 5개"],
    unit: "합동과 대칭",
  },
  {
    type: "calculation",
    expression: "정육각형의 대칭축의 수",
    answer: 6,
    steps: ["정n각형의 대칭축의 수 = n", "정육각형: 6개"],
    unit: "합동과 대칭",
  },
  // 추가 1개 (80개 달성)
  {
    type: "calculation",
    expression: "원의 대칭축의 수",
    answer: 0,
    steps: ["원은 대칭축이 무수히 많다", "셀 수 없이 많으므로 무한개"],
    unit: "합동과 대칭",
  },
];

// ===== 상식 데이터 (60개) =====
export const grade5KnowledgeData: KnowledgeEntry[] = [
  // 기존 15개
  {
    text: "한반도의 기후는 대체로 ___대 기후에 속한다.",
    answer: "온",
    category: "지리",
  },
  {
    text: "우리나라 최초의 헌법은 ___년에 제정되었다.",
    answer: "1948",
    category: "역사",
  },
  {
    text: "세포에서 에너지를 만드는 기관은 ___이다.",
    answer: "미토콘드리아",
    category: "과학",
  },
  {
    text: "지구의 자전 방향은 ___에서 동이다.",
    answer: "서",
    category: "과학",
  },
  { text: "삼국을 통일한 나라는 ___이다.", answer: "신라", category: "역사" },
  {
    text: "물질의 가장 작은 단위를 ___이라 한다.",
    answer: "원자",
    category: "과학",
  },
  {
    text: "국회에서 법을 만드는 것을 ___이라 한다.",
    answer: "입법",
    category: "사회",
  },
  {
    text: "조선 시대의 신분 제도는 양반, 중인, 상민, ___이 있다.",
    answer: "천민",
    category: "역사",
  },
  {
    text: "식물의 기공에서는 ___와 산소를 교환한다.",
    answer: "이산화탄소",
    category: "과학",
  },
  {
    text: "대한민국의 3권 분립은 입법, 행정, ___이다.",
    answer: "사법",
    category: "사회",
  },
  { text: "속력의 단위는 ___이다.", answer: "km/h", category: "과학" },
  {
    text: "소수점 아래 첫째 자리 숫자를 ___의 자리라 한다.",
    answer: "소수 첫째",
    category: "수학",
  },
  { text: "6·25 전쟁은 ___년에 시작되었다.", answer: "1950", category: "역사" },
  {
    text: "혈액을 온몸으로 보내는 기관을 ___이라 한다.",
    answer: "심장",
    category: "과학",
  },
  {
    text: "우리나라의 경제 체제는 ___경제이다.",
    answer: "시장",
    category: "사회",
  },
  // 추가 45개 (총 60개)
  {
    text: "우리나라에서 가장 긴 강은 ___이다.",
    answer: "낙동강",
    category: "지리",
  },
  {
    text: "고구려, 백제, 신라를 합쳐 ___시대라 한다.",
    answer: "삼국",
    category: "역사",
  },
  {
    text: "한글을 만든 조선의 왕은 ___이다.",
    answer: "세종대왕",
    category: "역사",
  },
  { text: "우리나라의 수도는 ___이다.", answer: "서울", category: "지리" },
  {
    text: "독도는 행정구역상 ___도에 속한다.",
    answer: "경상북",
    category: "지리",
  },
  {
    text: "백두산의 꼭대기에는 ___이라는 호수가 있다.",
    answer: "천지",
    category: "지리",
  },
  {
    text: "세계에서 가장 넓은 바다는 ___이다.",
    answer: "태평양",
    category: "지리",
  },
  {
    text: "우리나라의 전통 온돌은 ___난방 방식이다.",
    answer: "바닥",
    category: "문화",
  },
  { text: "조선을 세운 사람은 ___이다.", answer: "이성계", category: "역사" },
  {
    text: "임진왜란 때 바다에서 활약한 장군은 ___이다.",
    answer: "이순신",
    category: "역사",
  },
  { text: "고려를 세운 사람은 ___이다.", answer: "왕건", category: "역사" },
  {
    text: "우리나라 국보 제1호였던 문화재는 ___이다.",
    answer: "숭례문",
    category: "문화",
  },
  {
    text: "제주도는 ___으로 만들어진 화산섬이다.",
    answer: "현무암",
    category: "지리",
  },
  {
    text: "한반도는 ___대륙의 동쪽에 위치한다.",
    answer: "아시아",
    category: "지리",
  },
  { text: "대한민국의 국화는 ___이다.", answer: "무궁화", category: "문화" },
  {
    text: "태양계에서 가장 큰 행성은 ___이다.",
    answer: "목성",
    category: "과학",
  },
  {
    text: "물이 100도에서 끓는 것은 ___변화이다.",
    answer: "상태",
    category: "과학",
  },
  {
    text: "지구에서 달까지의 평균 거리는 약 ___만 km이다.",
    answer: "38",
    category: "과학",
  },
  {
    text: "식물의 뿌리가 하는 일은 물과 ___을 흡수하는 것이다.",
    answer: "양분",
    category: "과학",
  },
  {
    text: "곤충의 몸은 머리, 가슴, ___의 세 부분으로 나뉜다.",
    answer: "배",
    category: "과학",
  },
  { text: "대한민국의 국기는 ___이다.", answer: "태극기", category: "문화" },
  {
    text: "유네스코에 등재된 한국의 기록 유산 중 하나는 ___이다.",
    answer: "훈민정음",
    category: "문화",
  },
  {
    text: "위도가 높아질수록 기온은 ___해진다.",
    answer: "낮아",
    category: "지리",
  },
  {
    text: "우리나라에서 가장 높은 산은 ___이다.",
    answer: "한라산",
    category: "지리",
  },
  { text: "광복절은 매년 ___월 15일이다.", answer: "8", category: "역사" },
  {
    text: "세계 문화유산으로 지정된 조선의 궁궐은 ___이다.",
    answer: "창덕궁",
    category: "문화",
  },
  {
    text: "식물이 스스로 양분을 만드는 과정을 ___이라 한다.",
    answer: "광합성",
    category: "과학",
  },
  {
    text: "우리나라 화폐에 그려진 1만원권의 인물은 ___이다.",
    answer: "세종대왕",
    category: "문화",
  },
  {
    text: "조선 시대 과거 시험의 최종 단계를 ___이라 한다.",
    answer: "전시",
    category: "역사",
  },
  {
    text: "태양에서 세 번째로 가까운 행성은 ___이다.",
    answer: "지구",
    category: "과학",
  },
  {
    text: "우리나라에서 가장 큰 섬은 ___이다.",
    answer: "제주도",
    category: "지리",
  },
  { text: "고인돌은 ___시대의 무덤이다.", answer: "청동기", category: "역사" },
  { text: "경주는 ___의 수도였다.", answer: "신라", category: "역사" },
  {
    text: "우리나라의 전통 악기 중 현악기인 것은 ___이다.",
    answer: "가야금",
    category: "문화",
  },
  {
    text: "지구의 내부 구조 중 가장 바깥층을 ___이라 한다.",
    answer: "지각",
    category: "과학",
  },
  {
    text: "독립선언서를 읽은 곳은 서울 ___공원이다.",
    answer: "탑골",
    category: "역사",
  },
  {
    text: "우리나라의 전통 한옥 지붕 재료는 주로 ___이다.",
    answer: "기와",
    category: "문화",
  },
  {
    text: "5·18 민주화운동이 일어난 도시는 ___이다.",
    answer: "광주",
    category: "역사",
  },
  {
    text: "우리나라에서 쌀 생산량이 가장 많은 지역은 ___평야이다.",
    answer: "호남",
    category: "지리",
  },
  {
    text: "조선 시대 지방을 다스리던 관리를 ___이라 했다.",
    answer: "수령",
    category: "역사",
  },
  { text: "우리나라의 전통 달력은 ___력이다.", answer: "음", category: "문화" },
  {
    text: "대한민국의 국보 제1호 지정 체계는 ___년에 폐지되었다.",
    answer: "2021",
    category: "문화",
  },
  {
    text: "지구에서 가장 많은 물은 ___에 있다.",
    answer: "바다",
    category: "과학",
  },
  {
    text: "우리나라에서 벼농사를 가장 많이 짓는 지역은 ___지방이다.",
    answer: "호남",
    category: "지리",
  },
  { text: "고려의 수도는 지금의 ___시이다.", answer: "개성", category: "역사" },
];

// ===== 안전 데이터 (40개) =====
export const grade5SafetyData: SafetyEntry[] = [
  // 기존 10개
  {
    text: "개인정보를 요구하는 이메일은 ___일 수 있다.",
    answer: "피싱",
    category: "정보안전",
  },
  {
    text: "SNS에 위치 정보를 올리면 ___의 위험이 있다.",
    answer: "사생활 침해",
    category: "정보안전",
  },
  {
    text: "실험 중 화학 약품이 피부에 닿으면 즉시 ___로 씻는다.",
    answer: "흐르는 물",
    category: "실험안전",
  },
  {
    text: "황사가 심한 날에는 ___을 착용하고 외출한다.",
    answer: "마스크",
    category: "건강안전",
  },
  {
    text: "응급 상황 시 ___을 실시하면 생명을 구할 수 있다.",
    answer: "심폐소생술",
    category: "응급안전",
  },
  {
    text: "산에서 길을 잃으면 ___으로 이동하지 말고 제자리에서 구조를 기다린다.",
    answer: "아래",
    category: "생활안전",
  },
  {
    text: "음식물에 의한 기도 폐쇄 시 ___법을 실시한다.",
    answer: "하임리히",
    category: "응급안전",
  },
  {
    text: "폭염 시 야외 활동을 ___하고 시원한 곳에 머문다.",
    answer: "자제",
    category: "건강안전",
  },
  {
    text: "낯선 사람의 택배를 대신 ___하면 안 된다.",
    answer: "수령",
    category: "생활안전",
  },
  {
    text: "가정 내 비상 약품함에는 ___가 비치되어 있어야 한다.",
    answer: "소독약",
    category: "건강안전",
  },
  // 추가 30개 (총 40개)
  {
    text: "화재 발생 시 가장 먼저 ___을 눌러야 한다.",
    answer: "화재 경보기",
    category: "화재안전",
  },
  {
    text: "지진이 발생하면 ___아래로 대피한다.",
    answer: "튼튼한 책상",
    category: "재난안전",
  },
  {
    text: "물놀이할 때는 반드시 ___를 착용해야 한다.",
    answer: "구명조끼",
    category: "수상안전",
  },
  {
    text: "자전거를 탈 때는 반드시 ___를 착용해야 한다.",
    answer: "안전모",
    category: "교통안전",
  },
  {
    text: "횡단보도를 건널 때는 ___을 확인하고 건너야 한다.",
    answer: "신호등",
    category: "교통안전",
  },
  {
    text: "태풍이 올 때 창문에 ___를 붙이면 유리 파편 피해를 줄일 수 있다.",
    answer: "테이프",
    category: "재난안전",
  },
  {
    text: "119는 ___을 신고하는 전화번호이다.",
    answer: "화재와 응급",
    category: "응급안전",
  },
  {
    text: "비밀번호는 ___와 특수문자를 섞어 만들어야 안전하다.",
    answer: "숫자",
    category: "정보안전",
  },
  {
    text: "모르는 사람이 보낸 파일은 ___에 감염될 수 있으므로 열지 않는다.",
    answer: "바이러스",
    category: "정보안전",
  },
  {
    text: "실험실에서는 반드시 ___을 착용하고 실험한다.",
    answer: "보호 안경",
    category: "실험안전",
  },
  {
    text: "전기 콘센트에 물이 닿으면 ___의 위험이 있다.",
    answer: "감전",
    category: "생활안전",
  },
  {
    text: "엘리베이터에 갇혔을 때는 ___를 눌러 구조를 요청한다.",
    answer: "비상벨",
    category: "생활안전",
  },
  {
    text: "약을 먹을 때는 반드시 ___의 지시에 따라야 한다.",
    answer: "의사",
    category: "건강안전",
  },
  {
    text: "길을 건널 때 이어폰을 끼면 ___소리를 듣지 못해 위험하다.",
    answer: "자동차",
    category: "교통안전",
  },
  {
    text: "여름철 식중독 예방을 위해 음식은 충분히 ___해서 먹는다.",
    answer: "익혀",
    category: "건강안전",
  },
  {
    text: "온라인에서 만난 사람을 실제로 ___하면 위험할 수 있다.",
    answer: "만나",
    category: "정보안전",
  },
  {
    text: "화재 시 연기가 많으면 ___를 낮추고 대피한다.",
    answer: "몸",
    category: "화재안전",
  },
  {
    text: "미세먼지가 심한 날은 ___활동을 줄이는 것이 좋다.",
    answer: "바깥",
    category: "건강안전",
  },
  {
    text: "소화기 사용법의 첫 번째 단계는 안전___을 뽑는 것이다.",
    answer: "핀",
    category: "화재안전",
  },
  {
    text: "학교에서 비상 대피 훈련은 ___을 알기 위해 실시한다.",
    answer: "대피 경로",
    category: "학교안전",
  },
  {
    text: "겨울철 빙판길에서는 ___를 짧게 하여 걸어야 한다.",
    answer: "보폭",
    category: "생활안전",
  },
  {
    text: "번개가 칠 때 나무 아래에 서면 ___을 맞을 수 있다.",
    answer: "벼락",
    category: "재난안전",
  },
  {
    text: "개인정보를 온라인에 올릴 때는 ___에 동의해야 한다.",
    answer: "개인정보처리방침",
    category: "정보안전",
  },
  {
    text: "친구가 다쳤을 때 상처 부위를 ___으로 누르면 지혈이 된다.",
    answer: "깨끗한 천",
    category: "응급안전",
  },
  {
    text: "가스 냄새가 나면 ___을 열고 밖으로 대피한다.",
    answer: "창문",
    category: "생활안전",
  },
  {
    text: "야외 활동 시 자외선 차단을 위해 ___를 발라야 한다.",
    answer: "선크림",
    category: "건강안전",
  },
  {
    text: "학교 복도에서 뛰면 ___의 위험이 있다.",
    answer: "충돌",
    category: "학교안전",
  },
  {
    text: "감전 사고 시 전원을 먼저 ___해야 한다.",
    answer: "차단",
    category: "생활안전",
  },
  {
    text: "사이버 ___은 온라인에서 다른 사람을 괴롭히는 행위이다.",
    answer: "불링",
    category: "정보안전",
  },
  {
    text: "비 오는 날 우산 없이 걸으면 ___에 걸릴 수 있다.",
    answer: "감기",
    category: "건강안전",
  },
];

// ===== 한자 데이터 (60개) =====
export const grade5HanjaData: HanjaEntry[] = [
  // 기존 15개
  {
    character: "文",
    reading: "문",
    meaning: "글월 문",
    strokes: 4,
    words: ["문학", "문화", "작문"],
    sentence: "文學 작품을 감상했다.",
  },
  {
    character: "字",
    reading: "자",
    meaning: "글자 자",
    strokes: 6,
    words: ["한자", "문자", "활자"],
    sentence: "한글 字를 바르게 쓰자.",
  },
  {
    character: "書",
    reading: "서",
    meaning: "글 서",
    strokes: 10,
    words: ["서적", "도서", "서예"],
    sentence: "圖書관에서 책을 읽었다.",
  },
  {
    character: "數",
    reading: "수",
    meaning: "셈 수",
    strokes: 15,
    words: ["수학", "숫자", "다수"],
    sentence: "數學 문제를 풀었다.",
  },
  {
    character: "理",
    reading: "리",
    meaning: "다스릴 리",
    strokes: 11,
    words: ["이치", "관리", "도리"],
    sentence: "道理에 맞게 행동하자.",
  },
  {
    character: "科",
    reading: "과",
    meaning: "과목 과",
    strokes: 9,
    words: ["과학", "교과", "과목"],
    sentence: "科學 실험을 했다.",
  },
  {
    character: "東",
    reading: "동",
    meaning: "동녘 동",
    strokes: 8,
    words: ["동쪽", "동양", "극동"],
    sentence: "해가 東쪽에서 뜬다.",
  },
  {
    character: "西",
    reading: "서",
    meaning: "서녘 서",
    strokes: 6,
    words: ["서쪽", "서양", "서울"],
    sentence: "해가 西쪽으로 진다.",
  },
  {
    character: "南",
    reading: "남",
    meaning: "남녘 남",
    strokes: 9,
    words: ["남쪽", "남방", "남극"],
    sentence: "南쪽으로 여행을 갔다.",
  },
  {
    character: "北",
    reading: "북",
    meaning: "북녘 북",
    strokes: 5,
    words: ["북쪽", "북극", "북한"],
    sentence: "나침반은 北쪽을 가리킨다.",
  },
  {
    character: "白",
    reading: "백",
    meaning: "흰 백",
    strokes: 5,
    words: ["백색", "고백", "공백"],
    sentence: "白雪이 온 세상을 덮었다.",
  },
  {
    character: "靑",
    reading: "청",
    meaning: "푸를 청",
    strokes: 8,
    words: ["청소년", "청춘", "청색"],
    sentence: "靑春은 아름답다.",
  },
  {
    character: "年",
    reading: "년",
    meaning: "해 년",
    strokes: 6,
    words: ["연도", "내년", "올해"],
    sentence: "새 年이 밝았다.",
  },
  {
    character: "時",
    reading: "시",
    meaning: "때 시",
    strokes: 10,
    words: ["시간", "시대", "시기"],
    sentence: "時間을 아껴 쓰자.",
  },
  {
    character: "力",
    reading: "력",
    meaning: "힘 력",
    strokes: 2,
    words: ["노력", "체력", "힘"],
    sentence: "努力하면 꿈을 이룰 수 있다.",
  },
  {
    character: "心",
    reading: "심",
    meaning: "마음 심",
    strokes: 4,
    words: ["마음", "양심", "관심"],
    sentence: "善한 心을 가지자.",
  },
  // 추가 44개 (총 60개)
  {
    character: "學",
    reading: "학",
    meaning: "배울 학",
    strokes: 16,
    words: ["학교", "학생", "학문"],
    sentence: "學校에서 열심히 공부했다.",
  },
  {
    character: "校",
    reading: "교",
    meaning: "학교 교",
    strokes: 10,
    words: ["학교", "교실", "교장"],
    sentence: "우리 學校는 아름답다.",
  },
  {
    character: "生",
    reading: "생",
    meaning: "날 생",
    strokes: 5,
    words: ["학생", "생일", "생활"],
    sentence: "生日 축하합니다!",
  },
  {
    character: "先",
    reading: "선",
    meaning: "먼저 선",
    strokes: 6,
    words: ["선생", "조선", "우선"],
    sentence: "先生님을 존경합니다.",
  },
  {
    character: "大",
    reading: "대",
    meaning: "큰 대",
    strokes: 3,
    words: ["대학", "대한", "위대"],
    sentence: "大韓민국은 민주공화국이다.",
  },
  {
    character: "小",
    reading: "소",
    meaning: "작을 소",
    strokes: 3,
    words: ["소년", "소녀", "소학"],
    sentence: "小年은 꿈이 크다.",
  },
  {
    character: "中",
    reading: "중",
    meaning: "가운데 중",
    strokes: 4,
    words: ["중앙", "중심", "중학"],
    sentence: "中心을 잡고 서 보자.",
  },
  {
    character: "上",
    reading: "상",
    meaning: "위 상",
    strokes: 3,
    words: ["상위", "이상", "상급"],
    sentence: "以上으로 발표를 마칩니다.",
  },
  {
    character: "下",
    reading: "하",
    meaning: "아래 하",
    strokes: 3,
    words: ["하위", "이하", "하급"],
    sentence: "以下 내용을 참고하세요.",
  },
  {
    character: "山",
    reading: "산",
    meaning: "뫼 산",
    strokes: 3,
    words: ["산맥", "등산", "화산"],
    sentence: "山에 올라 경치를 보았다.",
  },
  {
    character: "水",
    reading: "수",
    meaning: "물 수",
    strokes: 4,
    words: ["수도", "홍수", "해수"],
    sentence: "깨끗한 水를 마시자.",
  },
  {
    character: "火",
    reading: "화",
    meaning: "불 화",
    strokes: 4,
    words: ["화재", "화산", "소화"],
    sentence: "火災 예방에 힘쓰자.",
  },
  {
    character: "土",
    reading: "토",
    meaning: "흙 토",
    strokes: 3,
    words: ["토지", "국토", "토양"],
    sentence: "國土를 소중히 여기자.",
  },
  {
    character: "金",
    reading: "금",
    meaning: "쇠 금",
    strokes: 8,
    words: ["금속", "황금", "세금"],
    sentence: "黃金보다 귀한 것은 건강이다.",
  },
  {
    character: "木",
    reading: "목",
    meaning: "나무 목",
    strokes: 4,
    words: ["목재", "수목", "목요일"],
    sentence: "나무(木)를 소중히 하자.",
  },
  {
    character: "日",
    reading: "일",
    meaning: "날 일",
    strokes: 4,
    words: ["일요일", "매일", "생일"],
    sentence: "每日 열심히 공부하자.",
  },
  {
    character: "月",
    reading: "월",
    meaning: "달 월",
    strokes: 4,
    words: ["월요일", "정월", "세월"],
    sentence: "歲月이 빨리 지나간다.",
  },
  {
    character: "天",
    reading: "천",
    meaning: "하늘 천",
    strokes: 4,
    words: ["천재", "천연", "하늘"],
    sentence: "天然 자원을 보호하자.",
  },
  {
    character: "地",
    reading: "지",
    meaning: "땅 지",
    strokes: 6,
    words: ["지구", "토지", "지도"],
    sentence: "地球를 보호하자.",
  },
  {
    character: "人",
    reading: "인",
    meaning: "사람 인",
    strokes: 2,
    words: ["인간", "인구", "인류"],
    sentence: "人間은 사회적 동물이다.",
  },
  {
    character: "民",
    reading: "민",
    meaning: "백성 민",
    strokes: 5,
    words: ["국민", "민주", "시민"],
    sentence: "國民의 권리를 존중하자.",
  },
  {
    character: "國",
    reading: "국",
    meaning: "나라 국",
    strokes: 11,
    words: ["국가", "한국", "외국"],
    sentence: "우리 國家를 사랑하자.",
  },
  {
    character: "王",
    reading: "왕",
    meaning: "임금 왕",
    strokes: 4,
    words: ["국왕", "왕자", "왕비"],
    sentence: "세종대王은 훈민정음을 만드셨다.",
  },
  {
    character: "正",
    reading: "정",
    meaning: "바를 정",
    strokes: 5,
    words: ["정직", "정의", "바르다"],
    sentence: "正直한 사람이 되자.",
  },
  {
    character: "足",
    reading: "족",
    meaning: "발 족",
    strokes: 7,
    words: ["만족", "부족", "족적"],
    sentence: "滿足스러운 결과를 얻었다.",
  },
  {
    character: "手",
    reading: "수",
    meaning: "손 수",
    strokes: 4,
    words: ["수공", "선수", "악수"],
    sentence: "선手처럼 멋지게 뛰었다.",
  },
  {
    character: "目",
    reading: "목",
    meaning: "눈 목",
    strokes: 5,
    words: ["목표", "주목", "과목"],
    sentence: "目標를 세우고 노력하자.",
  },
  {
    character: "口",
    reading: "구",
    meaning: "입 구",
    strokes: 3,
    words: ["인구", "입구", "구호"],
    sentence: "人口가 많은 도시이다.",
  },
  {
    character: "耳",
    reading: "이",
    meaning: "귀 이",
    strokes: 6,
    words: ["이목", "이비인후과"],
    sentence: "耳目을 집중하자.",
  },
  {
    character: "長",
    reading: "장",
    meaning: "긴 장",
    strokes: 8,
    words: ["장점", "성장", "회장"],
    sentence: "成長하는 모습이 보기 좋다.",
  },
  {
    character: "明",
    reading: "명",
    meaning: "밝을 명",
    strokes: 8,
    words: ["설명", "발명", "명절"],
    sentence: "發明은 생활을 편리하게 한다.",
  },
  {
    character: "方",
    reading: "방",
    meaning: "모 방",
    strokes: 4,
    words: ["방법", "방향", "사방"],
    sentence: "올바른 方法을 찾자.",
  },
  {
    character: "入",
    reading: "입",
    meaning: "들 입",
    strokes: 2,
    words: ["입학", "수입", "투입"],
    sentence: "入學을 축하합니다.",
  },
  {
    character: "出",
    reading: "출",
    meaning: "날 출",
    strokes: 5,
    words: ["출발", "수출", "출석"],
    sentence: "出發 시간을 확인하자.",
  },
  {
    character: "食",
    reading: "식",
    meaning: "먹을 식",
    strokes: 9,
    words: ["식사", "음식", "식당"],
    sentence: "음食을 골고루 먹자.",
  },
  {
    character: "車",
    reading: "차",
    meaning: "수레 차",
    strokes: 7,
    words: ["자동차", "열차", "기차"],
    sentence: "自動車를 조심하자.",
  },
  {
    character: "道",
    reading: "도",
    meaning: "길 도",
    strokes: 13,
    words: ["도로", "도리", "도덕"],
    sentence: "道德을 지키는 학생이 되자.",
  },
  {
    character: "空",
    reading: "공",
    meaning: "빌 공",
    strokes: 8,
    words: ["공간", "하늘", "공기"],
    sentence: "맑은 空氣를 마시자.",
  },
  {
    character: "花",
    reading: "화",
    meaning: "꽃 화",
    strokes: 8,
    words: ["화분", "국화", "무궁화"],
    sentence: "無窮花는 우리나라의 국화이다.",
  },
  {
    character: "草",
    reading: "초",
    meaning: "풀 초",
    strokes: 10,
    words: ["초원", "잡초", "약초"],
    sentence: "넓은 草原에서 뛰어놀았다.",
  },
  {
    character: "氣",
    reading: "기",
    meaning: "기운 기",
    strokes: 10,
    words: ["기운", "날씨", "기후"],
    sentence: "元氣차게 하루를 시작하자.",
  },
  {
    character: "音",
    reading: "음",
    meaning: "소리 음",
    strokes: 9,
    words: ["음악", "음성", "소음"],
    sentence: "音樂을 들으며 공부했다.",
  },
  {
    character: "色",
    reading: "색",
    meaning: "빛 색",
    strokes: 6,
    words: ["색상", "특색", "경색"],
    sentence: "가을 단풍의 色이 아름답다.",
  },
  {
    character: "電",
    reading: "전",
    meaning: "번개 전",
    strokes: 13,
    words: ["전기", "전화", "전자"],
    sentence: "電氣를 아껴 쓰자.",
  },
];

// ===== 영어 데이터 (60개) =====
export const grade5EnglishData: EnglishEntry[] = [
  // 기존 15개
  {
    sentence: "What do you want to be when you grow up?",
    translation: "커서 무엇이 되고 싶니?",
    word: "grow up",
    pronunciation: "그로우 업",
    practice: [
      "When I grow up, I want to be a ___.",
      "What do you want to be?",
    ],
  },
  {
    sentence: "I usually wake up at 7 o'clock.",
    translation: "나는 보통 7시에 일어나.",
    word: "usually",
    pronunciation: "유주얼리",
    practice: ["I usually ___ at ___.", "What do you usually do?"],
  },
  {
    sentence: "My hobby is reading books.",
    translation: "내 취미는 독서야.",
    word: "hobby",
    pronunciation: "하비",
    practice: ["My hobby is ___.", "What is your hobby?"],
  },
  {
    sentence: "Could you say that again, please?",
    translation: "다시 말씀해 주시겠어요?",
    word: "again",
    pronunciation: "어겐",
    practice: ["Could you ___ again?", "Please say that again."],
  },
  {
    sentence: "I have been to Jeju Island.",
    translation: "나는 제주도에 가 본 적이 있어.",
    word: "been",
    pronunciation: "빈",
    practice: ["I have been to ___.", "Have you been to Seoul?"],
  },
  {
    sentence: "There are many flowers in the garden.",
    translation: "정원에 많은 꽃이 있어.",
    word: "garden",
    pronunciation: "가든",
    practice: ["There are ___ in the ___.", "How many flowers?"],
  },
  {
    sentence: "She is taller than me.",
    translation: "그녀는 나보다 키가 커.",
    word: "taller",
    pronunciation: "톨러",
    practice: ["___ is taller than ___.", "Who is the tallest?"],
  },
  {
    sentence: "I need to finish my homework.",
    translation: "나는 숙제를 끝내야 해.",
    word: "finish",
    pronunciation: "피니쉬",
    practice: ["I need to finish ___.", "Did you finish your homework?"],
  },
  {
    sentence: "What subject do you like the most?",
    translation: "어떤 과목을 가장 좋아하니?",
    word: "subject",
    pronunciation: "서브젝트",
    practice: ["I like ___ the most.", "What subject is easy?"],
  },
  {
    sentence: "We should protect the environment.",
    translation: "우리는 환경을 보호해야 해.",
    word: "environment",
    pronunciation: "인바이런먼트",
    practice: ["We should protect ___.", "The environment is important."],
  },
  {
    sentence: "I am looking forward to the field trip.",
    translation: "나는 현장학습이 기대돼.",
    word: "forward",
    pronunciation: "포워드",
    practice: ["I am looking forward to ___.", "Are you excited?"],
  },
  {
    sentence: "Please turn off the lights.",
    translation: "불을 꺼 주세요.",
    word: "turn off",
    pronunciation: "턴 오프",
    practice: ["Please turn off the ___.", "Turn on the TV."],
  },
  {
    sentence: "He is good at playing the piano.",
    translation: "그는 피아노 연주를 잘해.",
    word: "good at",
    pronunciation: "굿 앳",
    practice: ["I am good at ___.", "What are you good at?"],
  },
  {
    sentence: "How was your weekend?",
    translation: "주말 어땠어?",
    word: "weekend",
    pronunciation: "위켄드",
    practice: ["How was your ___?", "My weekend was great."],
  },
  {
    sentence: "I agree with your opinion.",
    translation: "나는 네 의견에 동의해.",
    word: "agree",
    pronunciation: "어그리",
    practice: ["I agree with ___.", "Do you agree?"],
  },
  // 추가 45개 (총 60개)
  {
    sentence: "I went to the museum yesterday.",
    translation: "나는 어제 박물관에 갔어.",
    word: "museum",
    pronunciation: "뮤지엄",
    practice: ["I went to the ___ yesterday.", "Have you been to a museum?"],
  },
  {
    sentence: "Can I borrow your pencil?",
    translation: "네 연필 빌려도 될까?",
    word: "borrow",
    pronunciation: "바로우",
    practice: ["Can I borrow your ___?", "Sure, you can borrow it."],
  },
  {
    sentence: "My favorite season is spring.",
    translation: "내가 가장 좋아하는 계절은 봄이야.",
    word: "season",
    pronunciation: "시즌",
    practice: ["My favorite season is ___.", "What is your favorite season?"],
  },
  {
    sentence: "I will visit my grandparents next week.",
    translation: "나는 다음 주에 조부모님을 방문할 거야.",
    word: "visit",
    pronunciation: "비짓",
    practice: ["I will visit ___ next ___.", "When will you visit?"],
  },
  {
    sentence: "This book is more interesting than that one.",
    translation: "이 책이 저 책보다 더 재미있어.",
    word: "interesting",
    pronunciation: "인터레스팅",
    practice: ["This is more ___ than that.", "Is this book interesting?"],
  },
  {
    sentence: "I played soccer with my friends after school.",
    translation: "나는 방과 후에 친구들과 축구를 했어.",
    word: "played",
    pronunciation: "플레이드",
    practice: ["I played ___ with ___.", "What did you play?"],
  },
  {
    sentence: "She is wearing a red dress today.",
    translation: "그녀는 오늘 빨간 원피스를 입고 있어.",
    word: "wearing",
    pronunciation: "웨어링",
    practice: ["She is wearing a ___.", "What are you wearing?"],
  },
  {
    sentence: "We had a great time at the party.",
    translation: "우리는 파티에서 즐거운 시간을 보냈어.",
    word: "great",
    pronunciation: "그레이트",
    practice: ["We had a great time at ___.", "Did you have a great time?"],
  },
  {
    sentence: "I want to travel around the world.",
    translation: "나는 세계를 여행하고 싶어.",
    word: "travel",
    pronunciation: "트래블",
    practice: ["I want to travel to ___.", "Where do you want to travel?"],
  },
  {
    sentence: "The weather is getting colder.",
    translation: "날씨가 점점 추워지고 있어.",
    word: "weather",
    pronunciation: "웨더",
    practice: ["The weather is getting ___.", "How is the weather today?"],
  },
  {
    sentence: "He runs faster than anyone in our class.",
    translation: "그는 우리 반에서 누구보다 빨리 달려.",
    word: "faster",
    pronunciation: "패스터",
    practice: ["He runs faster than ___.", "Who is the fastest?"],
  },
  {
    sentence: "I learned how to cook pasta.",
    translation: "나는 파스타 만드는 법을 배웠어.",
    word: "learned",
    pronunciation: "러른드",
    practice: ["I learned how to ___.", "What did you learn?"],
  },
  {
    sentence: "Could you help me with this problem?",
    translation: "이 문제 좀 도와줄 수 있니?",
    word: "help",
    pronunciation: "헬프",
    practice: ["Could you help me with ___?", "I need your help."],
  },
  {
    sentence: "My dream is to become a scientist.",
    translation: "내 꿈은 과학자가 되는 거야.",
    word: "scientist",
    pronunciation: "사이언티스트",
    practice: ["My dream is to become a ___.", "What is your dream?"],
  },
  {
    sentence: "The mountain is higher than the hill.",
    translation: "산은 언덕보다 높아.",
    word: "higher",
    pronunciation: "하이어",
    practice: ["The ___ is higher than ___.", "Which is higher?"],
  },
  {
    sentence: "I ate breakfast before going to school.",
    translation: "나는 학교 가기 전에 아침을 먹었어.",
    word: "breakfast",
    pronunciation: "브렉퍼스트",
    practice: ["I ate ___ before ___.", "What did you have for breakfast?"],
  },
  {
    sentence: "She is the kindest person I know.",
    translation: "그녀는 내가 아는 가장 친절한 사람이야.",
    word: "kindest",
    pronunciation: "카인디스트",
    practice: ["She is the ___ person I know.", "Who is the kindest?"],
  },
  {
    sentence: "We planted trees on Arbor Day.",
    translation: "우리는 식목일에 나무를 심었어.",
    word: "planted",
    pronunciation: "플랜티드",
    practice: ["We planted ___ on ___.", "Did you plant any trees?"],
  },
  {
    sentence: "I have to practice the violin every day.",
    translation: "나는 매일 바이올린을 연습해야 해.",
    word: "practice",
    pronunciation: "프랙티스",
    practice: ["I have to practice ___.", "Do you practice every day?"],
  },
  {
    sentence: "The library is next to the park.",
    translation: "도서관은 공원 옆에 있어.",
    word: "library",
    pronunciation: "라이브러리",
    practice: ["The library is next to ___.", "Where is the library?"],
  },
  {
    sentence: "I was surprised by the magic show.",
    translation: "나는 마술 쇼에 놀랐어.",
    word: "surprised",
    pronunciation: "서프라이즈드",
    practice: ["I was surprised by ___.", "Were you surprised?"],
  },
  {
    sentence: "We should save water and electricity.",
    translation: "우리는 물과 전기를 절약해야 해.",
    word: "save",
    pronunciation: "세이브",
    practice: ["We should save ___.", "How can we save water?"],
  },
  {
    sentence: "I made a birthday card for my mom.",
    translation: "나는 엄마를 위해 생일 카드를 만들었어.",
    word: "made",
    pronunciation: "메이드",
    practice: ["I made a ___ for ___.", "What did you make?"],
  },
  {
    sentence: "The test was easier than I expected.",
    translation: "시험이 내가 예상한 것보다 쉬웠어.",
    word: "easier",
    pronunciation: "이지어",
    practice: ["The test was easier than ___.", "Was the test easy?"],
  },
  {
    sentence: "I enjoy listening to music.",
    translation: "나는 음악 듣는 것을 즐겨.",
    word: "enjoy",
    pronunciation: "인조이",
    practice: ["I enjoy ___.", "What do you enjoy doing?"],
  },
  {
    sentence: "There is a beautiful rainbow in the sky.",
    translation: "하늘에 아름다운 무지개가 있어.",
    word: "rainbow",
    pronunciation: "레인보우",
    practice: ["There is a ___ in the sky.", "Have you seen a rainbow?"],
  },
  {
    sentence: "I will do my best on the exam.",
    translation: "나는 시험에서 최선을 다할 거야.",
    word: "best",
    pronunciation: "베스트",
    practice: ["I will do my best on ___.", "Do your best!"],
  },
  {
    sentence: "She speaks English very well.",
    translation: "그녀는 영어를 매우 잘해.",
    word: "speaks",
    pronunciation: "스피크스",
    practice: ["She speaks ___ very well.", "Do you speak English?"],
  },
  {
    sentence: "I forgot to bring my textbook.",
    translation: "나는 교과서 가져오는 것을 잊었어.",
    word: "forgot",
    pronunciation: "포르갓",
    practice: ["I forgot to bring ___.", "Did you forget something?"],
  },
  {
    sentence: "The dolphin is smarter than we think.",
    translation: "돌고래는 우리가 생각하는 것보다 똑똑해.",
    word: "smarter",
    pronunciation: "스마터",
    practice: ["The ___ is smarter than ___.", "Which animal is the smartest?"],
  },
  {
    sentence: "I cleaned my room this morning.",
    translation: "나는 오늘 아침에 방을 청소했어.",
    word: "cleaned",
    pronunciation: "클린드",
    practice: ["I cleaned my ___ this ___.", "Did you clean your room?"],
  },
  {
    sentence: "Would you like some juice?",
    translation: "주스 좀 마실래?",
    word: "juice",
    pronunciation: "주스",
    practice: ["Would you like some ___?", "Yes, please. / No, thanks."],
  },
  {
    sentence: "I am proud of my country.",
    translation: "나는 내 나라가 자랑스러워.",
    word: "proud",
    pronunciation: "프라우드",
    practice: ["I am proud of ___.", "What are you proud of?"],
  },
  {
    sentence: "The elephant is bigger than the horse.",
    translation: "코끼리는 말보다 커.",
    word: "bigger",
    pronunciation: "비거",
    practice: ["The ___ is bigger than the ___.", "Which animal is bigger?"],
  },
  {
    sentence: "I like to draw pictures in my free time.",
    translation: "나는 여가 시간에 그림 그리는 것을 좋아해.",
    word: "draw",
    pronunciation: "드로",
    practice: ["I like to draw ___.", "What do you like to draw?"],
  },
  {
    sentence: "We are going to have a school festival.",
    translation: "우리는 학교 축제를 열 거야.",
    word: "festival",
    pronunciation: "페스티벌",
    practice: ["We are going to have a ___.", "When is the festival?"],
  },
  {
    sentence: "He is the tallest student in our school.",
    translation: "그는 우리 학교에서 가장 키가 큰 학생이야.",
    word: "tallest",
    pronunciation: "톨리스트",
    practice: ["He is the tallest ___ in ___.", "Who is the tallest?"],
  },
  {
    sentence: "I shared my lunch with my friend.",
    translation: "나는 친구와 점심을 나누어 먹었어.",
    word: "shared",
    pronunciation: "셰어드",
    practice: ["I shared my ___ with ___.", "Did you share your lunch?"],
  },
  {
    sentence: "The movie was exciting and fun.",
    translation: "그 영화는 신나고 재미있었어.",
    word: "exciting",
    pronunciation: "익사이팅",
    practice: ["The movie was ___ and ___.", "Was the movie exciting?"],
  },
  {
    sentence: "I hope it will be sunny tomorrow.",
    translation: "내일 맑았으면 좋겠어.",
    word: "hope",
    pronunciation: "호프",
    practice: ["I hope it will be ___.", "What do you hope for?"],
  },
  {
    sentence: "Can you swim in the ocean?",
    translation: "너 바다에서 수영할 수 있어?",
    word: "swim",
    pronunciation: "스윔",
    practice: ["Can you swim in the ___?", "I can swim very well."],
  },
  {
    sentence: "I took a picture of the sunset.",
    translation: "나는 일몰 사진을 찍었어.",
    word: "sunset",
    pronunciation: "선셋",
    practice: ["I took a picture of ___.", "The sunset is beautiful."],
  },
  {
    sentence: "Reading is more important than watching TV.",
    translation: "독서가 TV 보는 것보다 더 중요해.",
    word: "important",
    pronunciation: "임포턴트",
    practice: [
      "___ is more important than ___.",
      "What is the most important thing?",
    ],
  },
  {
    sentence: "I always brush my teeth before bed.",
    translation: "나는 항상 자기 전에 이를 닦아.",
    word: "always",
    pronunciation: "올웨이즈",
    practice: ["I always ___ before ___.", "Do you always brush your teeth?"],
  },
  {
    sentence: "She gave me a present for my birthday.",
    translation: "그녀가 내 생일 선물을 주었어.",
    word: "present",
    pronunciation: "프레젠트",
    practice: ["She gave me a ___ for ___.", "What present did you get?"],
  },
];

// ===== 글쓰기 프롬프트 (60개) =====
export const grade5WritingPrompts: string[] = [
  // 기존 20개
  "우리 사회의 문제점 하나를 선택하여 해결 방안을 제시하는 글을 써 보세요.",
  "존경하는 위인에게 편지를 써 보세요.",
  "내가 생각하는 좋은 리더의 조건에 대해 논술해 보세요.",
  "과학 기술의 발전이 우리 생활에 미치는 영향을 써 보세요.",
  "독서의 중요성에 대해 설득하는 글을 써 보세요.",
  "인터넷 사용의 장단점에 대해 의견을 써 보세요.",
  "역사 속 인물 한 명을 인터뷰한다면 어떤 질문을 할까요?",
  "환경 오염의 원인과 해결책에 대해 써 보세요.",
  "우정이란 무엇인지 자신의 경험을 바탕으로 써 보세요.",
  "내가 만약 다른 나라에서 태어났다면 어떤 삶을 살았을까요?",
  "학교에서 배운 것 중 가장 유익한 내용과 그 이유를 써 보세요.",
  "나의 강점과 약점을 분석하고 발전 계획을 써 보세요.",
  "가족의 의미에 대해 에세이를 써 보세요.",
  "내가 만약 1일 대통령이 된다면 무엇을 할까요?",
  "시(詩) 한 편을 읽고 감상문을 써 보세요.",
  "내가 살고 싶은 미래 도시를 상상하여 묘사해 보세요.",
  "봉사 활동의 경험과 느낀 점을 써 보세요.",
  "전통 문화를 보존해야 하는 이유를 설명하는 글을 써 보세요.",
  "동화 속 주인공에게 조언하는 편지를 써 보세요.",
  "나만의 시간 관리 방법을 소개하는 글을 써 보세요.",
  // 추가 40개 (총 60개)
  "내가 좋아하는 계절과 그 이유를 설명하는 글을 써 보세요.",
  "반려동물을 키우면서 배운 점에 대해 써 보세요.",
  "우리 동네에서 가장 좋아하는 장소를 소개하는 글을 써 보세요.",
  "10년 후의 나에게 편지를 써 보세요.",
  "내가 만약 발명가라면 어떤 것을 발명하고 싶은지 써 보세요.",
  "용기를 낸 경험에 대해 써 보세요.",
  "학교 급식에서 가장 좋아하는 메뉴와 그 이유를 써 보세요.",
  "내가 만약 시간 여행을 할 수 있다면 어느 시대로 가고 싶은지 써 보세요.",
  "좋은 친구가 되기 위해 필요한 조건에 대해 써 보세요.",
  "자연재해를 대비하는 방법에 대해 설명하는 글을 써 보세요.",
  "내가 읽은 책 중 가장 감동적인 책을 소개하는 글을 써 보세요.",
  "건강을 지키기 위한 생활 습관에 대해 써 보세요.",
  "학교에서 일어난 재미있는 에피소드를 글로 써 보세요.",
  "스마트폰 없이 하루를 보낸다면 어떨지 상상하여 써 보세요.",
  "다른 문화권의 음식을 체험한 경험을 써 보세요.",
  "우리 반을 더 좋은 반으로 만들기 위한 제안서를 써 보세요.",
  "새 학기 첫날의 감정을 일기로 써 보세요.",
  "내가 존경하는 가족에 대해 소개하는 글을 써 보세요.",
  "절약의 중요성에 대해 설득하는 글을 써 보세요.",
  "꿈을 이루기 위해 지금 할 수 있는 일에 대해 써 보세요.",
  "비 오는 날의 풍경을 묘사하는 글을 써 보세요.",
  "친구와 다툰 후 화해한 경험을 써 보세요.",
  "우리 학교의 자랑거리를 소개하는 글을 써 보세요.",
  "내가 만약 마법을 쓸 수 있다면 어떤 마법을 쓰고 싶은지 써 보세요.",
  "감사한 사람에게 감사 편지를 써 보세요.",
  "운동이 건강에 미치는 좋은 영향에 대해 써 보세요.",
  "미래의 교통수단을 상상하여 묘사해 보세요.",
  "내가 만약 선생님이 된다면 어떤 수업을 하고 싶은지 써 보세요.",
  "실패에서 배운 교훈에 대해 써 보세요.",
  "음식물 쓰레기를 줄이는 방법에 대해 써 보세요.",
  "내가 가장 행복했던 순간을 글로 써 보세요.",
  "학교 도서관을 더 좋게 만들기 위한 아이디어를 써 보세요.",
  "우리 가족만의 특별한 전통에 대해 소개하는 글을 써 보세요.",
  "내가 만약 우주를 여행한다면 어떤 경험을 하고 싶은지 써 보세요.",
  "양보와 배려가 중요한 이유에 대해 써 보세요.",
  "내가 좋아하는 스포츠를 소개하고 그 매력을 설명해 보세요.",
  "동물원의 동물들은 행복할까에 대해 자신의 의견을 써 보세요.",
  "내가 만약 로봇을 가지고 있다면 어떤 일을 시키고 싶은지 써 보세요.",
  "자연의 소중함을 깨달은 경험을 써 보세요.",
  "내가 만약 100살까지 산다면 어떤 삶을 살고 싶은지 써 보세요.",
];

// ===== NEW: 창의 데이터 (40개) =====
export const grade5CreativeData: KnowledgeEntry[] = [
  // 미술
  {
    text: "가까이 있는 것은 크게, 멀리 있는 것은 작게 그리는 기법을 ___법이라 한다.",
    answer: "원근",
    category: "미술",
  },
  {
    text: "빨강, 노랑, 파랑을 색의 ___이라 한다.",
    answer: "삼원색",
    category: "미술",
  },
  {
    text: "두 가지 이상의 색을 섞어 새로운 색을 만드는 것을 ___이라 한다.",
    answer: "혼색",
    category: "미술",
  },
  {
    text: "우리나라 전통 회화에서 산과 물을 그린 그림을 ___화라 한다.",
    answer: "산수",
    category: "미술",
  },
  {
    text: "찰흙으로 형태를 만드는 미술 활동을 ___이라 한다.",
    answer: "조소",
    category: "미술",
  },
  {
    text: "밝고 어두운 정도의 차이를 색의 ___이라 한다.",
    answer: "명도",
    category: "미술",
  },
  {
    text: "색의 선명하고 탁한 정도를 ___라 한다.",
    answer: "채도",
    category: "미술",
  },
  {
    text: "빨강, 주황 등 따뜻한 느낌을 주는 색을 ___색이라 한다.",
    answer: "난",
    category: "미술",
  },
  {
    text: "파랑, 초록 등 차가운 느낌을 주는 색을 ___색이라 한다.",
    answer: "한",
    category: "미술",
  },
  {
    text: "도화지에 물감을 접어 대칭 무늬를 만드는 기법을 ___기법이라 한다.",
    answer: "데칼코마니",
    category: "미술",
  },
  {
    text: "한국 전통 미술에서 다섯 가지 색을 ___이라 한다.",
    answer: "오방색",
    category: "미술",
  },
  {
    text: "판화에서 물감을 묻혀 종이에 찍는 것을 ___이라 한다.",
    answer: "인쇄",
    category: "미술",
  },
  // 음악
  {
    text: "음악에서 빠르기를 나타내는 용어를 ___라 한다.",
    answer: "빠르기말",
    category: "음악",
  },
  {
    text: "4분의 4박자에서 한 마디의 박수는 ___번이다.",
    answer: "4",
    category: "음악",
  },
  {
    text: "도레미파솔라시도에서 '도'에서 높은 '도'까지를 한 ___이라 한다.",
    answer: "옥타브",
    category: "음악",
  },
  {
    text: "우리나라 전통 타악기 중 가죽으로 만든 것은 ___이다.",
    answer: "장구",
    category: "음악",
  },
  {
    text: "음의 길고 짧음을 나타내는 것을 ___이라 한다.",
    answer: "음표",
    category: "음악",
  },
  {
    text: "여러 사람이 함께 노래하는 것을 ___이라 한다.",
    answer: "합창",
    category: "음악",
  },
  {
    text: "우리나라 전통 음악을 ___이라 총칭한다.",
    answer: "국악",
    category: "음악",
  },
  {
    text: "음악에서 셈여림을 나타내는 기호 'f'는 ___를 뜻한다.",
    answer: "세게",
    category: "음악",
  },
  {
    text: "음악에서 셈여림을 나타내는 기호 'p'는 ___를 뜻한다.",
    answer: "여리게",
    category: "음악",
  },
  {
    text: "리코더에서 구멍을 모두 막으면 ___음이 난다.",
    answer: "낮은",
    category: "음악",
  },
  {
    text: "같은 높이의 음이 반복되는 것을 ___이라 한다.",
    answer: "동음반복",
    category: "음악",
  },
  {
    text: "쉼표는 소리를 ___는 것을 나타낸다.",
    answer: "쉬",
    category: "음악",
  },
  // 디자인
  {
    text: "물건의 겉모양을 아름답고 쓰기 편하게 꾸미는 것을 ___이라 한다.",
    answer: "디자인",
    category: "디자인",
  },
  {
    text: "같은 모양이나 색이 규칙적으로 반복되는 무늬를 ___이라 한다.",
    answer: "패턴",
    category: "디자인",
  },
  {
    text: "포스터에서 가장 중요한 내용을 눈에 잘 띄게 하는 것을 ___이라 한다.",
    answer: "강조",
    category: "디자인",
  },
  {
    text: "왼쪽과 오른쪽이 똑같은 형태를 ___대칭이라 한다.",
    answer: "좌우",
    category: "디자인",
  },
  {
    text: "글자를 아름답게 디자인하는 것을 ___라 한다.",
    answer: "캘리그래피",
    category: "디자인",
  },
  // 감상
  {
    text: "미술 작품을 보고 느낌이나 생각을 말하는 것을 ___이라 한다.",
    answer: "감상",
    category: "감상",
  },
  {
    text: "'해바라기'를 그린 화가는 ___이다.",
    answer: "고흐",
    category: "감상",
  },
  {
    text: "풍속화는 ___의 생활 모습을 그린 그림이다.",
    answer: "서민",
    category: "감상",
  },
  {
    text: "김홍도의 '서당'은 조선 시대 ___의 모습을 그린 것이다.",
    answer: "학교",
    category: "감상",
  },
  {
    text: "신사임당이 잘 그린 그림의 소재는 ___이다.",
    answer: "풀벌레",
    category: "감상",
  },
  {
    text: "뮤지컬은 연기, 노래, ___이 결합된 공연이다.",
    answer: "춤",
    category: "감상",
  },
  {
    text: "오케스트라에서 지휘자가 사용하는 막대를 ___이라 한다.",
    answer: "지휘봉",
    category: "감상",
  },
  {
    text: "모나리자를 그린 화가는 ___이다.",
    answer: "레오나르도 다빈치",
    category: "감상",
  },
  {
    text: "판소리에서 북으로 장단을 치는 사람을 ___라 한다.",
    answer: "고수",
    category: "감상",
  },
  {
    text: "그림에서 빛과 그림자의 대비를 ___이라 한다.",
    answer: "명암",
    category: "감상",
  },
  {
    text: "전통 탈춤에서 사용하는 가면을 ___이라 한다.",
    answer: "탈",
    category: "감상",
  },
];

// ===== NEW: 과학 데이터 (40개) =====
export const grade5ScienceData: KnowledgeEntry[] = [
  // 생물
  {
    text: "식물의 잎에서 물이 수증기로 빠져나가는 현상을 ___이라 한다.",
    answer: "증산작용",
    category: "생물",
  },
  {
    text: "식물의 줄기는 물과 ___을 운반하는 역할을 한다.",
    answer: "양분",
    category: "생물",
  },
  {
    text: "꽃의 수술에서 만들어지는 가루를 ___이라 한다.",
    answer: "꽃가루",
    category: "생물",
  },
  {
    text: "식물의 뿌리 끝에 있는 솜털 같은 것을 ___이라 한다.",
    answer: "뿌리털",
    category: "생물",
  },
  {
    text: "동물이 겨울을 나기 위해 깊은 잠에 빠지는 것을 ___이라 한다.",
    answer: "겨울잠",
    category: "생물",
  },
  {
    text: "나비가 알에서 성충이 되기까지의 변화를 ___이라 한다.",
    answer: "완전변태",
    category: "생물",
  },
  {
    text: "척추가 없는 동물을 ___동물이라 한다.",
    answer: "무척추",
    category: "생물",
  },
  {
    text: "식물이 빛 방향으로 자라는 성질을 ___이라 한다.",
    answer: "굴광성",
    category: "생물",
  },
  {
    text: "씨앗이 싹 트는 것을 ___이라 한다.",
    answer: "발아",
    category: "생물",
  },
  {
    text: "물속에서 아가미로 숨 쉬는 동물은 ___류이다.",
    answer: "어",
    category: "생물",
  },
  // 물리
  {
    text: "물체가 빛을 받아 뒤쪽에 생기는 어두운 부분을 ___라 한다.",
    answer: "그림자",
    category: "물리",
  },
  {
    text: "소리가 물체에 부딪혀 되돌아오는 현상을 ___라 한다.",
    answer: "메아리",
    category: "물리",
  },
  {
    text: "자석에서 같은 극끼리는 서로 ___한다.",
    answer: "밀어낸",
    category: "물리",
  },
  {
    text: "물체의 무게를 재는 도구를 ___라 한다.",
    answer: "저울",
    category: "물리",
  },
  {
    text: "힘의 크기를 나타내는 단위는 ___이다.",
    answer: "뉴턴(N)",
    category: "물리",
  },
  {
    text: "빛이 거울에 반사되는 현상을 빛의 ___이라 한다.",
    answer: "반사",
    category: "물리",
  },
  {
    text: "진자의 한 번 왕복하는 데 걸리는 시간을 ___라 한다.",
    answer: "주기",
    category: "물리",
  },
  {
    text: "물체의 위치가 변하는 것을 ___이라 한다.",
    answer: "운동",
    category: "물리",
  },
  {
    text: "빛이 투명한 물체를 통과할 때 꺾이는 현상을 빛의 ___이라 한다.",
    answer: "굴절",
    category: "물리",
  },
  { text: "전기가 흐르는 길을 ___라 한다.", answer: "회로", category: "물리" },
  // 화학
  {
    text: "물질이 고체에서 액체로 변하는 것을 ___이라 한다.",
    answer: "융해",
    category: "화학",
  },
  {
    text: "물질이 액체에서 기체로 변하는 것을 ___라 한다.",
    answer: "기화",
    category: "화학",
  },
  {
    text: "물에 소금을 넣으면 소금이 ___된다.",
    answer: "용해",
    category: "화학",
  },
  {
    text: "물에 녹는 물질의 양에는 ___가 있다.",
    answer: "한계",
    category: "화학",
  },
  {
    text: "물이 얼어 얼음이 되면 부피가 ___한다.",
    answer: "증가",
    category: "화학",
  },
  {
    text: "용질이 물에 녹아 있는 액체를 ___이라 한다.",
    answer: "용액",
    category: "화학",
  },
  {
    text: "산성 용액에 리트머스 종이를 넣으면 ___색으로 변한다.",
    answer: "빨간",
    category: "화학",
  },
  {
    text: "염기성 용액에 리트머스 종이를 넣으면 ___색으로 변한다.",
    answer: "파란",
    category: "화학",
  },
  {
    text: "물질이 타서 새로운 물질이 생기는 변화를 ___이라 한다.",
    answer: "연소",
    category: "화학",
  },
  {
    text: "쇠가 공기 중의 산소와 반응하여 녹스는 것을 ___라 한다.",
    answer: "산화",
    category: "화학",
  },
  // 지구과학
  {
    text: "태양계에서 지구와 가장 가까운 행성은 ___이다.",
    answer: "금성",
    category: "지구과학",
  },
  {
    text: "달이 지구 주위를 한 바퀴 도는 데 약 ___일이 걸린다.",
    answer: "27",
    category: "지구과학",
  },
  {
    text: "구름에서 물방울이 떨어지는 것을 ___라 한다.",
    answer: "비",
    category: "지구과학",
  },
  {
    text: "공기 중 수증기가 차가운 표면에 물방울로 맺히는 것을 ___라 한다.",
    answer: "이슬",
    category: "지구과학",
  },
  {
    text: "지구의 공전 주기는 약 ___일이다.",
    answer: "365",
    category: "지구과학",
  },
  {
    text: "태양계의 행성 중 고리가 있는 것은 ___이다.",
    answer: "토성",
    category: "지구과학",
  },
  {
    text: "바람이 부는 이유는 기압의 ___때문이다.",
    answer: "차이",
    category: "지구과학",
  },
  {
    text: "지층이 양쪽에서 힘을 받아 굽어지는 것을 ___라 한다.",
    answer: "습곡",
    category: "지구과학",
  },
  {
    text: "날씨를 관측하는 곳을 ___이라 한다.",
    answer: "기상청",
    category: "지구과학",
  },
  {
    text: "지구 표면의 약 70%를 차지하는 것은 ___이다.",
    answer: "바다",
    category: "지구과학",
  },
];

// ===== NEW: 사회 데이터 (40개) =====
export const grade5SocialData: KnowledgeEntry[] = [
  // 지리
  {
    text: "우리나라는 아시아 대륙의 ___반도에 위치한다.",
    answer: "한",
    category: "지리",
  },
  {
    text: "우리나라의 동쪽 바다를 ___해라 한다.",
    answer: "동",
    category: "지리",
  },
  {
    text: "우리나라에서 가장 넓은 평야는 ___평야이다.",
    answer: "호남",
    category: "지리",
  },
  {
    text: "제주도의 상징적인 돌은 ___이다.",
    answer: "현무암",
    category: "지리",
  },
  {
    text: "우리나라의 서쪽 바다를 ___해라 한다.",
    answer: "서(황)",
    category: "지리",
  },
  {
    text: "위도와 경도를 이용하여 위치를 나타내는 것을 ___라 한다.",
    answer: "좌표",
    category: "지리",
  },
  {
    text: "산과 강이 많은 우리나라의 지형적 특징을 삼천리___이라 한다.",
    answer: "금수강산",
    category: "지리",
  },
  {
    text: "태백산맥은 우리나라의 ___쪽에 위치한다.",
    answer: "동",
    category: "지리",
  },
  {
    text: "지도에서 높낮이를 나타내는 선을 ___이라 한다.",
    answer: "등고선",
    category: "지리",
  },
  {
    text: "해안선이 복잡한 우리나라의 ___해안에는 갯벌이 발달했다.",
    answer: "서",
    category: "지리",
  },
  // 역사
  {
    text: "우리 민족 최초의 국가는 ___이다.",
    answer: "고조선",
    category: "역사",
  },
  {
    text: "고조선을 세운 사람은 ___이다.",
    answer: "단군왕검",
    category: "역사",
  },
  {
    text: "고구려의 전성기를 이끈 왕은 ___이다.",
    answer: "광개토대왕",
    category: "역사",
  },
  {
    text: "백제의 수도였던 현재의 도시는 ___이다.",
    answer: "공주",
    category: "역사",
  },
  {
    text: "세종대왕이 한글을 만든 연도는 ___년이다.",
    answer: "1443",
    category: "역사",
  },
  {
    text: "조선 시대 가장 오래 재위한 왕은 ___이다.",
    answer: "영조",
    category: "역사",
  },
  {
    text: "임진왜란이 일어난 해는 ___년이다.",
    answer: "1592",
    category: "역사",
  },
  {
    text: "병자호란 때 인조가 피난 갔던 곳은 ___이다.",
    answer: "남한산성",
    category: "역사",
  },
  {
    text: "조선의 법전인 경국대전을 완성한 왕은 ___이다.",
    answer: "성종",
    category: "역사",
  },
  {
    text: "우리나라 최초의 금속 활자는 ___에서 만들어졌다.",
    answer: "고려",
    category: "역사",
  },
  // 경제
  {
    text: "물건의 가격은 ___와 공급에 의해 결정된다.",
    answer: "수요",
    category: "경제",
  },
  {
    text: "은행에 돈을 맡기면 받을 수 있는 것을 ___라 한다.",
    answer: "이자",
    category: "경제",
  },
  {
    text: "나라에서 쓰는 돈을 마련하기 위해 국민이 내는 것은 ___이다.",
    answer: "세금",
    category: "경제",
  },
  {
    text: "물건을 만들어 내는 활동을 ___이라 한다.",
    answer: "생산",
    category: "경제",
  },
  {
    text: "물건이나 서비스를 사용하는 것을 ___이라 한다.",
    answer: "소비",
    category: "경제",
  },
  {
    text: "한정된 자원으로 최대 만족을 얻으려는 것을 ___적 선택이라 한다.",
    answer: "합리",
    category: "경제",
  },
  {
    text: "우리나라의 화폐를 발행하는 곳은 ___이다.",
    answer: "한국은행",
    category: "경제",
  },
  // 정치
  {
    text: "국민이 나라의 주인인 정치 체제를 ___라 한다.",
    answer: "민주주의",
    category: "정치",
  },
  {
    text: "대한민국 대통령의 임기는 ___년이다.",
    answer: "5",
    category: "정치",
  },
  {
    text: "국회의원을 뽑는 선거를 ___선거라 한다.",
    answer: "총",
    category: "정치",
  },
  {
    text: "법을 만드는 국가 기관은 ___이다.",
    answer: "국회",
    category: "정치",
  },
  {
    text: "재판을 담당하는 국가 기관은 ___이다.",
    answer: "법원",
    category: "정치",
  },
  {
    text: "나라를 다스리는 일을 담당하는 기관은 ___이다.",
    answer: "정부",
    category: "정치",
  },
  // 문화
  {
    text: "한국의 대표적인 발효 식품은 ___이다.",
    answer: "김치",
    category: "문화",
  },
  {
    text: "우리나라의 전통 주거 형태를 ___이라 한다.",
    answer: "한옥",
    category: "문화",
  },
  {
    text: "추석에 먹는 전통 음식은 ___이다.",
    answer: "송편",
    category: "문화",
  },
  {
    text: "설날에 어른들께 하는 인사를 ___라 한다.",
    answer: "세배",
    category: "문화",
  },
  {
    text: "한복에서 여자 상의를 ___라 한다.",
    answer: "저고리",
    category: "문화",
  },
  {
    text: "우리나라 전통 놀이 중 새해에 하는 것은 ___이다.",
    answer: "윷놀이",
    category: "문화",
  },
  {
    text: "한국의 전통 무술을 ___라 한다.",
    answer: "태권도",
    category: "문화",
  },
];
