import type {
  SpellingEntry,
  VocabEntry,
  KnowledgeEntry,
  SafetyEntry,
  MathEntry,
  HanjaEntry,
  EnglishEntry,
} from "@/types/curriculum";

// 3학년 1학기 교육과정 성취기준
export const grade3Semester1Standards = {
  math: [
    {
      code: "[2수01-14]",
      desc: "네 자리 이하의 수의 범위에서 덧셈과 뺄셈을 할 수 있다",
      unit: "덧셈과 뺄셈",
      difficulty: 3,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-15]",
      desc: "곱셈과 나눗셈의 관계를 이해한다",
      unit: "나눗셈",
      difficulty: 3,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[2수02-03]",
      desc: "평면도형의 이동을 이해한다",
      unit: "평면도형",
      difficulty: 3,
      weeks: [9, 11] as [number, number],
    },
    {
      code: "[2수03-04]",
      desc: "시간의 덧셈과 뺄셈을 할 수 있다",
      unit: "시간과 길이",
      difficulty: 3,
      weeks: [12, 14] as [number, number],
    },
    {
      code: "[2수01-16]",
      desc: "두 자리 수의 곱셈을 할 수 있다",
      unit: "곱셈",
      difficulty: 3,
      weeks: [14, 16] as [number, number],
    },
  ],
  korean: [
    {
      code: "[4국01-01]",
      desc: "대화의 즐거움을 알고 대화를 나눈다",
      unit: "대화",
      difficulty: 3,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4국02-01]",
      desc: "문단과 글의 중심 생각을 파악한다",
      unit: "중심 생각",
      difficulty: 3,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4국03-01]",
      desc: "중심 문장과 뒷받침 문장을 갖추어 글을 쓴다",
      unit: "문단 쓰기",
      difficulty: 3,
      weeks: [8, 11] as [number, number],
    },
    {
      code: "[4국04-01]",
      desc: "낱말을 분류하고 국어사전에서 찾는다",
      unit: "국어사전",
      difficulty: 3,
      weeks: [12, 14] as [number, number],
    },
  ],
  english: [
    {
      code: "[4영01-01]",
      desc: "알파벳 대소문자를 식별하고 읽을 수 있다",
      unit: "Alphabet",
      difficulty: 3,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[4영02-01]",
      desc: "쉽고 간단한 낱말이나 어구를 듣고 의미를 이해한다",
      unit: "Listening",
      difficulty: 3,
      weeks: [5, 8] as [number, number],
    },
    {
      code: "[4영03-01]",
      desc: "알파벳 대소문자를 쓸 수 있다",
      unit: "Writing",
      difficulty: 3,
      weeks: [9, 12] as [number, number],
    },
  ],
};

export const grade3Semester2Standards = {
  math: [
    {
      code: "[2수01-17]",
      desc: "분수를 이해하고 읽고 쓸 수 있다",
      unit: "분수와 소수",
      difficulty: 3,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수01-18]",
      desc: "단위분수의 크기를 비교할 수 있다",
      unit: "분수와 소수",
      difficulty: 3,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[2수02-04]",
      desc: "원의 구성 요소를 이해하고 원을 그릴 수 있다",
      unit: "원",
      difficulty: 3,
      weeks: [5, 7] as [number, number],
    },
    {
      code: "[2수03-05]",
      desc: "들이의 단위를 알고 어림하여 재어 볼 수 있다",
      unit: "들이와 무게",
      difficulty: 3,
      weeks: [8, 10] as [number, number],
    },
    {
      code: "[2수04-03]",
      desc: "자료를 수집하여 그림그래프로 나타내고 해석할 수 있다",
      unit: "자료 정리",
      difficulty: 3,
      weeks: [11, 14] as [number, number],
    },
  ],
  korean: [
    {
      code: "[4국01-02]",
      desc: "회의에서 의견을 적극적으로 교환한다",
      unit: "토의",
      difficulty: 3,
      weeks: [1, 3] as [number, number],
    },
    {
      code: "[4국02-02]",
      desc: "글의 유형을 고려하여 대강의 내용을 간추린다",
      unit: "요약하기",
      difficulty: 3,
      weeks: [4, 7] as [number, number],
    },
    {
      code: "[4국05-01]",
      desc: "감각적 표현에 주의하며 작품을 감상한다",
      unit: "문학 감상",
      difficulty: 3,
      weeks: [8, 11] as [number, number],
    },
  ],
  english: [
    {
      code: "[4영01-02]",
      desc: "쉽고 간단한 인사말을 듣고 이해할 수 있다",
      unit: "Greetings",
      difficulty: 3,
      weeks: [1, 4] as [number, number],
    },
    {
      code: "[4영02-02]",
      desc: "한두 문장으로 자기소개를 할 수 있다",
      unit: "Self Introduction",
      difficulty: 3,
      weeks: [5, 8] as [number, number],
    },
  ],
};

export const grade3SpellingData: SpellingEntry[] = [
  // 기존 22개
  {
    q1: "오늘 날씨가 되게 좋다.",
    q2: "오늘 날씨가 되개 좋다.",
    answer: 1,
    explanation: "'되게'는 '매우'의 뜻인 부사입니다.",
  },
  {
    q1: "반드시 숙제를 해야 한다.",
    q2: "반듯이 숙제를 해야 한다.",
    answer: 1,
    explanation: "'반드시'는 '꼭'의 뜻이고, '반듯이'는 '바르게'의 뜻입니다.",
  },
  {
    q1: "노란색 꽃이 아름답다.",
    q2: "노란색 꽃이 아름답따.",
    answer: 1,
    explanation: "'아름답다'에서 '-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "가르치다와 가리키다는 다르다.",
    q2: "가르키다와 가르치다는 다르다.",
    answer: 1,
    explanation: "'가르치다'(teach)와 '가리키다'(point)를 구분해야 합니다.",
  },
  {
    q1: "부엌에서 요리했다.",
    q2: "부억에서 요리했다.",
    answer: 1,
    explanation: "'부엌'이 올바른 표기입니다.",
  },
  {
    q1: "문을 잠갔다.",
    q2: "문을 잠궜다.",
    answer: 1,
    explanation: "'잠갔다'가 올바른 표기입니다.",
  },
  {
    q1: "할머니를 뵈었다.",
    q2: "할머니를 봬었다.",
    answer: 1,
    explanation: "'뵈었다'가 올바른 표기입니다.",
  },
  {
    q1: "며칠 동안 아팠다.",
    q2: "몇 일 동안 아팠다.",
    answer: 1,
    explanation: "'며칠'이 맞는 표현입니다.",
  },
  {
    q1: "해돋이를 보러 갔다.",
    q2: "해돋이를 보러 갔따.",
    answer: 1,
    explanation: "'갔다'에서 '-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "다르다와 틀리다는 다른 뜻이다.",
    q2: "다르다와 틀리다는 같은 뜻이다.",
    answer: 1,
    explanation:
      "'다르다'는 차이가 있다는 뜻이고, '틀리다'는 잘못되었다는 뜻입니다.",
  },
  {
    q1: "어이가 없다.",
    q2: "어의가 없다.",
    answer: 1,
    explanation: "'어이가 없다'가 올바른 표현입니다.",
  },
  {
    q1: "개수를 세어 보자.",
    q2: "갯수를 세어 보자.",
    answer: 1,
    explanation: "'개수'가 올바른 표기입니다. 사이시옷을 넣지 않습니다.",
  },
  {
    q1: "그녀는 금세 나아졌다.",
    q2: "그녀는 금새 나아졌다.",
    answer: 1,
    explanation: "'금세'(금시에의 줄임)가 올바른 표기입니다.",
  },
  {
    q1: "일찍이 도착했다.",
    q2: "일찌기 도착했다.",
    answer: 1,
    explanation: "'일찍이'가 올바른 표기입니다.",
  },
  {
    q1: "목걸이가 예쁘다.",
    q2: "목거리가 예쁘다.",
    answer: 1,
    explanation: "'목걸이'가 올바른 표기입니다.",
  },
  {
    q1: "설겆이를 도왔다.",
    q2: "설거지를 도왔다.",
    answer: 2,
    explanation: "'설거지'가 올바른 표기입니다.",
  },
  {
    q1: "곰곰히 생각했다.",
    q2: "곰곰이 생각했다.",
    answer: 2,
    explanation: "'-이'가 올바른 접미사입니다. '곰곰이'가 맞습니다.",
  },
  {
    q1: "정성껏 만들었다.",
    q2: "정성것 만들었다.",
    answer: 1,
    explanation: "'정성껏'이 올바른 표기입니다.",
  },
  {
    q1: "어떻게 해야 할까?",
    q2: "어떡게 해야 할까?",
    answer: 1,
    explanation: "'어떻게'가 올바른 표기입니다.",
  },
  {
    q1: "웬일로 일찍 왔니?",
    q2: "왠일로 일찍 왔니?",
    answer: 1,
    explanation: "'웬'은 '어찌된'의 뜻이고, '왠'은 '왜인'의 줄임입니다.",
  },
  {
    q1: "왠지 기분이 좋다.",
    q2: "웬지 기분이 좋다.",
    answer: 1,
    explanation: "'왠지'(왜인지)가 올바른 표기입니다.",
  },
  // 신규 38개 (총 60개)
  {
    q1: "나뭇잎이 떨어졌다.",
    q2: "나뭇입이 떨어졌다.",
    answer: 1,
    explanation: "'나뭇잎'이 올바른 표기입니다. 사이시옷 뒤에 '잎'이 옵니다.",
  },
  {
    q1: "깨끗히 청소했다.",
    q2: "깨끗이 청소했다.",
    answer: 2,
    explanation: "'ㅅ' 받침 뒤에는 '-이'가 옵니다. '깨끗이'가 맞습니다.",
  },
  {
    q1: "넓은 운동장에서 놀았다.",
    q2: "널분 운동장에서 놀았다.",
    answer: 1,
    explanation: "'넓은'이 올바른 표기입니다. 'ㄼ' 받침입니다.",
  },
  {
    q1: "값이 너무 비싸다.",
    q2: "갑이 너무 비싸다.",
    answer: 1,
    explanation: "'값'이 올바른 표기입니다. 겹받침 'ㄿ'을 씁니다.",
  },
  {
    q1: "안녕히 가세요.",
    q2: "안녕이 가세요.",
    answer: 1,
    explanation: "'ㅎ' 받침 뒤에는 '-히'가 옵니다. '안녕히'가 맞습니다.",
  },
  {
    q1: "축하합니다.",
    q2: "추카합니다.",
    answer: 1,
    explanation: "'축하'가 올바른 표기입니다. 소리 나는 대로 쓰지 않습니다.",
  },
  {
    q1: "이따가 만나자.",
    q2: "있다가 만나자.",
    answer: 1,
    explanation: "'이따가'가 올바른 표기입니다. '조금 뒤에'라는 뜻입니다.",
  },
  {
    q1: "사이좋은 친구",
    q2: "사이조은 친구",
    answer: 1,
    explanation: "'좋은'이 올바른 표기입니다. 'ㅎ' 받침을 살려 씁니다.",
  },
  {
    q1: "일부로 그런 게 아니야.",
    q2: "일부러 그런 게 아니야.",
    answer: 2,
    explanation: "'일부러'가 올바른 표기입니다. '고의로'라는 뜻입니다.",
  },
  {
    q1: "벌써 다 했어.",
    q2: "벌서 다 했어.",
    answer: 1,
    explanation: "'벌써'가 올바른 표기입니다. 된소리를 써야 합니다.",
  },
  {
    q1: "오랫만에 만났다.",
    q2: "오랜만에 만났다.",
    answer: 2,
    explanation: "'오랜만에'가 올바른 표기입니다. '오래간만에'의 줄임말입니다.",
  },
  {
    q1: "바람이 세차게 불었다.",
    q2: "바람이 세차개 불었다.",
    answer: 1,
    explanation: "'-게'가 올바른 부사형 어미입니다.",
  },
  {
    q1: "뒤뚱뒤뚱 걸었다.",
    q2: "뒤뚱뒤뚱 거렀다.",
    answer: 1,
    explanation: "'걸었다'가 올바른 표기입니다. '걷다'의 과거형입니다.",
  },
  {
    q1: "삼촌이 용돈을 줬다.",
    q2: "삼춘이 용돈을 줬다.",
    answer: 1,
    explanation: "'삼촌'이 올바른 표기입니다.",
  },
  {
    q1: "이 문제는 어렵다.",
    q2: "이 문제는 어렵따.",
    answer: 1,
    explanation: "'-다'가 올바른 종결어미입니다. 된소리가 아닙니다.",
  },
  {
    q1: "나는 기쁘다.",
    q2: "나는 기뿌다.",
    answer: 1,
    explanation: "'기쁘다'가 올바른 표기입니다.",
  },
  {
    q1: "할아버지 댁에 갔다.",
    q2: "하라버지 댁에 갔다.",
    answer: 1,
    explanation: "'할아버지'가 올바른 표기입니다.",
  },
  {
    q1: "점심때가 됐다.",
    q2: "점심때가 댔다.",
    answer: 1,
    explanation: "'됐다'(되었다)가 올바른 표기입니다.",
  },
  {
    q1: "서랍에 넣었다.",
    q2: "서랍에 너었다.",
    answer: 1,
    explanation: "'넣었다'가 올바른 표기입니다. '넣다'의 과거형입니다.",
  },
  {
    q1: "불량 식품을 먹지 말자.",
    q2: "불냥 식품을 먹지 말자.",
    answer: 1,
    explanation: "'불량'이 올바른 표기입니다.",
  },
  {
    q1: "잠깐만 기다려.",
    q2: "잠깐만 기달려.",
    answer: 1,
    explanation: "'기다려'가 올바른 표기입니다. '기다리다'의 활용형입니다.",
  },
  {
    q1: "풀잎에 이슬이 맺혔다.",
    q2: "풀잎에 이슬이 맺쳤다.",
    answer: 1,
    explanation: "'맺혔다'(맺히다의 과거형)가 올바른 표기입니다.",
  },
  {
    q1: "그릇을 닦았다.",
    q2: "그릇을 닥았다.",
    answer: 1,
    explanation: "'닦았다'(닦다의 과거형)가 올바른 표기입니다.",
  },
  {
    q1: "같이 놀자.",
    q2: "갗이 놀자.",
    answer: 1,
    explanation: "'같이'가 올바른 표기입니다.",
  },
  {
    q1: "얼른 뛰어가자.",
    q2: "얼른 띠어가자.",
    answer: 1,
    explanation: "'뛰어가자'가 올바른 표기입니다.",
  },
  {
    q1: "노란 병아리가 귀엽다.",
    q2: "노란 병아리가 귀엽따.",
    answer: 1,
    explanation: "'귀엽다'에서 '-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "아버지께서 말씀하셨다.",
    q2: "아버지게서 말씀하셨다.",
    answer: 1,
    explanation: "'께서'가 올바른 높임 조사입니다.",
  },
  {
    q1: "쓰래기를 분리수거했다.",
    q2: "쓰레기를 분리수거했다.",
    answer: 2,
    explanation: "'쓰레기'가 올바른 표기입니다.",
  },
  {
    q1: "할머니께 인사드렸다.",
    q2: "할머니게 인사드렸다.",
    answer: 1,
    explanation: "'께'가 올바른 높임 조사입니다.",
  },
  {
    q1: "수돗물을 마셨다.",
    q2: "수도물을 마셨다.",
    answer: 1,
    explanation: "'수돗물'이 올바른 사이시옷 표기입니다.",
  },
  {
    q1: "집에서 떡뽁이를 만들었다.",
    q2: "집에서 떡볶이를 만들었다.",
    answer: 2,
    explanation: "'떡볶이'가 올바른 표기입니다.",
  },
  {
    q1: "냉장고에 넣어 둬.",
    q2: "냉장고에 너어 둬.",
    answer: 1,
    explanation: "'넣어'가 올바른 표기입니다. '넣다'의 활용형입니다.",
  },
  {
    q1: "편지 봉투에 넣었다.",
    q2: "편지 봉투에 너었다.",
    answer: 1,
    explanation: "'넣었다'가 올바른 표기입니다.",
  },
  {
    q1: "짧은 글을 읽었다.",
    q2: "짤븐 글을 읽었다.",
    answer: 1,
    explanation: "'짧은'이 올바른 표기입니다. 겹받침 'ㄼ'입니다.",
  },
  {
    q1: "건전지를 바꿨다.",
    q2: "건전지를 바꾸었다.",
    answer: 2,
    explanation:
      "'바꾸었다'가 올바른 표기입니다. '바꿨다'도 허용되나 정식은 '바꾸었다'입니다.",
  },
  {
    q1: "일요일마다 교회에 간다.",
    q2: "일요일마다 교회에 간따.",
    answer: 1,
    explanation: "'간다'에서 '-다'가 올바른 종결어미입니다.",
  },
  {
    q1: "재밌는 이야기를 들었다.",
    q2: "재밌는 이야기를 드렀다.",
    answer: 1,
    explanation: "'들었다'가 올바른 표기입니다. '듣다'의 과거형입니다.",
  },
  {
    q1: "마실 물을 떠 왔다.",
    q2: "마실 물을 더 왔다.",
    answer: 1,
    explanation: "'떠 왔다'(뜨다의 활용형)가 올바른 표기입니다.",
  },
  {
    q1: "헷갈리는 문제였다.",
    q2: "헤깔리는 문제였다.",
    answer: 1,
    explanation: "'헷갈리다'가 올바른 표기입니다. 사이시옷이 들어갑니다.",
  },
];

export const grade3VocabData: VocabEntry[] = [
  // 기존 15개
  { meanings: ["나라를 다스리는 사람", "왕이라고도 해요"], answer: "임금" },
  { meanings: ["불을 끄는 사람", "빨간 차를 타요"], answer: "소방관" },
  { meanings: ["땅이 흔들리는 것", "건물이 무너질 수 있어요"], answer: "지진" },
  { meanings: ["물이 얼어서 된 것", "겨울에 볼 수 있어요"], answer: "고드름" },
  {
    meanings: ["높은 곳에서 물이 떨어지는 것", "자연 경관이에요"],
    answer: "폭포",
  },
  {
    meanings: ["하늘에서 빛이 번쩍이는 것", "천둥과 함께 와요"],
    answer: "번개",
  },
  {
    meanings: ["옛날이야기에 나오는 상상의 동물", "하늘을 날아요"],
    answer: "용",
  },
  { meanings: ["사물을 비추는 것", "내 모습이 보여요"], answer: "거울" },
  { meanings: ["지구를 작게 만든 모형", "둥근 모양이에요"], answer: "지구본" },
  {
    meanings: ["긴 줄 위를 걷는 것", "서커스에서 볼 수 있어요"],
    answer: "줄타기",
  },
  { meanings: ["나무로 만든 배", "물에 떠요"], answer: "뗏목" },
  {
    meanings: ["여러 사람이 함께 부르는 노래", "합창이라고도 해요"],
    answer: "합창",
  },
  { meanings: ["맛을 느끼는 기관", "입안에 있어요"], answer: "혀" },
  {
    meanings: ["하루 중 해가 가장 높이 뜨는 때", "12시쯤이에요"],
    answer: "정오",
  },
  { meanings: ["물건의 무거운 정도", "저울로 재요"], answer: "무게" },
  // 신규 45개 (총 60개)
  {
    meanings: ["하늘에 떠 있는 수증기 덩어리", "비가 오기 전에 많아져요"],
    answer: "구름",
  },
  { meanings: ["봄에 피는 분홍색 꽃", "나무에 피어요"], answer: "벚꽃" },
  { meanings: ["밤하늘에 빛나는 것", "반짝반짝 빛나요"], answer: "별" },
  { meanings: ["집을 짓는 사람", "건물을 만들어요"], answer: "건축가" },
  {
    meanings: ["아픈 사람을 치료하는 곳", "의사 선생님이 있어요"],
    answer: "병원",
  },
  { meanings: ["물건을 사고파는 곳", "채소와 과일을 팔아요"], answer: "시장" },
  { meanings: ["글을 쓰는 도구", "잉크가 들어 있어요"], answer: "볼펜" },
  { meanings: ["시간을 알려 주는 것", "벽에 걸려 있어요"], answer: "시계" },
  {
    meanings: ["빛이 나는 곤충", "여름 밤에 볼 수 있어요"],
    answer: "반딧불이",
  },
  { meanings: ["나무의 줄기에서 나오는 것", "새가 앉아요"], answer: "가지" },
  { meanings: ["바다에 사는 큰 동물", "물을 뿜어요"], answer: "고래" },
  {
    meanings: ["몸에 줄무늬가 있는 동물", "아프리카에 살아요"],
    answer: "얼룩말",
  },
  { meanings: ["하늘을 나는 탈것", "날개가 있어요"], answer: "비행기" },
  {
    meanings: ["땅속에서 자라는 주황색 채소", "토끼가 좋아해요"],
    answer: "당근",
  },
  {
    meanings: ["여러 가지 색이 나타나는 자연 현상", "비 온 뒤에 볼 수 있어요"],
    answer: "무지개",
  },
  {
    meanings: ["음식을 차갑게 보관하는 기계", "주방에 있어요"],
    answer: "냉장고",
  },
  { meanings: ["글자를 찍어 내는 기계", "종이에 인쇄해요"], answer: "프린터" },
  { meanings: ["길을 안내하는 표시", "방향을 알려 줘요"], answer: "표지판" },
  {
    meanings: ["물건을 담는 종이 주머니", "장보기 할 때 사용해요"],
    answer: "봉투",
  },
  {
    meanings: ["비가 올 때 쓰는 도구", "접었다 폈다 할 수 있어요"],
    answer: "우산",
  },
  { meanings: ["추울 때 목에 두르는 것", "따뜻해요"], answer: "목도리" },
  { meanings: ["발에 신는 것", "걸을 때 필요해요"], answer: "신발" },
  { meanings: ["글을 모아 놓은 것", "읽으면 지식이 생겨요"], answer: "책" },
  { meanings: ["나무에서 떨어지는 것", "가을에 색이 변해요"], answer: "낙엽" },
  { meanings: ["동물이 사는 집", "동물원에도 있어요"], answer: "우리" },
  {
    meanings: ["씨앗에서 처음 나오는 것", "잎이 되기 전 단계예요"],
    answer: "싹",
  },
  { meanings: ["물이 흐르는 곳", "산에서 시작해요"], answer: "시냇물" },
  { meanings: ["흙으로 만든 그릇", "예전에 많이 사용했어요"], answer: "토기" },
  { meanings: ["긴 목을 가진 동물", "나뭇잎을 먹어요"], answer: "기린" },
  { meanings: ["알을 낳는 새", "매일 아침 울어요"], answer: "닭" },
  { meanings: ["껍질이 단단한 과일", "속이 하얘요"], answer: "코코넛" },
  { meanings: ["쌀로 만든 우리나라 음식", "뜨거운 물을 부어요"], answer: "밥" },
  { meanings: ["학교에서 배우는 것", "시험을 봐요"], answer: "공부" },
  { meanings: ["바람이 세게 부는 자연 현상", "비를 동반해요"], answer: "태풍" },
  { meanings: ["얼음 위에서 타는 것", "겨울 운동이에요"], answer: "스케이트" },
  { meanings: ["악기를 연주하는 사람", "무대에서 공연해요"], answer: "연주자" },
  {
    meanings: ["소리를 크게 해 주는 기계", "음악을 들을 때 써요"],
    answer: "스피커",
  },
  {
    meanings: ["그림을 그리는 도구", "색깔이 여러 가지예요"],
    answer: "크레파스",
  },
  { meanings: ["종이를 자르는 도구", "날카로워요"], answer: "가위" },
  { meanings: ["물을 담는 투명한 그릇", "마실 때 사용해요"], answer: "컵" },
  { meanings: ["손가락에 끼는 장신구", "동그란 모양이에요"], answer: "반지" },
  { meanings: ["땅에서 뽑아 먹는 채소", "하얗고 매워요"], answer: "무" },
  {
    meanings: ["여러 사람이 함께 타는 차", "학교에 갈 때 타요"],
    answer: "버스",
  },
  { meanings: ["종이를 붙이는 데 쓰는 것", "끈적끈적해요"], answer: "풀" },
  {
    meanings: ["사람이나 동물의 뼈를 감싸는 것", "움직일 수 있게 해 줘요"],
    answer: "근육",
  },
];

export const grade3MathData: MathEntry[] = [
  // 기존 22개
  {
    type: "calculation",
    expression: "234 + 152",
    answer: 386,
    steps: [
      "4 + 2 = 6 (일의 자리)",
      "3 + 5 = 8 (십의 자리)",
      "2 + 1 = 3 (백의 자리)",
      "답: 386",
    ],
    unit: "세 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "367 + 245",
    answer: 612,
    steps: [
      "7 + 5 = 12, 일의 자리 2, 받아올림 1",
      "6 + 4 + 1 = 11, 십의 자리 1, 받아올림 1",
      "3 + 2 + 1 = 6 (백의 자리)",
      "답: 612",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "589 + 327",
    answer: 916,
    steps: [
      "9 + 7 = 16, 일의 자리 6, 받아올림 1",
      "8 + 2 + 1 = 11, 십의 자리 1, 받아올림 1",
      "5 + 3 + 1 = 9 (백의 자리)",
      "답: 916",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "745 - 312",
    answer: 433,
    steps: [
      "5 - 2 = 3 (일의 자리)",
      "4 - 1 = 3 (십의 자리)",
      "7 - 3 = 4 (백의 자리)",
      "답: 433",
    ],
    unit: "세 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "623 - 158",
    answer: 465,
    steps: [
      "3에서 8을 뺄 수 없으므로 받아내림",
      "13 - 8 = 5 (일의 자리)",
      "1에서 5를 뺄 수 없으므로 받아내림",
      "11 - 5 = 6 (십의 자리)",
      "5 - 1 = 4 (백의 자리)",
      "답: 465",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "23 × 4",
    answer: 92,
    steps: [
      "3 × 4 = 12, 일의 자리 2, 받아올림 1",
      "2 × 4 = 8, 8 + 1 = 9 (십의 자리)",
      "답: 92",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "15 × 6",
    answer: 90,
    steps: [
      "5 × 6 = 30, 일의 자리 0, 받아올림 3",
      "1 × 6 = 6, 6 + 3 = 9 (십의 자리)",
      "답: 90",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "34 × 7",
    answer: 238,
    steps: [
      "4 × 7 = 28, 일의 자리 8, 받아올림 2",
      "3 × 7 = 21, 21 + 2 = 23",
      "답: 238",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "12 ÷ 3",
    answer: 4,
    steps: ["12 안에 3이 4번 들어감", "3 × 4 = 12"],
    unit: "나눗셈",
    dividend: 12,
    divisor: 3,
    quotient: 4,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "20 ÷ 5",
    answer: 4,
    steps: ["20 안에 5가 4번 들어감", "5 × 4 = 20"],
    unit: "나눗셈",
    dividend: 20,
    divisor: 5,
    quotient: 4,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "35 ÷ 7",
    answer: 5,
    steps: ["35 안에 7이 5번 들어감", "7 × 5 = 35"],
    unit: "나눗셈",
    dividend: 35,
    divisor: 7,
    quotient: 5,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "17 ÷ 5",
    answer: 3,
    steps: ["17 안에 5가 3번 들어가고 2가 남음", "5 × 3 = 15, 나머지 2"],
    unit: "나머지가 있는 나눗셈",
    dividend: 17,
    divisor: 5,
    quotient: 3,
    remainder: 2,
  },
  {
    type: "calculation",
    expression: "23 ÷ 4",
    answer: 5,
    steps: ["23 안에 4가 5번 들어가고 3이 남음", "4 × 5 = 20, 나머지 3"],
    unit: "나머지가 있는 나눗셈",
    dividend: 23,
    divisor: 4,
    quotient: 5,
    remainder: 3,
  },
  {
    type: "calculation",
    expression: "1/4 + 1/4",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 더합니다", "1 + 1 = 2", "답: 2/4"],
    unit: "분수 덧셈",
    numbers: [1, 4, 1, 4],
  },
  {
    type: "calculation",
    expression: "3/5 - 1/5",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "3 - 1 = 2", "답: 2/5"],
    unit: "분수 뺄셈",
    numbers: [3, 5, 1, 5],
  },
  {
    type: "calculation",
    expression: "2시간 30분 + 1시간 40분",
    answer: 4,
    steps: [
      "30분 + 40분 = 70분 = 1시간 10분",
      "2시간 + 1시간 + 1시간 = 4시간",
      "답: 4시간 10분",
    ],
    unit: "시간 계산",
  },
  {
    type: "calculation",
    expression: "3시간 20분 - 1시간 50분",
    answer: 1,
    steps: [
      "20분에서 50분을 뺄 수 없으므로 1시간을 빌려옴",
      "80분 - 50분 = 30분",
      "2시간 - 1시간 = 1시간",
      "답: 1시간 30분",
    ],
    unit: "시간 계산",
  },
  {
    type: "calculation",
    expression: "48 ÷ 6",
    answer: 8,
    steps: ["48 안에 6이 8번 들어감", "6 × 8 = 48"],
    unit: "나눗셈",
    dividend: 48,
    divisor: 6,
    quotient: 8,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "56 ÷ 8",
    answer: 7,
    steps: ["56 안에 8이 7번 들어감", "8 × 7 = 56"],
    unit: "나눗셈",
    dividend: 56,
    divisor: 8,
    quotient: 7,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "42 × 3",
    answer: 126,
    steps: ["2 × 3 = 6 (일의 자리)", "4 × 3 = 12 (십의 자리)", "답: 126"],
    unit: "곱셈",
  },
  // 신규 58개 (총 80개)
  // 세 자리 덧셈 추가
  {
    type: "calculation",
    expression: "451 + 237",
    answer: 688,
    steps: [
      "1 + 7 = 8 (일의 자리)",
      "5 + 3 = 8 (십의 자리)",
      "4 + 2 = 6 (백의 자리)",
      "답: 688",
    ],
    unit: "세 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "176 + 458",
    answer: 634,
    steps: [
      "6 + 8 = 14, 일의 자리 4, 받아올림 1",
      "7 + 5 + 1 = 13, 십의 자리 3, 받아올림 1",
      "1 + 4 + 1 = 6 (백의 자리)",
      "답: 634",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "295 + 368",
    answer: 663,
    steps: [
      "5 + 8 = 13, 일의 자리 3, 받아올림 1",
      "9 + 6 + 1 = 16, 십의 자리 6, 받아올림 1",
      "2 + 3 + 1 = 6 (백의 자리)",
      "답: 663",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "534 + 289",
    answer: 823,
    steps: [
      "4 + 9 = 13, 일의 자리 3, 받아올림 1",
      "3 + 8 + 1 = 12, 십의 자리 2, 받아올림 1",
      "5 + 2 + 1 = 8 (백의 자리)",
      "답: 823",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "123 + 456",
    answer: 579,
    steps: [
      "3 + 6 = 9 (일의 자리)",
      "2 + 5 = 7 (십의 자리)",
      "1 + 4 = 5 (백의 자리)",
      "답: 579",
    ],
    unit: "세 자리 수 덧셈",
  },
  {
    type: "calculation",
    expression: "648 + 175",
    answer: 823,
    steps: [
      "8 + 5 = 13, 일의 자리 3, 받아올림 1",
      "4 + 7 + 1 = 12, 십의 자리 2, 받아올림 1",
      "6 + 1 + 1 = 8 (백의 자리)",
      "답: 823",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  {
    type: "calculation",
    expression: "703 + 198",
    answer: 901,
    steps: [
      "3 + 8 = 11, 일의 자리 1, 받아올림 1",
      "0 + 9 + 1 = 10, 십의 자리 0, 받아올림 1",
      "7 + 1 + 1 = 9 (백의 자리)",
      "답: 901",
    ],
    unit: "세 자리 수 덧셈",
    hasCarry: true,
  },
  // 세 자리 뺄셈 추가
  {
    type: "calculation",
    expression: "856 - 423",
    answer: 433,
    steps: [
      "6 - 3 = 3 (일의 자리)",
      "5 - 2 = 3 (십의 자리)",
      "8 - 4 = 4 (백의 자리)",
      "답: 433",
    ],
    unit: "세 자리 수 뺄셈",
  },
  {
    type: "calculation",
    expression: "500 - 237",
    answer: 263,
    steps: [
      "0에서 7을 뺄 수 없으므로 받아내림",
      "10 - 7 = 3 (일의 자리)",
      "9에서 3을 뺌 (백의 자리에서 받아내림)",
      "9 - 3 = 6 (십의 자리)",
      "4 - 2 = 2 (백의 자리)",
      "답: 263",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "912 - 467",
    answer: 445,
    steps: [
      "2에서 7을 뺄 수 없으므로 받아내림",
      "12 - 7 = 5 (일의 자리)",
      "0에서 6을 뺄 수 없으므로 받아내림",
      "10 - 6 = 4 (십의 자리)",
      "8 - 4 = 4 (백의 자리)",
      "답: 445",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "781 - 395",
    answer: 386,
    steps: [
      "1에서 5를 뺄 수 없으므로 받아내림",
      "11 - 5 = 6 (일의 자리)",
      "7에서 9를 뺄 수 없으므로 받아내림",
      "17 - 9 = 8 (십의 자리)",
      "6 - 3 = 3 (백의 자리)",
      "답: 386",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "600 - 128",
    answer: 472,
    steps: [
      "0에서 8을 뺄 수 없으므로 받아내림",
      "10 - 8 = 2 (일의 자리)",
      "9 - 2 = 7 (십의 자리)",
      "5 - 1 = 4 (백의 자리)",
      "답: 472",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "953 - 271",
    answer: 682,
    steps: [
      "3 - 1 = 2 (일의 자리)",
      "5 - 7을 뺄 수 없으므로 받아내림",
      "15 - 7 = 8 (십의 자리)",
      "8 - 2 = 6 (백의 자리)",
      "답: 682",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  {
    type: "calculation",
    expression: "847 - 563",
    answer: 284,
    steps: [
      "7 - 3 = 4 (일의 자리)",
      "4에서 6을 뺄 수 없으므로 받아내림",
      "14 - 6 = 8 (십의 자리)",
      "7 - 5 = 2 (백의 자리)",
      "답: 284",
    ],
    unit: "세 자리 수 뺄셈",
    hasBorrow: true,
  },
  // 곱셈 추가
  {
    type: "calculation",
    expression: "27 × 3",
    answer: 81,
    steps: [
      "7 × 3 = 21, 일의 자리 1, 받아올림 2",
      "2 × 3 = 6, 6 + 2 = 8 (십의 자리)",
      "답: 81",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "18 × 5",
    answer: 90,
    steps: [
      "8 × 5 = 40, 일의 자리 0, 받아올림 4",
      "1 × 5 = 5, 5 + 4 = 9 (십의 자리)",
      "답: 90",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "46 × 2",
    answer: 92,
    steps: [
      "6 × 2 = 12, 일의 자리 2, 받아올림 1",
      "4 × 2 = 8, 8 + 1 = 9 (십의 자리)",
      "답: 92",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "53 × 4",
    answer: 212,
    steps: [
      "3 × 4 = 12, 일의 자리 2, 받아올림 1",
      "5 × 4 = 20, 20 + 1 = 21",
      "답: 212",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "67 × 3",
    answer: 201,
    steps: [
      "7 × 3 = 21, 일의 자리 1, 받아올림 2",
      "6 × 3 = 18, 18 + 2 = 20",
      "답: 201",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "38 × 5",
    answer: 190,
    steps: [
      "8 × 5 = 40, 일의 자리 0, 받아올림 4",
      "3 × 5 = 15, 15 + 4 = 19",
      "답: 190",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "72 × 4",
    answer: 288,
    steps: ["2 × 4 = 8 (일의 자리)", "7 × 4 = 28", "답: 288"],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "19 × 7",
    answer: 133,
    steps: [
      "9 × 7 = 63, 일의 자리 3, 받아올림 6",
      "1 × 7 = 7, 7 + 6 = 13",
      "답: 133",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "85 × 2",
    answer: 170,
    steps: [
      "5 × 2 = 10, 일의 자리 0, 받아올림 1",
      "8 × 2 = 16, 16 + 1 = 17",
      "답: 170",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "29 × 6",
    answer: 174,
    steps: [
      "9 × 6 = 54, 일의 자리 4, 받아올림 5",
      "2 × 6 = 12, 12 + 5 = 17",
      "답: 174",
    ],
    unit: "곱셈",
  },
  // 나눗셈 추가
  {
    type: "calculation",
    expression: "24 ÷ 4",
    answer: 6,
    steps: ["24 안에 4가 6번 들어감", "4 × 6 = 24"],
    unit: "나눗셈",
    dividend: 24,
    divisor: 4,
    quotient: 6,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "36 ÷ 9",
    answer: 4,
    steps: ["36 안에 9가 4번 들어감", "9 × 4 = 36"],
    unit: "나눗셈",
    dividend: 36,
    divisor: 9,
    quotient: 4,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "45 ÷ 5",
    answer: 9,
    steps: ["45 안에 5가 9번 들어감", "5 × 9 = 45"],
    unit: "나눗셈",
    dividend: 45,
    divisor: 5,
    quotient: 9,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "63 ÷ 7",
    answer: 9,
    steps: ["63 안에 7이 9번 들어감", "7 × 9 = 63"],
    unit: "나눗셈",
    dividend: 63,
    divisor: 7,
    quotient: 9,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "72 ÷ 8",
    answer: 9,
    steps: ["72 안에 8이 9번 들어감", "8 × 9 = 72"],
    unit: "나눗셈",
    dividend: 72,
    divisor: 8,
    quotient: 9,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "54 ÷ 6",
    answer: 9,
    steps: ["54 안에 6이 9번 들어감", "6 × 9 = 54"],
    unit: "나눗셈",
    dividend: 54,
    divisor: 6,
    quotient: 9,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "81 ÷ 9",
    answer: 9,
    steps: ["81 안에 9가 9번 들어감", "9 × 9 = 81"],
    unit: "나눗셈",
    dividend: 81,
    divisor: 9,
    quotient: 9,
    remainder: 0,
  },
  {
    type: "calculation",
    expression: "42 ÷ 7",
    answer: 6,
    steps: ["42 안에 7이 6번 들어감", "7 × 6 = 42"],
    unit: "나눗셈",
    dividend: 42,
    divisor: 7,
    quotient: 6,
    remainder: 0,
  },
  // 나머지 있는 나눗셈 추가
  {
    type: "calculation",
    expression: "19 ÷ 4",
    answer: 4,
    steps: ["19 안에 4가 4번 들어가고 3이 남음", "4 × 4 = 16, 나머지 3"],
    unit: "나머지가 있는 나눗셈",
    dividend: 19,
    divisor: 4,
    quotient: 4,
    remainder: 3,
  },
  {
    type: "calculation",
    expression: "26 ÷ 3",
    answer: 8,
    steps: ["26 안에 3이 8번 들어가고 2가 남음", "3 × 8 = 24, 나머지 2"],
    unit: "나머지가 있는 나눗셈",
    dividend: 26,
    divisor: 3,
    quotient: 8,
    remainder: 2,
  },
  {
    type: "calculation",
    expression: "37 ÷ 6",
    answer: 6,
    steps: ["37 안에 6이 6번 들어가고 1이 남음", "6 × 6 = 36, 나머지 1"],
    unit: "나머지가 있는 나눗셈",
    dividend: 37,
    divisor: 6,
    quotient: 6,
    remainder: 1,
  },
  {
    type: "calculation",
    expression: "29 ÷ 8",
    answer: 3,
    steps: ["29 안에 8이 3번 들어가고 5가 남음", "8 × 3 = 24, 나머지 5"],
    unit: "나머지가 있는 나눗셈",
    dividend: 29,
    divisor: 8,
    quotient: 3,
    remainder: 5,
  },
  {
    type: "calculation",
    expression: "50 ÷ 7",
    answer: 7,
    steps: ["50 안에 7이 7번 들어가고 1이 남음", "7 × 7 = 49, 나머지 1"],
    unit: "나머지가 있는 나눗셈",
    dividend: 50,
    divisor: 7,
    quotient: 7,
    remainder: 1,
  },
  {
    type: "calculation",
    expression: "33 ÷ 4",
    answer: 8,
    steps: ["33 안에 4가 8번 들어가고 1이 남음", "4 × 8 = 32, 나머지 1"],
    unit: "나머지가 있는 나눗셈",
    dividend: 33,
    divisor: 4,
    quotient: 8,
    remainder: 1,
  },
  {
    type: "calculation",
    expression: "47 ÷ 9",
    answer: 5,
    steps: ["47 안에 9가 5번 들어가고 2가 남음", "9 × 5 = 45, 나머지 2"],
    unit: "나머지가 있는 나눗셈",
    dividend: 47,
    divisor: 9,
    quotient: 5,
    remainder: 2,
  },
  {
    type: "calculation",
    expression: "58 ÷ 7",
    answer: 8,
    steps: ["58 안에 7이 8번 들어가고 2가 남음", "7 × 8 = 56, 나머지 2"],
    unit: "나머지가 있는 나눗셈",
    dividend: 58,
    divisor: 7,
    quotient: 8,
    remainder: 2,
  },
  // 분수 추가
  {
    type: "calculation",
    expression: "2/5 + 1/5",
    answer: 3,
    steps: ["분모가 같으므로 분자끼리 더합니다", "2 + 1 = 3", "답: 3/5"],
    unit: "분수 덧셈",
    numbers: [2, 5, 1, 5],
  },
  {
    type: "calculation",
    expression: "4/6 - 2/6",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "4 - 2 = 2", "답: 2/6"],
    unit: "분수 뺄셈",
    numbers: [4, 6, 2, 6],
  },
  {
    type: "calculation",
    expression: "3/8 + 2/8",
    answer: 5,
    steps: ["분모가 같으므로 분자끼리 더합니다", "3 + 2 = 5", "답: 5/8"],
    unit: "분수 덧셈",
    numbers: [3, 8, 2, 8],
  },
  {
    type: "calculation",
    expression: "5/7 - 3/7",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "5 - 3 = 2", "답: 2/7"],
    unit: "분수 뺄셈",
    numbers: [5, 7, 3, 7],
  },
  {
    type: "calculation",
    expression: "1/3 + 1/3",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 더합니다", "1 + 1 = 2", "답: 2/3"],
    unit: "분수 덧셈",
    numbers: [1, 3, 1, 3],
  },
  {
    type: "calculation",
    expression: "6/9 - 4/9",
    answer: 2,
    steps: ["분모가 같으므로 분자끼리 뺍니다", "6 - 4 = 2", "답: 2/9"],
    unit: "분수 뺄셈",
    numbers: [6, 9, 4, 9],
  },
  // 시간 계산 추가
  {
    type: "calculation",
    expression: "1시간 45분 + 2시간 30분",
    answer: 4,
    steps: [
      "45분 + 30분 = 75분 = 1시간 15분",
      "1시간 + 2시간 + 1시간 = 4시간",
      "답: 4시간 15분",
    ],
    unit: "시간 계산",
  },
  {
    type: "calculation",
    expression: "4시간 10분 - 1시간 35분",
    answer: 2,
    steps: [
      "10분에서 35분을 뺄 수 없으므로 1시간을 빌려옴",
      "70분 - 35분 = 35분",
      "3시간 - 1시간 = 2시간",
      "답: 2시간 35분",
    ],
    unit: "시간 계산",
  },
  {
    type: "calculation",
    expression: "2시간 50분 + 1시간 25분",
    answer: 4,
    steps: [
      "50분 + 25분 = 75분 = 1시간 15분",
      "2시간 + 1시간 + 1시간 = 4시간",
      "답: 4시간 15분",
    ],
    unit: "시간 계산",
  },
  {
    type: "calculation",
    expression: "5시간 15분 - 2시간 40분",
    answer: 2,
    steps: [
      "15분에서 40분을 뺄 수 없으므로 1시간을 빌려옴",
      "75분 - 40분 = 35분",
      "4시간 - 2시간 = 2시간",
      "답: 2시간 35분",
    ],
    unit: "시간 계산",
  },
  // 길이 계산
  {
    type: "calculation",
    expression: "3km 400m + 2km 700m",
    answer: 6,
    steps: [
      "400m + 700m = 1100m = 1km 100m",
      "3km + 2km + 1km = 6km",
      "답: 6km 100m",
    ],
    unit: "길이 계산",
  },
  {
    type: "calculation",
    expression: "5km 200m - 1km 800m",
    answer: 3,
    steps: [
      "200m에서 800m을 뺄 수 없으므로 1km를 빌려옴",
      "1200m - 800m = 400m",
      "4km - 1km = 3km",
      "답: 3km 400m",
    ],
    unit: "길이 계산",
  },
  // 무게 계산
  {
    type: "calculation",
    expression: "2kg 300g + 1kg 800g",
    answer: 4,
    steps: [
      "300g + 800g = 1100g = 1kg 100g",
      "2kg + 1kg + 1kg = 4kg",
      "답: 4kg 100g",
    ],
    unit: "무게 계산",
  },
  {
    type: "calculation",
    expression: "3kg 100g - 1kg 600g",
    answer: 1,
    steps: [
      "100g에서 600g을 뺄 수 없으므로 1kg를 빌려옴",
      "1100g - 600g = 500g",
      "2kg - 1kg = 1kg",
      "답: 1kg 500g",
    ],
    unit: "무게 계산",
  },
  // 들이 계산
  {
    type: "calculation",
    expression: "1L 500mL + 2L 700mL",
    answer: 4,
    steps: [
      "500mL + 700mL = 1200mL = 1L 200mL",
      "1L + 2L + 1L = 4L",
      "답: 4L 200mL",
    ],
    unit: "들이 계산",
  },
  {
    type: "calculation",
    expression: "3L 200mL - 1L 500mL",
    answer: 1,
    steps: [
      "200mL에서 500mL을 뺄 수 없으므로 1L를 빌려옴",
      "1200mL - 500mL = 700mL",
      "2L - 1L = 1L",
      "답: 1L 700mL",
    ],
    unit: "들이 계산",
  },
  // 곱셈 추가
  {
    type: "calculation",
    expression: "63 × 5",
    answer: 315,
    steps: [
      "3 × 5 = 15, 일의 자리 5, 받아올림 1",
      "6 × 5 = 30, 30 + 1 = 31",
      "답: 315",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "47 × 8",
    answer: 376,
    steps: [
      "7 × 8 = 56, 일의 자리 6, 받아올림 5",
      "4 × 8 = 32, 32 + 5 = 37",
      "답: 376",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "56 × 9",
    answer: 504,
    steps: [
      "6 × 9 = 54, 일의 자리 4, 받아올림 5",
      "5 × 9 = 45, 45 + 5 = 50",
      "답: 504",
    ],
    unit: "곱셈",
  },
  {
    type: "calculation",
    expression: "31 ÷ 6",
    answer: 5,
    steps: ["31 안에 6이 5번 들어가고 1이 남음", "6 × 5 = 30, 나머지 1"],
    unit: "나머지가 있는 나눗셈",
    dividend: 31,
    divisor: 6,
    quotient: 5,
    remainder: 1,
  },
];

export const grade3KnowledgeData: KnowledgeEntry[] = [
  // 기존 15개
  { text: "우리나라의 국화는 ___이다.", answer: "무궁화", category: "사회" },
  { text: "태양계에는 ___개의 행성이 있다.", answer: "8", category: "과학" },
  {
    text: "식물의 뿌리가 하는 일은 물과 ___을 흡수하는 것이다.",
    answer: "양분",
    category: "과학",
  },
  {
    text: "우리 몸에서 음식을 소화하는 기관은 ___이다.",
    answer: "위",
    category: "과학",
  },
  {
    text: "나침반의 빨간 바늘은 항상 ___쪽을 가리킨다.",
    answer: "북",
    category: "과학",
  },
  {
    text: "세종대왕이 만든 우리나라의 글자는 ___이다.",
    answer: "한글",
    category: "역사",
  },
  {
    text: "지도에서 높은 곳은 ___색으로 표시한다.",
    answer: "갈",
    category: "사회",
  },
  {
    text: "물의 세 가지 상태는 고체, 액체, ___이다.",
    answer: "기체",
    category: "과학",
  },
  {
    text: "곤충의 몸은 머리, 가슴, ___로 나뉜다.",
    answer: "배",
    category: "과학",
  },
  {
    text: "우리나라의 전통 악기 중 줄이 있는 것은 ___이다.",
    answer: "가야금",
    category: "문화",
  },
  { text: "1L는 ___mL이다.", answer: "1000", category: "수학" },
  { text: "1kg은 ___g이다.", answer: "1000", category: "수학" },
  {
    text: "동서남북 중 해가 지는 방향은 ___쪽이다.",
    answer: "서",
    category: "과학",
  },
  { text: "올챙이가 자라면 ___가 된다.", answer: "개구리", category: "과학" },
  {
    text: "고구려, 백제, ___을 삼국이라 한다.",
    answer: "신라",
    category: "역사",
  },
  // 신규 45개 (총 60개)
  {
    text: "식물이 빛을 받아 양분을 만드는 것을 ___이라 한다.",
    answer: "광합성",
    category: "과학",
  },
  {
    text: "지구에서 가장 가까운 별은 ___이다.",
    answer: "태양",
    category: "과학",
  },
  {
    text: "뼈와 뼈를 이어 주는 것을 ___이라 한다.",
    answer: "관절",
    category: "과학",
  },
  { text: "우리나라의 수도는 ___이다.", answer: "서울", category: "사회" },
  { text: "물이 끓는 온도는 ___도이다.", answer: "100", category: "과학" },
  { text: "물이 어는 온도는 ___도이다.", answer: "0", category: "과학" },
  { text: "하루는 ___시간이다.", answer: "24", category: "수학" },
  { text: "1시간은 ___분이다.", answer: "60", category: "수학" },
  { text: "1분은 ___초이다.", answer: "60", category: "수학" },
  { text: "곤충의 다리는 ___개이다.", answer: "6", category: "과학" },
  { text: "거미의 다리는 ___개이다.", answer: "8", category: "과학" },
  {
    text: "식물의 잎에서 수분이 빠져나가는 것을 ___이라 한다.",
    answer: "증산",
    category: "과학",
  },
  {
    text: "우리나라 국기의 이름은 ___이다.",
    answer: "태극기",
    category: "사회",
  },
  { text: "한글날은 ___월 9일이다.", answer: "10", category: "사회" },
  {
    text: "나비의 한살이는 알 → 애벌레 → ___ → 어른벌레이다.",
    answer: "번데기",
    category: "과학",
  },
  {
    text: "사람의 이빨 중 앞니는 음식을 ___는 역할을 한다.",
    answer: "자르",
    category: "과학",
  },
  {
    text: "혈액이 온몸을 도는 것을 ___이라 한다.",
    answer: "혈액 순환",
    category: "과학",
  },
  {
    text: "태양계에서 지구 바로 안쪽에 있는 행성은 ___이다.",
    answer: "금성",
    category: "과학",
  },
  {
    text: "동물 중 알을 낳는 것을 ___동물이라 한다.",
    answer: "난생",
    category: "과학",
  },
  {
    text: "새끼를 낳는 동물을 ___동물이라 한다.",
    answer: "태생",
    category: "과학",
  },
  {
    text: "우리나라의 전통 명절 중 음력 1월 1일은 ___이다.",
    answer: "설날",
    category: "문화",
  },
  {
    text: "우리나라의 전통 명절 중 음력 8월 15일은 ___이다.",
    answer: "추석",
    category: "문화",
  },
  {
    text: "온도를 재는 도구를 ___이라 한다.",
    answer: "온도계",
    category: "과학",
  },
  {
    text: "지도에서 방위를 나타내는 기호를 ___이라 한다.",
    answer: "방위표",
    category: "사회",
  },
  {
    text: "지구의 약 70%를 차지하는 것은 ___이다.",
    answer: "바다",
    category: "과학",
  },
  { text: "자석에는 N극과 ___극이 있다.", answer: "S", category: "과학" },
  {
    text: "같은 극끼리는 밀어내고, 다른 극끼리는 ___.",
    answer: "끌어당긴다",
    category: "과학",
  },
  { text: "우리나라 돈의 단위는 ___이다.", answer: "원", category: "사회" },
  {
    text: "지도에서 실제 거리를 줄인 비율을 ___이라 한다.",
    answer: "축척",
    category: "사회",
  },
  {
    text: "식물의 줄기가 하는 일은 물과 양분을 ___하는 것이다.",
    answer: "운반",
    category: "과학",
  },
  {
    text: "공기 중에 가장 많은 기체는 ___이다.",
    answer: "질소",
    category: "과학",
  },
  {
    text: "사람이 숨을 쉴 때 필요한 기체는 ___이다.",
    answer: "산소",
    category: "과학",
  },
  {
    text: "빛이 물체에 부딪혀 되돌아오는 것을 ___이라 한다.",
    answer: "반사",
    category: "과학",
  },
  {
    text: "소리가 나는 물체는 ___하고 있다.",
    answer: "진동",
    category: "과학",
  },
  {
    text: "우리나라의 전통 음식인 김치의 주재료는 ___이다.",
    answer: "배추",
    category: "문화",
  },
  {
    text: "세종대왕이 한글을 만든 해는 ___년이다.",
    answer: "1443",
    category: "역사",
  },
  {
    text: "한 해에서 낮의 길이가 가장 긴 날을 ___이라 한다.",
    answer: "하지",
    category: "과학",
  },
  {
    text: "한 해에서 밤의 길이가 가장 긴 날을 ___이라 한다.",
    answer: "동지",
    category: "과학",
  },
  {
    text: "우리나라 최초의 국가는 ___이다.",
    answer: "고조선",
    category: "역사",
  },
  {
    text: "삼국 통일을 이룬 나라는 ___이다.",
    answer: "신라",
    category: "역사",
  },
  {
    text: "우리 몸에서 피를 온몸으로 보내는 기관은 ___이다.",
    answer: "심장",
    category: "과학",
  },
  {
    text: "식물이 자라기 위해 필요한 세 가지는 물, 빛, ___이다.",
    answer: "흙",
    category: "과학",
  },
  { text: "1km는 ___m이다.", answer: "1000", category: "수학" },
  { text: "1m는 ___cm이다.", answer: "100", category: "수학" },
  {
    text: "삼각형의 세 변의 길이의 합을 ___라 한다.",
    answer: "둘레",
    category: "수학",
  },
];

export const grade3SafetyData: SafetyEntry[] = [
  // 기존 10개
  {
    text: "인터넷에서 개인정보를 ___하면 안 된다.",
    answer: "공개",
    category: "정보안전",
  },
  {
    text: "친구가 다치면 ___에게 알린다.",
    answer: "선생님",
    category: "학교안전",
  },
  { text: "태풍이 오면 ___에 머문다.", answer: "실내", category: "재난안전" },
  {
    text: "모르는 사람의 차에 ___면 안 된다.",
    answer: "타",
    category: "생활안전",
  },
  {
    text: "가스 냄새가 나면 ___을 열고 대피한다.",
    answer: "창문",
    category: "화재안전",
  },
  {
    text: "놀이터에서 줄을 서서 ___를 지킨다.",
    answer: "차례",
    category: "학교안전",
  },
  {
    text: "음식물 알레르기가 있으면 ___에게 미리 알린다.",
    answer: "선생님",
    category: "건강안전",
  },
  {
    text: "무거운 물건은 ___를 굽혀 들어올린다.",
    answer: "무릎",
    category: "생활안전",
  },
  {
    text: "비상구 위치를 미리 ___해 둔다.",
    answer: "확인",
    category: "화재안전",
  },
  {
    text: "장마철에는 ___이 날 수 있으니 하천 근처에 가지 않는다.",
    answer: "홍수",
    category: "재난안전",
  },
  // 신규 30개 (총 40개)
  {
    text: "횡단보도를 건널 때는 ___을 살피고 건넌다.",
    answer: "좌우",
    category: "교통안전",
  },
  {
    text: "자전거를 탈 때는 반드시 ___를 착용한다.",
    answer: "헬멧",
    category: "교통안전",
  },
  {
    text: "교실에서 뛰면 ___의 위험이 있다.",
    answer: "넘어짐",
    category: "학교안전",
  },
  {
    text: "화재 시 연기가 많으면 ___을 낮추고 이동한다.",
    answer: "몸",
    category: "화재안전",
  },
  {
    text: "수영장에서는 반드시 ___의 지시를 따른다.",
    answer: "안전요원",
    category: "생활안전",
  },
  {
    text: "뜨거운 물에 ___을 수 있으니 조심한다.",
    answer: "데일",
    category: "생활안전",
  },
  {
    text: "눈이 오면 길이 ___해서 조심해야 한다.",
    answer: "미끄러워",
    category: "재난안전",
  },
  {
    text: "약은 반드시 ___의 허락을 받고 먹는다.",
    answer: "어른",
    category: "건강안전",
  },
  {
    text: "모르는 사람이 길을 물으면 가까운 ___에게 알린다.",
    answer: "어른",
    category: "생활안전",
  },
  {
    text: "119는 ___를 신고하는 전화번호이다.",
    answer: "화재",
    category: "화재안전",
  },
  {
    text: "112는 ___를 신고하는 전화번호이다.",
    answer: "범죄",
    category: "생활안전",
  },
  {
    text: "전기 콘센트에 젖은 손으로 ___하면 위험하다.",
    answer: "만지",
    category: "전기안전",
  },
  {
    text: "지진이 나면 ___아래로 들어가 몸을 보호한다.",
    answer: "책상",
    category: "재난안전",
  },
  {
    text: "음식을 먹기 전에 반드시 ___을 씻는다.",
    answer: "손",
    category: "건강안전",
  },
  {
    text: "횡단보도에서 ___가 초록색일 때 건넌다.",
    answer: "신호등",
    category: "교통안전",
  },
  {
    text: "버스에서 내릴 때는 차가 ___한 후에 내린다.",
    answer: "정차",
    category: "교통안전",
  },
  {
    text: "실내에서 칼이나 가위는 ___을 아래로 향하게 들고 다닌다.",
    answer: "날",
    category: "생활안전",
  },
  {
    text: "비 오는 날에는 ___색 옷을 입으면 잘 보인다.",
    answer: "밝은",
    category: "교통안전",
  },
  {
    text: "인터넷에서 ___을 함부로 다운로드하면 바이러스에 걸릴 수 있다.",
    answer: "파일",
    category: "정보안전",
  },
  {
    text: "친구를 ___하는 것은 학교 폭력이다.",
    answer: "괴롭히",
    category: "학교안전",
  },
  {
    text: "엘리베이터에서 갇히면 ___버튼을 누른다.",
    answer: "비상",
    category: "생활안전",
  },
  {
    text: "여름에는 ___을 충분히 발라 피부를 보호한다.",
    answer: "자외선차단제",
    category: "건강안전",
  },
  {
    text: "캠핑장에서 ___를 피울 때는 어른과 함께한다.",
    answer: "불",
    category: "화재안전",
  },
  {
    text: "감기에 걸리면 ___을 하여 다른 사람에게 옮기지 않는다.",
    answer: "마스크 착용",
    category: "건강안전",
  },
  {
    text: "공사장 근처에서는 ___를 주의하며 지나간다.",
    answer: "안전",
    category: "생활안전",
  },
  {
    text: "인터넷에서 나쁜 말을 하는 것은 ___이다.",
    answer: "사이버 폭력",
    category: "정보안전",
  },
  {
    text: "여름철 에어컨 적정 온도는 ___도이다.",
    answer: "26",
    category: "건강안전",
  },
  {
    text: "번개가 칠 때는 나무 ___에 서 있으면 위험하다.",
    answer: "아래",
    category: "재난안전",
  },
  {
    text: "학교에서 실험을 할 때는 선생님의 ___를 따른다.",
    answer: "지시",
    category: "학교안전",
  },
  {
    text: "미세먼지가 많은 날에는 ___활동을 줄인다.",
    answer: "바깥",
    category: "건강안전",
  },
];

export const grade3HanjaData: HanjaEntry[] = [
  // 기존 15개
  {
    character: "山",
    reading: "산",
    meaning: "뫼 산",
    strokes: 3,
    words: ["산맥", "등산", "화산"],
    sentence: "높은 山에 올라갔다.",
  },
  {
    character: "水",
    reading: "수",
    meaning: "물 수",
    strokes: 4,
    words: ["수영", "홍수", "수도"],
    sentence: "깨끗한 水를 마셨다.",
  },
  {
    character: "火",
    reading: "화",
    meaning: "불 화",
    strokes: 4,
    words: ["화재", "불꽃", "소화기"],
    sentence: "火가 나면 119에 전화한다.",
  },
  {
    character: "木",
    reading: "목",
    meaning: "나무 목",
    strokes: 4,
    words: ["나무", "목재", "목요일"],
    sentence: "木이 높이 자랐다.",
  },
  {
    character: "土",
    reading: "토",
    meaning: "흙 토",
    strokes: 3,
    words: ["토양", "토요일", "국토"],
    sentence: "土에 씨앗을 심었다.",
  },
  {
    character: "日",
    reading: "일",
    meaning: "날 일",
    strokes: 4,
    words: ["일요일", "생일", "매일"],
    sentence: "오늘은 좋은 日이다.",
  },
  {
    character: "月",
    reading: "월",
    meaning: "달 월",
    strokes: 4,
    words: ["월요일", "정월", "매월"],
    sentence: "밤하늘에 月이 떴다.",
  },
  {
    character: "人",
    reading: "인",
    meaning: "사람 인",
    strokes: 2,
    words: ["인간", "가인", "인구"],
    sentence: "모든 人은 소중하다.",
  },
  {
    character: "大",
    reading: "대",
    meaning: "큰 대",
    strokes: 3,
    words: ["대문", "거대", "최대"],
    sentence: "大한민국 만세!",
  },
  {
    character: "小",
    reading: "소",
    meaning: "작을 소",
    strokes: 3,
    words: ["소인", "소문", "최소"],
    sentence: "小한 것도 소중하다.",
  },
  {
    character: "上",
    reading: "상",
    meaning: "위 상",
    strokes: 3,
    words: ["상자", "이상", "상의"],
    sentence: "책상 上에 책이 있다.",
  },
  {
    character: "下",
    reading: "하",
    meaning: "아래 하",
    strokes: 3,
    words: ["하늘", "지하", "하의"],
    sentence: "나무 下에서 쉬었다.",
  },
  {
    character: "中",
    reading: "중",
    meaning: "가운데 중",
    strokes: 4,
    words: ["중심", "집중", "중요"],
    sentence: "교실 中에 모였다.",
  },
  {
    character: "天",
    reading: "천",
    meaning: "하늘 천",
    strokes: 4,
    words: ["천국", "천재", "천둥"],
    sentence: "天이 맑고 푸르다.",
  },
  {
    character: "地",
    reading: "지",
    meaning: "땅 지",
    strokes: 6,
    words: ["지구", "토지", "지도"],
    sentence: "地에 꽃이 피었다.",
  },
  // 신규 45개 (총 60개)
  {
    character: "金",
    reading: "금",
    meaning: "쇠 금",
    strokes: 8,
    words: ["금메달", "황금", "금요일"],
    sentence: "金메달을 받았다.",
  },
  {
    character: "白",
    reading: "백",
    meaning: "흰 백",
    strokes: 5,
    words: ["백색", "백설", "백조"],
    sentence: "白雪이 내렸다.",
  },
  {
    character: "靑",
    reading: "청",
    meaning: "푸를 청",
    strokes: 8,
    words: ["청소년", "청색", "청춘"],
    sentence: "靑春을 즐기자.",
  },
  {
    character: "赤",
    reading: "적",
    meaning: "붉을 적",
    strokes: 7,
    words: ["적색", "적십자", "적도"],
    sentence: "赤色 신호등에 멈춘다.",
  },
  {
    character: "左",
    reading: "좌",
    meaning: "왼 좌",
    strokes: 5,
    words: ["좌회전", "좌우", "좌석"],
    sentence: "左회전을 했다.",
  },
  {
    character: "右",
    reading: "우",
    meaning: "오른 우",
    strokes: 5,
    words: ["우회전", "좌우", "우측"],
    sentence: "右측통행을 한다.",
  },
  {
    character: "東",
    reading: "동",
    meaning: "동녘 동",
    strokes: 8,
    words: ["동쪽", "동해", "동물"],
    sentence: "해는 東에서 뜬다.",
  },
  {
    character: "西",
    reading: "서",
    meaning: "서녘 서",
    strokes: 6,
    words: ["서쪽", "서울", "서양"],
    sentence: "해는 西에서 진다.",
  },
  {
    character: "南",
    reading: "남",
    meaning: "남녘 남",
    strokes: 9,
    words: ["남쪽", "남산", "남자"],
    sentence: "南쪽은 따뜻하다.",
  },
  {
    character: "北",
    reading: "북",
    meaning: "북녘 북",
    strokes: 5,
    words: ["북쪽", "북극", "북한"],
    sentence: "北쪽에서 찬바람이 불었다.",
  },
  {
    character: "口",
    reading: "구",
    meaning: "입 구",
    strokes: 3,
    words: ["인구", "입구", "구호"],
    sentence: "口를 크게 벌려 말한다.",
  },
  {
    character: "目",
    reading: "목",
    meaning: "눈 목",
    strokes: 5,
    words: ["주목", "목표", "항목"],
    sentence: "目표를 세웠다.",
  },
  {
    character: "耳",
    reading: "이",
    meaning: "귀 이",
    strokes: 6,
    words: ["이비인후과", "이명", "귀"],
    sentence: "耳로 소리를 듣는다.",
  },
  {
    character: "手",
    reading: "수",
    meaning: "손 수",
    strokes: 4,
    words: ["수화", "선수", "악수"],
    sentence: "手를 깨끗이 씻었다.",
  },
  {
    character: "足",
    reading: "족",
    meaning: "발 족",
    strokes: 7,
    words: ["족적", "만족", "부족"],
    sentence: "두 足으로 걸어갔다.",
  },
  {
    character: "子",
    reading: "자",
    meaning: "아들 자",
    strokes: 3,
    words: ["자녀", "왕자", "아들"],
    sentence: "子는 부모를 공경한다.",
  },
  {
    character: "女",
    reading: "여",
    meaning: "여자 여",
    strokes: 3,
    words: ["여자", "여성", "소녀"],
    sentence: "少女가 노래를 불렀다.",
  },
  {
    character: "父",
    reading: "부",
    meaning: "아버지 부",
    strokes: 4,
    words: ["부모", "조부", "부친"],
    sentence: "父母님께 감사한다.",
  },
  {
    character: "母",
    reading: "모",
    meaning: "어머니 모",
    strokes: 5,
    words: ["모친", "부모", "조모"],
    sentence: "母의 사랑은 크다.",
  },
  {
    character: "兄",
    reading: "형",
    meaning: "형 형",
    strokes: 5,
    words: ["형제", "형님", "사형"],
    sentence: "兄과 함께 놀았다.",
  },
  {
    character: "弟",
    reading: "제",
    meaning: "아우 제",
    strokes: 7,
    words: ["형제", "제자", "자매"],
    sentence: "兄弟가 사이좋게 지낸다.",
  },
  {
    character: "一",
    reading: "일",
    meaning: "한 일",
    strokes: 1,
    words: ["일등", "하나", "통일"],
    sentence: "一등으로 들어왔다.",
  },
  {
    character: "二",
    reading: "이",
    meaning: "두 이",
    strokes: 2,
    words: ["이등", "이월", "이십"],
    sentence: "二月에 눈이 왔다.",
  },
  {
    character: "三",
    reading: "삼",
    meaning: "석 삼",
    strokes: 3,
    words: ["삼각형", "삼월", "삼국"],
    sentence: "三角형을 그렸다.",
  },
  {
    character: "四",
    reading: "사",
    meaning: "넉 사",
    strokes: 5,
    words: ["사계절", "사각형", "사월"],
    sentence: "四季節이 아름답다.",
  },
  {
    character: "五",
    reading: "오",
    meaning: "다섯 오",
    strokes: 4,
    words: ["오월", "오감", "오각형"],
    sentence: "五月에 가정의 달이다.",
  },
  {
    character: "六",
    reading: "육",
    meaning: "여섯 육",
    strokes: 4,
    words: ["육월", "육각형", "육지"],
    sentence: "六月에 여름이 시작된다.",
  },
  {
    character: "七",
    reading: "칠",
    meaning: "일곱 칠",
    strokes: 2,
    words: ["칠월", "칠판", "칠색"],
    sentence: "무지개는 七색이다.",
  },
  {
    character: "八",
    reading: "팔",
    meaning: "여덟 팔",
    strokes: 2,
    words: ["팔월", "팔각형", "팔도"],
    sentence: "八月에 방학이 끝난다.",
  },
  {
    character: "九",
    reading: "구",
    meaning: "아홉 구",
    strokes: 2,
    words: ["구월", "구구단", "구급"],
    sentence: "九九段을 외우자.",
  },
  {
    character: "十",
    reading: "십",
    meaning: "열 십",
    strokes: 2,
    words: ["십월", "십자가", "십진법"],
    sentence: "十月에 한글날이 있다.",
  },
  {
    character: "百",
    reading: "백",
    meaning: "일백 백",
    strokes: 6,
    words: ["백점", "백성", "백일"],
    sentence: "시험에서 百점을 받았다.",
  },
  {
    character: "千",
    reading: "천",
    meaning: "일천 천",
    strokes: 3,
    words: ["천원", "천년", "천리"],
    sentence: "千里 길도 한 걸음부터.",
  },
  {
    character: "萬",
    reading: "만",
    meaning: "일만 만",
    strokes: 13,
    words: ["만원", "만세", "만물"],
    sentence: "萬歲를 외쳤다.",
  },
  {
    character: "年",
    reading: "년",
    meaning: "해 년",
    strokes: 6,
    words: ["올해", "작년", "내년"],
    sentence: "새 年이 밝았다.",
  },
  {
    character: "力",
    reading: "력",
    meaning: "힘 력",
    strokes: 2,
    words: ["노력", "체력", "능력"],
    sentence: "努力하면 이룰 수 있다.",
  },
  {
    character: "正",
    reading: "정",
    meaning: "바를 정",
    strokes: 5,
    words: ["정직", "정확", "정의"],
    sentence: "正直하게 살자.",
  },
  {
    character: "王",
    reading: "왕",
    meaning: "임금 왕",
    strokes: 4,
    words: ["왕국", "국왕", "여왕"],
    sentence: "세종대王은 위대하다.",
  },
  {
    character: "氣",
    reading: "기",
    meaning: "기운 기",
    strokes: 6,
    words: ["기분", "천기", "인기"],
    sentence: "오늘은 氣분이 좋다.",
  },
  {
    character: "花",
    reading: "화",
    meaning: "꽃 화",
    strokes: 8,
    words: ["꽃", "화분", "개화"],
    sentence: "봄에 花가 피었다.",
  },
  {
    character: "草",
    reading: "초",
    meaning: "풀 초",
    strokes: 10,
    words: ["초원", "잡초", "풀밭"],
    sentence: "草원에서 뛰어놀았다.",
  },
  {
    character: "生",
    reading: "생",
    meaning: "날 생",
    strokes: 5,
    words: ["생일", "학생", "생활"],
    sentence: "生日 축하합니다.",
  },
  {
    character: "食",
    reading: "식",
    meaning: "먹을 식",
    strokes: 9,
    words: ["식사", "음식", "식당"],
    sentence: "食事 시간이다.",
  },
  {
    character: "入",
    reading: "입",
    meaning: "들 입",
    strokes: 2,
    words: ["입구", "입학", "수입"],
    sentence: "학교에 入學했다.",
  },
  {
    character: "出",
    reading: "출",
    meaning: "날 출",
    strokes: 5,
    words: ["출구", "출발", "수출"],
    sentence: "出口로 나갔다.",
  },
];

export const grade3EnglishData: EnglishEntry[] = [
  // 기존 15개
  {
    sentence: "Hello, my name is Minho.",
    translation: "안녕, 내 이름은 민호야.",
    word: "name",
    pronunciation: "네임",
    practice: ["My name is ___.", "What is your name?"],
  },
  {
    sentence: "I like apples.",
    translation: "나는 사과를 좋아해.",
    word: "like",
    pronunciation: "라이크",
    practice: ["I like ___.", "Do you like bananas?"],
  },
  {
    sentence: "How are you?",
    translation: "잘 지내니?",
    word: "how",
    pronunciation: "하우",
    practice: ["How are you?", "I am fine."],
  },
  {
    sentence: "This is my dog.",
    translation: "이것은 내 강아지야.",
    word: "dog",
    pronunciation: "도그",
    practice: ["This is my ___.", "I have a dog."],
  },
  {
    sentence: "I am happy.",
    translation: "나는 행복해.",
    word: "happy",
    pronunciation: "해피",
    practice: ["I am ___.", "Are you happy?"],
  },
  {
    sentence: "Thank you very much.",
    translation: "정말 고마워.",
    word: "thank",
    pronunciation: "땡크",
    practice: ["Thank you.", "Thank you for the gift."],
  },
  {
    sentence: "What is this?",
    translation: "이것은 무엇이니?",
    word: "what",
    pronunciation: "왓",
    practice: ["What is this?", "What is that?"],
  },
  {
    sentence: "I can run fast.",
    translation: "나는 빨리 달릴 수 있어.",
    word: "run",
    pronunciation: "런",
    practice: ["I can ___.", "Can you run?"],
  },
  {
    sentence: "It is sunny today.",
    translation: "오늘은 화창해.",
    word: "sunny",
    pronunciation: "써니",
    practice: ["It is ___ today.", "Is it rainy?"],
  },
  {
    sentence: "I have two brothers.",
    translation: "나는 남자 형제가 둘 있어.",
    word: "brother",
    pronunciation: "브라더",
    practice: ["I have ___ brothers.", "Do you have a sister?"],
  },
  {
    sentence: "She is my friend.",
    translation: "그녀는 내 친구야.",
    word: "friend",
    pronunciation: "프렌드",
    practice: ["She is my ___.", "He is my friend."],
  },
  {
    sentence: "I go to school.",
    translation: "나는 학교에 가.",
    word: "school",
    pronunciation: "스쿨",
    practice: ["I go to ___.", "Where do you go?"],
  },
  {
    sentence: "The cat is cute.",
    translation: "그 고양이는 귀여워.",
    word: "cute",
    pronunciation: "큐트",
    practice: ["The ___ is cute.", "Is it cute?"],
  },
  {
    sentence: "Good morning!",
    translation: "좋은 아침!",
    word: "morning",
    pronunciation: "모닝",
    practice: ["Good ___!", "Good night!"],
  },
  {
    sentence: "I eat breakfast.",
    translation: "나는 아침을 먹어.",
    word: "breakfast",
    pronunciation: "브렉퍼스트",
    practice: ["I eat ___.", "Do you eat lunch?"],
  },
  // 신규 45개 (총 60개)
  {
    sentence: "I see a bird.",
    translation: "나는 새 한 마리를 봐.",
    word: "bird",
    pronunciation: "버드",
    practice: ["I see a ___.", "Can you see the bird?"],
  },
  {
    sentence: "This is a book.",
    translation: "이것은 책이야.",
    word: "book",
    pronunciation: "북",
    practice: ["This is a ___.", "I like books."],
  },
  {
    sentence: "She has a pencil.",
    translation: "그녀는 연필이 있어.",
    word: "pencil",
    pronunciation: "펜슬",
    practice: ["She has a ___.", "I have a pencil."],
  },
  {
    sentence: "He is tall.",
    translation: "그는 키가 커.",
    word: "tall",
    pronunciation: "톨",
    practice: ["He is ___.", "She is short."],
  },
  {
    sentence: "I like blue.",
    translation: "나는 파란색을 좋아해.",
    word: "blue",
    pronunciation: "블루",
    practice: ["I like ___.", "What color do you like?"],
  },
  {
    sentence: "The sky is blue.",
    translation: "하늘은 파란색이야.",
    word: "sky",
    pronunciation: "스카이",
    practice: ["The ___ is blue.", "Look at the sky."],
  },
  {
    sentence: "I am a student.",
    translation: "나는 학생이야.",
    word: "student",
    pronunciation: "스튜던트",
    practice: ["I am a ___.", "She is a student."],
  },
  {
    sentence: "We are friends.",
    translation: "우리는 친구야.",
    word: "we",
    pronunciation: "위",
    practice: ["___ are friends.", "We play together."],
  },
  {
    sentence: "Where is my bag?",
    translation: "내 가방이 어디에 있니?",
    word: "bag",
    pronunciation: "백",
    practice: ["Where is my ___?", "My bag is here."],
  },
  {
    sentence: "I love my family.",
    translation: "나는 가족을 사랑해.",
    word: "family",
    pronunciation: "패밀리",
    practice: ["I love my ___.", "My family is big."],
  },
  {
    sentence: "He plays soccer.",
    translation: "그는 축구를 해.",
    word: "soccer",
    pronunciation: "사커",
    practice: ["He plays ___.", "Do you play soccer?"],
  },
  {
    sentence: "Open the door, please.",
    translation: "문을 열어 주세요.",
    word: "door",
    pronunciation: "도어",
    practice: ["Open the ___.", "Close the door."],
  },
  {
    sentence: "I drink milk.",
    translation: "나는 우유를 마셔.",
    word: "milk",
    pronunciation: "밀크",
    practice: ["I drink ___.", "Do you drink juice?"],
  },
  {
    sentence: "She is my sister.",
    translation: "그녀는 내 여동생이야.",
    word: "sister",
    pronunciation: "시스터",
    practice: ["She is my ___.", "I have one sister."],
  },
  {
    sentence: "I am ten years old.",
    translation: "나는 열 살이야.",
    word: "ten",
    pronunciation: "텐",
    practice: ["I am ___ years old.", "How old are you?"],
  },
  {
    sentence: "I have a red hat.",
    translation: "나는 빨간 모자가 있어.",
    word: "red",
    pronunciation: "레드",
    practice: ["I have a ___ hat.", "The apple is red."],
  },
  {
    sentence: "It is cold today.",
    translation: "오늘은 추워.",
    word: "cold",
    pronunciation: "콜드",
    practice: ["It is ___ today.", "It is hot."],
  },
  {
    sentence: "I want an ice cream.",
    translation: "나는 아이스크림을 원해.",
    word: "want",
    pronunciation: "원트",
    practice: ["I want ___.", "Do you want candy?"],
  },
  {
    sentence: "Look at the flowers.",
    translation: "꽃을 봐.",
    word: "flower",
    pronunciation: "플라워",
    practice: ["Look at the ___.", "The flowers are pretty."],
  },
  {
    sentence: "He is my teacher.",
    translation: "그는 나의 선생님이야.",
    word: "teacher",
    pronunciation: "티처",
    practice: ["He is my ___.", "She is a good teacher."],
  },
  {
    sentence: "I swim in the pool.",
    translation: "나는 수영장에서 수영해.",
    word: "swim",
    pronunciation: "스윔",
    practice: ["I ___ in the pool.", "Can you swim?"],
  },
  {
    sentence: "This is my house.",
    translation: "이것은 나의 집이야.",
    word: "house",
    pronunciation: "하우스",
    practice: ["This is my ___.", "Where is your house?"],
  },
  {
    sentence: "I ride a bicycle.",
    translation: "나는 자전거를 타.",
    word: "bicycle",
    pronunciation: "바이시클",
    practice: ["I ride a ___.", "Can you ride a bike?"],
  },
  {
    sentence: "Sit down, please.",
    translation: "앉아 주세요.",
    word: "sit",
    pronunciation: "싯",
    practice: ["___ down, please.", "Stand up."],
  },
  {
    sentence: "I draw a picture.",
    translation: "나는 그림을 그려.",
    word: "draw",
    pronunciation: "드로",
    practice: ["I ___ a picture.", "Can you draw?"],
  },
  {
    sentence: "She sings a song.",
    translation: "그녀는 노래를 불러.",
    word: "sing",
    pronunciation: "싱",
    practice: ["She ___ a song.", "I like to sing."],
  },
  {
    sentence: "The sun is big.",
    translation: "태양은 커.",
    word: "sun",
    pronunciation: "선",
    practice: ["The ___ is big.", "The sun is bright."],
  },
  {
    sentence: "I wash my hands.",
    translation: "나는 손을 씻어.",
    word: "wash",
    pronunciation: "워시",
    practice: ["I ___ my hands.", "Wash your face."],
  },
  {
    sentence: "Goodbye, see you tomorrow.",
    translation: "안녕, 내일 보자.",
    word: "goodbye",
    pronunciation: "굿바이",
    practice: ["___, see you.", "Goodbye, teacher."],
  },
  {
    sentence: "I read a book.",
    translation: "나는 책을 읽어.",
    word: "read",
    pronunciation: "리드",
    practice: ["I ___ a book.", "Do you read books?"],
  },
  {
    sentence: "The rabbit is white.",
    translation: "토끼는 하얀색이야.",
    word: "rabbit",
    pronunciation: "래빗",
    practice: ["The ___ is white.", "I have a rabbit."],
  },
  {
    sentence: "I sleep at nine.",
    translation: "나는 9시에 자.",
    word: "sleep",
    pronunciation: "슬립",
    practice: ["I ___ at nine.", "When do you sleep?"],
  },
  {
    sentence: "This apple is yummy.",
    translation: "이 사과는 맛있어.",
    word: "yummy",
    pronunciation: "야미",
    practice: ["This is ___.", "The cake is yummy."],
  },
  {
    sentence: "I have five fingers.",
    translation: "나는 손가락이 다섯 개 있어.",
    word: "five",
    pronunciation: "파이브",
    practice: ["I have ___ fingers.", "Count to five."],
  },
  {
    sentence: "My mother is kind.",
    translation: "우리 엄마는 친절해.",
    word: "kind",
    pronunciation: "카인드",
    practice: ["She is ___.", "Be kind to others."],
  },
  {
    sentence: "I clean my room.",
    translation: "나는 방을 청소해.",
    word: "clean",
    pronunciation: "클린",
    practice: ["I ___ my room.", "Clean your desk."],
  },
  {
    sentence: "It is windy today.",
    translation: "오늘은 바람이 불어.",
    word: "windy",
    pronunciation: "윈디",
    practice: ["It is ___ today.", "Is it windy?"],
  },
  {
    sentence: "I write my name.",
    translation: "나는 이름을 써.",
    word: "write",
    pronunciation: "라이트",
    practice: ["I ___ my name.", "Write your answer."],
  },
  {
    sentence: "He is my father.",
    translation: "그는 나의 아빠야.",
    word: "father",
    pronunciation: "파더",
    practice: ["He is my ___.", "My father is strong."],
  },
  {
    sentence: "I eat rice for lunch.",
    translation: "나는 점심에 밥을 먹어.",
    word: "rice",
    pronunciation: "라이스",
    practice: ["I eat ___.", "Do you eat rice?"],
  },
  {
    sentence: "They are playing.",
    translation: "그들은 놀고 있어.",
    word: "playing",
    pronunciation: "플레잉",
    practice: ["They are ___.", "We are playing."],
  },
  {
    sentence: "I see a rainbow.",
    translation: "나는 무지개를 봐.",
    word: "rainbow",
    pronunciation: "레인보우",
    practice: ["I see a ___.", "The rainbow is pretty."],
  },
  {
    sentence: "Turn left, please.",
    translation: "왼쪽으로 가세요.",
    word: "left",
    pronunciation: "레프트",
    practice: ["Turn ___.", "Go straight."],
  },
  {
    sentence: "I have a new toy.",
    translation: "나는 새 장난감이 있어.",
    word: "toy",
    pronunciation: "토이",
    practice: ["I have a ___.", "This toy is fun."],
  },
  {
    sentence: "The tree is green.",
    translation: "나무는 초록색이야.",
    word: "tree",
    pronunciation: "트리",
    practice: ["The ___ is green.", "I climb a tree."],
  },
];

export const grade3WritingPrompts: string[] = [
  // 기존 20개
  "우리 학교를 자세히 소개하는 글을 써 보세요.",
  "내가 가장 좋아하는 과목과 그 이유를 설명해 보세요.",
  "가족 여행에서 있었던 일을 순서대로 써 보세요.",
  "내가 존경하는 사람에 대해 써 보세요.",
  "우리 마을(동네)의 좋은 점을 소개해 보세요.",
  "내가 읽은 책에서 가장 기억에 남는 장면을 써 보세요.",
  "만약 내가 대통령이 된다면 무엇을 할까요?",
  "반려동물을 키워 본 경험(또는 키우고 싶은 이유)을 써 보세요.",
  "운동회에서 있었던 재미있는 일을 써 보세요.",
  "내가 만약 시간 여행을 할 수 있다면 어디로 갈까요?",
  "친구와 다투었다가 화해한 경험을 써 보세요.",
  "내가 직접 요리해 본 경험을 써 보세요.",
  "자연에서 가장 신기한 것은 무엇인지 써 보세요.",
  "내가 가고 싶은 나라와 그 이유를 써 보세요.",
  "생일에 받고 싶은 선물과 그 이유를 써 보세요.",
  "우리 반 친구들에게 하고 싶은 말을 편지로 써 보세요.",
  "감사한 마음을 전하는 글을 써 보세요.",
  "사계절 중 가장 좋아하는 계절과 그 이유를 써 보세요.",
  "내가 발명하고 싶은 물건은 무엇인지 상상해서 써 보세요.",
  "환경을 보호하기 위해 내가 할 수 있는 일을 써 보세요.",
  // 신규 40개 (총 60개)
  "방학 동안 가장 재미있었던 일을 써 보세요.",
  "내가 가장 좋아하는 음식과 그 이유를 설명해 보세요.",
  "내가 키우고 싶은 동물과 그 이유를 써 보세요.",
  "학교에서 가장 좋았던 경험을 써 보세요.",
  "내 꿈이 무엇인지, 왜 그 꿈을 갖게 되었는지 써 보세요.",
  "아끼는 물건에 대해 소개하는 글을 써 보세요.",
  "비 오는 날의 경험을 자세히 묘사해 보세요.",
  "친구를 소개하는 글을 써 보세요.",
  "만약 하늘을 날 수 있다면 어디에 가고 싶은지 써 보세요.",
  "가장 재미있는 놀이와 놀이 방법을 설명해 보세요.",
  "내가 도움을 받았던 경험과 느낌을 써 보세요.",
  "우리 가족의 주말 이야기를 써 보세요.",
  "좋아하는 만화 영화(애니메이션)를 소개해 보세요.",
  "봄에 볼 수 있는 자연의 변화를 관찰하여 써 보세요.",
  "겨울에 눈이 오면 하고 싶은 일을 써 보세요.",
  "내가 만약 선생님이 된다면 어떻게 가르칠지 써 보세요.",
  "도서관에서 있었던 경험을 써 보세요.",
  "내가 잘하는 것과 노력하고 싶은 것을 써 보세요.",
  "가장 기억에 남는 생일 파티에 대해 써 보세요.",
  "시골과 도시의 차이점에 대해 써 보세요.",
  "물을 아끼는 방법에 대해 제안하는 글을 써 보세요.",
  "우리 동네에서 가장 좋아하는 장소를 소개해 보세요.",
  "재활용의 중요성에 대해 써 보세요.",
  "내가 만약 동물이 된다면 어떤 동물이 되고 싶은지 써 보세요.",
  "체험학습에서 배운 것을 정리하여 써 보세요.",
  "가장 무서웠던 경험을 이야기해 보세요.",
  "나만의 비밀 장소에 대해 소개해 보세요.",
  "우리 가족만의 특별한 행사에 대해 써 보세요.",
  "좋아하는 운동을 소개하고, 그 규칙을 설명해 보세요.",
  "만약 투명 인간이 된다면 무엇을 하고 싶은지 써 보세요.",
  "우리 반에서 일어난 재미있는 에피소드를 써 보세요.",
  "편의점(또는 슈퍼)에서 겪은 일을 써 보세요.",
  "내가 만든 작품(그림, 만들기 등)을 소개하는 글을 써 보세요.",
  "미래의 학교는 어떤 모습일지 상상해서 써 보세요.",
  "동생이나 형(언니)에게 하고 싶은 말을 편지로 써 보세요.",
  "새 학년이 되면 하고 싶은 일을 써 보세요.",
  "내가 본 가장 아름다운 풍경을 묘사해 보세요.",
  "우리 학교 급식 중 가장 좋아하는 메뉴를 소개해 보세요.",
  "소풍에서 있었던 재미있는 일을 써 보세요.",
  "나의 하루 일과를 시간 순서대로 써 보세요.",
];

export const grade3CreativeData: KnowledgeEntry[] = [
  // 미술 (15개)
  {
    text: "빨간색과 노란색을 섞으면 ___색이 된다.",
    answer: "주황",
    category: "미술",
  },
  {
    text: "빨간색과 파란색을 섞으면 ___색이 된다.",
    answer: "보라",
    category: "미술",
  },
  {
    text: "노란색과 파란색을 섞으면 ___색이 된다.",
    answer: "초록",
    category: "미술",
  },
  {
    text: "흰색을 많이 섞으면 색이 ___해진다.",
    answer: "밝아",
    category: "미술",
  },
  {
    text: "검정색을 많이 섞으면 색이 ___해진다.",
    answer: "어두워",
    category: "미술",
  },
  {
    text: "찰흙으로 모양을 빚어 만드는 것을 ___이라 한다.",
    answer: "조소",
    category: "미술",
  },
  {
    text: "물감에 물을 많이 타서 그리는 그림을 ___화라 한다.",
    answer: "수채",
    category: "미술",
  },
  {
    text: "좌우가 똑같은 모양을 ___이라 한다.",
    answer: "대칭",
    category: "미술",
  },
  {
    text: "같은 모양이 반복되는 것을 ___이라 한다.",
    answer: "패턴",
    category: "미술",
  },
  {
    text: "종이를 접어 모양을 만드는 것을 ___이라 한다.",
    answer: "종이접기",
    category: "미술",
  },
  {
    text: "크레파스로 색칠한 위에 검정색을 덮고 긁어내는 기법을 ___이라 한다.",
    answer: "스크래치",
    category: "미술",
  },
  {
    text: "빨강, 파랑, 노랑을 삼___이라 한다.",
    answer: "원색",
    category: "미술",
  },
  {
    text: "여러 가지 재료를 붙여 만드는 미술 기법을 ___이라 한다.",
    answer: "콜라주",
    category: "미술",
  },
  {
    text: "판에 그림을 새기고 찍어내는 것을 ___이라 한다.",
    answer: "판화",
    category: "미술",
  },
  {
    text: "물감이 마르기 전에 다른 색을 칠하면 색이 자연스럽게 ___된다.",
    answer: "번짐",
    category: "미술",
  },
  // 음악 (13개)
  {
    text: "음악에서 빠르기를 나타내는 말 중 '빠르게'는 ___이다.",
    answer: "알레그로",
    category: "음악",
  },
  {
    text: "음악에서 세게 연주하라는 기호는 ___이다.",
    answer: "f (포르테)",
    category: "음악",
  },
  {
    text: "음악에서 여리게 연주하라는 기호는 ___이다.",
    answer: "p (피아노)",
    category: "음악",
  },
  {
    text: "4분의 4박자에서 한 마디에 ___박이 들어간다.",
    answer: "4",
    category: "음악",
  },
  {
    text: "리코더에서 왼손 엄지로 뒷구멍을 막고 불면 ___음이 난다.",
    answer: "시",
    category: "음악",
  },
  {
    text: "같은 빠르기로 반복되는 음악의 흐름을 ___이라 한다.",
    answer: "리듬",
    category: "음악",
  },
  {
    text: "높은음자리표는 ___모양으로 생겼다.",
    answer: "소용돌이",
    category: "음악",
  },
  {
    text: "도레미파솔라시 7개의 음을 ___이라 한다.",
    answer: "음계",
    category: "음악",
  },
  { text: "온음표는 ___박자를 나타낸다.", answer: "4", category: "음악" },
  { text: "2분음표는 ___박자를 나타낸다.", answer: "2", category: "음악" },
  { text: "4분음표는 ___박자를 나타낸다.", answer: "1", category: "음악" },
  {
    text: "여러 사람이 함께 노래 부르는 것을 ___이라 한다.",
    answer: "합창",
    category: "음악",
  },
  {
    text: "우리나라 전통 장단 중 '쿵 따 쿵 따'는 ___장단이다.",
    answer: "자진모리",
    category: "음악",
  },
  // 만들기 (6개)
  {
    text: "종이를 반으로 접어 자르면 ___모양이 나온다.",
    answer: "대칭",
    category: "만들기",
  },
  {
    text: "칼로 종이를 오릴 때는 ___판 위에서 해야 안전하다.",
    answer: "커팅",
    category: "만들기",
  },
  {
    text: "풀 대신 테이프로 붙이는 것을 ___이라 한다.",
    answer: "접착",
    category: "만들기",
  },
  {
    text: "재활용품으로 만들기를 하는 것을 ___아트라 한다.",
    answer: "업사이클",
    category: "만들기",
  },
  {
    text: "털실을 엮어 만드는 것을 ___이라 한다.",
    answer: "뜨개질",
    category: "만들기",
  },
  {
    text: "나무에 색을 칠하고 장식을 붙이는 것을 ___이라 한다.",
    answer: "꾸미기",
    category: "만들기",
  },
  // 감상 (6개)
  {
    text: "그림을 감상할 때 느끼는 생각이나 기분을 ___이라 한다.",
    answer: "감상문",
    category: "감상",
  },
  {
    text: "미술 작품을 전시하는 곳을 ___이라 한다.",
    answer: "미술관",
    category: "감상",
  },
  {
    text: "음악을 연주하는 공연장을 ___이라 한다.",
    answer: "음악당",
    category: "감상",
  },
  {
    text: "조각이나 도자기처럼 입체적인 작품을 ___작품이라 한다.",
    answer: "입체",
    category: "감상",
  },
  {
    text: "자연의 아름다운 모습을 그린 그림을 ___화라 한다.",
    answer: "풍경",
    category: "감상",
  },
  {
    text: "사람의 얼굴이나 모습을 그린 그림을 ___화라 한다.",
    answer: "초상",
    category: "감상",
  },
];
